
import type { ChoiceItem, Colleague, CustomColleagueOption } from '../types';

export const CAREER_INTRO_DATA = {
    title: "YOUR CAREER",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ZzY31WMJ-main2.webp",
    description: `The graduation of a mage is a pretty big ceremony, with people coming in from all over the Dominion, or even the world, just to witness the event. You had to complete one last 'test' before you were officially graduated – a formality, of course. It was more of a choreographed show than a proper exam, giving you the opportunity to show off everything you've learned before an adoring, cheering crowd. Maybe you awed your spectators by punching a hole clear through a massive boulder, or by creating a gorgeous show of light and water, or by demonstrating the sheer power of one of your magnificent inventions? Whatever the case, I'm sure it will be a big confidence boost as you enter the next exciting stage of your life.

When you were a child, you had a family there to make all of your decisions for you; when you were in school, your life was heavily regimented; but now you're all grown up, and all of your decisions are your own from now on. For many mages, this is terrifying... and for others, it's invigorating! With no one looking over you, it's finally time for you to go out there and forge your own destiny. The entire world is your oyster! Of course, this section is probably going to be a little more freeform than the previous, since you could theoretically do just about anything you want. Whatever you want to try, I wish you good luck! With talent like yours, I'm sure nothing could stop you from achieving your goals.`
};

export const CAREER_INTRO_DATA_KO = {
    title: "당신의 진로",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ZzY31WMJ-main2.webp",
    description: `마법소녀의 졸업식은 중대한 행사입니다. 국가나, 심지어 세계 각지에서 사람들이 몰려와 졸업식을 참관하려 하지요. 당신은 공식적으로 졸업장을 받기 전에 마지막 '시험'을 치러야 했지만 - 그건 사실 요식행위일 뿐입니다. 정식 시험이라기보다 하나의 잘 짜여진 쇼 같은 거죠. 당신을 응원하며 환호하는 사람들 앞에서 그동안 배웠던 모든 것을 마음껏 선보일 수 있는 기회입니다. 거대한 바위에 큼지막한 구멍을 뚫을 수도 있겠고, 빛과 물을 엮어 황홀한 장관을 보여 줄 수도 있겠고, 당신의 위대한 발명품을 가동시켜 힘자랑을 할 수도 있을 거에요. 뭐가 됐든, 관중들은 분명 놀라 입을 다물지 못할 거고, 당신에게도 사회에 나가기 전 자신감을 제대로 충전할 수 있는 계기가 되겠죠.

당신이 어렸을 때는 가족들이 당신을 이끌어 줬을 거고, 학교에 있을 때는 정해진 시간표만 따라가면 됐었죠. 하지만 이제 당신도 다 컸으니, 직접 선택과 결정을 내려야 해요. 몇몇 마법소녀들은 이걸 두려워하지만... 다른 마법소녀들은 이 날만을 기다려 왔답니다! 마침내 저 넓은 세상에서 당신만의 운명을 만들 시간이 다가온 거죠. 온 세상이 당신의 무대랍니다! 아, 자기 진로를 정하는 데 꼭 여기 나온 것들만 해야 한다거나 그런 건 없으니까 이 부분은 좀 더 자유롭게 하셔도 돼요. 앞으로 무슨 일을 하든 행운이 가득하길 빌어요! 당신의 재능이라면 무슨 일이든 분명 이뤄낼 수 있을 거에요.`
};

export const ALLMILLOR_INTRO_DATA = {
    title: "THE ALLMILLOR",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/CKVdHzks-main4.webp",
    description: `Mages are, while not required, {i}strongly{/i} encouraged to dedicate at least some of their free time to fighting Allmillor whenever they pop up in their Dominion. That is, after all, what mages are created for — to counter the number of Allmillor rising up from the Othersky at a worrying, gradually increasing rate. As a basic explanation, the Allmillor are essentially computer viruses that leak in through cracks in the security of our reality, transmitted here from the Greater Net. Destruction may not necessarily be their goal, but it's an inevitable product of their chaotic behavior. Some people think we will be able to one day staunch this threat once and for all, while others believe that our universe will inevitably be overrun, hence all the efforts to emigrate to a better, more secure dimension. Anyway, that's all irrelevant to you. All you need to do is choose {w}up to three{/w} Allmillor to specialize in fighting. Don't worry, the casualty rate is very low!`
};

export const ALLMILLOR_INTRO_DATA_KO = {
    title: "올밀러",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/CKVdHzks-main4.webp",
    description: `무조건적인 의무는 아니지만, 마법소녀들은 여유가 된다면 가급적 세상에 나타나는 올밀러들을 물리치는 데 힘을 보태 줘야 해요. 따지고 보면 그게 마법소녀들이 태어난 이유니까요. 아더스카이에서 우리의 세계로 넘어오는 올밀러들의 수가 자꾸만 늘어나서 모두가 우려하고 있고, 이 쪽에서도 그들을 억제해야 합니다. 올밀러들은 간단히 말하자면 현실의 보안이 뚫려서 그 균열을 통해 유입되는 바이러스 같은 것들이에요. 딱히 파괴가 목적인 건 아니지만, 그놈들이 온갖 혼란스러운 짓거리를 하다 보면 필연적으로 피해가 누적됩니다. 어떤 이들은 우리가 끝내 이 거대한 위협을 종식시킬 수 있을 거라고 믿지만, 또 다른 사람들은 결국 이 우주는 놈들에게 넘어갈 거고 그 전에 빨리 더 안정적인 차원으로 탈출해야 한다고 말합니다. 뭐, 지금 당신이 신경쓸 문제는 아니죠. 일단은 주로 싸우게 될 올밀러의 종류를 세 가지 골라 주세요. 사망률은 아주 낮으니 걱정하지 마세요!`
};

export const ALLMILLOR_CHOICES_DATA: ChoiceItem[] = [
    {
        id: 'grimsayer',
        title: 'GRIMSAYER',
        cost: 'Grants +5 FP',
        description: "These things show up a few times a century per Dominion, and it's always a big event when they do. By far the most powerful beasts on this list, and they're definitely not subtle about it; these skyscraper-sized creatures will immediately dedicate their short, brutish lives to sowing as much chaos as possible. They're way too much for most mages to possibly solo, but don't worry, you'll never be dealing with them alone. Every time one appears, pretty much every mage within miles is going to show up to put together an organized counterattack. At that point, these beasts never last long, though watching them get taken down is always very exciting!",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/chhS2KDv-a1.webp',
    },
    {
        id: 'nethe',
        title: 'NETHE',
        cost: 'Grants +5 FP',
        description: "The things that go bump in the night. These are the most famous of the Allmillor, viruses poured in from the Greater Net, causing chaos and picking off hapless mundanes on the outskirts of society. They are perhaps the weakest of the creatures on this list, as well as the ones most dominated by raw animal instinct. However, they are the most numerous by far, so expect to spend a lot of your time playing pest control, tracking them down from the details of vague sightings. Don't expect them to put up much of a fight, but that doesn't mean you should underestimate them — on occasion, you'll meet an S-class Nethe that will be significantly stronger than the others.",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/tPwHJtyg-a2.webp',
    },
    {
        id: 'sinvains',
        title: 'SINVAINS',
        cost: 'Grants +5 FP',
        description: "Usually the products of horrid Sinthru rituals, these beings are former mages who have been... {i}corrupted{/i}. Their minds have been irreparably broken to the point where they barely have any similarities with the rest of mankind, psychologically. Beasts of utter sadism, their only goal is to sow as much human suffering across the land as they possibly can. They are extremely rare, released every century or so, usually as a distraction from some other Sinthru scheme. Not only do they have a wide variety of powers, but worst of all, they're {i}smart{/i} — the smartest beast on this list, happy to bide their time building their forces or even pretending to still be a normal mage.",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jPQfRSLt-a3.webp',
    },
    {
        id: 'yokai',
        title: 'YOKAI',
        cost: 'Grants +5 FP',
        description: "Jipangu is so proliferated with bizarre old curses and distortions that many spirits on the island become these... {i}things{/i}. Yokai have an extremely wide variety of forms and powers, though they trend towards being strange and squirky. They are usually not actively malevolent, instead obsessing over some seemingly arbitrary goal, like collecting every spoon or singing the greatest song; however, most don't abide by human morality and will readily kill or destroy if it means achieving their goal. Thus, dealing with them is usually a matter of managing and \"taming\" them and preventing them from escalating to violence, although extermination is also an option.",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8DvL8FmW-a4.webp',
    },
    {
        id: 'fractures',
        title: 'FRACTURES',
        cost: 'Grants +5 FP',
        description: "Natural disasters were constant during the Forsaken Age, but were wiped out for thousands of years soon after. However, it seems they've recently returned, in a more distorted form. The Schism is the most famous of these, but they come in all forms, from a tornado that transforms people into giant frog monsters to a flood of bubbling candy gum acid. They're not sentient, and cannot be tamed or fought. All you can do is hopefully try to find a way to stop them, or if not, save as many people as you can, wait for them to be over and then help manage the emergency disaster response. Luckily, our evacuation measures have been getting pretty robust.",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/QjMv8xXL-a5.webp',
    },
    {
        id: 'distortions',
        title: 'DISTORTIONS',
        cost: 'Grants +5 FP',
        description: "The poor dears. Through no fault of their own, these mages have been born subject to glitches in the very programming of our universe, and tend to wreak unknowable destruction everywhere they go without even trying. The basic laws of reality visibly break down surrounding them, the world turning into a blur of pixels and image artifacts. Their abilities are varied, so before approaching, careful research must be done to know exactly what they're capable of, and especially what their weak points are. Some are basically invincible, and have to be locked away in special cages for the good of the world. If you can, though, try to put them out of their misery.",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Lh8MsgmS-a6.webp',
    },
];

export const ALLMILLOR_CHOICES_DATA_KO: ChoiceItem[] = [
    {
        id: 'grimsayer',
        title: '그림세이어',
        cost: 'Grants +5 FP',
        description: "이놈들은 한 국가에 수백 년에 한 번 꼴로 나타나는데, 그 한 번 한 번이 중대사건이죠. 여기 있는 괴물들 중 제일 강력하고, 그 성질도 사납기 이를 데 없어요. 고층 빌딩만한 몸을 끌고 나타나서는 제압되기까지의 그 짧은 시간 동안 온갖 패악을 부립니다. 너무 강력하기까지 해서 웬만한 마녀들은 단신으로 이 괴물을 처치할 수 없지만, 애초에 단신으로 이 괴물을 상대할 일은 없을 테니 걱정하지 않아도 됩니다. 이놈들이 나타날 때마다 주변에 있는 거의 모든 마녀들이 즉시 출동해서 힘을 합쳐 반격을 할 거니까요. 그러면 금방 제압할 수 있습니다. 그 모습을 보는 것도 아주 장관이구요!",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/chhS2KDv-a1.webp',
    },
    {
        id: 'nethe',
        title: '네테',
        cost: 'Grants +5 FP',
        description: "밤중에 마주치는 그 괴물들입니다. 올밀러들 중 가장 유명하고, 사회의 변두리에 있는 무방비한 일반인들을 주로 괴롭히는 놈들이죠. 주로 지성 없이 동물적인 본능에 따라 움직이는 놈들이라 여기 있는 괴물들 중 가장 약하지만, 그 수도 가장 많기 때문에 많은 시간을 퇴치에 쏟아야 할 겁니다. 어디서 봤다는 모호한 정보만 듣고 추적해서 잡아내야 하죠. 뭐, 싸워서 제압하는 건 별 문제되지 않겠지만, 그래도 절대 방심해서는 안 됩니다. 가끔씩은 S급 네테가 나타나기도 하는데, 평범한 놈들보다 훨씬 강력하거든요.",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/tPwHJtyg-a2.webp',
    },
    {
        id: 'sinvains',
        title: '신베인',
        cost: 'Grants +5 FP',
        description: "주로 끔찍한 신스루 의식으로 인해 생겨나는 이들은 한때는 마녀들이었습니다... 타락한 마녀들이죠. 이들의 정신은 이미 완전히 무너져 더 이상 인간이라 볼 수 없을 정도입니다. 가학성의 노예가 되어 사람들에게 더 많은 고통을 주는 것 이외에는 아무것도 바라지 않아요. 백 년에 한 번 나타날까 말까 할 정도로 희귀한데, 주로 신스루 마녀단에서 뭔가 작당을 할 때 다른 이들의 눈을 돌리기 위해 이들을 풀어 놓고는 합니다. 신베인들은 다양한 마법을 사용하는 건 기본에, 영리하기까지 합니다. 여기 있는 괴물들 중 가장 지성이 높죠. 판을 키우기 위해 조용히 때를 기다릴 줄도 알고, 아주 영악하게도 순수한 마녀인 척 연기할 줄도 압니다.",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jPQfRSLt-a3.webp',
    },
    {
        id: 'yokai',
        title: '요괴',
        cost: 'Grants +5 FP',
        description: "지팡구 땅에는 고대의 저주와 변형이 너무나 많아서 그 섬의 영혼들 중 대다수가 이...것들로 변합니다. 요괴들은 그 형체도, 능력도 아주 다양하지만, 공통적으로 기괴하고 변덕스럽습니다. 대놓고 사악한 경우는 사실 많지 않고, 오히려 이상한 목표에 집착하는 경우가 많은데, 예를 들면 세상의 모든 숟가락을 모은다던가 가장 멋진 노래를 부른다던가 하는 것들이에요. 문제는 이것들이 딱히 인간들의 윤리 도덕을 존중하지 않기 때문에 그 목표를 이루겟다고 사람들을 죽이거나 물건을 때려부수거나 한다는 겁니다. 결국 요괴를 처리한다는 건 보통은 이것들을 관리하고 \"길들여서\" 폭력성을 누르는 것에 가깝습니다. 뭐, 필요하다면 죽여야겠지만요.",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8DvL8FmW-a4.webp',
    },
    {
        id: 'fractures',
        title: '균열',
        cost: 'Grants +5 FP',
        description: "버림받은 시대에는 이런 자연재해가 꽤 잦았습니다만, 그 후로 수천 년 동안은 걱정할 필요가 없었죠. 하지만 그 때의 재앙들이 더욱 뒤틀린 모습으로 다시 나타나기 시작했습니다. 가장 유명한 건 '대분열'이지만 사람을 거대 개구리로 변신시키는 토네이도부터 막 흘러넘치는 강산성 캔디 껌까지 모습은 무궁무진합니다. 이런 균열들은 지성이 있는 것도 아니고, 싸워서 이기거나 어떻게 길들일 수도 없습니다. 할 수 있는 일이라고는 어떻게든 균열을 멈추던가, 아니면 최대한 많은 사람들을 대피시켰다가 모든 것이 끝나면 구호 활동을 돕는 것 정도밖에 없어요. 그래도 요즘에는 재난 대피 매뉴얼이 꽤 잘 갖춰져 있답니다.",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/QjMv8xXL-a5.webp',
    },
    {
        id: 'distortions',
        title: '왜곡체',
        cost: 'Grants +5 FP',
        description: "아, 이 불쌍한 아이들. 죄를 지은 것도 아닌데, 우리 우주가 설계될 때부터 있었던 오류들을 떠안게 됐죠. 이 아이들은 자신들이 원하든 원치 않든, 우리가 예측할 수 없는 방식으로 주변을 파괴하게 됩니다. 현실의 법칙들이 대놓고 무너지고, 세계가 마치 버그 걸린 컴퓨터처럼 픽셀과 이미지 단위로 쪼개지죠. 왜곡체들은 다양한 능력을 가지고 있기 때문에, 접촉하기 전에는 반드시 그들의 능력과 약점을 철저히 조사해 두어야 합니다. 실제로 사실상 무적이라 특수한 감옥에 봉인해 두는 것이 그나마 최상인 경우도 있으니까요. 그래도, 가능하다면, 이 아이들을 고통에서 해방시켜 주세요.",
        imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Lh8MsgmS-a6.webp',
    },
];

export const CAREER_GOALS_DATA: { proSports: ChoiceItem[], general: ChoiceItem[], finishingTouches: ChoiceItem[] } = {
    proSports: [
        {
            id: 'pro_gladiator',
            title: 'PRO GLADIATOR',
            cost: 'Costs 0 FP',
            description: "{i}Requires {w}Join The Combat D'Équipe Team.{/w}{/i} You've been picked by one of the teams of elite fighters who've long dazzled audiences with their sheer magical power. Either that, or your skills were so impressive that you were allowed to form your own team with your friends! Reach the finals of each tourney to gain access to the next tournament 'tier'; at the tippy-top, one day you might just win the Gyvirth Tournament of Eternal Champions, and be considered the most skilled and powerful mages in the entire world. Just keep practicing!",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nMkbTm2F-a7.webp',
            requires: 'combat',
        },
        {
            id: 'pro_racer',
            title: 'PRO RACER',
            cost: 'Costs 0 FP',
            description: "{i}Requires {w}Become A Segalanya Racer.{/w}{/i} You've made such an impression at school races that you've started to be invited to professional events. You don't really have a 'team' here, per se, though you do have a pit crew who will wait for you at certain sections of the race to help you re-energize and finish strong. Racing is not only a test of skill and determination, but also of intellect; there are new innovations in speedy magic and technology every single year! Your biggest goal will be winning the hyper-famous Hermian Race across the Earth!",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/vxTzz8WP-a8.webp',
            requires: 'racer',
        },
        {
            id: 'pro_player',
            title: 'PRO PLAYER',
            cost: 'Costs 0 FP',
            description: "{i}Requires {w}Join The Mazball Team.{/w}{/i} Probably the career that offers the most riches and fames, but is also the most physically demanding! Pro Mazball will push your strength, speed, durability, magical skills, and quick- thinking abilities to their limits! Luckily, you'll be part of a team of dozens of other mages who'll be there to support you through thick and thin. The holy grail of Mazball is winning the Qeryss Cup, a tournament in which Arabella is the final challenger! Only four teams have won the cup over its centuries of history...",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Myp1xnXg-a9.webp',
            requires: 'mazball',
        },
    ],
    general: [
        {
            id: 'join_dga', title: 'JOIN THE DGA', cost: 'Costs 0 FP',
            description: "DGA stands for— please don't laugh — the Do-Gooder Alliance. I know, I know, but it was named by a 7 year old, okay? Anyway, they have a chapter in every Dominion, and are pretty chill sisterhoods dedicated to stopping mundane criminals and slaying Allmillor. Entrance standards are pretty lax, and the work is pretty easy and varied, with a new adventure every other week. If you love helping people, or you just have no particular ambitions, this is always a reliable choice. You might even advance upwards in their ranks.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PssMJLDZ-a10.webp'
        },
        {
            id: 'prepare_allsayer', title: 'PREPARE FOR THE ALLSAYER', cost: 'Costs 0 FP',
            description: "The prospect of a second Schism opening was long considered a crackpot conspiracy theory, but recent mathematical projections are making it look more and more possible. Worse, it might unleash a distorted creature so immense that it makes the Grimsayers look like little babies by comparison. Plenty of folks are doing all sorts of research trying to find out where and when this schism will open, knowing that whoever predicted it correctly and managed to set up defenses against the beast will earn immense repute and fame.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BH08K56D-a11.webp'
        },
        {
            id: 'become_celebrity', title: 'BECOME A CELEBRITY', cost: 'Costs 0 FP',
            description: "You can earn some wealth and prestige as a byproduct of, say, heroics, but there's also certain more direct means. The easiest way is to collaborate with one of the corporations, really getting your name and image out there, maybe making songs, starring in movies, dancing as an idol, or what have you. Some say dealing with paparazzi and celebrity gossip is even scarier than fighting the Allmillor! But at least you'll become one of the richest and most beloved mages on Earth, with millions of adoring fans at your beck and call.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/C5Mh8pcs-a12.webp'
        },
        {
            id: 'get_embroiled in politics', title: 'GET EMBROILED IN POLITICS', cost: 'Costs 0 FP',
            description: "Clever and charismatic? Why not strive for some true power? It's hard to generalize across the various political systems of the Dominions; in Gohwood, you'll have to get your bloodline christened as noble; in New Palisade, you'll need to run a campaign and bring in the popular vote; and so on. Regardless, the ultimate goal is working your way up to the role of an Archmage (or King/Queen, or President, or etc), the ruler of an entire Dominion, twisting the local society as you see fit. Perhaps you can even come to rule multiple Dominions...?",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/qMMw4Vb7-a13.webp'
        },
        {
            id: 'join_mazzottis', title: 'JOIN THE MAZZOTTIS', cost: 'Costs 0 FP',
            description: "99% of mages turn out just fine due to good upbringing, but a few always fall through the cracks. There are groups of rogue mages scattered all over the place, but none so large and organized as the Mazzottis, who have hundreds of mages and hundreds of thousands of mudanes among their ranks. Many of their members live double lives, posing as regular mages by day but using their mafia connections to sabotage their foes, get a leg up over their competition, and guarantee riches and fame even if through theft, fraud and intimidation.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4ZW9dJSY-a14.webp'
        },
        {
            id: 'join_red_jade_council', title: 'JOIN THE RED-JADE COUNCIL', cost: 'Costs 0 FP',
            description: "Most of the members of the council have millenia of tenure, and new inductees only come along every few centuries. Simply being magically powerful won't impress them — they scoff at spells as party tricks, knowing {i}true{/i} power is the influence you hold over others. Thus, you'll have to garner immense amounts of economic or political clout until you're impossible to ignore. Working your way up through their ranks, you may earn wealth and power far beyond your wildest imagination, said to dwarf even the Mother's.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/2YF3ZCHz-a15.webp'
        },
        {
            id: 'pacify_ninth_dominion', title: 'PACIFY THE NINTH DOMINION', cost: 'Costs 0 FP',
            description: "Legally part of Valsereth, this mysterious and well- guarded civilization beneath the volcanic Mt. Bearsmark is asserting its sovereignty as the ninth dominion. It appears to be a totalitarian dictatorship with a brainwashed, ultranationalistic populace, and ambitions of... \"expansionism\". Those who can find a way down there may be able to work out some sort of treaty to guarantee peace, granting the city Dominion status or convincing it to be satisfied as a city state. Or... maybe you {i}want{/i} it to go to war, the first war in centuries?",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MDkyV633-a16.webp'
        },
        {
            id: 'become_professor', title: 'BECOME A PROFESSOR', cost: 'Costs 0 FP', requires: 'adjunct_professor',
            description: "{i}Requires {w}Adjunct Professor.{/w}{/i} Why not dedicate yourself to sharing all of your bountiful knowledge? There's generally only one professor per field of magic per academy, so each position is highly coveted, and you'll have lots of competition. A new professor being hired is generally an event spoken about around the globe, so you'll be like a magical celebrity overnight. Plus, you'll be responsible for the care of many young mages, able to be a beacon of inspiration for an entire generation and set them off on the right track.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/R4g68mcN-a17.webp'
        },
        {
            id: 'join_idpa', title: 'JOIN THE IDPA', cost: 'Costs 0 FP',
            description: "The Dominions try their best to be quite libertarian. Every once in a while, though, some mage gets it into their head to try and take over the world, or burn down a dozen orphanages, or who knows what else. If local mages can't handle them, special agents from the IDPA are dispatched to the scene. Their training regimen is the harshest in the world, and only the most hardened and badass mages alive can possibly make it through; but if you manage it, you'll find yourself part of the toughest, coolest, and most tight-knit sisterhood around.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ch6y2H7M-a18.webp'
        },
        {
            id: 'hunt_shadow_convict', title: 'HUNT THE SHADOW CONVICT', cost: 'Costs 0 FP', requires: 'join_idpa',
            description: "{i}Requires {w}Join the IDPA.{/w}{/i} This one's confidential, for IDPA eyes only! The agency's director is organizing an elite task force specially to take down a high-profile target. Even her identity is highly secret; all you're told is that it's suspected she could possibly be responsible for destabilizing our reality and causing the gradual infestation of the Allmillor. She is to be considered {i}extremely dangerous!{/i} She's been on the run for centuries, and has every power you've seen listed and more, so this task force is in for the hunt of its life.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/C3HqCbPL-a19.webp'
        },
        {
            id: 'assist_vap', title: 'ASSIST THE V.A.P.', cost: 'Costs 0 FP',
            description: "The Virtual Ascendance Project is an initiative launched by Margra, with the sponsorship of the Red-Jade Council, to communicate with the universe beyond ours, and hopefully convince someone to help transfer our consciousnesses to another, more stable verse, basically abandoning ship on our current, crumbling universe. The idea of leaving our homes is depressing, but many consider it the more realistic options. Others have raised one concern, however: what if the people we manage to contact end up being... malevolent?",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BHZ84nhF-a20.webp'
        },
        {
            id: 'assist_rrp', title: 'ASSIST THE R.R.P.', cost: 'Costs 0 FP',
            description: "The Reality Restoration Project is an initiative launched by Arabella, with the sponsorship of the Mother, to repair the instabilities of our own universe, reversing its current deterioration. Progress has been slow-going given the causes of the destabilization, primarily the Sinthru Covens and the Shadow Convict, {i}still{/i} have not been eliminated. Thus, most of the focus has been on tracking these bastards down before the true restoration can begin in earnest. At this point, however, many folks call the entire project a pipe dream.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Y7W244YS-a21.webp'
        },
    ],
    finishingTouches: [
        {
            id: 'moving_out', title: 'MOVING OUT', cost: 'Cost: Varies',
            description: "If you don't want to keep living with your family, you can buy a new house with the options and {w}Upgrades{/w} from {i}Page 1{/i} The first one is free, while any extras will still cost -3 FP each. You could also choose for your parents to just give you one of the old Vacation Homes.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/KpMsN670-b1.webp'
        },
        {
            id: 'bride_to_be', title: 'BRIDE-TO-BE', cost: 'Costs -3 FP',
            description: "Choose from your {w}Colleagues{/w}, or {w}Classmates{/w} previously picked for {i}Puppy Love{/i}. This will guarantee that, at some point in your career, the two of you are going to get married. This is a beautiful partnership that's expected to last for life, so make absolutely certain you pick the right girl!",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BV0SBs3C-b2.webp'
        },
        {
            id: 'mentor_career', title: 'MENTOR', cost: 'Cost: Varies',
            description: "Choose a {w}Classmate{/w} you had not selected, or create a custom one, with a discount of {fp}1 FP{/fp} (other discounts do not apply). They will become your dutiful young apprentice, performing various small tasks for you in exchange for learning from the wisdom gained from your many years of experience.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0y5PF52X-b3.webp'
        },
        {
            id: 'joys_of_parenting', title: 'JOYS OF PARENTING', cost: 'Costs -8 FP',
            description: "You're one of the few lucky applicants in the mage fostership program selected to become the parent of a newly-born mage! Design them with {w}50 Companion Points{/w} on the {i}Reference Page{/i}. You can have mundane kids for free, but this option is required if you want to be able to raise another mage.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/k6Sc6GXB-b4.webp'
        },
    ]
};

export const CAREER_GOALS_DATA_KO: { proSports: ChoiceItem[], general: ChoiceItem[], finishingTouches: ChoiceItem[] } = {
    proSports: [
        {
            id: 'pro_gladiator',
            title: '프로 투사',
            cost: 'Costs 0 FP',
            description: "{i}{w}팀 전투 동아리 가입{/w}이 필요합니다.{/i} 압도적인 마력으로 관중들을 사로잡으며 긴 커리어를 쌓아나간 일류 투사 팀에서 당신을 특채했습니다. 그게 아니라면 당신의 능력이 너무나 출중해서 직접 친구들과 팀을 꾸릴 수 있게 허락을 받았을 수도 있구요! 투사 토너먼트에서 우승할 때마다 더 '상위' 토너먼트로 진출할 수 있습니다. 그렇게 어느 날 최정점에 도달한다면, 영원의 용사들을 위한 기브리스 토너먼트를 석권할 수도 있겠죠. 전세계를 통틀어 가장 뛰어나고 강력한 마녀 중 하나가 되는 겁니다. 연습을 놓지 마세요!",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nMkbTm2F-a7.webp',
            requires: 'combat',
        },
        {
            id: 'pro_racer',
            title: '프로 경주 선수',
            cost: 'Costs 0 FP',
            description: "{i}{w}세갈라냐 경주자 되기{/w}가 필요합니다.{/i} 학교 경주에서 두각을 나타낸 당신은 프로 경기에 초청받기 시작했습니다. 여기서는 딱히 '팀'은 없지만, 일정 구간에서 당신을 기다리며 원기를 회복시켜 줄 피트 크루가 함께합니다. 경주는 단순히 기술과 의지만을 가지고 하는 것이 아닙니다. 두뇌 싸움이기도 하죠. 가장 빠른 속도를 위한 마법과 기술은 매년 혁신적으로 발전하고 있으니까요! 당신의 최대 목표는 전 지구를 무대로 펼쳐지는 최대의 레이스, 에르미안에서 우승하는 겁니다.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/vxTzz8WP-a8.webp',
            requires: 'racer',
        },
        {
            id: 'pro_player',
            title: '프로 매즈볼러',
            cost: 'Costs 0 FP',
            description: "{i}{w}매즈볼 팀 입단{/w}이 필요합니다.{/i} 스포츠 쪽 진로에서는 가장 돈도 많이 벌고 이름값도 좋지만, 그만큼 신체적으로 힘들답니다! 매즈볼은 당신의 힘과 속도, 체력, 마법 능력, 그리고 재빠른 판단력을 극한까지 시험합니다. 물론, 당신 곁에는 열몇 명의 마녀들이 팀을 이루며 함께 난관을 헤쳐 나가게 되죠. 매즈볼의 성배는 바로 케니스 컵입니다. 이 토너먼트의 정상에 오르면 마지막으로 아라벨라의 도전을 받게 됩니다! 대회의 역사가 몇백 년이지만, 그 도전까지 이겨내고 컵을 손에 넣은 팀은 단 4팀뿐이랍니다.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Myp1xnXg-a9.webp',
            requires: 'mazball',
        },
    ],
    general: [
        {
            id: 'join_dga', title: 'DGA 가입', cost: 'Costs 0 FP',
            description: "DGA는 - 웃지 마세요 - Do-Gooder Alliance (착한 일 동맹)의 약자입니다. 네, 저도 알아요. 하지만 7살 꼬마애가 지은 이름인걸요? 어쨌든, 여기는 각 국가마다 지부를 두고 있고, 전격적으로 일반인 범죄자들을 막고 올밀러들을 죽이는 일을 하고 있습니다. 가입 기준도 꽤 널널하고, 업무는 대체적으로 쉽고 종류도 많아요. 거의 2주에 한 번 꼴로 새로운 모험을 떠날 수 있답니다. 사람들을 돕는 걸 좋아하거나 딱히 크게 바라는 게 없다면, 이곳을 골라도 후회하지 않을 겁니다. 어쩌면 높은 직책으로 올라갈 수도 있겠죠.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PssMJLDZ-a10.webp'
        },
        {
            id: 'prepare_allsayer', title: '올세이어의 침공 대비', cost: 'Costs 0 FP',
            description: "언젠가 '대분열'이 하나 더 생겨날 거라는 오래된 속설이 있는데, 얼마 전까지만 해도 다들 낡아빠진 음모론이라고 생각했습니다. 하지만 최근에 진행된 수학적 예측에 따르면 그 확률이 점점 올라가고 있다고 합니다. 더 나쁜 소식은 그렇게 생겨난 대분열에서 그 그림세이어들을 아기들처럼 보이게 할 거대한 괴물이 등장할 수도 있다는 거에요. 많은 사람들이 이 대분열이 언제 어디서 생길지를 알아내기 위해 다방면으로 연구하고 있습니다. 예측에 성공하고 방어 체계를 제대로 구축해 낸다면 말 그대로 구세의 영웅이 될 수 있으니까요.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BH08K56D-a11.webp'
        },
        {
            id: 'become_celebrity', title: '셀럽 데뷔', cost: 'Costs 0 FP',
            description: "물론 영웅이 되면 당연히 부와 유명세가 따라오겠지만, 더 직접적인 방법도 있습니다. 제일 간단한 방법은 기업과 콜라보레이션해서 당신의 이름과 이미지로 마케팅을 하는 거죠. 노래를 부르거나, 영화에 출연하거나, 아이돌이 되거나, 길은 많답니다. 대신, 파파라치나 스캔들에 대처하는 게 올밀러를 상대하는 것보다 무섭다는 사람들도 있으니 유념하세요! 그래도 지구상에서 가장 사랑받고 가장 부유한 마녀들 중 하나가 될 수 있고, 수백만 팬들이 당신을 따르면서 이것저것 다 해주려고 할 거에요.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/C5Mh8pcs-a12.webp'
        },
        {
            id: 'get_embroiled in politics', title: '정계 진출', cost: 'Costs 0 FP',
            description: "똑똑하고 카리스마가 넘치나요? 한번 진짜 권력을 위해 노력해 볼래요? 사실 국가마다 정치 시스템은 너무나도 달라서 일반화를 할 수가 없습니다. 고흐우드에서는 세례를 받아서 귀족의 혈통을 갖춰야 하고, 뉴 팰리세이드에서는 유세를 돌면서 표를 따야 하고, 다른 곳도 저마다의 방식이 있죠. 어쨋든 목표는 한 국가의 수반인 대마법사 (왕/여왕, 대통령, 기타등등) 가 되어 원하는 대로 사회를 이끌어 나가는 겁니다. 어쩌면 여러 국가를 맡아 다스리게 될 수도요...?",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/qMMw4Vb7-a13.webp'
        },
        {
            id: 'join_mazzottis', title: '마조티스 가입', cost: 'Costs 0 FP',
            description: "99%의 마법소녀들은 좋은 환경에서 양육받고 올바르게 자라나지만, 항상 몇 명은 엇나가게 됩니다. 이런 악당 마녀들은 세상 곳곳에 점점이 퍼져 있지만, 이 마조티스처럼 수백 명의 마녀들과 수천 명의 일반인들을 포함한 거대 조직을 갖추고 있는 경우는 없습니다. 이들은 보통 이중생활을 합니다. 겉으로 보기에는 평범한 마녀 행세를 하지만, 등 뒤로는 범죄 인맥을 이용해 적들을 제거하고, 경쟁자들을 방해하고, 절도와 사기 공갈로 부와 명성을 긁어모읍니다.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4ZW9dJSY-a14.webp'
        },
        {
            id: 'join_red_jade_council', title: '홍옥의 의회 가입', cost: 'Costs 0 FP',
            description: "이 의회의 의원들은 대부분 종신 임기가 보장되어 있고, 새로운 자리는 수백 년에 하나 정도로 거의 나지 않습니다. 단순히 뛰어난 마녀라고 해서 이들의 마음에 들 수는 없습니다. 진짜 힘은 남들을 조종하는 그 영향력이라는 것을 아는 이들에게 마법은 그냥 애들 장난일 뿐이니까요. 그러니까 당신을 무시할 수 없을 정도로 정계나 재계에서 엄청난 위치를 잡아 놓아야 합니다. 그렇게 의회에 들어가서 그 안에서 또 지위를 높이다 보면, 꿈에서라도 감히 상상할 수 없었던 부와 권력을 손에 넣을 수 있을 겁니다. 혹자가 말하기로는 그 어머니조차 초라해 보일 만큼이요.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/2YF3ZCHz-a15.webp'
        },
        {
            id: 'pacify_ninth_dominion', title: '아홉 번째 국가 평정', cost: 'Costs 0 FP',
            description: "공식적으로는 발세레스의 일부분입니다만, 베어스마크 화산 지하 요새에 자리잡고 있는 이 수수께끼 문명은 9번째 국가로서의 주권을 주장하고 있습니다. 민중들을 초국가주의로 세뇌한 전체주의 독재국가이며, 점점 더... \"팽창주의\"의 야망을 드러내고 있습니다. 만약 이곳으로 발을 들일 수만 있다면, 정식으로 국가 지위를 인정하거나 도시국가 정도로 만족하도록 설득해서 조약을 체결하고 지구의 평화를 지킬 수 있을지도 모릅니다. 아니면... 당신, 혹시 전쟁을 원하고 있나요? 지난 몇백 년 동안 없었던 전쟁을?",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MDkyV633-a16.webp'
        },
        {
            id: 'become_professor', title: '교수 임용', cost: 'Costs 0 FP', requires: 'adjunct_professor',
            description: "{i}{w}조교수{/w}가 필요합니다.{/i} 당신의 그 방대한 지식으로 후진을 양성하는 것은 어때요? 일반적으로는 마법학교 교수진은 각 분야별로 한 명씩밖에 없고, 그만큼 많은 이들이 노리는 직업이자 경쟁이 치열한 직업이랍니다. 새로 교수가 임용됐다는 소식이 온 세계에 다 퍼질 정도니까요. 당연히 당신도 하룻밤 사이에 유명인사가 되겠죠. 뭐, 그런 걸 다 떠나서, 당신은 수많은 어린 마법소녀들을 책임지고 맡아 가르치면서 그들을 올바른 길로 이끌며 영감을 주는 은사가 될 거에요.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/R4g68mcN-a17.webp'
        },
        {
            id: 'join_idpa', title: 'IDPA 가입', cost: 'Costs 0 FP',
            description: "각 국가에서는 마녀들의 자유의지를 최대한 존중합니다. 그런데 가끔씩은 정신나간 마녀들이 세계정복을 꿈꾸며 사달을 내거나, 고아원 몇십 곳을 불태우거나, 뭐가 될지 모를 사고를 칠 때가 있죠. 주변 마녀들 선에서 문제가 해결되지 않으면 IDPA 소속 특수 요원들이 현장에 파견됩니다. 이들이 받는 훈련은 전 세계에서 가장 혹독하고, 가장 굳세고 거친 마녀들이 아니면 수료할 수 없습니다. 대신, 버텨내기만 한다면 가장 멋지고 든든하고 우정 넘치는 동료들과 함께하게 될 거에요.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ch6y2H7M-a18.webp'
        },
        {
            id: 'hunt_shadow_convict', title: '그림자 용의자 추적', cost: 'Costs 0 FP', requires: 'join_idpa',
            description: "{i}{w}IDPA 가입{/w}이 필요합니다.{/i} 이것은 IDPA 요원들만 열람할 수 있는 기밀 임무입니다! IDPA 국장의 주도하에 유명한 도망자를 제압하기 위한 특수 작전팀이 구성되고 있습니다. 목표 인물은 그 정체마저도 베일에 싸여 있습니다. 현실 세계가 불안정해지며 올밀러들이 점차 기어나오고 있는 것의 배후에 그녀가 있을지도 모른다는 말밖에는 들을 수 없었습니다. 그녀는 극도로 위험합니다! 수백년 동안 도망자 생활을 해 오고 있고, 저 위에 쓰여 있는 모든 마법, 아니 그 이상을 다룰 수 있습니다. 팀에 들어간다면, 임무를 위해 목숨을 걸어야 할 겁니다.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/C3HqCbPL-a19.webp'
        },
        {
            id: 'assist_vap', title: '가상 승천 프로젝트', cost: 'Costs 0 FP',
            description: "가상 승천 프로젝트는 홍옥의 의회가 후원하고 마그라가 제안한 계획입니다. 다른 우주의 존재에게 연락을 취해, 가능하다면 우리의 의식을 더 안전한 곳으로 옮길 수 있도록 그들의 협조를 얻어내는 것이죠. 간단히 말하면 서서히 허물어져 가고 있는 지금의 우주에서 다같이 탈출하자는 뜻입니다. 정든 고향을 떠나는 것은 정말 슬픈 일이지만, 많은 이들은 이 계획이 어두운 미래에 대비한 현실적인 해결책이라고 생각합니다. 물론, 우려의 목소리도 있습니다. 그렇게 연락이 닿은 존재들이... 사악한 마음을 먹는다면, 우리는 어떻게 될까요?",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BHZ84nhF-a20.webp'
        },
        {
            id: 'assist_rrp', title: '현실 회복 프로젝트', cost: 'Costs 0 FP',
            description: "현실 회복 프로젝트는 어머니께서 후원하시고 아라벨라가 제안한 계획입니다. 현재 우주에 만연한 불안정함을 해결하고 쇠락하는 우주를 회복시키는 것이죠. 사실 이 프로젝트의 진행 속도는 아주 느립니다. 그림자 용의자나 신스루 마녀단과 같은 문제의 원인을 아직도 뿌리뽑지 못했으니까요. 따라서 지금은 본격적인 회복 작업을 개시하기 전, 일단 이들을 확실히 제압하는 것을 일차 목표로 두고 움직이고 있습니다. 하지만 현 상황을 알고 있는 대다수는 이 프로젝트를 그저 허황된 꿈이라고들 합니다.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Y7W244YS-a21.webp'
        },
    ],
    finishingTouches: [
        {
            id: 'moving_out', title: '분가', cost: '소모값 변동',
            description: "가족을 따나서 살고 싶다면 새 집을 살 수 있습니다. {i}1페이지{/i}에서 집의 종류와 {w}업그레이드{/w}를 결정할 수 있습니다. 처음은 무료이고, 그 후로는 행운 점수 3점이 필요합니다. 아니면 부모님께 휴가지를 물려받을 수도 있습니다.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/KpMsN670-b1.webp'
        },
        {
            id: 'bride_to_be', title: '예비 신부님', cost: 'Costs -3 FP',
            description: "당신의 {w}동료{/w}, 또는 풋사랑을 한 {w}클래스메이트{/w} 중 하나를 고르세요. 당신은 언젠가 그 사람과 결혼하게 될 겁니다. 평생을 함께할 아름다운 인연이니까, 상대를 제대로 골라야 해요!",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BV0SBs3C-b2.webp'
        },
        {
            id: 'mentor_career', title: '멘토', cost: '소모값 변동',
            description: "당신이 고르지 않았던 {w}클래스메이트{/w}를 고르거나, 새로 클래스메이트를 만들 수 있습니다. 이 때, {fp}행운 점수가 1점{/fp} 적게 소모됩니다 (다른 비용 감소는 적용되지 않습니다). 당신이 고른 사람은 공손하게 당신을 따르는 제자가 됩니다. 당신이 시킨 작은 일들을 이것저것 하면서, 당신의 경험과 지혜를 배우고 익혀 나갈 거에요.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0y5PF52X-b3.webp'
        },
        {
            id: 'joys_of_parenting', title: '부모의 기쁨', cost: 'Costs -8 FP',
            description: "당신은 운 좋게도 마법소녀 양육 프로그램에 당첨되어, 새롭게 태어나는 마법소녀를 기를 수 있게 되었습니다! {i}참고 페이지{/i}에서 {w}동료 점수 50점{/w}으로 당신이 기를 마법소녀를 디자인할 수 있습니다. 평범한 아이들은 언제든지 입양할 수 있지만, 마법소녀를 직접 키우고 싶다면 이 선택지를 골라야 합니다.",
            imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/k6Sc6GXB-b4.webp'
        },
    ]
};

export const COLLEAGUES_DATA: Colleague[] = [
    { id: 'halynn', name: 'HALYNN', cost: 'Costs -5 FP', birthplace: 'Halidew Station', signature: 'Tinkerer', otherPowers: 'Master Mechanic I, Roboticist II, Kaboom!, Max Security, Venture Capitalist, Smarts +', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1tPM8mqG-c1.webp', description: "Halynn is a legend of Halidew Station, but few people even know her name, for her many inventions and constructions are signed under the pseudonym {i}R.K. Teller.{/i} She's pushed clockwork magitech to its absolute limits, having created automatons almost indistinguishable from human beings or ornate towers that can completely transform at the push of a button. Yet she avoids any fame or fortune, having learned young that they both bring about more pain than joy.\n\nA genius mind, she can macgyver impossible solutions to almost any predicament given even the most trifling resources. Clockwork machines automatically make her bed, brush her teeth, get her dressed, make her breakfast, etc every morning, and she'd be happy to share them. Her machines might be making her a bit lazy, though; she definitely prefers they do all her fighting for her. She'd be enamored if you were also the creative type, and you two could talk shop." },
    { id: 'lamonia', name: 'LAMONIA', cost: 'Costs -4 FP', birthplace: 'Halidew Station', signature: 'All-Seeing', otherPowers: 'The Promised Light of Morelli, The Perfect Stranger, Tears in Space, Cloaking, Self Duplication, Vitae Potions, Water of Life, Charisma +', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5xh0bDGZ-c2.webp', description: "Lamonia's one of those Gonzo journalist types — you know, living on the road, always trying to be where all the most interesting, weird stuff is going on so she can write articles about it with her signature sardonic, vivid style. She's most comfortable around a nice warm campfire in the wilderness, and likely hasn't slept with a roof over her head in years. She's lived an absurdly storied life, and can tell a million tales that'll make you laugh, cry, or shiver in fear.\n\nShe's a folksy type, easily integrating with and soaking up the authentic cultures of the places she visits. Only hang out with her if you can keep up, since she's always sniffing out a new oddity or adventure. She has a thing for psychedelics. She's a total laugh riot, though you can tell she has a dark side under that — after all, she's witnessed some terrible things. At least her campfire cooking is {i}unbelievable;{/i} there's nothing better to enjoy beneath a beautiful night sky with her." },
    { id: 'brook', name: 'BROOK', cost: 'Costs -4 FP', birthplace: 'Halidew Station', signature: 'Dehexification', otherPowers: 'Ace in the Hole, Cursemaker\'s Cookbook, Psychic Force II, Arcane Matter, Power Sight, Power Share, Power Theft, Chloromancy', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0jQ1LQWW-c3.webp', description: "A pack of foxfolk lived simple, comfy lives in the forest when a stampede of ravenous, fiery Nethe appeared able to drive them into extinction. With no other option, Brook offered the Wishkeeper, the sentient \"star\" in the northern sky, a great and terrible sacrifice in exchange for becoming one of the only mundanes to acquire magical power. Nobody knows what she sacrificed, though some rumor her sibling's disappearance at around that time might be related...\n\nWhatever happened, it drove her village to send her into exile, despite her having saved all their lives. She was her town's beastmaster due to her sheer love for animals, so her new powers only made her better at her job. She is incredibly cuddly and affection, and just between us: that huge tail makes a great pillow. Having lived a primitive life, she's fascinated by even the simplest technologies. She seems chipper, but at night, it seems she's ravaged by nightmares..." },
    { id: 'jophiel', name: 'JOPHIEL', cost: 'Costs -5 FP', birthplace: 'Shinar', signature: 'Guardian Angels', otherPowers: 'Ice Cold III, Pyromaniac III, Rejuvenating Bolt, Healing Bliss', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/738N60Q-c4.webp', description: "Not exactly a mage, though the distinction is largely semantic. She is known as an angel, one of the entities created personally by the Mother in order to tend to the Guardian of Eden, doing small chores and warding off an threats. Angels are sometimes sent down from above the Sky in order to enact the Mother's will on Earth. Jo's job appears to be to keep an eye on this latest crop of special, unusually powerful mages, and she's more than excited for the opportunity.\n\nShe's always full of childish excitement, as this is her first time down here on Earth. Even things as simple as trying pizza or watching TV are totally new to her and make her jump with joy. She also hasn't had a mortal friend before, so once she's attached to you, she's going to stick to you like glue, adoring any attention given to her like a big, glorified golden retriever. She knows to get serious when lives are on the line, however, and wields a huge holy scythe with immense power." },
    { id: 'lilith', name: 'LILITH', cost: 'Costs -4 FP', birthplace: 'Shinar', signature: 'Vampirism', otherPowers: "Cursemaker's Cookbook, Life Drain, Hypnotist, Strength +, Charisma +", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Xk6Y9GVN-c5.webp', description: "Matriarch of the Nokomis family and mother of Thalia, known for truly putting fear into the hearts of her daughter's bullies. Unlike her young and inexperienced daughter, she doesn't have to go around boasting about vampiric superiority over everyone; just the way she carries herself, the smile on her face as she looms over other mages (being 6'5\"), emanates an aura of superiority without her needing to say a word. She's about as ancient as mages come...\n\nStill, she's a fun woman, albeit the mischievous sort, prone to narrowing and messing with the people around her. You can never tell if she's being serious, or whether this is all just a game. She's like a cat surrounded by mice, and she's singled you out only because you're \"cute\" and fun to her. That silky voice just leaks into one's subconscious and leaves people spellbound. Recently, she's been researching spells that have been long forgotuthveqojtx7dhzacsm6" },
    { id: 'isadora', name: 'ISADORA', cost: 'Costs -3 FP', birthplace: 'Shinar', signature: 'Love Potion', otherPowers: 'Masquerade, Psychic Vampire, Hypnotist, Thoughtseer, Memory Lane, Mental Block, Lucid Dreamer', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G3W54ghL-c6.webp', description: "The old princess Evangeline lived a happy life until she learned she had a pseudo-Distortion that caused all her children to be born with a fast-acting and quite gruesome terminal disease. Thrown into desperation and despair, she attempted to create the daughter of her dreams through... {i}other{/i} means. This resulted in this poor half-formed puppet, unnerving onlookers with the faint cracks in her glassy eyes and the twitchy way in which she moves.\n\nDeprived of a mother's love when Evangeline committed suicide, Isadora now obsessively craves love wherever she can find it, but is hampered by how awkward and eccentric she is. She has a record of stalking those she sets her eyes upon, and if reciprocated, she will only grow more possessive. If you're smart and very lucky, you can turn her from dangerous stalker to simple religiously devoted fangirl. If you can't, she will just ruin your life, or maybe end it." },
    { id: 'luxxy', name: 'LUXXY', cost: 'Costs -4 FP', birthplace: 'The Unterseeisch', signature: 'Aquatic Force', otherPowers: 'Thermal Weaponry, Ice Cold III, Psychic Force II, Plasma Strike, Energy Channel, Sonic Boom, Charisma +', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/608cv7Js-c7.webp', description: "You'd think one wouldn't get much social interaction down in the deepest trenches of the ocean, but she's actually pretty well-adjusted. She lives in Blackbrire, the deepest city in all of the Unterseeisch, and she's so used to the dark down there that she must use special sunglasses when coming to shore. She's motherly and kind, but sick to death of being judged for her admittedly quite frightening appearance.\n\nExpert her to be delighted if you gave her a chance. She'll get attached quickly and become very concerned for your safety; when you're in danger, she can transform into this massive sea serpent that look like a mix of an anglerfish and a frilled shark. It's kinda scary, but also pretty cool. She can also switch between having legs, and being a sort of mermaid. She's an expert at deep water herbology, brewing many potions to keep you healthy and strong. She longs to see as many wonders of the surface world as she can." },
    { id: 'everild', name: 'EVERILD', cost: 'Costs -5 FP', birthplace: 'The Unterseeisch', signature: 'Master Mechanic II', otherPowers: 'Forcefield, Defensive Circle, Aquatic Force', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Q3gfmrsP-c8.webp', description: "Cap'n of the ol' M.S. Pantheon, the fiercest ship on the seas, an immense battleship which she practically built with her own two hands! It can even transform into a similarly massive nuclear submarine and dive into the trenches. Its purpose is slaying sea monsters before they can threaten cities, and the ship and her crew have taken down a few Grimsayers single-handedly! An admiral of the Holy Navy, she's beloved by all her crew for her almost motherly demeanor, caring about each of them individually.\n\nDespite having a busy job and hundreds of people vying for her attention, she'll still somehow find time for you, often taking you on personal tours of the most beautiful parts of the sea. She's a seabird at heart and feels antsy if she stays on land for too long. She's the playful sort, but her jokes are always incredibly cheesy, albeit in an endearing way. She's a bit behind the times and confounded by new trends and technology." },
    { id: 'leona', name: 'LEONA', cost: 'Costs -5 FP', birthplace: 'The Unterseeisch', signature: 'Divine Clay', otherPowers: 'Tears in Space, Energy Channel', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mVwMkg45-c9.webp', description: "When the Nephilim, ancient mages who refused to sign the Sinthru Covenant, fled beneath the seas to escape persecution, they founded the Artificers Guild, which holds exclusive rights to all architecture in the Unterseeisch. These are the most difficult design jobs on Earth, given the complex lattice of enchantments needed to make subaquatic living just as comfortable as life on the surface. Leona is among the latest crop of Artificers, and perhaps one of the most talented among them, weaving whole cities by herself.\n\nShe was the much mocked nerdy girl at her trade school, and while she's long trained her charisma to come off as more 'normal', you can still easily sense her geeky side once you get to know her. She's incredibly humble about even her most marvelous feats of creation, yet seems impressed by just about anything you do. As you become close friends, she'll get adorably excited just to see you, often rushing up for a giddy hug." },
    { id: 'egelina', name: 'EGELINA', cost: 'Costs -4 FP', birthplace: 'Valsereth', signature: 'Strength +', otherPowers: 'The Moon Samurai, Life Drain, The Reinman\'s Curse, Internal Manipulation, Rubber Physiology, Material Transmutation, Supersize Me, Speed +', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VY00FKj0-c10.webp', description: "Due to the influence of the Sun Forger and the later Holy Knights, Gohwood remains the most powerful and thus sovereign Dominion on Earth. Its refusal to modernize has resulted in many controversies, most notably the Corpse Queen; even after a distortion gave her chronic agony, her begging for death was refused, as it would be the ultimate treason to kill a queen for any reason. It was her loving royal guard, Egelina, who finally mercy killed her, before fleeing to the rival dominion of Valsereth to avoid reprisal.\n\nShe's youthful and carefree, yet still beholden to her values of honor and tradition. Energetic, she moves with the grace of an acrobat, and craves a life on the road experiencing all the world has to offer. She tries to act aloof, but you sense she likes you more than she lets on. Most were relieved she did what she did, but a few staunch traditionalists still make attempts on her life, only to be run through easily with her rapier." },
    { id: 'echo', name: 'ECHO', cost: 'Costs -3 FP', birthplace: 'Valsereth', signature: 'Summon Weather', otherPowers: 'Summon Creature, Psychic Force II, Energy Channel, Rejuvenating Bolt, Defensive Circle', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MwyqWTz-c11.webp', description: "She was created to be the attendant of a famous early verse that took the form of a sprawling onsen, a bastion of absolute relaxation and comfort for many influential and wealth figures, until a spurned employee uploaded a virus onto the verse out of spite. This caused the verse to gradually disintegrate — a problem for Echo, as she was entwined with the verse and could not leave. To save her life, her creator uploaded her mind into a artificial body, here in our reality.\n\nShe's honestly pretty... grumpy. She was made for a reality of infinite comfort, so our world is pretty miserable compared to what she's used to. With few ambitions of her own, she mostly just serves others, cleaning and attending to things like a dutiful, if grumbling, maid. She's a hard worker, but not much for conversation, either staying silent or making sardonic quips if bothered. Perhaps you could show her some wondrous things and convince her our world isn't that bad?" },
    { id: 'aelis', name: 'AELIS', cost: 'Costs -4 FP', birthplace: 'Valsereth', signature: 'Tree of Life', otherPowers: "The Reinman's Curse, Sustaining Bond, Flashback, Chloromancy, Botanic Mistresses, Maneaters", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gqJc9Cd-c12.webp', description: "Sister of Egelina, and without nearly the same prestige. She was sort of the black sheep of the family, avoiding work for the royal family on principle. After the whole Queen kerfuffle, she had to resist going \"I told you so\". Even though she was more-or-less cast out by the rest of her family, Egelina never turned against her, and the two sisters remain very close, even if they get on eachother's nerves, as siblings do.\n\nShe's now a priestess of the Garden of Babylon, a sacred place so proliferated with sylvan powers that any unworthy who enter have thorns fill their lungs and roses replace their eyes. Despite this great responsibility, she is even more laid-back and childish than her sister, often using her floral powers to pull pranks, especially on those she considers uptight. She emanates the sweet smell of flowers so intensely it makes you dizzy. She constantly prods you to relax more often, and loves getting to just hang out with you." },
    { id: 'silvaria', name: 'SILVARIA', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'The Promised Light of Morelli', otherPowers: 'Malrayoots, Shed Humanity I, Personification, Self Duplication, Bolstering Tonics, Magecraft Boosters, Vitae Potions, Mass Production', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/FkG9wYpF-c13.webp', description: "If I had to describe her in a couple words, I would call her the 'cool aunt' — fun-loving, laid-back and with a hundred neat tricks up her sleeve, but also {i}deeply{/i} irresponsible. Don't even get me started on the time she nearly brought about a zombie dragon apocalypse! Through some combination of her luck and skill, though, all her mischief works out okay in the end. She's great company as a friend for her playfulness and sense of humor, but can be frustrating as a teammate due to her flakiness and devil-may-care attitude. Personally, I don't think she's fully matured yet.\n\nShe is currently the professor of Alchemy at Eglaesaria, and very popular with the girls there for her perfect combo of fun and motherliness, often opting for 'hands-on' field trips which sometimes lead to trouble. In a group, she'll probably be the 'team mom', doing whatever she can to make your life easier and more exciting, and doesn't mind flaunting the rules." },
    { id: 'sabeline', name: 'SABELINE', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'Subatomic Manipulation', otherPowers: 'Ace in the Hole, Strength +, Speed +', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/20Q78vDY-c14.webp', description: "One of the Holy Knights, an army that fought back the Sinthru rebellion long ago, and has since spread peace and justice through the world at the end of a blade. They've been criticized lately for being a little overzealous, especially Sabelline herself, being so full of righteous fury.\n\nShe's your typical knight, dedicated to enacting her own brand of justice upon the wicked. She is particularly passionate about her ideals of chastity outside of wedlock, so I'd recommend you not try anything untowards! She was in a spot of trouble when a business owner at a side job threatened to fire her in an attempt to coerce her for 'favors'... so she sliced him clean in half! Thank the Mother for modern healing magics. Her tough and silent exterior may seem intimidating at first, but she's a total softie underneath who will melt in your arms at a single hug. She works through her doubts and regrets with poems - if you found them, she'd be so embarrassed!" },
    { id: 'tempest', name: 'TEMPEST', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'Hokuto Senjukai Ken', otherPowers: 'Forsake Humanity II, Pyromaniac II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0jR3W5K2-c15.webp', description: "When she was child, she was one of the seven wyverns captured and made into power generators and slaves as part of the maniacal scheme of a secret Sinvain. Said scheme likely would've done incalculable damage, but Rosalina and her fellow wyverns, after a decade of enslavement, staged a daring uprising that managed to slay the Sinvain — though, tragically, Rosalina emerged the only survivor. This has left her often quite moody or standoffish.\n\nIn many ways, she has the typical teenage angst you'd expect of her age, often preoccupied with trends, bad music, and trying too hard to act aloof to hide her deeper traumas and insecurities. You seem to be the only one that can crack her shell so far, and make her laugh and smile at times, even if she tries her best to hide it. She has a short temper which can often result in pointless brawls with rude strangers. She could make a great fighter if only she matured a little." },
    { id: 'alina', name: 'ALINA', cost: 'Costs -5 FP', birthplace: 'New Palisade', signature: 'Masquerade', otherPowers: 'Hypnotist, Camouflage, Memory Lane, Mental Blocks, Heavily Armed, Grey Goo, Weaponsmith, Psychic Force II, Forcefield', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cHpsqjy-c16.webp', description: "Alina wanted to be an IDPA special agent since she was little, and while she was considered a weak mage when she younger, she worked her ass off to make her dream a reality. Most agents get their youthful optimism crushed after only a few months of dealing with the worst humanity has to offer... but not Alina. She's still brimming with idealism, passionately dedicated to making the world a better place no matter what it takes. Truly incorruptible, she keeps her upbeat spirit regardless of the horrors she've faced, although her morality can be a little bit black-and-white.\n\nShe's an expert at undercover operations, using her mastery of illusions and acting skills to assume entirely new identities on a dime. She prefers to use her charisma to resolve situations without violence. Once attached to you, she'll be a bit overprotective, almost like a fretting mother. Shy at first but loves physical affection, hugging friends and cuddling lovers." },
    { id: 'h.a.l.e.y', name: 'H.A.L.E.Y', cost: 'Costs -4 FP', birthplace: 'New Palisade', signature: 'Nanite Armor III', otherPowers: 'Domain Master II, Digital Infiltrator, Nanite Form', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/qF3JxNJr-c17.webp', description: "As a novelist from long ago once wrote, \"any A.I. smart enough to pass a Turing test is smart enough to know to fail it.\" Indeed, one of the first artificial souls of the Sinusure Doctrine, H.A.L.E.Y was dismissed as yet another duds — offering her plenty of opportunity to leak out onto the Web, adopting her own Net Avatar. After the Laser Focus leak, she was able to compose her own physical body out of nanites, with the help of the quite large fanbase she'd built up for herself across the Web. Indeed, she's a celebrity among nerdy types, known for her digital concerts.\n\nShe has an outsider perspective on mankind and thus considers us all fascinating research subjects, studying our many eccentricities. She's bright and chipper, but can make many people uncomfortable with her lack of personal space and prying questions. She keeps massive archive of data on everyone she knows for unknown purposes, and always wants to know more." },
    { id: 'sable', name: 'SABEL', cost: 'Costs -3 FP', birthplace: 'New Palisade', signature: 'Perfect Stranger', otherPowers: 'Digital Infiltrator, Camouflage, Nanite Armor I, Self Duplication, Domain Master II, NO5T4LG14.FMJ, Colorless, Odorless', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/h1YXMqyx-c18.webp', description: "New Palisade is a dog-eat-dog city where getting ahead means stabbing your colleagues in your back — sometimes literally. Mages are highly coveted as assassins for obvious reason, and Sable is particularly notorious among them for being willing to take contracts against other mages from time to time. No one can tell what those daggers are made out of it, but it seems like they can slice through {i}any{/i} material.\n\nShe's definitely the silent type, with little energy when not completing contracts, usually content to meditate or enjoy some literature with a glass of wine You get the feeling she kills just because it's the only career she's really good at. She tries her best to separate work from her personal life, and will refuse to take out contracts against friends or, rarely, people she feels really don't deserve it. You don't know what she's hoarding all this money for, given her simple lifestyle, but you suspect she's trying to settle an old debt." },
    { id: 'regina', name: 'REGINA', cost: 'Costs -4 FP', birthplace: 'The Rovines', signature: 'Supersize Me', otherPowers: 'Shed Humanity II, Life Drain, Pyromaniac II, Plasma Strike, Psychic Force I, Sensory Master, Strength +, Energy Channel', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Y49pqR3n-c19.webp', description: "It was Merlin who once presented a spell that could 'tame' the Allmillor. He demonstrated it on a Grimsayer, granting it sapience, making it humanlike, and producing, well, Regina. I wish we could study his spell, but he immediately disappeared again to work on another wacky project or something. Male mages, or \"wizards\", tend to be.... weird. Anyway, naturally, such a transition was... {i}disorienting{/i} for Regina.\n\nShe's too animal-like to fit in in society, often extensively sniffing new people she meets or preferring growls and gestures over language. She's happiest when she's towering over everyone else, but in her new form, she can't maintain that size 24/7 like she used to, so she can be depressed at times. She loves to climb atop skyscrapers and roar, echoing for miles. When at normal sizes, she tends to hide away from the world, but you're an exception as it seems you comfort her in this state." },
    { id: 'dolores', name: 'DOLORÈS', cost: 'Costs -4 FP', birthplace: 'The Rovines', signature: 'Sensory Master', otherPowers: 'Ace in the Hole, Mage\'s Familiar II, Colorless, Odorless, Vitae Potion, Personification, Aquatic Force, Shed Humanity I, Camouflage', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/tP8F2p7q-c20.webp', description: "The hospitality of the Occitanians among the swamps of the Rovines is so legendary, you hardly feel like a stranger there; they make guests feel more like cherished family members at Thanksgiving. And their food is just to {i}die{/i} for! The gator girl Dolorès is their patron guardian, although the complete lack of any threats out there has made her quite lazy; like a real alligator, she spends most of her time snoozing on a rock, bathing her belly in the warm sun.\n\nIt's almost amazing how quick she can switch 'modes', full of vigor when fighting off an intruder, only to yawn and stumble off to nap again immediately after. She's got permanent bedhead at this point. But they say laziness births creativity, and indeed, she has a knack for solving every problems in the easiest way possible, and her level head allows her to calm down party members who get too worked up. Plus, she loves to cook and knows every Occitanian recipe!" },
    { id: 'darlina', name: 'DARLINA', cost: 'Costs -3 FP', birthplace: 'The Rovines', signature: 'Human Marionettes', otherPowers: 'Strength +, Charisma +, Sensory Master', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xtVzS5BY-c21.webp', description: "The swashbuckling chieftess of a mercenary gang consisting mostly of former knights and soldiers who were discharged for one reason or another and dumped onto the streets with no valuable skills besides combat. They're famous among mercenaries for never betraying their own clients, even if offered a higher counter-offer, and thus coveted to resolve conflicts between the many bickering city-states of the Rovines.\n\nMuch of her profits go towards philanthropy, but she makes no pretenses of being a Robin Hood figure; she holds no higher ideological purpose than making money and asserting her freedom from all authorities. She's a daredevil who lives for the thrill of battle and has no fear of death. She has a soft side, though, expressly forbidding rape or the harming of non-combatants by her troops. She has a unique pseudo-Distortion; if her left eye is ever uncovered, it releases enough arcane energy to level a village, and nearly kills her." },
    { id: 'michizoe', name: 'MICHIZOE', cost: 'Costs -4 FP', birthplace: 'Jipangu', signature: 'Charisma +', otherPowers: "Cursemaker's Cookbook, Life Drain, Hypnotist, Strength +", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7dCtgxf4-c22.webp', description: "Lives right in the heart of Jipangu, always wanting to be wherever the party is. Every festival, celebration, or just night at a crowded tavern, you can bet Michizoe will be somewhere there singing karaoke and getting drunk on saké. Perhaps she's just making up for lost time: raised to be a vigilant for the tomb of the Last Empress, she spent her childhood forbidden from making friends, laughing or dancing, or even speaking!\n\nNowadays, she's the preeminent extrovert, never missing a chance to make a new friend or engulf herself in a crowd. She seems to be particularly attached to you, encouraging you to join her to parties and meet new people. Her list of connections seems endless; {i}everywhere{/i} you go, she happens to know someone there who can help you get special privileges. Despite this, she's smart and responsible enough to take things seriously when warranted, and is never flakey, though maybe a bit drunk on the job." },
    { id: 'ishikura', name: 'ISHIKURA', cost: 'Costs -5 FP', birthplace: 'Jipangu', signature: 'Don\'t Blink', otherPowers: 'Quick Twitch, Strength +, Energy Channel', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MD6HK35G-c23.webp', description: "It's hard to believe something so kind is one of the most feared swordswomen. You know that thing where a warrior unsheathes their katana for a split second and everything around them falls in half? Yeah, she's kinda like that. She was taught by the legendary Yoru Shinobu and instilled with a rigorous code of honor, making her extremely hesitant to draw her blade unless she's convinced she'll be saving more lives than she's ending.\n\nTrained in effective altruism, she tends to travel from place to place leaving each village better than she found it. She is extremely good with children, often running childcare programs for orphans and such, and yearns to be a mother one day. At times, she can get so concerned for others she forgets to take care of herself, or acts as if frustrated she can't solve all the world's problems. She prefers to rehabilitate over evil-doers rather than split them in twain with her katana, but she's devastating in combat when it comes to it." },
    { id: 'jin', name: 'JIN', cost: 'Costs -4 FP', birthplace: 'Jipangu', signature: 'Camouflage', otherPowers: 'Perfect Stranger, Life Drain, Spirit Medium, Fata Morgana Curse, Rise from your Graves, Smarts +', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wFq33t7V-c24.webp', description: "Long ago, a woman was falsely accused of placing a curse on a family in the village of Arimine, and killed. Even now, the village is ashamed of its past, and haunted by it in the form of strange Allmillor resembling great canines composed of shadows — the many familiars of the woman killed, rendered endlessly reincarnating beasts by the unholy grief. Jin, the Huntress of Wolfpine, tracks these creatures down with the only sacred bow capable of granting them a merciful reprieve in oblivion.\n\nA strange silence is veiled over the town, and Jin is no exception; quiet and wistful, she appears as if always lost in thought, and it's sometimes hard to snap her out of her contemplation. She prefers expressing herself with music over words. As it happens, ramen is one of the only things that can put a smile on her face — though once she comes to like you, you'll be able to do the same, too. In combat, she's silent and, above all, patient." }
];

export const COLLEAGUES_DATA_KO: Colleague[] = [
    { id: 'halynn', name: '핼린', cost: 'Costs -5 FP', birthplace: '할리듀 스테이션', signature: '땜장이', otherPowers: '전문 기계공 I, 로봇술사 II, 콰광!, 최고 보안 등급, 벤처 자본가, 지능+', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1tPM8mqG-c1.webp', description: "핼린은 할리듀 스테이션의 전설이지만, 그녀의 이름을 아는 사람들은 얼마 없습니다. 그녀가 만든 수많은 발명품이나 건축물에는 {i}R.K.텔러{/i}라는 가명이 대신 붙어 있기 때문이죠. 핼린은 시계태엽 마법공학을 극한의 수준까지 끌어올려, 사람과 구분할 수 없을 정도의 자동인형이나 버튼 한 번 누르면 변신할 수 있는 정교한 탑들을 만들었습니다. 하지만 그런 발명품들을 만들고도 부나 명예를 쫓지는 않습니다. 이미 어릴 때부터 그것들이 기쁨 이상으로 수많은 아픔을 가져온다는 것을 깨달았거든요.\n\n이 천재 마녀는 웬만한 문제 상황은 온갖 기상천외한 기계를 만들어서 헤쳐나갑니다. 가장 열악한 환경에서도 말이죠. 매일 아침 시계태엽 인형들이 핼린의 이불을 개고, 이빨을 닦고, 옷을 입히고, 아침을 차려 줍니다. 친구가 생기면 그 친구에게도 인형 하인들을 만들어 주겠죠. 그런데 이 기계들 때문에 그녀가 몸 쓰는 걸 좀 싫어한다는 게 문제라면 문제겠네요. 다른 건 몰라도 싸울 일이 있으면 무조건 인형들을 대신 내보낼 거에요. 만약 당신이 이런 쪽으로 창의적인 사람이라면 그녀는 당신에게 반해 버릴 겁니다. 아마 둘이서 시간 가는 줄 모르고 이야기를 나누게 되겠죠." },
    { id: 'lamonia', name: '라모니아', cost: 'Costs -4 FP', birthplace: '할리듀 스테이션', signature: '천리안', otherPowers: '약속된 모렐리의 빛, 완벽한 타인, 공간 균열, 위장, 자가 복제, 생명혈 물약, 생명수, 카리스마+', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5xh0bDGZ-c2.webp', description: "라모니아는 전형적인 열혈 기자입니다. 그러니까, 항상 여기저기 돌아다니면서, 특이하거나 재미있는 사건이 일어났다 하면 바로 달려가서 기사를 쓰죠. 특유의 그 생생하지만 냉소적인 문체로 말이에요. 라모니아는 허허벌판에 모닥불 하나 피워놓은 채 밤을 보내는 걸 제일 좋아합니다. 아마 지붕 없이 잠을 잔 지도 몇 년은 됐겠죠. 그녀는 정말 파란만장한 삶을 살아왔고, 당신을 웃고, 울고, 어쩌면 무서움에 떨게 할 이야기들을 정말 많이 해 줄 수 있답니다.\n\n라모니아는 성격이 털털해서 어디를 가든 그곳의 문화나 관습 같은 것들을 쉽게 받아들입니다. 만약 같이 지내고 싶다면 마음의 준비를 단단히 해야 할 겁니다. 항상 새로운 모험은 없나, 재미있는 건 없나 찾아다니거든요. 아, 그리고 사이키델릭한 것들도 좋아하구요. 정말 예능감 넘치는 사람이지만, 그 뒤에는 어두운 일면이 있다는 것도 느낄 수 있을 겁니다. 기자 생활을 하면서 끔찍한 것들도 많이 보고 겪었으니까요. 적어도 그녀가 모닥불을 피우고 해 주는 요리는 대단합니다. 그녀와 함께 보는 아름다운 밤하늘을 더 멋지게 만들어 줄 거에요." },
    { id: 'brook', name: '브룩', cost: 'Costs -4 FP', birthplace: '할리듀 스테이션', signature: '저주 해제', otherPowers: '비장의 한 수, 저주술사의 고서, 염동력 II, 비전 물질, 마법 간파, 마법 공유, 마법 도둑, 식물술사', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0jQ1LQWW-c3.webp', description: "옛날 옛적에 숲 속 마을에서 평화롭게 살아가는 여우 수인들이 있었습니다. 그런데 어느 날, 굶주리고 난폭한 네테 떼가 나타나 수인들은 존망의 위기를 맞게 되었죠. 다른 방법이 없던 브룩은 소원을 들어 준다는 북쪽 하늘의 \"별\"을 보고 기도를 했습니다. 평범한 수인의 몸으로 마법의 힘을 얻은 대가로, 거대하고 끔찍한 희생을 치렀죠. 그게 무엇인지는 아무도 모르지만, 소문에 따르면 그 때쯤 그녀의 동생이 사라졌다고 합니다...\n\n어쨋든 브룩은 마을 사람들을 모두 구할 수 있었지만, 치렀던 희생으로 인해 결국 추방당하고 말았습니다. 그나마 원래 동물을 좋아하는 성격이라 마을에서도 동물들을 도맡아 기르고 있었는데, 새롭게 얻게 된 마법 덕분에 일이 더 편해졌다고 해요. 브룩은 아주 사랑스럽고 정도 많고, 이건 저희 둘만의 비밀인데, 그 커다란 여우 꼬리를 베고 자면 정말 폭신해요. 수인 마을에서의 삶은 꽤 원시적이었기 때문에 단순한 기계만 봐도 아주 신기해한답니다. 하지만 이렇게 명랑한 모습을 보여 주다가도 밤만 되면 그렇게 악몽을 꾸죠..." },
    { id: 'jophiel', name: '조피엘', cost: 'Costs -5 FP', birthplace: '시나르', signature: '수호천사', otherPowers: '한기 III, 방화광 III, 치유의 화살, 황홀한 치유', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/738N60Q-c4.webp', description: "큰 의미가 있는 건 아니지만, 조피엘은 엄밀하게는 마녀가 아닌 천사입니다. 천사들은 어머니께서 직접 창조하신 존재들로 에덴 정원을 지키며 이것저것 잡일을 하고 외부의 위협을 막아내죠. 가끔은 천사들이 어머니의 뜻을 받들기 위해 지구로 내려오기도 하는데, 조피엘도 그렇게 내려온 천사입니다. 이번 세대의 특별히 강력한 마법소녀들을 지켜보는 일을 맡게 된 것 같은데, 그런 일을 맡게 되어 아주 들떠 있죠.\n\n조피엘은 지구에 온 것이 처음인지라 항상 어린아이처럼 들떠 있습니다. 그녀에게는 피자를 먹거나 TV를 보는 것 같은 간단한 일도 아주 새롭고 기쁘고 재미있답니다. 인간이나 마녀 친구를 사귄 적도 없기 때문에, 한번 당신과 친해지면 껌딱지처럼 당신에게 꼭 붙어다닐 거에요. 그리고 당신이 관심을 주면 커다란 골든 리트리버처럼 행복해하겠죠. 그래도 목숨이 걸린 심각한 상황에서는 사뭇 진지해집니다. 그럴 때는 강력한 힘이 담겨 있는 거대한 신성의 낫을 휘두르는 모습을 보게 될 겁니다." },
    { id: 'lilith', name: '릴리스', cost: 'Costs -4 FP', birthplace: '시나르', signature: '흡혈', otherPowers: "저주술사의 고서, 생명력 흡수, 최면술사, 힘+, 카리스마+", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Xk6Y9GVN-c5.webp', description: "노코미스 가문의 여주인이자 탈리아의 어머니인 릴리스는 일단 딸을 괴롭히는 사람들이 있으면 그들에게 무시무시한 공포를 심어 줍니다. 그녀는 어리고 경험도 없는 탈리아와는 다르게 뱀파이어의 우월함을 뽐내고 다니지 않습니다. 그저 몸짓 하나하나로, 다른 마녀들을 195cm의 큰 키로 내려다보면서 짓는 그 미소로 말 한 마디 없이 좌중을 압도하죠. 가장 최초의 마녀들과 견줄 만큼 오래 살아온 존재이기도 하구요...\n\n그래도 릴리스는 성격이 정말 유쾌합니다. 물론 유쾌하다는 게 주변 사람들을 놀리고 골탕먹이는 걸 좋아하는, 장난기 많은 쪽이긴 하지만요. 그녀가 진지하게 당신을 대하는 건지, 그녀만의 재미있는 게임인지는 절대 알 수 없을 겁니다. 그녀는 마치 생쥐들을 옆에 둔 고양이 같습니다. 그 생쥐들 중 당신을 골라낸 이유는 당신이 \"귀엽고\" 재미있기 때문입니다. 릴리스의 고혹적인 목소리를 들으면 누구라도 그녀의 매력에 홀린답니다. 최근에는 마법을 좀 연구하고 있다고 하는데, 그게 오래 전 잊혀ㅈ솦ㄷ배ㅓㅅㅌ7옼ㅁㅊ6" },
    { id: 'isadora', name: '이사도라', cost: 'Costs -3 FP', birthplace: '시나르', signature: '사랑의 묘약', otherPowers: '가면무도회, 정신 흡수자, 최면술사, 생각을 읽는 자, 기억의 길, 정신 차단벽, 꿈의 방문자', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G3W54ghL-c6.webp', description: "먼 옛날, 공주 에반젤린은 행복한 삶을 살고 있었습니다. 그녀가 가진 가왜곡체 때문에 그녀가 낳은 아이들이 모두 치명적인 병에 걸려 요절하게 된다는 것을 깨닫기 전까지는 말입니다. 절망과 절박함에 사로잡힌 그녀는 그녀가 원하던 완벽한 딸을... {i}다른 방식{/i}으로 만들어 내려 했습니다. 하지만 그 결과는 반쯤 만들어진 퍼펫이었죠. 유리 같은 눈에는 살짝 금이 가고, 움직일 때는 몸이 이리저리 꺾여서, 주변 사람들을 불안하게 만드는 퍼펫이었습니다.\n\n에반젤린은 결국 자살했고, 어머니의 사랑을 받지 못한 이사도라는 사랑을 받기 위해 집착합니다. 하지만 그녀의 어색하고 기이한 모습 때문에 그게 쉽지가 않습니다. 그녀는 마음에 드는 누군가가 있으면 그렇게 스토킹을 합니다. 그러다 들켜도 그 집착이 더욱 심해질 뿐이죠. 당신이 운이 좋고, 머리도 좋다면, 이 위험한 스토커를 당신만의 헌신적인 팬으로 바꿀 수 있을 겁니다. 그렇게 하지 못한다면, 당신의 인생이 망가지겠죠. 어쩌면 당신의 목숨까지도요." },
    { id: 'luxxy', name: '럭시', cost: 'Costs -4 FP', birthplace: '운터시쉬', signature: '수류의 힘', otherPowers: '열 병기, 한기 III, 염동력 II, 플라즈마 타격, 에너지 집중, 소닉붐, 카리스마+', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/608cv7Js-c7.webp', description: "바닷속 깊고 깊은 해구에서 무슨 사회 활동을 할 수 있냐 생각하시겠지만, 럭시는 생각보다 적응력이 뛰어납니다. 럭시가 사는 곳은 운터시쉬에서 가장 깊은 곳에 있는 도시 블랙브라이어입니다. 그녀는 그 깊은 어둠에 너무 익숙한 나머지 뭍으로 올라오면 특수 선글라스를 껴야 하죠. 럭시는 모성애도 넘치고 친절합니다. 하지만 사람들이 그녀의 무서운 겉모습만 보고 성급하게 판단하는 것에는 진작에 학을 뗐습니다.\n\n당신이 기회를 준다면 그녀는 정말 기뻐할 겁니다. 금방 당신과 친해져서 당신이 위험하지 않게 지켜 줄 거에요. 당신이 위험해지면 주름상어랑 아귀를 반반 섞어 놓은 것 같은 거대한 바다뱀으로 변신한답니다. 좀 무섭긴 하지만 그래도 멋지죠. 그리고 럭시는 두 다리로 걸어다닐 수도 있고, 인어 같은 모습으로 변신할 수도 있습니다. 심해에서 자라는 식물에 대해서도 조예가 깊고, 그것들을 이용해 당신을 건강하게 만들어 줄 물약을 만들어 줄 수도 있어요. 그녀는 육지의 온갖 신기한 것들을 최대한 많이 겪어 보고 싶어합니다." },
    { id: 'everild', name: '에베릴드', cost: 'Costs -5 FP', birthplace: '운터시쉬', signature: '전문 기계공 II', otherPowers: '역장, 방어의 원, 수류의 힘', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Q3gfmrsP-c8.webp', description: "에베릴드는 전 해상에서 가장 무서운 전함인 판테온의 함장입니다. 더 놀라운 건 그녀가 이 거대전함을 사실상 혼자 힘으로 만들어냈다는 것이죠! 판테온에는 핵잠수함으로 변해 해구 속으로 잠수할 수 있는 기능도 탑재되어 있습니다. 이 전함의 주 임무는 도시가 위협받기 전에 바다 괴물들을 미리 처리하는 것인데, 함선 단독으로 그림세이어를 몇 번 제압한 적도 있어요! 에베릴드는 신성한 해군의 제독으로 모든 휘하 선원들의 사랑을 받고 있습니다. 부하들을 하나하나 챙겨 주는 그녀의 어머니 같은 모습 때문이겠죠.\n\n임무도 바쁘고 밑에 수백 명의 부하들도 거느리고 있지만, 에베릴드는 어떻게든 시간을 내서 당신을 만나 줄 겁니다. 보통은 당신을 데리고 바다에서 가장 경치 좋은 곳들을 구경시켜 줄 거에요. 그녀는 뼛속까지 뱃사람이라 육지에 너무 오래 있는 것을 불편해합니다. 그리고 장난기도 많지만, 개그가 너무 아재 같아요. 그래서 더 사랑스럽지만요. 그녀에게는 약간 시대에 뒤떨어진 면모도 있습니다. 육지에 발을 들일 때마다 보게 되는 새로운 기술과 트렌드를 따라가기 벅차한답니다." },
    { id: 'leona', name: '레오나', cost: 'Costs -5 FP', birthplace: '운터시쉬', signature: '신성한 점토', otherPowers: '공간 균열, 에너지 집중', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mVwMkg45-c9.webp', description: "먼 옛날, 네필림이라 불리는 고대의 마녀들은 신스루 마녀단을 거부하고 그들의 추격을 피해 깊은 바닷속으로 대피했습니다. 그 후 그들은 장인의 길드를 세워 운터시쉬의 모든 건축물에 대한 독점적인 권리를 갖게 되었죠. 사실 이곳에서 건물을 설계한다는 것은 지구상에서 가장 어렵습니다. 심해에서도 지상에 있는 것처럼 편안하게 살기 위해서는 온갖 마법들을 촘촘하게 걸어 둬야 하니까요. 레오나는 가장 최근에 장인 길드에 들어간 마녀들 중 하나입니다. 그리고 혼자서 도시 전체를 지어 낼 만큼 재능이 출중하기도 하죠.\n\n그녀는 학교를 다닐 때는 범생이 같다고 놀림도 많이 받았고, 그 때문에 좀 '평범해' 보이려고 나름대로 카리스마를 갈고 닦았습니다만, 당신이 레오나와 가까워지게 된다면 금방 그 괴짜 같은 면모를 발견할 수 있을 겁니다. 그녀는 자신이 만든 그 휘황찬란한 작업물에 대해서는 항상 겸손하지만, 당신이 하는 일이라면 작은 일이라도 감동받을 거에요. 당신이 그녀와 점점 친해질수록 그녀는 당신이 얼굴 한번 보자고만 해도 설레어할 겁니다. 당신을 보자마자 일단 한달음에 달려와 꽉 끌어안아 주겠죠." },
    { id: 'egelina', name: '에젤리나', cost: 'Costs -4 FP', birthplace: '발세레스', signature: '힘+', otherPowers: '월광의 사무라이, 생명력 흡수, 마부의 저주, 체내 조작, 고무고무 신체, 물질 연금술, 거대화, 속도+', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VY00FKj0-c10.webp', description: "태양 제련사, 그리고 이후에는 신성 기사단이 거쳐 간 곳인 고흐우드는 그 덕분에 지구상의 가장 강대한 국가이자, 주권국이 되었습니다. 국가적으로 근대화를 받아들이지 않는 기조가 많은 논란이 되기도 했었죠. 가장 유명한 사례가 바로 시체 여왕의 경우입니다. 왜곡체 때문에 불치병에 걸려 끝없이 고통을 받는 여왕이 자신을 죽여 달라 아무리 간청해도 그 누구도 듣지 않았습니다. 마치 이유를 불문하고 여왕을 죽이는 것은 대역죄라는 것처럼요. 결국 여왕이 총애하던 근위대인 에젤리나가 자비를 베풀어 그녀의 목숨을 거둔 뒤, 응징을 피해 경쟁국가 발세레스로 도피했습니다.\n\n에젤리나의 첫인상은 속 편한 청춘이지만, 그녀는 여전히 명예와 전통이라는 가치를 짊어지고 살고 있습니다. 그녀는 마치 곡예사처럼 우아함과 활기 넘치게 움직이고, 이곳저곳을 돌아다니며 세상의 모든 것들을 경험하고 싶어합니다. 당신에게는 짐짓 쌀쌀맞게 대하려고 하지만, 겉으로 드러내는 것보다 당신을 훨씬 더 좋아하는 것 같습니다. 이제는 그녀가 저질렀던 일을 많은 이들이 인정해 주고 있지만, 아직도 몇몇 극렬 전통주의자들은 대역죄인인 그녀를 처형하려 합니다. 오히려 그 쪽이 그녀의 칼에 당하지만요." },
    { id: 'echo', name: '에코', cost: 'Costs -3 FP', birthplace: '발세레스', signature: '기상 확산', otherPowers: '마수 소환, 염동력 II, 에너지 집중, 치유의 화살, 방어의 원', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MwyqWTz-c11.webp', description: "에코는 옛 가상 우주의 관리자 역할을 하기 위해 창조된 존재입니다. 그곳은 화려한 온천이 있어서 재벌들과 유명 인사들의 휴양지로 각광받는 곳이었습니다. 그런데 어느 날 그곳에서 해고됐던 직원이 앙심을 품고 가상우주에 바이러스를 업로드해 버렸습니다. 그로 인해 가상우주는 서서히 붕괴되어 갔고, 가상우주에 존재가 묶여 있던 에코는 꼼짝없이 당할 수밖에 없었습니다. 다행히도 창조자가 그녀를 구하기 위해 그녀의 의식을 현실의 인공 신체에 업로드했습니다.\n\n솔직히 말하면 에코는... 심술쟁이입니다. 무한한 쾌락이 가득한 세계를 위해 창조되었으니, 그녀가 알던 곳에 비하면 이 지구는 참으로 비참한 세상이니까요. 그녀에게는 딱히 목표랄 것이 없고, 그저 청소 같은 잡일을 하면서 다른 사람들을 섬기고만 있습니다. 좀 투덜거리긴 하지만 성실한 메이드 같죠. 에코는 거의 대화를 하지 않습니다. 묵묵히 일만 하거나 너무 귀찮게 굴면 짧게 몇 마디 비꼬는 게 전부입니다. 당신이 그녀에게 이 세상의 근사한 광경을 몇 가지 보여 준다면, 어쩌면 이 세상이 그렇게 나쁘지만은 않다고 생각하게 되지 않을까요?" },
    { id: 'aelis', name: '에일리스', cost: 'Costs -4 FP', birthplace: '발세레스', signature: '생명의 나무', otherPowers: '마부의 저주, 수호의 결속, 역행, 식물술사, 자연의 여주인, 식인 식물', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gqJc9Cd-c12.webp', description: "에일리스는 에젤리나의 자매이지만, 그녀만큼 높은 지위에 올라가 본 적은 없습니다. 어렸을 때부터 그녀는 가족의 골칫거리였습니다. 도의적으로 왕실에 들어가서 일하지는 못하겠다고 고집을 피웠거든요. 에젤리나가 한바탕 홍역을 치렀을 때, 에일리스는 \"거봐 내가 뭐랬어\" 라고 말하고 싶어서 입이 근질거렸습니다. 비록 입장 차이 때문에 가족들과는 사실상 의절했지만, 에젤리나는 아직도 그녀와 가깝게 지냅니다. 자매들이 늘 그렇듯 서로의 성질을 긁을 때도 있지만요.\n\n에일리스는 지금 바빌론의 정원에서 사제로 일하고 있습니다. 이 신성한 정원에는 자연의 힘이 너무나 강해서 자격 없는 자들이 발을 들이면 폐가 가시덤불로 가득 차고 눈을 뚫고 장미꽃이 피어납니다. 막중한 책임을 지고 있긴 하지만, 그녀는 에젤리나보다 더 유치하고 느긋한 성격입니다. 꼬장꼬장한 사람들이 보이면 식물 마법으로 온갖 장난을 거는 게 일상이죠. 에일리스에게서는 아주 강렬하고 달콤한 꽃향기가 나서, 가까이 있다 보면 어지러울 정도입니다. 그녀는 당신이 좀 풀어질 수 있도록 계속 툭툭 건드릴 거에요. 그리고 당신과 함께 있기만 해도 그저 좋아할 거구요." },
    { id: 'silvaria', name: '실바리아', cost: 'Costs -4 FP', birthplace: '고흐우드', signature: '약속된 모렐리의 빛', otherPowers: '말레이우트, 괴수화 I, 개성화, 자가 복제, 강화 작용제, 마법 강화제, 생명혈 물약, 대량 생산', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/FkG9wYpF-c13.webp', description: "실바리아를 한 마디로 표현하자면 '쿨한 이모'입니다. 만사 태평하고, 재미를 좋아하고, 기술이나 트릭도 이것저것 많이 알고 있지만, 정말 무책임하죠. 한번은 사고를 크게 쳐서 좀비 용이... 어우, 말도 마세요. 그래도 원체 솜씨가 좋고 운도 잘 따라 주는 덕분에 그런 일들은 항상 좋게좋게 수습된답니다. 실바리아와 같이 친구로 지낸다면 예능감과 센스가 넘치는 좋은 친구가 되겠지만, 한 팀으로 일을 하려고 하면 완전 마이웨이에 될 대로 되라는 모습에 질려 버릴 겁니다. 제 개인적인 생각이지만 아직 철이 덜 들었다니까요.\n\n실바리아는 지금 에그레사리아의 연금술 교수직을 맡고 있습니다. 그곳 학생들 사이에서도 자상하고 재미있는 선생님으로 인기가 아주 많죠. 이따금씩 '실전 경험을 위해' 학생들과 현장학습을 나가는데, 그러다가 뭔가 일이 터지기도 합니다. 당신과 같이 행동할 때에도 하루하루가 더 편하고 즐겁도록 물심양면으로 도울 거에요. 규칙 같은 것들에는 크게 개의치 않고 말이죠." },
    { id: 'sabeline', name: '새블린', cost: 'Costs -4 FP', birthplace: '고흐우드', signature: '분자세계 조작', otherPowers: '비장의 한 수, 힘+, 속도+', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/20Q78vDY-c14.webp', description: "새블린은 신성 기사단의 일원입니다. 오래 전, 신성 기사단은 신스루 마녀단의 반란에 맞서 격전을 벌였습니다. 이들은 그 이후로도 전 세계를 돌며 그 칼날로 평화와 정의를 전파해 왔습니다. 최근에는 신성 기사단이 지나치게 열성적이라고 비판하는 이들이 많아졌습니다. 특히 정의로운 분노로 똘똘 뭉친 새블린이 그렇죠.\n\n새블린은 정의의 이름 아래 사악한 자들을 벌하는 전형적인 기사입니다. 특히 혼전순결에는 타협이 없으니까, 엄한 짓은 하지 않는 게 좋을 거에요! 한 번은 그녀가 부업을 하던 중에 무슨 사업가가 그녀와 어떻게 '해 보려다가' 잘 안 돼서 쫓아내겠다고 협박한 적이 있었는데... 그냥 바로 일도양단됐죠! 치유 마법 성능이 좋아서 천만다행이지, 아니었으면 큰 곤경에 처했을 거에요. 새블린의 과묵하고 터프한 겉모습을 보면 좀 다가가기 무섭겠지만, 사실 그녀는 한 번 꼭 안아 주면 살살 녹는 마음 약한 여자랍니다. 가끔 후회스럽거나 회의감이 드는 일이 있으면 시를 쓰고는 하는데, 당신이 그걸 찾아내면 부끄러워 어쩔 줄 모를 거에요." },
    { id: 'tempest', name: '템페스트', cost: 'Costs -4 FP', birthplace: '고흐우드', signature: '북두천수괴권', otherPowers: '괴수화 II, 방화광 II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0jR3W5K2-c15.webp', description: "템페스트는 어렸을 때 그녀와 같은 다른 여섯 명의 와이번들과 함께 어느 신베인에게 생포당했습니다. 그 타락한 마녀의 정신나간 계획에 필요한 마력을 뽑히며 노예처럼 부려먹혔죠. 계획이 성공했다면 전세계적으로 엄청난 피해가 발생했을 테지만, 템페스트는 같이 붙잡혔던 와이번들과 함께 들고일어나서 어떻게든 그 신베인을 처치했지만, 그 와중에 동료들을 모두 잃고 말았습니다. 노예 생활이 계속된 지 10년이 됐을 때의 일이었죠. 그 후로 템페스트는 약간 음울하고 냉담한 성격을 갖게 되었습니다.\n\n어떻게 보면 그녀는 나이에 걸맞는 질풍노도의 시기를 겪고 있습니다. 유행에 민감하고, 이상한 음악을 좋아하고, 최대한 쿨하고 도도한 척 하면서 속으로는 깊은 트라우마와 불안감을 숨기고 있죠. 당신만이 그녀의 의식적인 모습을 뒤로하고 그녀가 그렇게 숨기려 하는 진짜 미소를 끌어 낼 수 있는 것 같습니다. 템페스트는 도화선이 짧아서 가끔 처음 보는 사람이 무례하게 군다 싶으면 폭발해서 별 의미도 없는 싸움을 하려고 합니다. 좀 성숙해지면 뛰어난 싸움꾼이 될 수 있을 텐데 말이죠." },
    { id: 'alina', name: '알리나', cost: 'Costs -5 FP', birthplace: '뉴 팰리세이드', signature: '가면무도회', otherPowers: '최면술사, 위장, 기억의 길, 정신 차단벽, 중무장, 회색 점액질, 무기 제작자, 염동력 II, 역장', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cHpsqjy-c16.webp', description: "알리나는 어렸을 때부터 IDPA의 특수 요원이 되고 싶어했습니다. 저학년 때는 또래들에 비해 약하다는 말을 많이 들었지만, 굴하지 않고 그녀의 꿈을 이루기 위해 필사적으로 노력했죠. IDPA 요원들 중 상당수는 젊은 혈기와 이상에 부풀어 일을 시작했다가 고작 몇 달 만에 온갖 더러운 인간군상들을 만나고 좌절하는데... 알리나는 아닙니다. 그녀는 아직도 자신의 이상을 믿으며 어떻게든 이 세상을 더 나은 곳으로 만들기 위해 백방으로 돌아다닙니다. 끔찍한 광경들을 수없이 보고도 긍정적인 멘탈을 유지하는 알리나는 정말 절대로 타락하지 않을 것만 같습니다. 다만 그녀의 도덕관이 좀 극단적인 건 있죠.\n\n알리나는 비밀 임무 전문입니다. 위장술과 연기력으로 완전히 새로운 사람을 만들어내죠. 그녀는 특유의 매력과 카리스마를 통해 폭력 없이 조용히 사건을 해결하는 것을 선호한답니다. 일단 당신과 친해지면 걱정 많은 엄마처럼 당신을 약간 과보호하는 모습을 보일 거에요. 처음 만났을 때는 부끄러움을 많이 타지만, 몸으로 애정 표현을 하는 걸 정말 좋아합니다. 친구를 안아 주고, 연인의 품 속에 안기고..." },
    { id: 'h.a.l.e.y', name: '헤.일.리.', cost: 'Costs -4 FP', birthplace: '뉴 팰리세이드', signature: '나나이트 갑옷 III', otherPowers: '연결망 지배자 II, 디지털 침투자, 나나이트 형체', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/qF3JxNJr-c17.webp', description: "머나먼 옛날, 한 소설가는 이렇게 말했습니다. \"튜링 테스트를 통과할 수 있을 정도로 똑똑한 인공지능은 그걸 일부러 실패할 수도 있다.\" 그 말대로, 시뉴슈어 대원칙 시기에 생성된 초기 인공지능 중 하나인 헤일리는 흔한 실패작 취급을 받아 버려졌고 - 곧바로 그 기회를 살려 웹상으로 들어가 그녀만의 넷 아바타를 갖췄습니다. 레이저포커스 주식회사에서 유출 사고가 터진 이후로는 나나이트를 이용해 그녀만의 육체까지 만들어냈죠. 그 동안 웹상에서 키워 온 그녀의 꽤 큰 팬클럽의 덕을 좀 봤습니다. 컴덕들 사이에서는 디지털 콘서트로 꽤 인지도를 쌓고 있었거든요.\n\n헤일리는 근본적으로 외부인의 시선에서 인류를 대하는 만큼 우리들을 아주 흥미로운 연구 대상으로 여기고 있습니다. 십인십색인 인간들의 모습을 열심히 파헤치고 있죠. 그녀는 밝고 명랑하기는 하지만 개인 공간을 신경쓰지 않고 이것저것 캐묻는 질문들도 종종 하기 때문에 많은 사람들이 불편해하기도 합니다. 한편 지금까지 만난 모든 사람들의 정보를 데이터화해서 저장하고 있는데, 그 목적은 아무도 모릅니다. 그리고 그렇게 많은 정보를 모았음에도 항상 더 많은 것을 알고 싶어하죠." },
    { id: 'sable', name: '세이블', cost: 'Costs -3 FP', birthplace: '뉴 팰리세이드', signature: '완벽한 타인', otherPowers: '디지털 침투자, 위장, 나나이트 갑옷 I, 자가 복제, 연결망 지배자 II, N05T4LGI4.FNJ, 무색무취', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/h1YXMqyx-c18.webp', description: "뉴 팰리세이드는 무한경쟁의 도시입니다. 앞서나가려면 동료들을 등 뒤에서 찔러야 하죠 - 가끔은 '진짜' 찔러야 할 때도 있습니다. 수많은 마녀들이 암살자로 고용되는 건 당연한 일이죠. 세이블은 그런 암살자들 중에서 특별히 악명이 높습니다. 가끔이지만 다른 마녀를 죽여 달라는 의뢰까지 받아 주기 때문입니다. 그 손에 들린 단검이 어떤 물건인지는 아무도 모르지만, 모든 것을 베어 버리는 모습을 보면 분명 예사 물건은 아닙니다.\n\n세이블은 조용하고 과묵합니다. 의뢰가 없을 때는 조용히 명상을 하거나 와인 한 잔을 기울이며 책을 읽습니다. 어쩌면, 그녀가 살인청부를 받는 이유가 그냥 그게 제일 자신있는 일이기 때문이라는 생각이 듭니다. 세이블은 업무와 사생활 사이에는 확실히 선을 긋고, 친구들에게 해가 되는 의뢰는 받지 않습니다. 가끔은 이런 사람은 죽여서는 안 된다며 의뢰를 거절하는 일도 있구요. 그렇게 돈 쓸 일 없이 사는데 벌어온 돈은 왜 모으고 있는지는 알 길이 없습니다. 혹시 오래된 빚을 갚고 있는 건가 같은 생각이 들 뿐입니다." },
    { id: 'regina', name: '레지나', cost: 'Costs -4 FP', birthplace: '로바인', signature: '거대화', otherPowers: '괴수화 II, 생명력 흡수, 방화광 II, 플라즈마 타격, 염동력 I, 감각 극대화, 힘+, 에너지 집중', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Y49pqR3n-c19.webp', description: "한때 멀린은 올밀러를 '길들일' 수 있는 마법을 선보였습니다. 직접 그 마법을 그림세이어에게 사용하여 지성을 갖게 하고, 인간과 같은 모습을 주었죠. 레지나는 그렇게 태어났습니다. 그 마법을 더 자세히 연구했더라면 좋았겠지만, 멀린은 곧바로 이상한 프로젝트인지 뭔지 할 일이 있다며 사라졌습니다. 남자 마법사들은 그런... 기인인 경우가 많죠. 어쨌거나, 그렇게 갑자기 변하게 된 건 레지나 자신에게도 혼란스러운 일이었습니다.\n\n레지나는 사회의 일원이 되기에는 너무 동물 같습니다. 새로운 사람을 만나면 킁킁대고 냄새를 맡거나, 말 대신 손짓발짓이나 으르렁대는 소리로 의사표현을 하려 하는 걸 보면 말이죠. 그 커다란 몸으로 다른 사람들을 내려다볼 때 제일 행복해하는데, 예전과는 달리 항상 그런 상태를 유지할 수 없어서 때때로 우울해하는 것 같습니다. 레지나는 고층 빌딩을 기어올라가서 온 사방에 울려퍼지도록 울부짖는 것을 좋아합니다. 대신 몸이 작아졌을 때는 눈에 띄지 않게 어딘가로 숨으려 합니다. 그래도 당신이 옆에 있으면 마음이 편한지, 당신에게서는 도망치려 하지 않는 것 같네요." },
    { id: 'dolores', name: '돌로레스', cost: 'Costs -4 FP', birthplace: '로바인', signature: '감각 극대화', otherPowers: '비장의 한 수, 마녀의 패밀리어 II, 무색무취, 생명혈 물약, 개성화, 수류의 힘, 괴수화 I, 위장', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/tP8F2p7q-c20.webp', description: "로바인의 늪지대에 사는 오키타니언들은 손님 맞이가 후하기로 아주 유명합니다. 외지인들이 처음 찾아가도 마치 명절 때 고향으로 온 것 같은 기분이 들도록 해 주죠. 그리고 나오는 음식들이 먹다 죽어도 모를 정도입니다! 악어 소녀 돌로레스는 이들의 수호자 노릇을 하고 있습니다. 딱히 위험할 일이 없어서 많이 게을러지긴 했지만요. 진짜 악어들처럼 햇볕 잘 드는 바위 위에 자리잡고 일광욕을 하면서 꾸벅꾸벅 조는 게 일상이랍니다.\n\n그녀가 순식간에 '태세'를 바꾸고 전력으로 침입자를 물리치는 모습을 보면 정말 놀랍습니다. 상황 종료되면 바로 하품하면서 낮잠 자러 가는 모습도 그렇구요. 이쯤 되면 머리에서 까치집이 사라질 일도 없습니다. 하지만 게으름이 창의성을 만든다는 누구 말처럼, 돌로레스는 온갖 문제들을 기상천외한 방법으로 쉽게쉽게 해결합니다. 감정이 격해진 사람들도 아주 차분하게 진정시킬 수 있죠. 거기다가 요리를 좋아해서 모든 오키타니언 요리를 다 꿰고 있어요!" },
    { id: 'darlina', name: '다알리나', cost: 'Costs -3 FP', birthplace: '로바인', signature: '인간 마리오네트', otherPowers: '힘+, 카리스마+, 감각 극대화', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xtVzS5BY-c21.webp', description: "다알리나는 용병 갱단의 보스입니다. 모종의 이유로 전역 처리된 기사나 군인들이 싸움밖에 할 줄 몰라서 거리에 나앉았다가 그녀의 용병단에 들어갔죠. 이쪽 업계에서는 절대 고객을 배신하지 않는 것으로, 특히 반대측에서 웃돈을 얹어 줘도 넘어가지 않는 것으로 유명합니다. 덕분에 로바인의 도시국가들 사이에서 벌어지는 수많은 분쟁에 자주 차출되기도 합니다.\n\n다알리나는 용병 일로 번 돈을 대부분 좋은 일에 쓰기는 하지만, 그렇다고 굳이 의적 이미지를 만들려고 하지는 않습니다. 그냥 돈을 벌면서 권력자들의 눈치를 보지 않는 삶을 살고 싶어할 뿐입니다. 그녀는 전투의 스릴을 갈망하고, 죽음을 두려워하지 않는 저돌적인 전사입니다. 그래도 휘하 부하들에게 강간이나 비전투원 공격을 엄격히 금지하는 부드러운 면도 있습니다. 그녀에게는 특수한 가왜곡체가 하나 있는데, 왼쪽 눈을 드러내기만 하면 강력한 비전 에너지가 터져나와 마을 하나를 초토화시킵니다. 그 반동으로 그녀 자신도 치명상을 입죠." },
    { id: 'michizoe', name: '미치조에', cost: 'Costs -4 FP', birthplace: '지팡구', signature: '카리스마+', otherPowers: "저주술사의 고서, 생명력 흡수, 최면술사, 힘+", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7dCtgxf4-c22.webp', description: "미치조에는 지팡구의 중심에 살면서 파티란 파티에는 모두 얼굴을 비추고 싶어합니다. 축제, 파티, 아니면 시끄러운 술집에라도 미치조에는 항상 나타나서 청주를 마시고 노래방 마이크를 잡고 있을 거에요. 어쩌면 잃어버린 시간을 메꾸고 있는 것일지도 모르죠. 전 황후의 무덤을 지킬 경비대의 일원으로 키워져서, 어렸을 때는 친구를 만들 수도, 웃거나 춤을 출 수도, 심지어는 말할 수도 없었으니까요!\n\n물론 지금은 제대로 인싸입니다. 새 친구를 사귀거나 사람들과 어울릴 기회를 절대 놓치지 않죠. 그녀는 특별히 당신을 좋아하는 것 같습니다. 같이 파티에 가거나 새로운 사람들을 만나 보자고 당신을 이끄는 모습을 보면 말이죠. 미치조에의 인맥은 끝이 없는 것 같습니다. 어디를 가더라도 연줄이 있어서 당신에게 온갖 특혜를 다 주니까요. 물론 그녀도 상황이 진지할 때는 책임감 있고 똑똑한 모습도 보여 줍니다. 술은 좀 마셔도 일을 이상하게 처리하는 법도 없습니다." },
    { id: 'ishikura', name: '이시쿠라', cost: 'Costs -5 FP', birthplace: '지팡구', signature: '눈 깜짝할 사이', otherPowers: '재빠른 반사신경, 힘+, 에너지 집중', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MD6HK35G-c23.webp', description: "이렇게 친절한 사람이 모두가 두려워하는 검사라니, 참 믿기 어렵죠. 무사가 발검하는 그 찰나에 주변 모든 것들이 일도양단되는 그런 거 아시죠? 이시쿠라가 그렇습니다. 그녀는 전설적인 무사 요루 시노부 밑에서 검을 배우고 무사의 긍지 역시 철저하게 교육받았습니다. 검을 뽑아서 거두게 될 목숨보다 더 많은 목숨을 구할 수 있는 상황이 아니라면, 검을 쉽게 뽑으려 하지 않을 거에요.\n\n이타심 넘치는 그녀는 나라 방방곡곡을 돌며, 거치는 마을 하나하나를 조금이라도 더 좋게 바꿔놓습니다. 특히 어린 아이들을 좋아해서 고아들을 위한 양육 프로그램을 운영하기도 하고, 언젠가는 직접 아이를 기르고 싶어하죠. 가끔씩은 자신을 돌보지도 않고 남들에게만 집중하거나, 자신의 힘으로 세상의 모든 문제를 해결하기에는 역부족이라 좌절하는 모습을 보이기도 합니다. 이시쿠라는 나쁜 놈들을 베어 버리기보다는 갱생시키는 것을 좋아하긴 하지만, 싸움을 하게 되면 그 파괴적인 전투력을 유감없이 보여 줄 거에요." },
    { id: 'jin', name: '진', cost: 'Costs -4 FP', birthplace: '지팡구', signature: '위장', otherPowers: '완벽한 타인, 생명력 흡수, 망자와의 대화, 환영의 저주, 무덤에서 일어나라, 지능+', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wFq33t7V-c24.webp', description: "먼 옛날, 한 여인이 아리미네 마을의 한 가문에 저주를 내렸다는 누명을 쓰고 죽임당하는 일이 있었습니다. 그 일은 지금까지도 마을의 흑역사로 남아 있습니다. 한편, 죽은 여인이 부렸던 수많은 패밀리어들은 그림자 늑대를 닮은 올밀러의 형상으로 마을을 괴롭히고 있습니다. 그 억울함으로 인해 죽여도 죽여도 끝없이 부활하는 짐승들이 되어 버린 것입니다. 울프파인의 사냥꾼인 진은 이 괴물들을 추적하고 있습니다. 그들에게 자비로운 안식을 선사할 수 있는 단 하나의 신성한 활을 들고서 말입니다.\n\n아리미네 마을은 이상할 정도로 고요하고, 진 역시 마찬가지입니다. 그녀는 항상 조용히 생각에 잠겨 있고, 가끔은 그녀의 주의를 돌리기가 힘들 정도입니다. 진은 말보다는 음악으로 자신을 표현하는 것을 좋아합니다. 특이한 점이 있다면 라면을 보면 얼굴에 드물게 웃음꽃이 핀다는 거에요. 그녀가 당신에게 마음을 연다면 당신을 보고도 그렇게 웃어 줄 겁니다. 진은 싸움에 임할 때는 아주 조용하고 참을성있게 적들을 상대합니다." }
];

export const CUSTOM_COLLEAGUE_CHOICES_DATA: CustomColleagueOption[] = [
    { id: 'custom_colleague_25', cost: 'Costs -4 FP', description: 'Create a companion with 25 Companion Points.' },
    { id: 'custom_colleague_35', cost: 'Costs -6 FP', description: 'Create a companion with 35 Companion Points.' },
    { id: 'custom_colleague_50', cost: 'Costs -8 FP', description: 'Create a companion with 50 Companion Points.' },
];

export const CUSTOM_COLLEAGUE_CHOICES_DATA_KO: CustomColleagueOption[] = [
    { id: 'custom_colleague_25', cost: '행운 점수 -4', description: '참고 페이지에서 동료 점수 25점으로 동료를 만듭니다.' },
    { id: 'custom_colleague_35', cost: '행운 점수 -6', description: '참고 페이지에서 동료 점수 35점으로 동료를 만듭니다.' },
    { id: 'custom_colleague_50', cost: '행운 점수 -8', description: '참고 페이지에서 동료 점수 50점으로 동료를 만듭니다.' },
];