
import type { School, ChoiceItem, Classmate, CustomClassmateOption } from '../types';

export const SCHOOLS_DATA: { [key: string]: School } = {
  halidew: { 
    id: 'kaliam_tech', 
    title: 'KALIAM TECH', 
    description: "The forefront of magitechnological innovation the world over, almost every modern luxury we take for granted has its roots in Kaliam researchers. Hard-working and ambitious students will fit in well, but lazier sorts may be put off by the often brutal workload. You'll be surrounded by brilliant minds.", 
    costBlurb: "{j}Juathas Sigils{/j} cost two less {bp}Blessing Points{/bp} for {i}Blessings administered by {w}Margra{/w}{/i}.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/W4bHtB7F-sch1.webp' 
  },
  shinar: { 
    id: 'sheol_academy', 
    title: 'SHEOL ACADEMY', 
    description: "The oldest school of magecraft, Sheol seems strange and impenetrable to new students, but if you apply yourself enough (or have good connections), you can slowly work your way into its ancient, exclusive sororities and discover there's a {i}lot{/i} more going on here meets the eye. There's long-buried secrets hidden around every corner, if you know where to look.", 
    costBlurb: "{bp}Sinthru Sigils{/bp} cost two less {bp}Blessing Points{/bp}.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4wQRPD9B-sch2.webp' 
  },
  unterseeisch: { 
    id: 'st_lucindas', 
    title: "ST. LUCINDA'S SCHOOL", 
    description: "A small town in itself, St. Lucinda's is probably the most laid-back and fun school out there, with quite relaxed standards and lots of partying. While students here are often stereotyped as lazy, there's actually plenty of opportunities for more ambitious student to learn a lot from the school's wise Sea Saints.", 
    costBlurb: "{j}Juathas Sigils{/j} cost two less {bp}Blessing Points{/bp} for {i}Blessings administered by {w}Fidelia{/w}{/i}.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/FqLwSkw3-sch3.webp' 
  },
  valsereth: { 
    id: 'strasmara', 
    title: 'STRASMIARA', 
    description: "This Earth's equivalent of the Ivy League. This school boasts some of the smartest and most powerful mages in the world, but its students are stereotyped as snobbish and egotistical. It's the forefront of efforts to research ways to push the Blessings to their absolute limit, and is even the institution that hosts the Irrun Gauntlet. Can be stressful due to its high standards.", 
    costBlurb: "{r}Xuth Sigils{/r} cost three less {bp}Blessing Points{/bp}.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/tpKN3jCW-sch4.webp' 
  },
  gohwood: { 
    id: 'eglaesaria', 
    title: 'THE EGLAESARIA', 
    description: "Formed by a group of powerful dragons many millennia ago; only one of these dragons still lives, serving as the academy's massive, imposing headmaster. It prizes a more simple, combat-centered approach to magic, and many of the greatest warriors in history were taught here. Honor is paramount.", 
    costBlurb: "{j}Juathas Sigils{/j} cost two less {bp}Blessing Points{/bp} for {i}Blessings administered by {w}Arabella{/w}{/i}.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TB1z4y1d-sch5.webp' 
  },
  palisade: { 
    id: 'triumph_towers', 
    title: 'TRIUMPH TOWERS', 
    description: "Tied for the tallest towers in New Palisade, so much so that they use portals instead of elevators. This is a private school known as the spot for rich kids, and life here is the pinnacle of opulence and luxury, although it can sometimes feel unnervingly corporate. Social influence is treasured here, so it's a good choice for those who want to establish some celebrity status.", 
    costBlurb: "{y}Lekolu Sigils{/y} cost two less {bp}Blessing Points{/bp}.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Y4CG2h57-sch6.webp' 
  },
  rovines: { 
    id: 'droudnore', 
    title: 'DROUDNORE INSTITUTE', 
    description: "Known for its smokestacks, the Doudnore Institute is perhaps the most modest school, situated on its own spacious private island. Criticized by some for having a less exciting atmosphere than other schools, but it's a perfect choice for more serious students who want to learn very practical magic, and don't want to fret about with theoretical magic like at the Strasmiara.", 
    costBlurb: "{j}Juathas Sigils{/j} cost one less {bp}Blessing Point{/bp}.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0RLvt7Td-sch7.webp' 
  },
  jipangu: { 
    id: 'horikoshi_koko', 
    title: 'HORIKOSHI KOKO', 
    description: "Placed atop Mount Ishikawa, just above the clouds, a variety of charms and hexes make it impossible for all mundanes to ever access. Students tend to get there via portals built in their various shrines. It is steeped in ancient traditions, and constantly alive with fun festivals, parades, ceremonies, and other activities.", 
    costBlurb: "{i}Sigils{/i} cost one less {bp}Blessing Point{/bp} for {i}Blessings administered by {w}Drysdea{/w}{/i}.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/FkLW44SM-sch8.webp' 
  },
};

export const SCHOOLS_DATA_KO: { [key: string]: School } = {
  halidew: { 
    id: 'kaliam_tech', 
    title: '칼리암 공대', 
    description: "칼리암 공대는 이 세계에서 마법공학의 선두주자 자리를 굳건히 지키고 있습니다. 이곳의 연구진은 일상 생활에서 우리가 당연하게 사용하는 수많은 문명의 이기들을 개발해 왔습니다. 근면하고 꿈이 큰 학생들은 이곳에 잘 맞겠지만, 약간 느슨한 학생들이라면 빡센 로드에 치일 수도 있습니다. 주변에는 정말 똑똑한 사람들이 많을 거에요.", 
    costBlurb: "{i}{w}마그라{/w}에게 축복을 부여받을 때,{/i} {j}자타스 표식{/j}에 소모되는 {bp}축복 점수{/bp}가 2점 감소합니다.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/W4bHtB7F-sch1.webp' 
  },
  shinar: { 
    id: 'sheol_academy', 
    title: '황천의 학당', 
    description: "황천의 학당은 가장 오래 된 마법학교로, 신입생들에게는 약간 배타적인 것 같습니다. 하지만 제대로 지원한다면 (또는 적당한 인맥이 있다면) 유서 깊은 학교 내 조직들의 일원으로 합류해, 이곳에서 실제로 무엇이 일어나는지 직접 확인해 볼 수 있을 겁니다. 이 학교에서는 구석구석 수많은 비밀들을 파헤칠 수 있습니다. 어떻게 찾는지 방법만 알아낸다면 말이죠.", 
    costBlurb: "{bp}신스루 표식{/bp}에 소모되는 {bp}축복 점수{/bp}가 2점 감소합니다.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4wQRPD9B-sch2.webp' 
  },
  unterseeisch: { 
    id: 'st_lucindas', 
    title: "성 루신다 학교", 
    description: "작은 마을처럼 지어져 있는 이 학교는 아마 모든 마법학교를 통틀어 가장 자유분방하고 재미있는 학교일 겁니다. 여기서는 학칙도 꽤 널널하고 파티도 자주 열립니다. 학생들이 게으르다는 편견은 있지만, 열의 넘치는 학생들이라면 이 학교의 현명한 바다 성인들로부터 정말 많은 것들을 배울 수 있을 겁니다.", 
    costBlurb: "{i}{w}피델리아{/w}에게 축복을 부여받을 때,{/i} {j}자타스 표식{/j}에 소모되는 {bp}축복 점수{/bp}가 2점 감소합니다.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/FqLwSkw3-sch3.webp' 
  },
  valsereth: { 
    id: 'strasmara', 
    title: '스트라스미아라', 
    description: "이 세계의 아이비 리그입니다. 이곳은 전 세계에서 가장 강력하고 현명한 마녀들을 배출한 것으로 유명하지만, 학생들이 자존심 높고 고상한 척한다는 말이 많이 돌아다니기도 합니다. 이곳은 마법소녀들이 받은 축복의 한계에 도전하는 연구의 최전선이며, 그 일환으로 이룬의 건틀릿을 주최하기도 합니다. 높은 성취 기준 탓에 꽤 스트레스받을 수도 있어요.", 
    costBlurb: "{r}주스 표식{/r}에 소모되는 {bp}축복 점수{/bp}가 3점 감소합니다.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/tpKN3jCW-sch4.webp' 
  },
  gohwood: { 
    id: 'eglaesaria', 
    title: '에그레사리아', 
    description: "수천 년 전 강력한 고룡들이 이 학교를 세웠습니다. 그들 중 아직까지 살아 있는 마지막 용이 이 학교의 교장입니다. 이곳에서는 마법을 보다 단순하고 전투 중점적인 방식으로 가르칩니다. 유사 이래 가장 강력했던 전사들이 이곳을 졸업했었습니다. 이곳에서 명예는 제일의 가치입니다.", 
    costBlurb: "{i}{w}아라벨라{/w}에게 축복을 부여받을 때,{/i} {j}자타스 표식{/j}에 소모되는 {bp}축복 점수{/bp}가 2점 감소합니다.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TB1z4y1d-sch5.webp' 
  },
  palisade: { 
    id: 'triumph_towers', 
    title: '승리의 탑', 
    description: "이 두 마천루는 뉴 팰리세이드에서 가장 높은 건물들입니다. 그 높이가 너무나 높은 탓에 승강기 대신 포탈을 이용해야 할 정도지요. 이곳은 부유한 집 자제들을 위한 사립 학교로 잘 알려져 있고 실제로 내부에서는 호사의 정점을 누릴 수 있습니다. 다만, 가끔은 불안할 정도로 살벌한 대기업 같은 분위기를 자아내기도 하죠. 이곳에서는 사회적 영향력이 아주 중요시되기 때문에, 혹시나 상류층과의 인맥을 좀 얻고 싶은 사람이 있다면 승리의 탑이 아주 적합할 겁니다.", 
    costBlurb: "{y}레콜루 표식{/y}에 소모되는 {bp}축복 점수{/bp}가 2점 감소합니다.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Y4CG2h57-sch6.webp' 
  },
  rovines: { 
    id: 'droudnore', 
    title: '드라우드노어 학원', 
    description: "넓은 섬에 단독으로 위치하고, 연기나는 굴뚝으로 유명한 드라우드노어 학원은 아마 마법학교 중 가장 소박한 곳일 겁니다. 몇몇 이들은 이곳이 다른 마법학교에 비하면 좀 따분하다고 혹평을 하지만, 아주 실용적인 마법을 배우고 싶어하는 진지한 학생들이라면 여기보다 더 좋은 곳은 없을 겁니다. 특히 스트라스미아라처럼 이론적인 마법을 가지고 골머리를 앓을 필요도 없으니까요.", 
    costBlurb: "{j}자타스 표식{/j}에 소모되는 {bp}축복 점수{/bp}가 1점 감소합니다.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0RLvt7Td-sch7.webp' 
  },
  jipangu: { 
    id: 'horikoshi_koko', 
    title: '호리코시 코코', 
    description: "구름 너머 이시카와 산 정상에 자리잡고 있는 이 학교에는 수많은 주문과 사술이 걸려 있어서 평범한 자들은 발을 들일 수조차 없습니다. 학생들은 여러 사당에 설치된 포탈을 통해 통학합니다. 이곳에는 오래된 전통이 깊게 스며들어 있고, 재미있는 축제와 퍼레이드, 예식, 그리고 여러 활동들이 수시로 개최됩니다.", 
    costBlurb: "{i}{w}드리스데아{/w}에게 축복을 부여받을 때,{/i} 모든 {i}표식{/i}에 소모되는 {bp}축복 점수{/bp}가 1점 감소합니다.", 
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/FkLW44SM-sch8.webp' 
  },
};

export const HEADMASTERS_DATA: ChoiceItem[] = [
    { id: 'waning', title: 'WANING', cost: 'Grants +6 FP', description: "They were a legend centuries ago, but over time, their competence has only dwindled. Now, the school is chronically unorganized and mismanaged, with them only kept due to their influence and long tenure.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/W4ZzC7qL-head1.webp' },
    { id: 'stringent', title: 'STRINGENT', cost: 'Grants +3 FP', description: "They hail from the old-fashioned 'spare the rod, skip the child' ideas of schooling. They're just as competent, if not moreso, but their sternness and short temper means you definitely don't want to earn their ire.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yrT9Y8b-head2.webp' },
    { id: 'competent', title: 'COMPETENT', cost: 'Costs 0 FP', description: "They're youthful in how laid-back and friendly they are, but show their age in their great wisdom and ability to manage the busy school with ease. They tend to work in the background, rarely taking an active role.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/YF9M4wcf-head3.webp' },
    { id: 'sagely', title: 'SAGELY', cost: 'Costs -3 FP', description: "With centuries of knowledge and experience, your education will be cultivated to a razor point under their management. They overflow with wisdom, and you'll look forward to your rare conversations with them.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/35bdq6kX-head4.webp' },
    { id: 'venerable', title: 'VENERABLE', cost: 'Costs -6 FP', description: "A legendary scholar revered around the world, you are almost awed at their brilliance. Despite their prestige, they make a point to dedicate time to personally assisting and bonding with students.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TqN04nx1-head5.webp' },
];

export const HEADMASTERS_DATA_KO: ChoiceItem[] = [
    { id: 'waning', title: '노쇠한', cost: 'Grants +6 FP', description: "수 세기 전에는 살아 있는 전설이셨습니다만, 역시 이분도 세월을 이길 수는 없었습니다. 사실 마법학교도 제대로 운영되지 못한 채 오랜 세월이 지난 상황이지만, 그 영향력과 교수들의 종신 재직권 탓에 어떻게 버티는 수준입니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/W4ZzC7qL-head1.webp' },
    { id: 'stringent', title: '엄격한', cost: 'Grants +3 FP', description: "오래 된 금언이죠. '매를 아끼면 애를 망친다'에 충실한 분입니다. 물론 충분히 능력이 있는 분이지만, 불 같은 성격에다 아주 엄하시기 때문에 이분의 노여움을 사면 정말이지 큰일날 겁니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yrT9Y8b-head2.webp' },
    { id: 'competent', title: '유능한', cost: 'Costs 0 FP', description: "젊은이들의 감각과 친절함도 갖고 있지만, 이분이 이 큰 마법학교를 현명하게 이끌어가시는 모습을 보면 연륜이 느껴집니다. 보통 무대 뒤에서 조용히 일하고 직접 나서는 경우는 거의 없습니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/YF9M4wcf-head3.webp' },
    { id: 'sagely', title: '박식한', cost: 'Costs -3 FP', description: "수백 년 동안 경험과 학식을 쌓아 오신 이분 밑에서 배우면 정말 많은 것을 얻어 갈 수 있습니다. 아주 가끔이지만 현자라 불리기 충분한 이분과 이야기를 나눌 기회가 있을 텐데, 벌써부터 기대되네요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/35bdq6kX-head4.webp' },
    { id: 'venerable', title: '존경받는', cost: 'Costs -6 FP', description: "이분은 전세계에서 두루 존경받는 학자입니다. 그 지식의 깊이만으로 당신이 놀랄 정도입니다. 이렇게나 귀하고 바쁜 분이신데도 틈만 나면 시간을 내서 학생들을 도와 주시는 분이기도 합니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TqN04nx1-head5.webp' },
];

export const TEACHERS_DATA: ChoiceItem[] = [
    { id: 'mama_bear', title: 'THE MAMA BEAR', cost: 'Costs -3 FP', description: "Eminently motherly and protective, she seemingly has infinite free time to devote to personally bonding with each student, not only educating them but offering support and help with all of their problems.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/3y9C7tRv-teacher1.webp' },
    { id: 'entertainer', title: 'THE ENTERTAINER', cost: 'Costs -2 FP', description: "Their classes feel less like lectures and more like uproacious comedy bits, yet you still learn a ton! Their teaching methods are brilliant and engaging, and you'll make sure you get through class stress-free.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5WBTBSrc-teacher2.webp' },
    { id: 'sweetheart', title: 'THE SWEETHEART', cost: 'Costs -1 FP', description: "A walking bundle of pure wholesomeness, bringing fresh-baked cookies to class and acting like a mom more than a teacher. The problem is, they're so coddling it can feel like you aren't learning as much...", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4wCqDfWd-teacher3.webp' },
    { id: 'professional', title: 'THE PROFESSIONAL', cost: 'Costs -1 FP', description: "They're not your friend, they're your teacher. They will be strict, but fair, and if you're willing to put in the effort, you'll find you learned more in their class than any others. Just don't expect any coddling.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/S4c2M2X3-teacher4.webp' },
    { id: 'geek', title: 'THE GEEK', cost: 'Costs 0 FP', description: "They're super passionate about their chosen field, and their class is highly organized and optimized. However, they can sometimes have trouble expressing their knowledge, and may move too fast.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5hrs8qm5-teacher5.webp' },
    { id: 'free_spirit', title: 'FREE SPIRIT', cost: 'Costs 0 FP', description: "Super kind, almost overly so, and a bit disorganized and fast-and-loose with their teaching. Often experiments with teaching techniques, which sometimes work extremely well, and sometimes go terribly.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nqrggCS0-teacher6.webp' },
    { id: 'oddity', title: 'THE ODDITY', cost: 'Costs 0 FP', description: "Your teacher actually isn't human, but a fascinating or mystical creature of some sort! Sure, this will result in rather questionable effectiveness at teaching... but in my opinion, the awe and novelty are worth it.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/604RGN2T-teacher7.webp' },
    { id: 'inexperienced', title: 'THE INEXPERIENCED', cost: 'Grants +1 FP', description: "You can tell they're trying their best, but they're obviously brand new at this. They're often shy and nervous in front of class, and tend to be pretty clumsy and unorganized. Maybe they'll get better, with a little help?", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4ZtTWGrp-teachernew1.webp' },
    { id: 'sleeper', title: 'THE SLEEPER', cost: 'Grants +2 FP', description: "They're likeable, at least... but they're just so tired all the time. Nobody knows why, but it seriously affects their teaching. Often they'll just have you study amongst yourselves while they nap at their desk.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/RkWHLXsT-teachernew2.webp' },
    { id: 'curmudgeon', title: 'THE CURMUDGEON', cost: 'Grants +3 FP', description: "They've got a nasty temper and zero tolerance for any impropriety, slacking or childishness. They're fine at what they do, but the atmosphere in their class is tense to say the least. Everyone is afraid of them!", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LzQcktGR-teachernew3.webp' },
];

export const TEACHERS_DATA_KO: ChoiceItem[] = [
    { id: 'mama_bear', title: '엄마 같은', cost: 'Costs -3 FP', description: "모성애와 보호본능이 넘치는 이 교수님은 학생들 개개인과 깊이 교류하기 위해 시간을 아낌없이 투자할 겁니다. 공부를 가르치는 것 말고도 문제가 있다면 발벗고 나서서 도와 줄 거에요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/3y9C7tRv-teacher1.webp' },
    { id: 'entertainer', title: '1타강사', cost: 'Costs -2 FP', description: "이분의 수업은 강의라기보다는 스탠드업 코미디 같습니다. 물론 내용은 머릿속에 쏙쏙 들어오구요! 교수법이 참 기발하고 매력적이어서 스트레스받지 않고 공부할 수 있을 겁니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5WBTBSrc-teacher2.webp' },
    { id: 'sweetheart', title: '사랑스러운', cost: 'Costs -1 FP', description: "수업에 직접 구운 쿠키를 들고 오는, 순수한 매력이 넘치는 분입니다. 교수님이라기보다는 가족 같은데, 문제는 너무 당신을 애지중지해서 뭔가 많이 배운다는 느낌이 잘 안 들어요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4wCqDfWd-teacher3.webp' },
    { id: 'professional', title: '전문가', cost: 'Costs -1 FP', description: "이분은 당신의 친구가 아니라 교수입니다. 엄하지만 공정하고, 충분한 노력을 하면 다른 교수님들보다 훨씬 많은 가르침을 받게 될 것입니다. 다만 오냐오냐하는 태도는 바라지 마세요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/S4c2M2X3-teacher4.webp' },
    { id: 'geek', title: '천재형', cost: 'Costs 0 FP', description: "이 교수님은 전공 분야에 관한 한 열정이 넘치고, 수업도 체계적이고 최적화가 잘 되어 있습니다. 다만 가르쳐야 하는 것을 잘 표현하지 못할 수도, 진도를 너무 빨리 나갈 수도 있습니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5hrs8qm5-teacher5.webp' },
    { id: 'free_spirit', title: '자유분방한', cost: 'Costs 0 FP', description: "지나칠 정도로 친절하고, 약간 널널하게 강의하는 교수님입니다. 이따금씩 여러 가지 교수법을 시험해 볼 텐데, 가끔은 아주 좋은 결과가 있지만 끔찍한 결과가 나올 때도 있죠.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nqrggCS0-teacher6.webp' },
    { id: 'oddity', title: '탈인간', cost: 'Costs 0 FP', description: "이 교수님은 사실 인간이 아니라 모종의 신비한 생명체입니다! 당연히 얼마나 잘 가르칠지는 논란의 여지가 있겠지만... 제 생각에는 그 특이함과 신선함만으로도 수업을 들을 가치가 있어요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/604RGN2T-teacher7.webp' },
    { id: 'inexperienced', title: '초임', cost: 'Grants +1 FP', description: "최선을 다하는 모습이 눈에 보이지만, 어쩔 수 없이 초임 교수인 게 티가 납니다. 학생들 앞에서 낯을 가리거나 긴장하고, 약간 서투를 때가 많습니다. 도움의 손길이 있다면 나아지겠죠?", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4ZtTWGrp-teachernew1.webp' },
    { id: 'sleeper', title: '잠꾸러기', cost: 'Grants +2 FP', description: "최소한 호감은 가는 교수님이지만... 그렇게 피곤해 보일 수가 없습니다. 이유는 알 수 없지만 그 때문에 강의에 지장이 생길 정도입니다. 아마 교수님이 책상에 엎드려 자는 동안에 당신과 학생들이 알아서 자습할 일이 많을 거에요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/RkWHLXsT-teachernew2.webp' },
    { id: 'curmudgeon', title: '괴팍한', cost: 'Grants +3 FP', description: "성격도 더럽고, 태도 불량이나 유치한 모습은 참아 주지 않습니다. 강의력이야 의심할 여지가 없지만, 수업 분위기는 잘 쳐 줘야 '긴장감 넘치는' 수준입니다. 다들 이 교수님을 무서워하니까요!", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LzQcktGR-teachernew3.webp' },
];

export const DURATION_DATA: ChoiceItem[] = [
    { id: '2_years', title: '-2 YEARS', cost: 'Grants +15 FP, Grants +5 BP', description: "You want to get out the door as quick as possible so you can start getting some hands-on experience! You'll be missing out on a lot of educational opportunities, though.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GqCC6yq-year1.webp' },
    { id: '6_years', title: '-6 YEARS', cost: 'Grants +15 BP', description: "The most common length of time by far. This is enough to get students a decent education in whatever will ensure their success in future careers. Considered the goldilocks zone.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/R4yLPbnx-year2.webp' },
    { id: '10_years', title: '-10 YEARS', cost: 'Grants +20 BP', description: "A more uncommon choice fit for more studious scholars. You will gain new appreciation for your Blessings, though your lack of job experience may be a boon for your competition.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HpBXpjrH-year3.webp' },
    { id: '15_years', title: '-15 YEARS', cost: 'Grants +25 BP', description: "By now, you've been here for a majority of your life. It's a second home to you now, but you'll have to say painful goodbyes to the many friends who move on before you.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7xV8dvdq-year4.webp' },
    { id: '20_years', title: '+20 YEARS', cost: 'Grants +30 BP', description: "You have officially been lost in the sauce of academia! You'll learn much, but wonder whether your time would've been better suited gaining practical experience out in the field.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/d0h4CzY0-year5.webp' },
];

export const DURATION_DATA_KO: ChoiceItem[] = [
    { id: '2_years', title: '~2년', cost: 'Grants +15 FP, Grants +5 BP', description: "당신은 최대한 빨리 교문을 떠나 실전 경험을 쌓고 싶어합니다! 물론 그만큼 교육적인 기회가 없어지겠지만요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GqCC6yq-year1.webp' },
    { id: '6_years', title: '~6년', cost: 'Grants +15 BP', description: "보통 학생들이 공부하는 기간입니다. 향후 진로가 뭐가 됐든 이 정도면 성공할 수 있을 만큼 충분히 교육을 받을 수 있어요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/R4yLPbnx-year2.webp' },
    { id: '10_years', title: '~10년', cost: 'Grants +20 BP', description: "학자 타입의 사람들에게 맞는, 약간은 비주류인 선택지입니다. 당신의 축복을 새롭게 받아들일 수 있게 되지만, 직업 경험이 없다는 것 때문에 경쟁자들에게 밀릴 수도 있죠.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HpBXpjrH-year3.webp' },
    { id: '15_years', title: '~15년', cost: 'Grants +25 BP', description: "이쯤 되면 인생의 대부분을 마법학교에서 보낸 셈입니다. 이곳이 또 하나의 집처럼 느껴지겠지만, 수많은 친구들이 먼저 학교를 떠나는 것을 맘아프게 배웅해 줘야 할 겁니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7xV8dvdq-year4.webp' },
    { id: '20_years', title: '20년 이상', cost: 'Grants +30 BP', description: "거의 학교에 뼈를 묻은 셈이네요. 배우는 것은 정말 많겠지만, 이 시간 동안 현장에서 직접 경험을 쌓는 게 낫지 않았을까 하는 생각을 하게 될 것입니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/d0h4CzY0-year5.webp' },
];

export const CLUBS_DATA: ChoiceItem[] = [
    { id: 'combat', title: 'JOIN THE COMBAT D\'ÉQUIPE TEAM', cost: 'Costs -6 FP', description: "Join a team of fighters and battle other teams in the coliseums to ascend through the brackets and win dazzling tournaments! Said coliseums are placed in pocket dimensions that ensure that no fatal or permanent injuries can be suffered by any participants. Almost every goes except Sinthru magic.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TMc2N31j-club1.webp' },
    { id: 'racer', title: 'BECOME A SEGALANYA RACER', cost: 'Costs -6 FP', description: "Settle disputes on whose method of traveling is fastest, in races that can span from only a mile or so, all the way up to circumnavigating the entire planet! Pretty much anything goes, from flying on a broomstick to soaring on a jet plane. The only rules: no interfering with other racers, and no teleportation.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/F4xDmkmp-club2.webp' },
    { id: 'mazball', title: 'JOIN THE MAZBALL TEAM', cost: 'Costs -6 FP', description: "Kind of like basketball, but imagine it with the 'nets' a half mile apart, and both teams can fly, move fast enough to break the sound barrier, and sabotage eachother with a dizzying variety of spells. Needless to say, Mazball matches are incredibly hard to follow, but entertaining to watch nonetheless.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0y9VLsGD-club3.webp' },
    { id: 'student_council', title: 'STUDENT COUNCIL', cost: 'Costs -3 FP', description: "Student council president is basically the highest level of power you can have over your peers (short of becoming faculty). Competition is fierce, though! It's good practice if considering a political career.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VWJ0Qw5k-club4.webp' },
    { id: 'study_hall', title: 'STUDY HALL', cost: 'Costs -3 FP', description: "Let's be honest. \"Study hall\" is pretty much just a pretense for the geeky girls to get together and play tabletop games, eat snacks, and gush about those weird cartoons they make over in Jipangu.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mF8hvrxS-club5.webp' },
    { id: 'community_watch', title: 'COMMUNITY WATCH', cost: 'Costs -3 FP', description: "{i}Technically,{/i} they're only supposed to be doing stuff like rescuing cats from trees. Off the record, they go out and stop bank robberies and such! They're big on heroics... even if it doesn't always go well.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/v6VngtPZ-club6.webp' },
    { id: 'school_band', title: 'SCHOOL BAND', cost: 'Costs -3 FP', description: "I cannot express in words what magic instruments sound like. Just know it's the kind of sound that moves your very soul. Good way to get fame, too, given they perform for all sorts of major venues.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/bgGCZB75-club7.webp' },
    { id: 'art_club', title: 'ART CLUB(S)', cost: 'Costs -3 FP', description: "Poetry, painting, knitting... whatever kind of art you're into, I'm sure there's a club out there. See cool art and show off your own works! Creating art is nourishing to the soul, or so I've always heard.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7dMgp7cN-club8.webp' },
    { id: 'beastmastery', title: 'BEASTMASTERY CLUB', cost: 'Costs -3 FP', description: "Made for students planning to own a familiar, this club's members meet and learn how to train and interact with a wide variety of fantastical creatures. If you like petting animals, this is the best club ever.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VY2pwPdq-club9.webp' },
    { id: 'outdoorsmanship', title: 'OUTDOORSMANSHIP CLUB', cost: 'Costs -3 FP', description: "A small but extremely friendly bunch of mages who like exploring the far reaches of the world, going on sight-seeing tours through Dominions before stopping to set up cozy little camps in the wilds.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/n8qQghpm-club10.webp' },
    { id: 'fitness_club', title: 'FITNESS CLUB', cost: 'Costs -3 FP', description: "Reaching your potential isn't just about learning! It also requires dedicated practice and training. This club offers endless encouragement and support, helping you to your goals free of judgement.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/9kSPpVqq-club11.webp' },
    { id: 'theatre_club', title: 'THEATRE CLUB', cost: 'Costs -3 FP', description: "Express yourself by writing, dancing, or performing in plays, alongside a super creative and laid-back bunch! This will hone a bunch of skills, with acting teaching you to manipulate and persuade people.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wNWVLkDD-club12.webp' },
    { id: 'school_nurse', title: 'SCHOOL NURSE', cost: 'Costs -3 FP', description: "The hardest-working bunch around, helping their peers through healing, blessings of reinforcement, counselling, physical training, and etc. Great if you want to learn to be a healer or otherwise support.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rG0DFHQS-club13.webp' },
    { id: 'night_school', title: 'NIGHT SCHOOL', cost: 'Costs -3 FP', description: "Vampires and werewolves and—scariest of all—goths! The girls that attend night school tend to be quite spooky, but they're nicer than they look. All being outcasts, they stick together like glue.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jkd1yvsX-club14.webp' },
    { id: 'sukeban_gang', title: 'SUKEBAN GANG', cost: 'Costs -3 FP', description: "A band of juvenile delinquents rebelling against social norms and generally getting into trouble. They're loyal to eachother like a family through thick and thin — there's no other group as close-knit!", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cXVxsxdm-club15.webp' },
];

export const CLUBS_DATA_KO: ChoiceItem[] = [
    { id: 'combat', title: '팀 전투 동아리 가입', cost: 'Costs -6 FP', description: "이 동아리에 가입하면 다른 마법소녀들과 팀을 맺고 투기장에서 팀 단위로 전투를 벌이게 됩니다. 대진을 헤치고 올라가며 토너먼트에서 우승해 보세요! 이 투기장들은 주머니 차원에 위치하고 있어서 참가자들이 영구적이나 치명적인 부상을 입을 일은 없습니다. 신스루 마법만 빼면 거의 모든 마법이 허용됩니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TMc2N31j-club1.webp' },
    { id: 'racer', title: '세갈라냐 경주자 되기', cost: 'Costs -6 FP', description: "어떤 여행 수단이 가장 빠른지 한 번 겨뤄 보세요. 작게는 1마일 경주도, 크게는 세계 일주도 가능합니다! 방식에 제한은 없습니다. 빗자루를 타고 날든 제트기로 하늘을 누비든 당신 마음입니다. 규칙은 딱 두 가지입니다. 다른 경주자들 방해하지 말기, 순간이동 하지 말기.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/F4xDmkmp-club2.webp' },
    { id: 'mazball', title: '매즈볼 팀 입단', cost: 'Costs -6 FP', description: "농구랑 비슷하지만, '골대'가 800m 떨어져 있고, 양 팀이 초음속으로 날아다니고, 상대를 여러 가지 마법으로 방해합니다. 매즈볼을 직접 하는 게 정말 어렵다는 건 말할 필요도 없겠죠? 물론 보는 건 정말 재밌습니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0y9VLsGD-club3.webp' },
    { id: 'student_council', title: '학생회', cost: 'Costs -3 FP', description: "학생회장 정도면 학생으로서 당신이 가질 수 있는 권력의 최고점입니다. (교직원이 되는 게 아니라면요) 경쟁이 심한 건 명심하세요! 혹시 정계에 진출하고 싶다면 좋은 경험이 될 겁니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VWJ0Qw5k-club4.webp' },
    { id: 'study_hall', title: '공부 동아리', cost: 'Costs -3 FP', description: "솔직하게 말할게요. \"공부 동아리\"라 하지만 덕력 있는 마법소녀들이 모여서 보드게임 하고, 간식 먹고, 지팡구에서 나온 이상한 만화들 이야기 하는 곳입니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mF8hvrxS-club5.webp' },
    { id: 'community_watch', title: '자경단', cost: 'Costs -3 FP', description: "공식적으로는 나무 위에 올라간 고양이 구조하기 같은 것만 해야 하지만, 비공식적으로는 은행에 강도가 들면 출동해서 범인을 잡습니다! 정말 영웅적인 학생들이지만... 가끔 일이 틀어질 때도 있지요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/v6VngtPZ-club6.webp' },
    { id: 'school_band', title: '학교 밴드', cost: 'Costs -3 FP', description: "마법 걸린 악기들이 어떤 소리를 내는지는 말로 표현을 못하겠네요. 그냥 영혼을 울리는 소리라고 해 두죠. 이 밴드를 통해서 괜찮은 공연장에서 공연할 기회를 잡는다면 쉽게 유명해질 수 있을 겁니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/bgGCZB75-club7.webp' },
    { id: 'art_club', title: '예술부', cost: 'Costs -3 FP', description: "시 짓기, 그림 그리기, 뜨개질... 뭐든 간에 당신에게 맞는 동아리가 있을 겁니다. 멋진 예술 작품들을 감상하고, 당신의 작품도 자랑해 보세요! 예술이 정서 함양에 좋다잖아요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7dMgp7cN-club8.webp' },
    { id: 'beastmastery', title: '동물 조련 동아리', cost: 'Costs -3 FP', description: "패밀리어를 갖고 싶어하는 학생들을 위한 동아리입니다. 이곳에서는 여러 신비한 동물들과 소통하고 그들을 훈련시키는 방법을 배울 수 있어요. 동물들 쓰다듬고 싶으면 여기가 딱입니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VY2pwPdq-club9.webp' },
    { id: 'outdoorsmanship', title: '아웃도어 여행 동아리', cost: 'Costs -3 FP', description: "이 동아리 구성원들은 수가 많지는 않지만 모두 친절하고, 세계 구석구석을 탐험하는 것을 좋아합니다. 다른 국가들을 관광하는 여행으로 시작해서 야생 속에 작고 아늑한 캠프를 세우고 밤을 보내는 것까지 하게 되겠죠.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/n8qQghpm-club10.webp' },
    { id: 'fitness_club', title: '헬스부', cost: 'Costs -3 FP', description: "당신의 잠재력을 개화하는 것은 학업에만 국한된 게 아닙니다! 반복된 연습과 훈련 역시 필요하죠. 이 동아리에서는 당신이 목표를 이룰 수 있을 때까지 계속해서 당신을 돕고 격려해 줄 겁니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/9kSPpVqq-club11.webp' },
    { id: 'theatre_club', title: '연극부', cost: 'Costs -3 FP', description: "연극을 쓰거나 배역을 맡아 연기하거나, 이 창의적이고 자유로운 부원들 옆에서 자신을 표현해 보세요! 연기를 통해 다른 사람들을 설득하고, 또 능숙하게 다루는 방법을 배울 수 있습니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wNWVLkDD-club12.webp' },
    { id: 'school_nurse', title: '양호실 보조', cost: 'Costs -3 FP', description: "마법학교에서 가장 성실한 학생들이 치료, 강화의 축복, 상담, PT 등등을 통해 동기들을 돕고 있습니다. 치유사나 관련 직종에 종사하고 싶다면 여기에서 경험을 쌓을 수 있어요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rG0DFHQS-club13.webp' },
    { id: 'night_school', title: '야학', cost: 'Costs -3 FP', description: "뱀파이어, 늑대인간, 그리고 가장 무서운, 고스족들이 있습니다! 야학에 다니는 마법소녀들은 겉으로 보기에는 무섭지만, 보기보다 착한 친구들입니다. 다들 크고 작게 따돌림을 받는 처지라서, 서로 긴밀하게 뭉치기도 하구요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jkd1yvsX-club14.webp' },
    { id: 'sukeban_gang', title: '일진', cost: 'Costs -3 FP', description: "사회의 미풍양속과 사사건건 부딪치며 문제를 일으키고 다니는 무리들입니다. 서로에게 충실한 건 마치 가족 같습니다 - 이보다 끈끈한 사이는 찾을 수 없을걸요!", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cXVxsxdm-club15.webp' },
];

export const MISC_ACTIVITIES_DATA: ChoiceItem[] = [
    { id: 'mentor', title: 'MENTOR', cost: 'Costs varies, Grants varies', description: "Very lucky and promising mages sometimes get assigned a mentor! These are skilled and experienced mages who will manage your education. Choose a {w}Colleague{/w} from page 5, or create your own, although their {fpx}FP{/fpx} price is doubled. However, you gain {bpx}BP{/bpx} equal to half of the amount of {fpx}FP{/fpx} you had to spend.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jPVVjzph-mis1.webp' },
    { id: 'puppy_love', title: 'PUPPY LOVE', cost: 'Costs -1 FP', description: "{i}♬ And they called it puppy looove...{/i} Choose from your {w}Classmates{/w}. What starts as an schoolyard crush can blossom into a relationship that lasts you centuries! You can always try romance, but this option guarantees it will work. How quickly, though, depends on the effort you put in.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/hF2LN38F-mis2.webp' },
    { id: 'teachers_assistant', title: 'TEACHERS ASSISTANT', cost: 'Costs -5 FP, Grants +2 BP', description: "{i}Requires {w}>10 Years{/w} or greater.{/i} They say the best way to internalize something is to teach it to somebody else. For this reason, as you reach a high level in your discipline, it is a great idea to help a teacher instruct a class! You won't usually be lecturing, but you will be helping the students learn.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfMp6D38-mis3.webp' },
    { id: 'adjunct_professor', title: 'ADJUNCT PROFESSOR', cost: 'Costs -5 FP, Grants +3 BP', description: "{i}Requires {w}>15 Years{/w} or greater, and {w}Teachers Assistant{/w}.{/i} You're basically faculty now! Well, not really. But you're still participating in academic research at the institution, and you're even teaching your very own classes! This is the perfect opportunity to teach and inspire a whole generation of mages.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mVQpXNnm-mis4.webp' },
];

export const MISC_ACTIVITIES_DATA_KO: ChoiceItem[] = [
    { id: 'mentor', title: '멘토', cost: '소모값 변동', description: "유망하고 운 좋은 마법소녀들은 가끔씩 멘토를 지정받기도 합니다! 이 능력있고 경험 많은 마녀들이 당신의 학업을 도와 줄 거에요. 5페이지에서 {w}동료{/w}를 선택하거나, 직접 만들 수 있습니다. 다만 선택에 필요한 {fpx}행운 점수{/fpx}가 두 배가 됩니다. 대신, 소모한 {fpx}행운 점수{/fpx}의 절반에 해당하는 {bpx}축복 점수{/bpx}를 얻습니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jPVVjzph-mis1.webp' },
    { id: 'puppy_love', title: '풋사랑', cost: 'Costs -1 FP', description: "{i}♬ 사람들은 그걸 풋사랑이라고 했죠...{/i} {w}클래스메이트{/w}를 하나 선택하세요. 학교 운동장에서 그녀를 보고 반한 것이 수백 년 동안 이어지는 관계의 시작이 될 수도 있습니다! 물론 항상 연애는 할 수 있지만, 이 선택지가 있으면 무조건 성공할 거에요. 얼마나 빨리 진도가 나가는지는 당신의 노력에 달려 있지만요.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/hF2LN38F-mis2.webp' },
    { id: 'teachers_assistant', title: '조교', cost: 'Costs -5 FP, Grants +2 BP', description: "{i}최소 {w}10년{/w}의 기간이 필요합니다.{/i} 뭔가를 체화시키는 가장 좋은 방법은 남들에게 가르치는 것이라는 말이 있죠. 그렇기에 당신 정도 경험을 쌓은 학생이라면 교수님의 수업을 도와 보는 것도 좋을 거에요! 물론 직접 강의할 일은 많지 않겠지만, 학생들이 공부하는 걸 도와 주는 거죠.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfMp6D38-mis3.webp' },
    { id: 'adjunct_professor', title: '조교수', cost: 'Costs -5 FP, Grants +3 BP', description: "{i}최소 {w}15년{/w}의 기간이 필요하고, {w}조교{/w}를 선택해야 합니다.{/i} 이제 당신은 학교의 교직원입니다! 아, 공식적으로는 아니지만요. 하지만 어찌됐든 마법학교에서 연구를 하고 있고, 직접 강의에도 나가잖아요! 한 세대의 마법소녀들을 가르치고 영감을 불어넣어 주기에는 딱 좋은 기회입니다.", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mVQpXNnm-mis4.webp' },
];

export const CLASSMATES_DATA: Classmate[] = [
    { id: 'keeling', name: 'KEELING', cost: 'Costs -4 FP', birthplace: 'Halidew Station', signature: 'Subatomic Manipulation', otherPowers: 'Forcefield, Psychic Force II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8LQbDZH8-c1.webp', description: "What a strange mage she is, with a lower body looking like some sort of giant, sand-bleached serpent. She's quite powerful; if she stares at a mundane with enough concentration, she can turn them into a pillar of sand, or create storms of sand powerful enough to disorient and wound mages. She's thus been set as the guardian of the Labyrinth of Concordia, which contains the sum of the world's knowledge, buried in the annals of the college.\n\nQuite lazy, she naps most of the day away — preferably coiled up tight around somebody, considering people warm and comfy. Hope you don't mind sand in your shoes. She's kind of like a housecat: if you're too pushy, she won't like you, but if you give her space, she can become quite loyal and affection, in her own way. She loves to read, and remembers an impossible amount of trivia. When angered enough, she goes from cute to properly terrifying!" },
    { id: 'starla', name: 'STARLA', cost: 'Costs -4 FP', birthplace: 'Halidew Station', signature: 'The Promised Light of Morelli', otherPowers: 'Sustaining Bond, Healing Bliss, Guardian Angel, Vitae Potions, Water of Life, Bolstering Tonics, Smarts +', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yFsnGy9s-c2.webp', description: "The justice system usually balks at capital punishment, preferring rehabilitation, but not even the Mother could coax the vileness from the archlich Elvira. So, she was instead forced to reincarnate, wiping the slate clean — though Starla sees memories of her old self's crimes in occasional nightmares, and is still burdened by the lingering guilt. She's trying to spend this new existence saving lives instead of taking them.\n\nShe's currently the curator at the city's museum, believing those who do not remember the past are doomed to repeat. Very prim and proper, she always dresses like a formal event and can be quite perturbed by crudeness. Bright and passionate, she likes sharing her love of learning with others, and will help immensely with passing your classes and training with new spells. Commonly called an old soul, and loves music from centuries ago. She'll be super proud and excited to show you her museum collection." },
    { id: 'nyla', name: 'NYLA', cost: 'Costs -3 FP', birthplace: 'Halidew Station', signature: 'Roboticist II', otherPowers: 'Tears in Space, Camouflage, All-Seeing, Arcane Matter, Smarts +, Material Transmutation', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1Fc6hXg-c3.webp', description: "Hmm... a tragic case. In Halidew, it is a rite of passage at primary school graduation to create and release an automaton known as a steambird. Nyla and her friend, Lexie, thought they could particularly impress by equipping theirs with a metathermal generator. Sadly, it malfunctioned horribly, and Lexie was killed in the explosion.\n\nShe was much more popular than Nyla ever was, so from then on, fair or not, people branded Nyla the girl whose incompetence cost the city a very beloved mage. She's been a recluse ever since, tinkering with her robots and avoiding everyone else. I hear she internalized what people say and really does blame herself. Such a shame. She used to be a joy! Always making robots to help her friends with even their most minor chores, having them throw parties and performances to entertain everyone in town, skipping around with a goofy smile on her face. If you could get the old her back, you'd have a great friend." },
    { id: 'araminta', name: 'ARAMINTA', cost: 'Costs -4 FP', birthplace: 'Shinar', signature: 'Summon Creature', otherPowers: 'Gathoth Puzzle, Advanced Verse Package, Summon Weather, Natural Environment, Shifting Weather, Artificial Environment, Broken Space, Broken Time', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1tjhYst1-c4.webp', description: "She's not trying to get you to join a cult, is she? We told Araminta. No. More. Cults! I don't care who \"V'arrkra the Forgotten One\" is. I swear, those hermit esotericist families on the outskirts of Shinar believe in the damndest things. Lovely girl otherwise, though. And to be fair, I suspect the reason she gets into those things is partly to help support her poor, beloved grandfather. After his stint in the Sinthrus' hell-verse all those millenia ago, he's just never been the same...\n\nOn that note, she has a verse of her own. And it can't be a terribly pleasant place, judging by the horrid tentacle creatures with a thousand eyes she can bring trawling out of it. But if you're brave enough, feel free to take her up on her offer to join her for a nice pot of tea. She's got a spooky aesthetic, but deep down, I think she's just a sweet girl who desperately wants to be understood. Talking to her, sometimes you do get the feeling she might be onto something..." },
    { id: 'orenda', name: 'ORENDA', cost: 'Costs -4 FP', birthplace: 'Shinar', signature: 'Undead Beast', otherPowers: 'Life Drain, Grasping Dead, Rise From Your Graves, Spirit Medium, Fata Morgana Curse', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BVBtCKJk-c5.webp', description: "She really wants to be a good mage! She's trying her best! But her anxiety gets the better of her, and she often clumsily whiffs her attempts at magic in the most embarrassing ways. At least her wise undead-guardian-turned-father-figure, Xonnan, is always there to pick her up when she's down, even if he can be a bit sheltering (and is probably better at magic than she is). She tries her hardest to live up to her mother, one of the best necromancers in history, hoping to make her proud one day. I think the poor girl is still in denial over the fact her mother doesn't care about her in the slightest...\n\nBeyond that, though, she's fun to hang out with. She's quite geeky, and gets adorably excited when allowed to gush about all of her favorite myths and legends in extreme detail. She'll know the lore of every treasure or ruin you find out on your adventures — provided you can convince her overprotective guardian to let her go out." },
    { id: 'thalia', name: 'THALIA', cost: 'Costs -3 FP', birthplace: 'Shinar', signature: 'Vampirism', otherPowers: 'Hypnotist, Psychic Vampire, Psychic Force I, Strength +, Speed +', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/n86LWZMX-c6.webp', description: "Born into the mysterious Nokomis family, a bloodline through which vampirism runs due to an age-old curse. You get the sense she's been bullied for her vampiric nature, which may be why she became a bit of a bully herself as a way of getting back at the world. Now, she smugly insists that vampires are the superior lifeform, and gets her kicks by pranking and terrifying the other students, who have a superstitious fear of her. She seems to have a particular interest in you, so she may prove a thorn in your side.\n\nStill, you get hints that she likes you more than she lets on. She seems to quietly seethe with jealousy when she sees you hanging out with someone else too much, and will subject them to increased mischief as if to ward them off. And being kind to her, rather than judgemental, can make her smug condescension give way to shocked, flustered stammering. Maybe there's a way to break through to her softer side?" },
    { id: 'valorie', name: 'VALORIE', cost: 'Costs -5 FP', birthplace: 'The Unterseeisch', signature: 'Aquatic Force', otherPowers: 'Psychic Force I, Forcefield, Sonic Boom, Plasma Strike, Energy Channel', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xK7kwN0G-c7.webp', description: "Rare for someone boastful to be able to back up their words, but Valorie did so with style when she slayed that Leviathan single-handedly, making her the youngest mage this millennium to solo a Grimsayer-tier Allmillor! She's quite prideful and playfully braggadocious, but not in the all-too-common way that drags other people down; instead, she strives to build her friends up, and is the first to sing their praises if they match or surpass her achievements. Her self-confidence and constant compliments often rubs off on friends with low self-esteem, making them feel much better about themselves.\n\nShe's the preeminent girly girl, enamored by fashion, makeup, shopping, and all the usual suspects. If you ever need a fashionista to make you look fabulous, she'd be happy to help. Just note she may be a little {i}too{/i} preoccupied with chasing trends. She's very relaxed most of the time, but insulting her friends earns her wrath!" },
    { id: 'stella', name: 'STELLA', cost: 'Costs -4 FP', birthplace: 'The Unterseeisch', signature: 'Smarts +', otherPowers: 'Ice Cold II, Aquatic Force, Energy Channel, Venture Capitalist, Tinkerer, Weaponsmith', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Nb2jwhF-c8.webp', description: "Stella's mother could frankly be called a nag, but generously be called a perfectionist. And perfect her she did. Average grades of 98, could play several instruments and three sports by 5, ran her own small company by 8... and all at the cost of a normal childhood. The upside to this is that she usually does things perfectly, and is thus happy as a clam. The downside is that if almost anything she's doing is even slightly {i}imperfect{/i}, she becomes overwhelmed with anxiety!\n\nShe still works basically 24/7 — leisure is a foreign concept to her — yet she somehow still finds the time to do nice things for her friends to make their lives easier. She projects an aura of prim and proper, and is fastidiously organized, dedicating every moment to self-improvement. She's a perfect study buddy or companion, but can seem like an uninterested friend, for she simply gets stressed out when not busy! It will take time to get her to be able to just hang out." },
    { id: 'bianca', name: 'BIANCA', cost: 'Costs -3 FP', birthplace: 'The Unterseeisch', signature: 'Superpowered Mind', otherPowers: 'Sensory Master, Energy Channel', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/tpSc7n6b-c9.webp', description: "She grew up until now as a lighthouse operator with her father... and became just as drab as her old man, I must say. Can you imagine sitting around on an empty island staring at the sea for a decade? I'd go mad! But it accustomed her to a very slow and quiet lifestyle, so she really struggles to keep up with the hustle and bustle of school life. Smart as a whip, though. That observant, analytical mind of hers just notices things nobody else does... and while she rarely opens her mouth, whenever she does, her words are full of wisdom beyond her years.\n\nShe really likes spending time with her friends, but isn't one for conversation. Reading books together, watching the birds... that's what some people consider a good time, I guess. Waste of potential, though! With that brain, she could be the world's best tactician. Will you inspire her to abandon her placid ways and become a badass action girl? Or is there merit to a quiet life?" },
    { id: 'estrella', name: 'ESTRELLA', cost: 'Costs -4 FP', birthplace: 'Valsereth', signature: 'Speed +', otherPowers: 'Psychic Force I, Quick Twitch, Energy Channel, Sonic Boom', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8LYbXgBM-c10.webp', description: "Her one dream was to become a professional Segalanya racer, and she made great strides... until she hideously embarrassed herself while demonstrating her skills to an industry bigwig. No matter what, you can't seem to get any details about what actually happened — people just make vague allusions to the 'gryphon incident' while giggling to each other. Whatever happened, it convinced her her dreams were dashed forever, and she's gotten all youthfully mopey and melodramatic about it.\n\nEver-so-pragmatic, she's the ideal voice of reason — useful, considering how 'eccentric' the other classmates are — but she can oft straddle the line between realism and downright cynicism. Still, she's happy to give you a shoulder to cry on and a caution against your more ill-advised ideas. She helps others through their issues, but always keeps her own struggles bottled up inside, even with her closest friends." },
    { id: 'siouxsie', name: 'SIOUXSIE', cost: 'Costs -5 FP', birthplace: 'Valsereth', signature: 'Pyromaniac III', otherPowers: 'Thermal Weaponry, Plasma Strike, Strength +, Phase Shift, Rubber Physiology', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/hF3vVsCN-c11.webp', description: "Describing herself as a missionary from the mysterious \"ninth Dominion\" beneath Mount Bearsmark, Siouxsie is ever-too-eager to preach the perfection of her fiery god Obium. She's quite a happy-go-lucky girl, even in cases where it's extremely inappropriate to be so — it's quite unnerving to watch her prance about so cheerfully all while searing the flesh from her enemies. She considers flames to be a blessing, not something to be feared, so we had to teach her that she can't just set everything on fire.\n\nShe loves destruction and is always yearning for a chance to wreak havoc, especially upon those who dare wrong her friends. She recognizes she's a fish out of water on the surface world, so she'll stick close to you and obediently follow all of your advice, thinking you an expert. She's pretty trusting and gullible, so you can convince her of some wacky things if you so choose. Once you have her loyalty, it will never waver." },
    { id: 'chandra', name: 'CHANDRA', cost: 'Costs -5 FP', birthplace: 'Valsereth', signature: 'Self Duplication', otherPowers: 'Phase Shift, Internal Manipulation, Supersize Me, Sensory Master, Energy Channel, Personification', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zVp39dGt-c12.webp', description: "Raised by a clan of famous treasure hunters, and already following in their footsteps, well-known for having acquired a staggering amount of valuable enchanted artifacts despite her young age. Smart and talented enough to coast by with modest passing grades for near-zero effort, as she believes the best way to learn is to get first-hand experience, and likes to skip classes to sniff out treasures and quests — half of which lead her to glory, and the other half leading her to a thorough scolding from the headmaster after she gets herself into trouble yet again.\n\nWhile she's incredibly reckless and blasé about her own safety, she's oddly cautiously when it comes to yours. She'll lose her mind if it ever seems like you've been hurt, and you'll get the biggest tearful hug once it turns out you're okay. She's the kind to surreptitiously tick treasures where her friends will 'discover' them, just to see their smiles. VERY competitive with her rivals." },
    { id: 'illuse', name: 'ILLUSE', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'Spectral Form', otherPowers: 'Life Drain, Psychic Vampire, Spirit Medium, Fata Morgana Curse, Thoughtseer, Lucid Dreamer, Memory Lane', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/sv6z0RJZ-c13.webp', description: "Dismissed as a mere urban legend by most students, Illuse seems to be the spirit of a slain mage reborn into a physical body with the intent of being added to the harem of a quite cruel necromancer — who, instead, died herself under very mysterious circumstances. Illuse is a mysterious girl who rarely likes to be seen by strangers, usually acting as an invisible poltergeist, or sometimes appearing in people's dreams. Playful and mischievous, snobs or bullies around campus are often subject to pranks by some unseen force few will believe exists.\n\nIf she likes you, she's clingy but quite shy, following you around and invisibly making your life easier. Expect to find all your chores done while you were out, or to wake up to breakfast in bed, or to hear of your foes tormented by a clever trickster. However, she'll need gradually encouragement and coaxing to be willing to actually reveal herself to you more and more." },
    { id: 'xena', name: 'XENA', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'Thermal Weaponry', otherPowers: 'Ice Cold III, Speed +, Aquatic Force, Energy Channel', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/pvB1B3wY-c14.webp', description: "This one's a real stoic, always as cool as that sword she swings around. That's how everyone was up in Ialedo — simple, honest folk. She was raised a Knight of Snowholme, dedicated to protecting the whole region... but there was nothing they could do once three grimsayers showed up. I have to imagine she's upset, deep down, after watching her home be wiped away.\n\nShe's deadpan and gets straight to the point, which makes many people think she just has a dry sense of humor, so she gets confused when people start laughing at what she considered a serious remark. She also takes everything pretty literally, so don't expect her to understand metaphor or hyperbole. Still, her utter calmness in any situation tends to calm those around her, and she can be the voice of reason when her friends minds get clouded by emotion or panic. And you'll find she's not truly as emotionless as she appears, if you get her to open up to you." },
    { id: 'rosalind', name: 'ROSALIND', cost: 'Costs -3 FP', birthplace: 'Gohwood', signature: 'Breaker of Minds', otherPowers: 'Crowd Control, Material Transmutation', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/CpWrfqRq-c15.webp', description: "The royal magus lineages of Gohwood don't participate in the same foster program as regular mages, so we can't vet the sort of families they go into. This can lead to some... questionable parenting. Poor Rosalind here is the type of girl used to having an army of servants, and is struggling to come to grips with the fact the real world isn't quite like life at the Mayleaf Palace. She's set to inherit the entire ancient Gohwood monarchy, after all! So she can come off as a little bossy and prissy, I must admit.\n\nI'd say you should knock her ego down a peg, but... I feel a more gentle approach might work just as well, honestly. I can't even imagine the pressure she must be under... and have you heard the way her parents scream at her when she so much as curtsies the wrong way? She could use a friend who can bring her down to Earth and show her more to life. If you can win her over, you'll have a future queen on your side!" },
    { id: 'ruby', name: 'RUBY', cost: 'Costs -4 FP', birthplace: 'New Palisade', signature: 'Heavily Armed', otherPowers: 'Nanite Armor II, Manual Override, CH402.NP5, Domain Master I, Weapon Sabotage, Metal Skin, Grey Goo, Strength +, Incredible Will', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/j9qYhKLQ-c16.webp', description: "Sporty and utterly competitive, Ruby hopes to become the absolute best at everything she does. She's one of the top Mazball players at her age level, even though she often gets into trouble due to her frequent showboating and overestimating her own abilities. She designed that massive fist she can juggle up, and can send her enemies flying across the entire field!\n\nIf you two can find a shared interest, she's the perfect friendly rival — both of you pushing eachother to work harder and get better and better. With others, though, she can have a short temper, especially if she keeps getting trounced by a better opponent. She can train basically non-stop for months trying to overtake them! It's pretty... obsessive. She looks down on laziness and will always try to help you break out of your comfort zones and pursue your goals. She oft speaks before she thinks, though, so she can accidentally come off as a bit rude." },
    { id: 'cordelia', name: 'CORDELIA', cost: 'Costs -3 FP', birthplace: 'New Palisade', signature: 'Psychic Surgery', otherPowers: 'Flashback, Charisma +, Healing Bliss, Defensive Circle, Guardian Angel, Rejuvenating Bolt', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mPQg27B-c17.webp', description: "This one scares me a tiny bit! She tests highly for antisocial personality disorder... in other words, a sociopath, meaning she can't feel empathy for others. That doesn't mean she's {i}evil!{i} Just a bit... troubled. She is a brilliant surgeon, though, especially given her young age. If you're injured, she's very enthusiastic about cutting you open and fixing what's wrong. Maybe too enthusiastic.\n\nAround most people, she fakes a very polite, demure personality. It's chillingly convincing. Her real self is quite, well, cynical, with a dry wit and a pitch black sense of humor. She's not afraid to speak her mind and take the piss out of things others consider sacred, which may be useful if you want a friend who can offer very frank critique. If you're dim-witted, you'll only annoy her, but if you're bright enough to earn her respect, she's incredibly loyal. She's, ahem, trying her best to stay on the straight and narrow... but she could definitely use a positive influence!" },
    { id: 'anna', name: 'ANNA', cost: 'Costs -3 FP', birthplace: 'New Palisade', signature: '?????', otherPowers: 'Forcefield, Energy Channel, Sonic Boom', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SDpwhdbK-c18.webp', description: "Anna is no typical mage, but a Distortion — her power comes not from the Mother, but from a glitch in reality. Namely, anything she truly believes in becomes real. This may sound easy to take advantage of, but she's immune to psychic manipulation, and her strange psychology makes her impossible to intentionally fool. Trust me, a team of rather unscrupulous scientists tried their best, and they were rewarded for their efforts only by getting slaughtered by Anna's rather disturbing \"imaginary friend\", Mr. Muggins.\n\nNow fostered by the state, Anna is the 'weird kid' in school, usually off in her own little world. When conversed with, she's super excitable, bubbly and affectionate, yet basically impossible to understand. She prefers to express herself by making paintings and giving hugs and gifts — the universal languages. She has no friends, so if you're nice to her, she'd be ecstatic! And her power can be useful in unpredictable ways." },
    { id: 'stacy', name: 'STACY', cost: 'Costs -4 FP', birthplace: 'The Rovines', signature: 'Weaponsmith', otherPowers: 'Master Mechanic I, Tinkerer, Kaboom!, Max Security, Nanite Armor I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/6RtQ9kFQ-c19.webp', description: "Pffft, oh my gosh. She's so adorable walking around with a 20mm rifle the same size as her. She'll grow into it, I'm sure. Her mom was a hardcore prepper, one of those types who think reality will collapse in a century, so Stacy has been undergoing brutal military training since she was a toddler. School has finally afforded her an opportunity to escape, but she struggles fitting in. She can tell you {i}everything{i} about IEDs or weapon calibers, but knows nothing about buying clothes or doing schoolwork or even just how to interact with her fellow mages.\n\nShy and awkward, she's used to a heavily regimented life and has trouble making her own decisions. A quiet part of her fantasizes about what it's like to be a more typically girly girl and get to wear cute dresses. She'll be immensely grateful to you if you help her break out of her comfort zone. And if you like guns, she'd be more than happy to gush about them for hours." },
    { id: 'meryll', name: 'MERYALL', cost: 'Costs -4 FP', birthplace: 'The Rovines', signature: 'Beastmaster', otherPowers: "Mage's Familiar III, Sustaining Bond, Healing Bliss, Rejuvenating Bolt, Defensive Circle", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BKf1nC3h-c20.webp', description: "The school keeps getting noise complaints about her dorm room — it's like an entire zoo in there! She's got everything from fluttering little fairies, to three-headed snakes, to a kappa of all things, although she seems most attached to a big poison-spitting manticore named Jandi. Chief beastmaster of Castle Borthrough, she explored all over and met nearly every kind of beast, but there's a few rare species she's still looking for.\n\nShe has extensively studied healing magic in order to play veterinarian for her pets, and help her friends as well. She's quite the serious sort, with only her pets (and you) bringing a smile to her face, and a bit hard-headed about her ideals, which encompass anything from honor, helping those in need, and respecting animals. She's got a real righteous fury and a desire to see wrongdoers brought to justice. However, she is not cruel, and prefers to see people change their ways rather than having to battle them." },
    { id: 'zorreth', name: 'ZORRETH', cost: 'Costs -3 FP', birthplace: 'The Rovines', signature: 'Shed Humanity II', otherPowers: 'Pyromaniac II, Plasma Strike, Sonic Boom, Strength +, Speed +', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SD8Kj6sm-c21.webp', description: "She disappeared off the grid long ago, and was presumed dead. Then, we found out her parents were actually messily devoured after picking a fight with a pair of dragons, who proceeded to adopt \"Zorreth\". The school managed to work out a deal with them to let her come here, but she's a bit of a handful. She considers herself a dragon and far above mankind, and is easy to anger, transforming into her 3 story tall draconic form and causing a huge mess. She can be placated with shiny things to add to her 'hoard', which can be as simple as a marble or a button.\n\nIf she likes you, she'll decide you're \"one of the good humans\" and treat you like a treasured pet. She'll ferociously defend you against all who would harm you, but can be quite possessive. Maybe you can help her learn to fit in better? Just, whatever you do, {i}don't{i} hurt her. Her mom's an {i}actual{i} dragon, and one so massive she makes Zorreth's draconic form look tiny by comparison." },
    { id: 'ayuzawa', name: 'AYUZAWA', cost: 'Costs -5 FP', birthplace: 'Jipangu', signature: "Oni's Blessing", otherPowers: 'Strength +, Charisma +, Quick Twitch, Weaponsmith, Energy Channel, Defensive Circle, Phase Shift', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gbcpH1vn-c22.webp', description: "Oni are extremely rare and benevolent yokai that rarely choose a lucky newborn mage to fuse with, offering them immense powers in return for enlisting them in the onis' eternal war against all other sorts of yokai. Not that Ayuzawa, being the goody-two-shoes hero type she is, needed any prodding to dedicate herself to defending her beloved school against its spiritual assailants. President of the student council and a few other clubs, and prospective valedictorian of her class, no one has as much school spirit as she does!\n\nGiven her track record, she'll probably act like a supportive big sister, giving you advice, making sure you're safe and even packing your lunches. You're going to have to set some boundaries if you don't want her babying you. Eminently responsible, almost overly so, she'd rather die than be late to a scheduled meeting. Idealistic, she tends to assume the best of everybody, and is prone to being easily taken advantage of." },
    { id: 'momoi', name: 'MOMOI', cost: 'Costs -5 FP', birthplace: 'Jipangu', signature: 'Master Telepath', otherPowers: "Cursemaker's Cookbook, Shed Humanity I, Psychic Force I, Chloromancy, Thoughtseer, Lucid Dreamer", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GQj3z2cS-c23.webp', description: "She's taken full advantage of Jipangu reverence for mages, living in her massive shrine in the woods and calling herself the Goddess of the Hachimori — sitting on a bean bag throne and being hand-fed snacks by her dutiful supplicants, the whole shebang. Smug and playful, it seems she has decided you are the heir to the title of 'Protector of the Goddess', and will set up devious little challenges to test whether you are yet worthy to be her 'right-hand mage'.\n\nHailing from a looong line of kitsunes, the protection of nature is always her top priority, and defiling her forest is a quick way to spur her to fury. She transforms into a large, white-furred, nine-tailed fox when fighting off intruders. Her followers have to spend a half hour just grooming her tails every day. She gets very grumpy and pouty when someone denies her divinity. She likes spending quiet foggy mornings together in the woods drinking sencha tea." },
    { id: 'licenda', name: 'LICENDA', cost: 'Costs -3 FP', birthplace: 'Jipangu', signature: 'Flowers of Blood', otherPowers: 'Life Drain, Spirit Medium, Spectral Form', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LDQjngdm-c24.webp', description: "I must strongly caution you on this one. Poor Licenda here is as broken as a person can be, a complete shell of her former self, barely ever even speaking. Years ago, she emerged the only surviving kidnapping victim of a deranged sexual cult of sadists and hedonists, egging each other on to be ever more \"creative\" in their tortures. The things they {i}did{i} to her were expunged from all records, and most who've heard the details opted for a memory wipe rather than live with that terrible knowledge. She still isn't allowed to die, even. Outside of the Sinthru covens, these sorts of things have {i}never{i} happened since the Forsaken Age, thousands of years ago! Perhaps our reality really is devolving...\n\nIt seems she's still followed by the ghost of her past - literally. Most spirits are easily dispatched, but this one is completely unprecedented in its power and violent nature. There's technically no evidence of any connection, but... I feel I must warn you a few people who've hung around Licenda have disappeared under mysterious circumstances. Some rumor that the spirit is her own sister, whose life she was forced to snuff out for the viewing pleasure of their captors. I don't even remember what her name was." }
];

export const CLASSMATES_DATA_KO: Classmate[] = [
    { id: 'keeling', name: '킬링', cost: 'Costs -4 FP', birthplace: '할리듀 스테이션', signature: '분자세계 조작', otherPowers: '역장, 염동력 II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8LQbDZH8-c1.webp', description: "하반신이 거대한 모래빛깔의 뱀 형상인 기이한 마법소녀입니다. 그녀의 힘은 상당히 강력해서 평범한 물체를 얼마 동안 집중해서 쳐다보는 것으로 모래로 바꿔 버릴 수도 있고, 마녀들의 감각을 흐트러뜨리고 부상을 입힐 수 있는 강력한 모래폭풍을 만들어 낼 수도 있습니다. 이 때문인지 그녀는 콩코르디아 미로의 수호자로 내정되었습니다. 그 미로 속에 있는 학교의 기록 속에는 이 세계의 모든 지식이 담겨 있지요.\n\n킬링은 게으른 편이라 낮 시간은 대부분 잠을 자면서 보냅니다. 누군가에게 꽉 똬리를 틀고 자는 걸 좋아하는데, 사람들이 따뜻하고 폭신해서 그런답니다. 신발에 모래가 좀 들어가도 그러려니 하는 게 좋겠죠. 그녀는 약간 집고양이 같아서, 당신이 너무 밑어붙이면 당신을 싫어하겠지만 어느 정도 거리를 두면 그녀만의 애정과 충실함을 보여 줄 겁니다. 킬링은 독서를 좋아하고 온갖 잡다한 정보들을 다 기억하고 있습니다. 하지만 화가 나면 그녀의 귀여움이 무시무시함으로 바뀔 테니까 조심하세요!" },
    { id: 'starla', name: '스탈라', cost: 'Costs -4 FP', birthplace: '할리듀 스테이션', signature: '약속된 모렐리의 빛', otherPowers: '수호의 결속, 황홀한 치유, 수호천사, 생명혈 물약, 생명수, 강화 작용제, 지능+', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yFsnGy9s-c2.webp', description: "이 세계의 사법부에서도 사형은 꺼리며 가능하면 교정과 갱생으로 대체하려 합니다만, 고위 리치 엘비라의 사악함은 위대하신 어머니마저도 몰아 낼 수 없었습니다. 하여 환생을 통해 모든 것을 새롭게 시작하는 수밖에 없었는데, 그럼에도 스탈라가 가끔씩 악몽을 꿀 때 전생에 지은 죄의 기억이 떠오릅니다. 그녀는 아직도 죄책감을 느끼며, 새로운 삶을 다른 이들의 목숨을 빼앗는 대신 구하는 데에 쓰려고 하고 있습니다.\n\n지금 그녀는 도시 박물관의 큐레이터를 맡고 있는데, 과거를 기억하지 못하는 자들은 과거의 실수를 반복하게 된다고 믿기 때문입니다. 스탈라는 항상 정장을 갖춰 입으며, 조악한 것들은 그냥 넘어가지 못하는 요조숙녀입니다. 그녀는 또한 밝고 열정이 넘치며, 배움의 즐거움을 다른 이들과 나누고 싶어합니다. 당신이 수업을 통과하거나 새로운 마법을 연습하는 데에도 엄청난 도움이 되어 줄 겁니다. 사람들은 다들 그녀를 나이든 사람 취급하고, 그녀도 실제로 몇백 년 된 음악을 좋아합니다. 또한 그녀는 당신에게 기꺼이 자신이 자랑스럽게 여기는 박물관 전시품들을 보여 줄 겁니다." },
    { id: 'nyla', name: '닐라', cost: 'Costs -3 FP', birthplace: '할리듀 스테이션', signature: '로봇술사 II', otherPowers: '공간 균열, 위장, 천리안, 비전 물질, 지능+, 물질 연금술', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1Fc6hXg-c3.webp', description: "흠... 비극의 소녀입니다. 할리듀의 초등학생들은 졸업할 때 전통적으로 '증기새'라고 불리는 오토마톤을 하나 만들어서 방생합니다. 닐라와 그녀의 친구 렉시는 그녀들의 오토마톤에 열변환 발전기를 장착하면 모두들 감탄할 것이라고 생각했습니다. 하지만 슬프게도 치명적인 기기 오작동이 일어나는 바람에 렉시가 폭발에 휘말려 죽고 말았죠.\n\n렉시는 닐라보다 훨씬 더 인기가 많았기 때문에, 그 후로 사람들은 닐라를 자신의 무능력으로 사랑스러운 마법소녀를 죽여 버린 아이로 낙인찍어 버렸습니다. 그게 맞는 평가인지는 상관하지도 않았죠. 닐라는 그 후로 지금까지 다른 모든 사람들을 피한 채 로봇만 만지는 삶을 살고 있습니다. 제가 듣기로는 사람들이 하는 말을 진심으로 받아들여 자기 자신을 탓하고 있다고 합니다. 안타까운 일이죠. 예전에는 정말 활기찬 아이였는데! 친구들의 잔심부름 하나하나까지 로봇을 만들어서 도와 주고, 로봇으로 파티와 공연을 열어서 마을 사람들을 웃게 하고, 자기도 헤실헤실 웃으면서 폴짝폴짝 뛰어다니던 소녀였는데 말입니다. 당신이 그 모습을 되찾아 줄 수만 있다면 그녀는 정말 좋은 친구가 돼 줄 겁니다." },
    { id: 'araminta', name: '아라민타', cost: 'Costs -4 FP', birthplace: '시나르', signature: '마수 소환', otherPowers: '가토스의 퍼즐, 고급 가상 우주 패키지, 기상이변, 인공 환경, 뒤틀린 공간, 뒤틀린 시간', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1tjhYst1-c4.webp', description: "설마 또 이상한 교단의 포교활동을 하고 있는 건 아니겠죠? 우린 분명히 아라민타에게 말했어요. 교단은. 필요. 없다고! \"잊혀진 자 바'크라\"가 누구인지 저는 관심도 없단 말이에요. 정말이지 시나르 외곽에 있는 밀교 숭배자들은 별의별 이상한 걸 다 믿는다니까요. 뭐, 그것만 빼면 사랑스러운 소녀랍니다. 그리고 공정하게 말하자면, 이 친구가 이런 일을 하는 이유 중에는 가난하신 할아버지를 돕기 위한 것도 있다고 하니까요. 수천 년 전에 신스루 지옥에서 일하다 오신 뒤로는 예전 같지 않으시다고 합니다.\n\n그래서 말인데요, 아라민타에게는 자신만의 가상 우주가 있습니다. 그리고 그 안에서 천 개의 눈이 달린 촉수 괴물들을 소환하는 모습을 보면 별로 좋은 세계는 아닌 것 같아요. 하지만 당신이 용감하다면 같이 차 한 잔 하자는 그녀의 제안을 한번 수락해 보세요. 취향이 좀 소름돋지만, 그래도 누군가 자신을 이해해 주길 바라는 착한 아이일 거에요. 직접 이야기를 나눠 보면 뭔가 꾸미고 있다는 느낌이 들 수도 있구요..." },
    { id: 'orenda', name: '오렌다', cost: 'Costs -4 FP', birthplace: '시나르', signature: '언데드 야수', otherPowers: '생명력 흡수, 사자의 손아귀, 망자와의 대화, 환영의 저주', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BVBtCKJk-c5.webp', description: "정말 뛰어난 마녀가 되고 싶어하는 소녀입니다! 물론 매사에 최선을 다하구요! 하지만 불안감이나 긴장 때문인지 자주 마법에 실패해서 부끄러운 일을 당하는 때가 많습니다. 적어도 그녀의 언데드 보호자이자 아버지 같은 존재인 조난이 항상 그녀를 위로해 줍니다. 마법을 더 잘 쓸 것 같은 존재가 과보호를 한다는 느낌을 지울 수는 없지만요. 오렌다는 어머니와 같은 경지에 이르기 위해 항상 노력하고 있습니다. 역사상 가장 실력있는 강령술사 중 하나였던 어머니를 자랑스럽게 만들고 싶으니까요. 제 생각에는 이 가엾은 소녀는 자기 어머니가 자신에게는 아무 관심이 없다는 사실을 애써 부정하고 있는 것 같지만...\n\n그걸 뒤로 하고 보면 같이 다니기 참 좋은 친구입니다. 약간 괴짜 같은 느낌이 있어서, 좋아하는 신화나 전설 이야기들을 들려 주면서 신내 하는 것을 보고 있으면 참 귀엽거든요. 같이 모험을 떠나다가 보물이나 유적지라도 찾게 된다면 그녀가 거기에 얽힌 이야기를 술술 풀어놓을 겁니다. 물론 먼저 걱정 많은 보호자님을 설득하야겠지만요." },
    { id: 'thalia', name: '탈리아', cost: 'Costs -3 FP', birthplace: '시나르', signature: '흡혈', otherPowers: '최면술사, 정신 흡수자, 염동력 I, 힘+, 속도+', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/n86LWZMX-c6.webp', description: "탈리아는 대대로 전해져 내려오는 저주로 인해 뱀파이어가 된 노코미스 가문에서 태어났습니다. 당신이 짐작하듯이 그녀는 뱀파이어의 천성 때문에 따돌림을 당했었고, 그 반동으로 남을 괴롭히기 좋아하는 성격이 되었습니다. 이제 그녀는 콧대를 높이며 뱀파이어들이 우월한 생명체라는 것을 주장하고 다닙니다. 미신 때문에 그녀를 무서워하는 다른 학생들을 놀리고 괴롭히며 즐기는 건 덤이구요. 탈리아는 당신에게 특별히 관심이 있는 것 같습니다. 꽤 귀찮아질지도 모르겠네요.\n\n그래도 가만 보면 그녀가 겉으로 드러내는 것보다 당신을 훨씬 더 좋아하는 것 같습니다. 다른 누군가와 같이 다니는 것 같다 싶으면 조용히 질투심을 불태우고, 마치 쫓아내려는 듯 온갖 짓궂은 장난을 쳐 댈 겁니다. 그리고 비판 대신 친절한 모습을 보여 준다면 평소의 도도함은 온데간데없이 얼굴이 빨개져서 말을 더듬는 모습도 볼 수 있을 거에요. 그 여린 모습을 어떻게 끌어 낼 수 없을까요?" },
    { id: 'valorie', name: '발로리', cost: 'Costs -5 FP', birthplace: '운터시쉬', signature: '수류의 힘', otherPowers: '염동력 I, 역장, 소닉붐, 플라즈마 타격, 에너지 집중', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xK7kwN0G-c7.webp', description: "이거저거 자랑하는 사람치고 행동이 받쳐 주는 경우는 참 드물지만, 단신으로 거대괴수를 처치한 발로리는 예외입니다. 지난 천 년 동안 그림세이어를 죽인 마법소녀들 중 가장 어리니까요! 발로리는 꽤 자존심이 높고 장난기 넘치게 온갖 허세와 자랑을 늘어놓습니다. 다만 다른 사람들을 깎아내리는 흔해빠진 방식이 아니고, 그만큼 친구들을 끌어올리기 위해 노력합니다. 친구들이 그녀를 따라잡거나 넘어서면 누구보다 먼저 축하해 줄 거에요. 덕분에 자존감이 낮은 친구들도 그녀와 같이 있으면 여러 모로 용기를 얻게 됩니다.\n\n발로리는 패션과 화장, 쇼핑 같은 것들을 좋아하는 아주 전형적인 소녀입니다. 만약에 당신이 패셔니스타의 도움을 받고 싶어한다면 기꺼이 도와 줄 거에요. 다만 그녀가 유행을 따라가는 것에 살짝 과몰입할 수 있다는 건 염두에 두세요. 발로리는 보통은 아주 느긋한 성격이지만, 그녀의 친구들을 욕하면 진심으로 화낼 거에요!" },
    { id: 'stella', name: '스텔라', cost: 'Costs -4 FP', birthplace: '운터시쉬', signature: '지능+', otherPowers: '한기 II, 수류의 힘, 에너지 집중, 벤처 자본가, 땜장이, 무기 제작자', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Nb2jwhF-c8.webp', description: "스텔라의 어머니는 좋게 말해 완벽주의자, 곧장 말해 잔소리꾼입니다. 덕분에 스텔라도 완벽한 마법소녀가 되었죠. 평균 점수 98점, 5살에 악기 여러 종류와 스포츠 3종 섭렵, 8살에 소규모 회사 경영... 모두 평범한 어린 시절과 바꿔 이뤄낸 것들입니다. 좋은 점은 스텔라는 보통은 일을 아주 완벽하게 처리하고, 그러면서 아주 행복해한다는 겁니다. 안 좋은 점은 그러다 혹시라도 아주 약간의 흠이라도 생기면 불안해서 어쩔 줄 모른다는 거구요!\n\n스텔라는 아직도 쉼없이 일하며 삽니다. 휴가라는 말을 너무 낯설어해요. 그치만 어떻게든 시간을 내서 친구들의 삶을 더 윤택하게 만들어 줄 무언가를 해 줍니다. 그녀에게는 단정하고 정숙한 분위기가 있고, 항상 자기 계발을 위해 정진합니다. 같이 공부하거나 일할 동료로는 최적이지만, 약간 무관심해 보일 수도 있습니다. 사실 스텔라는 자기 몸이 바쁘지 않으면 스트레스를 받거든요! 단순히 같이 놀러 나가자고 설득하는 것에도 많은 시간이 필요할 겁니다." },
    { id: 'bianca', name: '비앙카', cost: 'Costs -3 FP', birthplace: '운터시쉬', signature: '초월자의 정신', otherPowers: '감각 극대화, 에너지 집중', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/tpSc7n6b-c9.webp', description: "비앙카는 아버지와 함께 등대지기 일을 하며 자랐습니다... 그 아버지처럼 지겨운 사람이 된 것도 무리는 아니죠. 당신은 무인도에서 텅 빈 바다만 쳐다보며 수십 년을 버틸 수 있겠습니까? 하지만 그런 삶을 살아 온 비앙카는 느긋하고 조용한 삶에 너무나 익숙해져서 시끌벅적한 학교생활에 적응하는 걸 힘들어합니다. 그래도 아주 재치 넘치고 똑똑한 친구입니다. 주의력과 분석력이 뛰어나서 남들은 다 지나치는 것들을 눈치채기도 하구요... 아주 가끔 입을 열 때면 소녀라고 믿기 힘든 깊은 지혜가 드러납니다.\n\n비앙카는 친구들과 함께 지내는 것을 좋아하지만, 대화를 즐기는 스타일은 아닙니다. 같이 독서하고, 새들을 구경하고... 뭐, 그런 걸 좋아하는 이들도 있으니까요. 하지만 너무 아까워요! 그 머리면 이 세계에서 제일 뛰어난 전략가가 될 수도 있을 텐데. 당신이 그녀에게 영감을 불어넣어서 예전의 조용한 삶 대신 멋들어진 투희의 길로 이끌 수 있을까요? 아니면, 그냥 조용히 사는 것도 그만한 장점이 있을까요?" },
    { id: 'estrella', name: '에스트렐라', cost: 'Costs -4 FP', birthplace: '발세레스', signature: '속도+', otherPowers: '염동력 I, 재빠른 반사신경, 에너지 집중, 소닉붐', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8LYbXgBM-c10.webp', description: "에스트렐라에게 단 한 가지 꿈이 있다면 프로 세갈라냐 경주자가 되는 것이었습니다. 그리고 그 꿈에 성큼성큼 다가가고 있었죠... 산업계의 거물에게 자기 기술을 시연하다가 더도 없을 망신을 당하기 전까지는 말입니다. 아마 당신이 뭘 해도 그날 정확히 무슨 일이 있었는지는 알 수 없을 겁니다. 사람들이 그냥 두루뭉실하게 '그리폰 사건'에 대해 몇 마디 하면서 서로 웃기 바쁘거든요. 자세한 상황이 어땠던지 간에, 에스트렐라의 꿈은 그날로 끝장났고, 그날로 소녀의 우울함과 멜랑꼴리에 빠져 지내고 있습니다.\n\n에스트렐라는 아주 실용적인 성품을 가지고 있고, 항상 이성적인 목소리를 냅니다. 다른 친구들이 '별종'인 걸 생각하면 꽤 도움이 되지만, 문제는 실용주의가 갑자기 끝없는 냉소주의로 바뀔 수 있다는 거죠. 그래도 당신이 우울할 때면 어깨를 빌려 줄 거고, 뭔가 안 될 것 같은 생각을 하면 말려 줄 겁니다. 그녀는 남들의 문제를 기꺼이 도와 주겠지만, 자기를 힘들게 하는 것들은 가장 친한 친구들에게도 드러내지 않고 마음 속에 꼭 품고 있습니다." },
    { id: 'siouxsie', name: '사이우시', cost: 'Costs -5 FP', birthplace: '발세레스', signature: '방화광 III', otherPowers: '열 병기, 플라즈마 타격, 힘+, 위상 변화, 고무고무 신체', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/hF3vVsCN-c11.webp', description: "사이우시는 스스로를 베어즈마크 산 아래에 숨겨진 신비한 \"아홉 번째 국가\" 출신 용병이라고 소개합니다. 그리고 그녀가 섬기는 불의 신 오비움의 완전함을 설파할 기회만을 찾고 있죠. 이 소녀는 때와 장소를 가리지 않고 아주 태평한 모습을 보여 줍니다. 그게, 전쟁터에서 적들의 살점을 태우면서 발랄하게 뛰어다니는 것을 보고 있으면 우리까지 불안해지거든요. 사이우시는 불꽃을 공포의 대상이 아닌 축복으로 받아들이고 있었기 때문에, 얼마 동안은 아무거나 불 붙이고 다니면 안 된다는 것을 가르쳐야 했습니다.\n\n그녀는 이거저거 파괴하는 것을 좋아하고 난장판을 만들 기회라면 놓치지 않습니다. 특히 그녀의 친구들을 해코지한 자들은 가만 두려 하지 않을 거에요. 그녀는 자기가 이 세계에서는 물 밖에 나온 물고기 같다는 것을 잘 알고 있기 때문에, 당신에게 딱 붙어서 당신이 하는 말은 모두 잘 들을 겁니다. 순진하고 남을 잘 믿기 때문에 원한다면 엄한 것들을 시킬 수도 있을 거에요. 한 번 그녀의 마음을 얻으면, 절대 돌아서지 않을 겁니다." },
    { id: 'chandra', name: '찬드라', cost: 'Costs -5 FP', birthplace: '발세레스', signature: '자기 복제', otherPowers: '위상 변화, 체내 조작, 거대화, 감각 극대화, 에너지 집중, 개성화', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zVp39dGt-c12.webp', description: "찬드라는 유명한 보물 사냥꾼 일가에서 자랐습니다. 그리고 벌써 보물 사냥꾼의 길에 들어서서, 어린 나이에도 불구하고 귀한 마법 유물들을 정말 많이 찾아낸 것으로 명성을 얻었죠. 그녀는 별 힘을 들이지 않고 적당한 성적으로 시험을 통과할 만큼의 재능을 가지고 있습니다. 그래서인지 뭔가를 배우는 가장 좋은 방법은 직접 경험하는 것이라는 지론을 갖고 있고, 보물과 임무를 찾아서 수업을 빼먹는 일이 예사입니다. 모험의 절반은 영광스러운 성공으로 끝나지만, 나머지 절반은 교장 선생님께 따끔한 꾸중을 듣고 다시금 문제를 일으키러 가는 쪽으로 끝나죠.\n\n찬드라는 자신의 안전은 딱히 신경쓰지 않고, 무모한 짓도 자주 하지만, 당신이라면 얘기가 달라집니다. 당신이 다친 것 같으면 큰 상심에 빠질 것이고, 당신이 괜찮다고 하면 눈물 가득한 눈으로 당신을 꼭 끌어안아 줄 거에요. 그리고 친구들이 '발견할'수 있는 곳에 보물을 조용히 숨겨 뒀다가, 그걸 발견하고 웃는 모습을 멀리서 지켜보고는 한답니다. 라이벌과 경쟁이 붙는다면 물러서는 법이 없지만요." },
    { id: 'illuse', name: '일루제', cost: 'Costs -4 FP', birthplace: '고흐우드', signature: '영체화', otherPowers: '생명력 흡수, 정신 흡수자, 망자와의 대화, 환영의 저주, 생각을 읽는 자, 꿈의 방문자, 기억의 길', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/sv6z0RJZ-c13.webp', description: "많은 학생들이 도시전설로 치부하기는 합니다만, 한 잔혹한 강령술사가 자기 하렘에 넣기 위해 마녀를 죽이고 그 혼을 새로운 육체에 집어넣은 것이 지금의 일루제라고 합니다. 그 강령술사가 어째서인지 모르겠지만 대신 죽어 버렸지만요. 일루제는 낯선 이들에 눈에 띄는 것을 꺼리는 신비스러운 소녀입니다. 보통은 안 보이는 폴터가이스트처럼 행동하거나 사람들의 꿈에 나타나고는 합니다. 이 장난기 많고 짓궃은 소녀 덕에 학교의 일진들이나 밥맛들이 보이지 않는 무언가로부터 온갖 이상한 일을 당합니다. 누구한테 말한다고 믿을 사람도 얼마 없죠.\n\n일루제가 당신을 좋아하게 된다면, 당신에게 꼭 붙어 다니면서도 낯을 가릴 겁니다. 눈에 보이지 않게 당신을 따라다니며 하루하루를 편하게 해 줄 거에요. 아마 나갔다 들어오면 방이 청소되어 있을 거고, 아침에 일어나면 밥이 차려져 있다거나, 당신을 싫어하는 사람들이 재수없는 일을 당했다는 말이 들려올지도 모릅니다. 하지만, 그녀가 당신 앞에 실제로 모습을 드러내려면 당신이 그녀를 살살 달래면서 격려해 줘야 할 거에요." },
    { id: 'xena', name: '제나', cost: 'Costs -4 FP', birthplace: '고흐우드', signature: '열 병기', otherPowers: '한기 III, 속도+, 수류의 힘, 에너지 집중', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/pvB1B3wY-c14.webp', description: "제나는 자기가 들고 다니는 칼만큼이나 차갑고 진지한 소녀입니다. 이알레도에서는 다들 그렇게 꾸밈 없이 정직했었죠. 그녀는 어렸을 때부터 스노우홈의 수호 기사로 키워졌지만, 그림세이어 세 놈이 나타났을 때는 그녀를 포함해서 모두들 속수무책이었습니다. 고향이 폐허가 되는 것을 지켜봐야만 했던 제나의 마음이 어땠을까요.\n\n제나는 대화할 때는 아주 무표정하게 직설적인 화법을 구사합니다. 그런데 사람들은 보통 그게 진지 개그 같은 거라고 생각하죠. 그래서 제나는 자기는 아주 심각하게 말한 걸 갖고 사람들이 자지러지면 상당히 당황합니다. 또 모든 것을 문자 그대로 받아들이기 때문에, 비유나 과장을 섞어 말하면 알아듣지 못할 겁니다. 그래도 매사 냉정침착한 성격 덕분에 주변 사람들도 쉽게 진정할 수 있고, 친구들이 감정에 휘둘리거나 패닉에 빠졌을 때 이성을 찾게 해 줄 수도 있습니다. 그리고 당신이 제나가 마음을 열게 할 수만 있다면, 사실 그렇게 무감정하지 않다는 것도 알 수 있을 거에요." },
    { id: 'rosalind', name: '로잘린드', cost: 'Costs -3 FP', birthplace: '고흐우드', signature: '정신 파괴자', otherPowers: '군중 제어, 물질 연금술', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/CpWrfqRq-c15.webp', description: "고흐우드의 왕족 마녀 혈통은 일반 마법소녀들을 대상으로 하는 양육 프로그램에는 참여하지 않습니다. 마법소녀의 양육을 맡을 가족을 심사하거나 할 수 없기 때문에, 약간... 가정교육이 잘못되는 경우도 있죠. 불쌍한 로잘린드는 수많은 시종들을 거느리는 삶에 너무 익숙해진 탓에 실제 세상이 메이리프 궁전과는 너무나 다르다는 것을 받아들이기 힘들어하고 있습니다. 뭐, 역사 깊은 고흐우드 왕가의 후계자이니 그럴 만도 하죠! 그러니까 좀 으스대고 점잔빼는 공주님 같은 아이라는 얘기는 해 둬야겠네요.\n\n마음 같아서는 그 높은 콧대를 어떻게 꺾어 버리라고 하고 싶지만... 솔직히 말하면 아주 부드럽게 접근해도 효과가 좋을 거에요. 사실 이 소녀가 받을 압박을 생각하면... 혹시 로잘린드가 인사 한 번 잘못하면 부모님들이 그렇게 소리지른다는 거 들어 보셨나요? 평범한 세상을 두루 구경시켜 줄 친구가 있으면 참 좋을 거에요. 당신이 그녀의 마음을 얻으면, 미래의 여왕님을 곁에 두는 거잖아요!" },
    { id: 'ruby', name: '루비', cost: 'Costs -4 FP', birthplace: '뉴 팰리세이드', signature: '중무장', otherPowers: '나나이트 갑옷 II, 수동 제어, CH402.MP5, 연결망 지배자 I, 무기 사보타주, 금속 피부, 회색 점액질, 힘+, 초인적인 의지', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/j9qYhKLQ-c16.webp', description: "스포츠를 좋아하고 경쟁심 넘치는 루비는 도전하는 모든 분야에서 최고가 되고 싶어합니다. 그 나이에 루비보다 매즈볼을 잘 하는 사람이 없어요. 그녀가 자기 능력을 과신하거나 세레머니를 하다가 곤경에 처할 때가 많은데도 말이죠. 루비가 소환하는 그 거대한 주먹은 자기가 직접 디자인한 겁니다. 거기에 맞으면 그냥 경기장 끝에서 끝으로 날아가는 거에요! \n\n만약에 당신이 루비와 공통의 관심사를 찾을 수 있다면 선의의 라이벌이 뭔지 제대로 느낄 수 있을 겁니다. 서로를 밀어붙이면서 매일매일 더 나아지기 위해 노력하는 거죠. 하지만 그게 아니라면 꽤 다혈질적인 면모를 보여 줄 겁니다. 특히 더 실력 좋은 사람을 만나서 큰코 다쳤다면 말입니다. 아마 몇 달 동안 쉬지도 않고 훈련하면서 꼭 이기려고 할 거에요. 좀... 집착이 심하죠. 루비는 게으른 건 딱 싫어하고, 언제나 당신이 알을 깨고 목표를 향해 힘차게 나아가도록 도와 주려 합니다. 근데 생각보다 말이 먼저 나가는 타입이라 가끔은 의도치 않게 무례해질 때가 있어요." },
    { id: 'cordelia', name: '코델리아', cost: 'Costs -3 FP', birthplace: '뉴 팰리세이드', signature: '초능력 수술', otherPowers: '역행, 카리스마+, 황홀한 치유, 방어의 원, 수호천사, 치유의 화살', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mPQg27B-c17.webp', description: "이 친구는 좀 무섭네요! 반사회적 성격 장애 테스트에서 점수가 높아서... 다시 말해 공감 능력이 없는 소시오패스라는 겁니다. 그렇다고 나쁜 소녀는 아니에요! 그냥... 여러모로 걱정스러운 거죠. 그래도 그 어린 나이에 수술 실력이 엄청납니다. 당신이 다치면 기다렸다는 듯이 절개를 넣고 잘못된 부분을 고쳐 줄 거에요. 너무 열정적이라 문제일지도 모르지만.\n\n코델리아는 주변에 사람들이 있다면 얌전하고 공손한 연기를 합니다. 정말 소름돋게도 완벽해요. 진짜 성격은, 음, 시니컬하고, 블랙 유머에 무감정한 위트를 곁들였죠. 남들이 꺼리는 주제라도 신랄하게 까내리는 걸 주저하지 않기 때문에 솔직한 비판을 해 줄 친구를 찾는다면 코델리아가 어울릴 겁니다. 당신이 좀 둔하다면 코델리아는 짜증만 내겠지만, 그녀가 존중할 만큼 똑똑하다면 정말 의리 넘치는 친구가 되어 줄 거에요. 지금은 정도를 걷기 위해 모든 노력을 다 하고 있지만... 긍정적인 영향을 받는다면 분명 좋겠죠!" },
    { id: 'anna', name: '안나', cost: 'Costs -3 FP', birthplace: '뉴 팰리세이드', signature: '?????', otherPowers: '역장, 에너지 집중, 소닉붐', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SDpwhdbK-c18.webp', description: "안나는 평범한 마법소녀가 아니라 왜곡체입니다. 그녀의 힘은 어머니로부터 물려받은 것이 아니라 현실에 발생한 오류에서 기인합니다. 말하자면, 그녀가 진심으로 믿는 모든 것이 현실이 되는 힘이죠. 얼핏 듣기로는 쉽게 역이용할 수 있는 힘 같지만, 안나는 정신 조작에 면역인 데다가, 특유의 정신 상태 때문에 의도적으로 속일 수도 없습니다. 한 번은 좀 부도덕한 과학자들이 최선을 다해 시도해 봤는데, 결국에는 다들 안나의 무서운 \"상상 속 친구\"인 머긴스 씨에게 학살당하고 말았어요.\n\n지금은 국가에서 안나를 양육 중입니다. 학교에서는 혼자만의 세계에 빠져 있는 '이상한 친구'로 통하죠. 대화를 나눠 보면 아주 활발하고 명랑하고 애정이 넘치지만, 그녀의 말을 이해할 수 없을 거에요. 안나는 그림을 그리거나 선물을 주거나 포옹을 하는 것으로 의사를 표현하는 것을 선호합니다. 만국공통의 언어잖아요? 친구가 여태 없어서, 당신이 잘 대해 주면 기뻐서 어쩔 줄 모를 겁니다. 그리고 그 힘이 예상 못 한 방식으로 당신을 돕게 될 수도 있어요." },
    { id: 'stacy', name: '스테이시', cost: 'Costs -4 FP', birthplace: '로바인', signature: '무기 제작자', otherPowers: '전문 기계공 I, 땜장이, 콰광!, 최고 보안 등급, 나나이트 갑옷 I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/6RtQ9kFQ-c19.webp', description: "이런, 세상에. 자기 키만한 20mm 라이플을 들고 다니는 모습이 정말이지 귀엽네요. 뭐, 좀 지나면 그 총도 몸에 맞겠죠.\n\n스테이시의 어머니는 골수 생존주의자였습니다. 그, 백 년 안에 세상이 멸망한다고 생각하는 사람들이요. 그래서 스테이시는 걸음마를 할 때부터 혹독한 군사 훈련을 받았습니다. 마법학교에 입학해서야 벗어날 수 있게 됐지만, 학교에 적응하는 것을 어려워하고 있죠. IED나 총탄 규격 같은 건 줄줄 꿰고 있지만, 옷을 사거나 과제를 하거나 마법소녀 친구들과 이야기하는 법은 아예 모르니까요.\n\n이 부끄럼 많은 소녀는 엄격한 군대식 생활이 몸에 배어서 직접 의사결정을 하는 것을 어려워합니다. 마음 속 한 구석에서는 평범한 소녀처럼 살면서 예쁜 드레스를 입으면 어떨까 공상을 하죠. 스테이시는 자신이 모르던 삶을 당신이 가르쳐 주게 된다면 정말 고마워할 겁니다. 그리고 혹시나 당신이 총을 좋아한다면 몇 시간 동안 강의를 해 줄 거에요." },
    { id: 'meryll', name: '메리알', cost: 'Costs -4 FP', birthplace: '로바인', signature: '동물 조련사', otherPowers: "마녀의 패밀리어 III, 수호의 결속, 황홀한 치유, 치유의 화살, 방어의 원", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BKf1nC3h-c20.webp', description: "메리알의 기숙사 방이 너무 시끄럽다는 민원이 끊이지를 않습니다. 거기는 그냥 동물원이거든요! 날아다니는 작은 요정들부터, 머리 셋 달린 뱀, 캇파에 이르기까지 별의 별 것들이 다 있지만, 메리알이 제일 좋아하는 동물은 잔디라는 이름이 붙은 커다란 독 뱉는 만티코어입니다. 볼스루 성의 수석 동물 조련사인 이 소녀는 세계 각지를 탐험하며 온갖 동물들을 다 만나 봤지만, 아직도 몇몇 희귀종들을 찾아다니고 있습니다.\n\n메리알은 수의사 역할을 하는 한편 친구들을 돕기 위해서 치유 마법을 집중적으로 공부했습니다. 애완동물들 (그리고 당신)이 없으면 잘 웃지도 않는 진지한 성격에, 자신의 이상을 위해서라면 냉정한 면도 보여 줍니다. 명예를 지키고, 도움이 필요한 이들을 돕고, 동물들을 존중하는 것 말이에요. 불의를 보면 참지 못하고, 나쁜 놈들이 정의의 심판을 받는 것을 보고 싶어하기도 하죠. 하지만 그렇다고 메리알이 잔혹한 건 아닙니다. 자기가 직접 싸우지 않고도 다른 사람들이 올바른 길로 가는 것을 보고 싶어한답니다." },
    { id: 'zorreth', name: '조레스', cost: 'Costs -3 FP', birthplace: '로바인', signature: '괴수화 II', otherPowers: '방화광 II, 플라즈마 타격, 소닉붐, 힘+, 속도+', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SD8Kj6sm-c21.webp', description: "그녀는 오래 전에 소식이 끊겨서 모두가 죽은 줄로만 알았습니다. 그러다 우리는 이 소녀의 부모님이 용 두 마리와 싸움이 붙어서 끔찍하게 잡아먹혔고, 그 용들이 \"조레스\"를 데려가 키우기로 했다는 것을 알아냈습니다. 마법학교에서 어떻게든 계약을 맺어서 조레스를 데려왔지만, 이 친구는 좀 제멋대로입니다. 자기를 인간보다 훨씬 우월한 용족이라 여기고, 툭하면 화가 머리 끝까지 나서 3층 건물만한 용 형태로 변신하면서 사방을 뒤집어 놓죠. 그녀가 '수집'할 반짝이는 물건을 주면 좀 진정되는데, 구슬이나 단추 같은 작은 것도 충분하답니다.\n\n조레스가 당신을 좋아하게 된다면 당신을 \"좋은 인간\"으로 여기고 귀한 애완동물처럼 다룰겁니다. 당신을 해코지하려는 누군가가 있으면 아주 사납게 쫓아내겠지만, 동시에 당신을 소유하려 하겠죠. 어쩌면 당신이 그녀가 이곳에 적응하는 걸 도와 줄 수도 있겠죠? 근데, 뭘 하든 건에, 절대 조레스에게 상처를 주지 마세요. 이 소녀의 어머니는 진짜 용이고, 그것도 조레스의 용 형태보다 몇십 배는 큰 용이니까요." },
    { id: 'ayuzawa', name: '아유자와', cost: 'Costs -5 FP', birthplace: '지팡구', signature: "오니의 축복", otherPowers: '힘+, 카리스마+, 재빠른 반사신경, 무기 제작자, 에너지 집중, 방어의 원, 위상 변화', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gbcpH1vn-c22.webp', description: "오니는 아주 희귀하고 자애로운 요괴입니다. 이들은 아주 가끔 갓 태어난 마법소녀를 골라 그녀와 융합하는데, 엄청난 힘을 부여하는 대신 다른 요괴들과의 영원한 전쟁에 참여시키죠. 물론 아유자와는 딱히 누가 그렇게 등을 떠밀어서 사랑하는 학교를 못된 혼령들로부터 지키고 있는 게 아닙니다. 원래부터 정의감 넘치는 히어로였으니까요. 아유자와는 학생회장에 다른 동아리 회장직까지 몇 개 맡고 있고, 자기 반에서는 이미 졸업생 대표로 내정되어 있습니다. 이만큼 애교심 넘치는 마법소녀도 없을 거에요!\n\n지금까지의 모습으로 보면 아유자와는 착한 큰언니처럼 당신에게 충고를 해 주고, 항상 안전하게 다니는지 확인하고, 심지어 점심 도시락을 싸 줄지도 모릅니다. 그녀가 당신을 아기처럼 돌보는 걸 원하지 않는다면 어느 정도 선을 그어야 할 거에요. 아유자와는 책임감이 철철 흘러넘쳐서 약속에 늦느니 차라리 죽고 말 정도입니다. 그리고 모두가 다 최고라고 생각하는 이상주의자이기 때문에, 이리저리 이용당하게 될지도 몰라요." },
    { id: 'momoi', name: '모모이', cost: 'Costs -5 FP', birthplace: '지팡구', signature: '텔레파시 달인', otherPowers: '저주술사의 고서, 괴수화 I, 염동력 I, 식물술사, 생각을 읽는 자, 꿈의 방문자', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GQj3z2cS-c23.webp', description: "지팡구 사람들은 마녀들을 신봉합니다. 그리고 모모이는 그걸 최대한으로 이용해 먹고 있죠. 숲 속 거대한 사당 안에 실면서 하치모리의 여신이라 자칭하고, 빈백 옥좌에 앉아서 신실한 추종자들이 떠먹여 주는 간식을 받아먹고 지냅니다. 이 장난기 많고 의기양양한 소녀는 '여신의 수호자'의 칭호를 당신에게 물려주기로 했고, 아주 교묘한 시험들을 통해 당신이 그녀의 오른팔이 될 자격이 충분한지 시험하려 할 겁니다.\n\n모모이는 유서 깊은 여우 일족의 일원으로 항상 자연을 보호하는 것을 최우선으로 생각합니다. 그녀의 숲을 누군가 더럽힌다면 곧 분노한 그녀를 마주하게 되겠죠. 그녀는 침입자들과 싸울 때는 하얀 털의 커다란 구미호로 변신합니다. 추종자들은 매일 반 시간씩 그 꼬리털을 다듬어야 하구요. 모모이는 누군가 그녀의 신성함을 부정한다면 제대로 심통이 나서 삐져 버립니다. 그리고 당신과 같이 있게 된다면 아침에 안개 낀 숲 속에서 함께 센차를 마시는 걸 즐길 겁니다." },
    { id: 'licenda', name: '라이센다', cost: 'Costs -3 FP', birthplace: '지팡구', signature: '혈화', otherPowers: '생명력 흡수, 망자와의 대화, 영체화', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LDQjngdm-c24.webp', description: "조심하세요. 라이센다는 마음이 무너진 채 예전 모습의 껍데기만 남아, 이제는 거의 입도 열지 않습니다. 몇 년 전 섹스에 미친 사디스트들과 쾌락주의자들의 교단이 대대적인 납치 사건을 일으켰을 때, 그곳에서 유일하게 살아남은 피해자가 라이센다였습니다. 납치범들은 더욱 \"창의적인\" 고문을 하기 위해 서로 경쟁했고, 실제로 그녀가 무슨 일을 당했는지는 전부 말소되어 있지만, 그 이야기를 들은 사람들 대부분은 그 지식을 안고 가느니 기억을 지우는 쪽을 택했습니다. 그리고 라이센다는 죽고 싶어도 죽을 수도 없는 처지입니다. 신스루 마녀단을 빼면 이런 일은 몇천 년 전의 '버림받은 시대' 이후로 한 번도 일어나지 않았으니까요! 어쩌면 세상이 실제로 잘못돼 가고 있는 걸지도요...\n\n라이센다에게는 지금도 과거의 유령이 따라다니고 있는 것 같습니다. 말 그대로요. 웬만한 혼령들은 쉽게 처리할 수 있지만, 이쪽은 전례가 없었던 힘과 폭력성을 지니고 있습니다. 그리고, 실제로 물증은 없지만... 라이센다와 같이 지내던 사람들 일부가 석연찮게 실종되었다는 이야기는 꼭 해야겠네요. 소문에 따르면 그 유령이 라이센다의 누이라고 합니다. 납치범들을 즐겁게 하기 위해 그녀가 직접 누이를 죽여야 했다고 하는데, 그 누이의 이름은 아예 기억도 안 나네요." }
];

export const CUSTOM_CLASSMATE_CHOICES_DATA: CustomClassmateOption[] = [
    { id: 'custom_classmate_25', cost: 'Costs -4 FP', description: 'Create a companion with 25 Companion Points.' },
    { id: 'custom_classmate_35', cost: 'Costs -6 FP', description: 'Create a companion with 35 Companion Points.' },
    { id: 'custom_classmate_50', cost: 'Costs -8 FP', description: 'Create a companion with 50 Companion Points.' },
];

export const CUSTOM_CLASSMATE_CHOICES_DATA_KO: CustomClassmateOption[] = [
    { id: 'custom_classmate_25', cost: '행운 점수 -4', description: '동료 점수 25점으로 클래스메이트를 만듭니다.' },
    { id: 'custom_classmate_35', cost: '행운 점수 -6', description: '동료 점수 35점으로 클래스메이트를 만듭니다.' },
    { id: 'custom_classmate_50', cost: '행운 점수 -8', description: '동료 점수 50점으로 클래스메이트를 만듭니다.' },
];