
import type { CompanionOption } from '../types';

export const COMPANION_INTRO = {
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/B2TnNC34-companions.webp',
    description: "You can decide what they look like on your own. You can also choose contradictory personality traits, if you want. Note that companions can't have their own companions, automatons, puppets, etc."
};

export const COMPANION_INTRO_KO = {
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/B2TnNC34-companions.webp',
    description: "당신이 직접 당신만의 동료를 구상할 수 있습니다. 원한다면 상충되는 성격을 고를 수도 있습니다. 동료의 동료, 동료의 오토마톤, 동료의 퍼펫... 등등은 설정할 수 없습니다."
};

export const COMPANION_CATEGORIES: CompanionOption[] = [
    { id: 'mage', title: 'MAGE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nMCFYnCq-mage.webp', cost: 0, description: "Just a regular human being, created by the Mother herself every Theosis Day! They tend to possess great powers, but also have their own goals, opinions and desires. Whether these align or conflict with yours can be decided in the {w}Relationship{/w} category just below. Pretty fun people usually, though!", requirement: 'Required if no other conditions are met' },
    { id: 'puppet', title: 'PUPPET', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ccMjxSdd-puppet.webp', cost: 0, description: "Created through a complex and advanced bastardization of the process through which the Mother creates mages, these creatures are virtually indistinguishable from a human, aside from their general uncanny valley vibe and the sheer diligence with which they serve their creator.", requirement: 'Requires, and is required if, Human Marionette/Verse Attendant' },
    { id: 'automaton', title: 'AUTOMATON', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/pjypXBps-automation.webp', cost: 0, description: "Human-like entities with a wide variety of possible appearances created by imbuing an advanced machine with an artificial soul. They are highly durable and intelligent, but their true sapience is a subject of debate, and the way they express their emotions can feel either dulled or forced.", requirement: 'Requires, and is required if, Roboticist II' },
    { id: 'undead', title: 'UNDEAD', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0WtKCyd-undead.webp', cost: 0, description: "The rotting remains of a mage who once lived brought back to life, generally striking disgust and fear into the hearts of all who witness them. Their intimidation factor is immense, and they benefit from increased regeneration from cuts and blunt damage. Expect funny looks, however, at the very least.", requirement: 'Requires, and is required if, Undead Thrall' },
];

export const COMPANION_CATEGORIES_KO: CompanionOption[] = [
    { id: 'mage', title: '마법소녀', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nMCFYnCq-mage.webp', cost: 0, description: "테오시스 축제날마다 어머니께서 창조하시는 바로 그 마법소녀들입니다! 강한 힘을 지닌 경우가 많지만, 자기만의 목표와 가치관, 그리고 욕망을 가지고 있습니다. 당신과 얼마나 잘 맞게 될지는 바로 밑에 있는 관계 항목에서 결정하시면 됩니다. 그래도 보통은 꽤 유쾌한 사람들이죠!", requirement: '다른 조건을 만족하지 못한다면, 반드시 선택해야 합니다.' },
    { id: 'puppet', title: '퍼펫', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ccMjxSdd-puppet.webp', cost: 0, description: "어머니께서 마법소녀들을 창조하시는 그 방식을 조악하게나마 흉내내서 만들어지는 이 생명체들은 사실상 인간과 다를 것이 없습니다. 다만, 특유의 불쾌한 골짜기와 창조주에게 맹목적으로 복종한다는 점이 다르지요.", requirement: '인간 마리오네트 / 가상 우주 관리자를 선택한 경우에만, 반드시 선택해야 합니다.' },
    { id: 'automaton', title: '오토마톤', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/pjypXBps-automation.webp', cost: 0, description: "이 인간을 닮은 존재들은 고도로 정밀한 기계에 인공 영혼을 부여해서 만들어지고, 다양한 외형을 지닐 수 있습니다. 아주 지능이 높고 강인하지만, 정말 지혜로운지에 관해서는 논란의 여지가 있고, 감정을 표출하는 방식이 약간 둔하거나 강제되어 보일 수 있습니다.", requirement: '로봇술사 II를 선택한 경우에만, 반드시 선택해야 합니다.' },
    { id: 'undead', title: '언데드', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0WtKCyd-undead.webp', cost: 0, description: "죽은 마녀의 썩어가는 유해를 되살렸습니다. 언데드를 목격하는 이들은 대부분 혐오감과 공포를 느낄 것입니다. 그만큼 위협적인 건 말할 것도 없고, 둔기나 날붙이에 의한 상처쯤은 금방 회복할 수 있습니다. 하지만 그 겉모습은 잘 쳐 줘야 우스꽝스러운 수준이겠죠.", requirement: '언데드 노예를 선택한 경우에만, 반드시 선택해야 합니다.' },
];

export const COMPANION_RELATIONSHIPS: CompanionOption[] = [
    { id: 'frenemies', title: 'FRENEMIES', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/bM2FtkXB-frenmies.webp', cost: 0, description: "Either due to conflicting beliefs and personalities, or mere circumstances, you two will be at odds when you first meet. You'll still cooperate, but expect to get on each other's nerves. It won't be impossible for you to become better friends, but you'll have to make a genuine effort." },
    { id: 'friends', title: 'FRIENDS', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/6SvqL3N-friends.webp', cost: 5, description: "You won't really have much trouble getting along! Circumstances will conspire to make you friends, and they will like you well enough. They'll definitely be fun just to hang around with, though if you want them to become something even more, you'll have to put in the extra work." },
    { id: 'best_friends', title: 'BEST FRIENDS', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/QjmNt2Bs-bestfriends.webp', cost: 10, description: "They will totally get along with you like two peas in a pod shortly after your first meeting, and the two of you will become fast friends, making lots of happy memories together. They'll be one of your closest friends, or maybe you'll become even closer." },
    { id: 'lovey_dovey', title: 'LOVEY DOVEY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5gQkTQHS-loveydovey.webp', cost: 15, description: "You don't even have to try to earn their affection; they will absolutely adore you pretty much the moment that you meet! This can remain a platonic affection, or you can decide for it to progress into a romantic love. Either way, it's going to be nice having your own cheerleader." },
    { id: 'subservient', title: 'SUBSERVIENT', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/d4fWCJYY-subservient.webp', cost: 0, description: "It doesn't really matter what they feel about you! After all, since you created them with your own magic, you can pretty much have them act however you please. Afford them some autonomy if you wish, or micromanage their every move completely.", requirement: 'Requires, and is required if, not Mage' },
];

export const COMPANION_RELATIONSHIPS_KO: CompanionOption[] = [
    { id: 'frenemies', title: '애증', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/bM2FtkXB-frenmies.webp', cost: 0, description: "성격이나 신념이 맞지 않든, 아니면 그냥 상황이 안 좋든 간에, 첫 만남부터 사이가 나쁠 겁니다. 뭐, 협력이야 하겠지만, 서로 신경을 긁어댈 게 뻔히 보이네요. 친구 관계를 진전시킬 수 없다는 건 아닌데, 꽤 진지하게 노력해야 할 겁니다." },
    { id: 'friends', title: '친구', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/6SvqL3N-friends.webp', cost: 5, description: "별 탈 없이 잘 지낼 수 있겠네요! 이런저런 일을 겪다 보면 어느 새 친구가 될 거고, 그 쪽에서도 당신을 좋아할 거에요. 같이 놀기만 해도 재미있겠지만, 좀 더 진도를 나가고 싶으면 그래도 노력을 해야겠죠?" },
    { id: 'best_friends', title: '베프', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/QjmNt2Bs-bestfriends.webp', cost: 10, description: "처음으로 만난 지 얼마 되지 않아 친자매처럼 꼭 붙어다니게 될 겁니다. 당신과 빨리 친해지면서 좋은 추억도 많이 만들 수 있을 거구요. 서로 가장 소중한 친구 사이가 될 건 확실합니다. 아니, 어쩌면 그 이상도 될 수 있겠죠." },
    { id: 'lovey_dovey', title: '꽁냥꽁냥', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5gQkTQHS-loveydovey.webp', cost: 15, description: "애정을 얻으려고 당신이 노력을 할 필요도 없어요. 만나자마자 첫눈에 반해 버릴 텐데요! 플라토닉 러브에서 머물 수도 있고, 당신이 원한다면 더 진한 연애로 발전시킬 수도 있겠죠. 뭐가 됐든 당신을 응원해 주는 사람이 있다는 건 참 좋을 거에요." },
    { id: 'subservient', title: '주종 관계', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/d4fWCJYY-subservient.webp', cost: 0, description: "그 쪽에서 당신을 어떻게 생각하는지는 사실 별 상관이 없습니다! 아니, 당신이 직접 마법으로 창조한 존재인데 당신 마음대로 행동하게 할 수 있죠. 원한다면 자율성을 조금 부여해도 되고, 일거수일투족에 모두 관여할 수도 있습니다.", requirement: '카테고리가 마법소녀가 아닌 경우 필수' },
];

export const COMPANION_PERSONALITY_TRAITS: CompanionOption[] = [
    { id: 'shy', title: 'SHY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nXDMPhZ-shy.webp', cost: 0, description: '' },
    { id: 'confident', title: 'CONFIDENT', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ds2TTXTj-confident.webp', cost: 2, description: '' },
    { id: 'anxious', title: 'ANXIOUS', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/NnLPj9n6-anxious.webp', cost: 0, description: '' },
    { id: 'brave', title: 'BRAVE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/9344Y0Q3-brave.webp', cost: 2, description: '' },
    { id: 'reserved', title: 'RESERVED', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/N2CzQ43h-reserved.webp', cost: 0, description: '' },
    { id: 'playful', title: 'PLAYFUL', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jkVwdDrH-playful.webp', cost: 2, description: '' },
    { id: 'grumpy', title: 'GRUMPY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G3HxBSq5-grumpy.webp', cost: 0, description: '' },
    { id: 'laid_back', title: 'LAID BACK', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PGj5n2VJ-laidback.webp', cost: 2, description: '' },
    { id: 'selfish', title: 'SELFISH', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Z1JXvxqg-selfish.webp', cost: 0, description: '' },
    { id: 'kind', title: 'KIND', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/60S5fTHq-kind.webp', cost: 2, description: '' },
    { id: 'ditzy', title: 'DITZY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/dsbDXpqd-ditzy.webp', cost: 0, description: '' },
    { id: 'bright', title: 'BRIGHT', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/207SSMYg-bright.webp', cost: 2, description: '' },
    { id: 'sad', title: 'SAD', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7d7svrx7-sad.webp', cost: 0, description: '' },
    { id: 'cheerful', title: 'CHEERFUL', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nMq2tDFB-cheerful.webp', cost: 2, description: '' },
    { id: 'sleepy', title: 'SLEEPY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/W7xLDNG-sleepy.webp', cost: 0, description: '' },
    { id: 'energetic', title: 'ENERGETIC', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DfWGgf2M-energetic.webp', cost: 2, description: '' },
    { id: 'awkward', title: 'AWKWARD', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fVkBgkw1-awkward.webp', cost: 0, description: '' },
    { id: 'charismatic', title: 'CHARISMATIC', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gMKfJp3g-charismatic.webp', cost: 2, description: '' },
    { id: 'prudish', title: 'PRUDISH', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cKd9vH1G-prudish.webp', cost: 0, description: '' },
    { id: 'flirty', title: 'FLIRTY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yFZRsJcS-flirty.webp', cost: 2, description: '' },
    { id: 'simple', title: 'SIMPLE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rKYQp4Ch-simple.webp', cost: 0, description: '' },
    { id: 'creative', title: 'CREATIVE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0pzJBN5H-creative.webp', cost: 2, description: '' },
    { id: 'smug', title: 'SMUG', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zHNX8vfs-smug.webp', cost: 0, description: '' },
    { id: 'humble', title: 'HUMBLE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GQWmhvvw-humble.webp', cost: 2, description: '' },
    { id: 'prissy', title: 'PRISSY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rGx2hm1D-prissy.webp', cost: 0, description: '' },
    { id: 'pragmatic', title: 'PRAGMATIC', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/CKwW7zQ2-pragmatic.webp', cost: 2, description: '' },
    { id: 'brash', title: 'BRASH', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/hx0TgngV-brash.webp', cost: 0, description: '' },
    { id: 'wise', title: 'WISE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/JFdhz3g8-wise.webp', cost: 2, description: '' },
    { id: 'lazy', title: 'LAZY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LDgqBGyM-lazy.webp', cost: 0, description: '' },
    { id: 'determined', title: 'DETERMINED', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/RTLPnP8h-determined.webp', cost: 2, description: '' },
];

export const COMPANION_PERSONALITY_TRAITS_KO: CompanionOption[] = [
    { id: 'shy', title: '부끄러워함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nXDMPhZ-shy.webp', cost: 0, description: '' },
    { id: 'confident', title: '자신감 넘침', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ds2TTXTj-confident.webp', cost: 2, description: '' },
    { id: 'anxious', title: '불안해함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/NnLPj9n6-anxious.webp', cost: 0, description: '' },
    { id: 'brave', title: '용감함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/9344Y0Q3-brave.webp', cost: 2, description: '' },
    { id: 'reserved', title: '차분함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/N2CzQ43h-reserved.webp', cost: 0, description: '' },
    { id: 'playful', title: '장난기 많음', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jkVwdDrH-playful.webp', cost: 2, description: '' },
    { id: 'grumpy', title: '심술쟁이', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G3HxBSq5-grumpy.webp', cost: 0, description: '' },
    { id: 'laid_back', title: '태평함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PGj5n2VJ-laidback.webp', cost: 2, description: '' },
    { id: 'selfish', title: '이기적', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Z1JXvxqg-selfish.webp', cost: 0, description: '' },
    { id: 'kind', title: '친절함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/60S5fTHq-kind.webp', cost: 2, description: '' },
    { id: 'ditzy', title: '어리바리', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/dsbDXpqd-ditzy.webp', cost: 0, description: '' },
    { id: 'bright', title: '똑똑함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/207SSMYg-bright.webp', cost: 2, description: '' },
    { id: 'sad', title: '우울함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7d7svrx7-sad.webp', cost: 0, description: '' },
    { id: 'cheerful', title: '쾌활함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nMq2tDFB-cheerful.webp', cost: 2, description: '' },
    { id: 'sleepy', title: '잠꾼', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/W7xLDNG-sleepy.webp', cost: 0, description: '' },
    { id: 'energetic', title: '활기참', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DfWGgf2M-energetic.webp', cost: 2, description: '' },
    { id: 'awkward', title: '특이함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fVkBgkw1-awkward.webp', cost: 0, description: '' },
    { id: 'charismatic', title: '카리스마', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gMKfJp3g-charismatic.webp', cost: 2, description: '' },
    { id: 'prudish', title: '내숭쟁이', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cKd9vH1G-prudish.webp', cost: 0, description: '' },
    { id: 'flirty', title: '카사노바', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yFZRsJcS-flirty.webp', cost: 2, description: '' },
    { id: 'simple', title: '단순함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rKYQp4Ch-simple.webp', cost: 0, description: '' },
    { id: 'creative', title: '창의적', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0pzJBN5H-creative.webp', cost: 2, description: '' },
    { id: 'smug', title: '의기양양', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zHNX8vfs-smug.webp', cost: 0, description: '' },
    { id: 'humble', title: '겸손함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GQWmhvvw-humble.webp', cost: 2, description: '' },
    { id: 'prissy', title: '점잔빼는', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rGx2hm1D-prissy.webp', cost: 0, description: '' },
    { id: 'pragmatic', title: '실용적인', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/CKwW7zQ2-pragmatic.webp', cost: 2, description: '' },
    { id: 'brash', title: '성급함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/hx0TgngV-brash.webp', cost: 0, description: '' },
    { id: 'wise', title: '현명함', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/JFdhz3g8-wise.webp', cost: 2, description: '' },
    { id: 'lazy', title: '게으름', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LDgqBGyM-lazy.webp', cost: 0, description: '' },
    { id: 'determined', title: '의지 넘침', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/RTLPnP8h-determined.webp', cost: 2, description: '' },
];

export const COMPANION_PERKS: CompanionOption[] = [
    { id: 'inhuman_form', title: 'INHUMAN FORM', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/67D2jD7f-inhumanform.webp', cost: 5, description: "Things like, say, a girl with cat ears is completely fine, but if you want to complete something completely inhuman like a centaur or lamia, you're going to have to pick this choice. Create their monstrous form with {w}40 Beast Points{/w} on the {i}Reference Page{/i} excluding options marked with an *." },
    { id: 'special_weapon', title: 'SPECIAL WEAPON', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DPV6k8cj-specialweapon.webp', cost: 5, description: "They will either already possess or be granted a unique enchanted weapon that can be created using {w}20 Weapons Points{/w} down below. This will allow them to channel their abilities more efficiently, allowing them take two extra {wn}Kaarn{/wn}-level spells, or one extra {fpx}Purth{/fpx}-level spell." },
    { id: 'signature_power', title: 'SIGNATURE POWER', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G4Vfc5py-signaturepower.webp', cost: 5, description: "Your companion will have a signature power which she's most known for, to be affected by one of the boosts on this list: pastebin.com/GkqPm98A. Can be taken multiple times, but each purchase beyond the first will cost {w}10 Points{/w}. If you choose a {r}Xuth{/r}-tier spell, the price of this perk is doubled." },
    { id: 'impressive_career', title: 'IMPRESSIVE CAREER', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gMyktjKh-impressivecareer.webp', cost: 5, description: "Choose one of the organizations listed on {i}Page 5{/i} or any applicable groups elsewhere in the CYOA. Your companion is now part of that group and gets associated benefits, and can help you join. Double price for Holy Knights or IDPA, triple price for Red-Jade Council. Can't join political careers.", requirement: 'Must be Human' },
    { id: 'dark_magician', title: 'DARK MAGICIAN', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/B5kkBbbg-darkmagician.webp', cost: 3, description: "This companion dabbles in the black arts, which can provide them some incredible but terrible powers. Every time you take this perk, the companion can have one {bpx}Sinthru{/bpx}-level spell, as long as it's within a blessing where they already have at least two spells of any level. Can be taken up to 4 times." },
];

export const COMPANION_PERKS_KO: CompanionOption[] = [
    { id: 'inhuman_form', title: '인외의 형상', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/67D2jD7f-inhumanform.webp', cost: 5, description: "가령 '고양이귀가 달린 마법소녀' 같은 건 전혀 문제가 없지만, 켄타우로스나 라미아처럼 인외의 존재를 설정하고 싶다면 이 특성을 골라야 합니다. {w}동물 점수 40점{/w}이 주어집니다. 참고 페이지에서 동료의 상세한 모습을 설정하세요. 단, *표시가 된 선택지는 고를 수 없습니다." },
    { id: 'special_weapon', title: '특별한 무기', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DPV6k8cj-specialweapon.webp', cost: 5, description: "동료가 고유한 마법 무기를 가지고 시작하거나, 당신이 그 무기를 제공할 수 있습니다. 무기를 디자인하기 위한 {w}무기 점수 20점{/w}이 주어집니다. 아니면 당신의 무기를 그대로 베낄 수도 있겠죠. 덕분에 동료는 자신의 힘을 더 잘 발휘할 수 있게 되어, {wn}카른{/wn} 등급의 마법 2종류나 {fpx}퍼르스{/fpx} 등급의 마법 1종류를 추가로 사용할 수 있습니다." },
    { id: 'signature_power', title: '주력기', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G4Vfc5py-signaturepower.webp', cost: 5, description: "당신의 동료는 자신을 대표하는 주력기를 갖게 됩니다. 주력기는 Boost 버튼을 누른 것과 같은 강화를 적용받게 됩니다. 동료가 여러 가지의 주력기를 가질 수도 있지만, 첫 번째 주력기를 제외하면 {w}10점{/w}이 소모됩니다. 주력기가 {r}주스{/r} 등급의 마법이라면, 소모 점수가 두 배가 됩니다." },
    { id: 'impressive_career', title: '인상적인 경력', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gMyktjKh-impressivecareer.webp', cost: 5, description: "6페이지에 명시된 단체나, 이 CYOA에 언급된 기타 적합한 단체를 하나 고르세요. 당신의 동료는 그 단체의 일원이 되어 해당하는 특전을 지원받고, 당신이 가입할 수 있게 도와 줄 수도 있습니다. 성기사단이나 IDPA를 선택하는 경우 10점이, 홍옥의 의회를 선택하는 경우 15점이 소모됩니다. 정치적인 조직을 고를 수는 없습니다.", requirement: '인간일 때만 가능' },
    { id: 'dark_magician', title: '흑마술사', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/B5kkBbbg-darkmagician.webp', cost: 3, description: "당신의 동료는 흑마술을 공부해서 강력하지만 끔찍한 힘을 다룰 수 있습니다. 이 특성을 선택할 때마다 동료가 {bpx}신스루{/bpx} 등급의 마법을 1종류 사용할 수 있게 됩니다. 단, 최소 2가지 이상의 마법을 배워 놓은 축복 안에서 선택해야 합니다. 최대 4회 선택할 수 있습니다." },
];

export const COMPANION_POWER_LEVELS: CompanionOption[] = [
    { id: 'below_average', title: 'BELOW AVERAGE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/sfX3Gs0-belowaverage.webp', cost: 0, description: "They are definitely among the least powerful mages in the world. Sure, they're still leagues above mundanes, but they're probably going to work best as support rather than direct fighters.\n\nThey can be given the {wn}Essential Boons{/wn}, one {fpx}Purth{/fpx}-level spell, and three {wn}Kaarn{/wn}-level spells, spread across a maximum of two {w}Blessings{/w}." },
    { id: 'average', title: 'AVERAGE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/KpTd1DPQ-average.webp', cost: 15, description: "This is the level of magical acumen most majority of mages are at. Good enough to learn spells in a couple different blessings, making them very formidable fighters.\n\nThey can be given the {wn}Essential Boons{/wn}, two {fpx}Purth{/fpx}-level spells, and six {wn}Kaarn{/wn}-level spells, spread across a maximum of three {w}Blessings{/w}." },
    { id: 'above_average', title: 'ABOVE AVERAGE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1D3cyCf-aboveaverage.webp', cost: 30, description: "They're a particularly talented mage that stands head-and-shoulders above their peers.\n\nThey can be given the {wn}Essential Boons{/wn}, one {rx}Xuth{/rx}-level spell (if they have at least four spells within the same blessing), two {fpx}Purth{/fpx}-level spells, and six {wn}Kaarn{/wn}-level spells, spread across a maximum of four {w}Blessings{/w}. Can't have {w}Maria's Gift{/w}." },
];

export const COMPANION_POWER_LEVELS_KO: CompanionOption[] = [
    { id: 'below_average', title: '평균 이하', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/sfX3Gs0-belowaverage.webp', cost: 0, description: "이 세계의 평균적인 마법소녀들보다 약하다는 것에는 의심의 여지가 없습니다. 물론 일반인들과는 넘을 수 없는 격차가 있지만, 그래도 전방에 직접 나서는 것보다는 후방 지원을 맡기는 게 좋을 겁니다.\n\n   {wn}필수 혜택{/wn}이 주어집니다. 최대 2종류의 {w}축복{/w}을 고르고, 그 안에서 {wn}카른{/wn} 등급 마법 3종류와 {fpx}퍼르스{/fpx} 등급 마법 1종류를 선택할 수 있습니다." },
    { id: 'average', title: '평균', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/KpTd1DPQ-average.webp', cost: 15, description: "마법소녀들의 절대 다수는 이 정도의 힘을 갖고 있습니다. 여러 종류의 축복에 걸쳐서 꽤 많은 마법을 쓸 수 있기 때문에 싸우게 된다면 꽤 까다롭죠.\n\n   {wn}필수 혜택{/wn}이 주어집니다. 최대 3종류의 {w}축복{/w}을 고르고, 그 안에서 {wn}카른{/wn} 등급 마법 6종류와 {fpx}퍼르스{/fpx} 등급 마법 2종류를 선택할 수 있습니다." },
    { id: 'above_average', title: '평균 이상', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1D3cyCf-aboveaverage.webp', cost: 30, description: "동기들보다 월등히 뛰어난, 재능이 넘치는 마법소녀들입니다.\n\n   {wn}필수 혜택{/wn}이 주어집니다. 최대 4종류의 {w}축복{/w}을 고르고, 그 안에서 {wn}카른{/wn} 등급 마법 6종류와 {fpx}퍼르스{/fpx} 등급 마법 2종류를 선택할 수 있습니다. 한 축복 안에서 4종류 이상의 마법을 배운 경우에 한해서, {rx}주스{/rx} 등급 마법을 1종류 고를 수 있습니다. {w}마리아의 선물{/w}은 선택할 수 없습니다." },
];

// WEAPONS
export const WEAPON_INTRO = {
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cjC2mvr-weapons.webp',
    description: "You will have to decide how, exactly, each carved Blessing is used by your weapon. For projectile spells, it's as simple as launching them from the tip: but for other spells, you may have to get creative!"
};

export const WEAPON_INTRO_KO = {
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cjC2mvr-weapons.webp',
    description: "무기를 활용해서 당신의 마법을 사용하는 정확한 과정은 직접 설정해야 합니다. 투사체를 발사하는 마법이라면 무기 끝부분에서 발사하는 걸로 충분하겠지만, 다른 마법이라면 당신만의 창의적인 뭔가가 필요해요!"
};

export const WEAPON_CATEGORIES: CompanionOption[] = [
    { id: 'blunt_melee', title: 'BLUNT MELEE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SXRSN6tn-bluntmelee.webp', description: "Pretty tough sturdy weapons good for whacking other mages around. They can't use ranged attacks, but can release a different spell effect with every hit in order to massively augment your blows. A good hammer with a good spell can send other mages flying! This category also includes gauntlets." },
    { id: 'bladed_melee', title: 'BLADED MELEE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dfc94JDg-bladedmelee.webp', description: "Blades are good against mundanes, but most fights between mages tend to be PG-rated. While it's possible to give mages a lot of bump and bruises, it's pretty damn hard to lop a limb off or disembowel them or anything gorey like that. Ranged spells can be 'fired' from the end of the blade." },
    { id: 'grenades', title: 'GRENADES', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BVDQpV0C-grenades.webp', description: "See the description for Launchers. These are not quite as powerful, nor can they be fired as far, but they're much more numerous and quick; just keep a grenade belt on you and start lobbing them as fast as you can, filling the entire battlefield with a dozen different spell effects." },
    { id: 'wand', title: 'WAND', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/CK3XjfTh-wand.webp', description: "The default weapon, and the one I'd recommend for any mages confused as to how the other weapons would work with certain spells. Wands act as an extension of your will, and firing off spells with them is as easy as doing so with your own hands. Plus, you can give them cute customizations!" },
    { id: 'staff', title: 'STAFF', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wTCM0yL-staff.webp', description: "A bit more 'serious' than the wand. Staffs are generally more powerful, augmenting the spells emblazoned upon them, yet they're much slower and more unwieldy to use. They're better used for those big, climatic attacks rather than a bunch of small, regular ones." },
    { id: 'bow', title: 'BOW', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/pDYJ1pW-bow.webp', description: "Probably the cutest of the conventional weapons. Similar to the gun, this unleashes spell effects on direct targets, but its piercing power makes them even more devastating, often causing spells to explode out from inside of their target. Requires a ton of skill and training, though!" },
    { id: 'gun', title: 'GUN', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/hFJNPhVK-gun.webp', description: "As a rule of thumb, the faster it fires, the less effect each shot has. Therefore, each bullet fired usually represents a fraction of the power of a full spell, but with enough lead pouring downstream, it quickly adds up. Bullets are 'charged' with spells and release their effects on the targets they hit." },
    { id: 'launcher', title: 'LAUNCHER', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HDn7Cp98-launcher.webp', description: "Similar to grenades, but instead of only affecting targets hit directly, the spell's effect is released on the entire surrounding area. For example, use {w}Sonic Boom{/w} for a conventional explosion, or {w}Pyromaniac{/w} for a fire bomb! Missiles are slower, though, each one needing to be loaded by hand." },
    
];

export const WEAPON_CATEGORIES_KO: CompanionOption[] = [
    { id: 'blunt_melee', title: '근접 둔기', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SXRSN6tn-bluntmelee.webp', description: "다른 마법소녀들을 두들겨 팰 수 있는 튼튼하고 투박한 무기입니다. 원거리전은 할 수 없지만 한 번 타격할 때마다 다양한 마법 효과를 방출하며 당신의 공격을 강화할 수 있습니다. 좋은 마법에 좋은 망치라면 적들을 이리저리 날려 버릴 수 있죠! 여기에는 건틀릿류의 무기도 포함됩니다." },
    { id: 'bladed_melee', title: '근접 도검', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dfc94JDg-bladedmelee.webp', description: "도검류는 일반인들을 상대로는 치명적일 수 있지만, 마법소녀들끼리 칼을 들고 싸운다면 끽해야 12세 이용가 수준입니다. 상처나 멍은 낼 수 있어도 사지를 자른다던가 내장이 흘러나온다던가 그런 잔인한 장면을 만들기는 아주 힘들거든요. 원거리 마법은 칼날 끝에서 '발사'할 수 있습니다." },
    { id: 'grenades', title: '수류탄', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BVDQpV0C-grenades.webp', description: "'발사기' 설명을 참고하세요. 그만큼 강력하거나 사거리가 길지는 않지만, 수량과 속도로 승부합니다. 수류탄 벨트를 매고 있다가 최대한 빨리 던져대면 전장을 순식간에 열몇 가지 마법으로 뒤덮을 수 있죠." },
    { id: 'wand', title: '완드', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/CK3XjfTh-wand.webp', description: "가장 기본적인 무기이자, 다른 무기로 마법을 어떻게 부려야 할지 고민되는 마법소녀에게 추천하는 무기입니다. 완드는 당신의 의지의 연장선처럼 작동합니다. 손으로 마법을 시전하는 것만큼 아주 자연스럽게 마법을 쓸 수 있죠. 귀여운 커마는 덤이구요!" },
    { id: 'staff', title: '스태프', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wTCM0yL-staff.webp', description: "완드보다 좀 '심각한' 무기입니다. 스태프를 사용하면 당신의 마법을 보다 더 강화시킬 수 있지만, 느리고 거추장스럽다는 단점이 있습니다. 작고 평범한 공격 여러 번을 날리는 것보다는 크고 결정적인 기술을 한두 번 날리는 데 적합합니다." },
    { id: 'bow', title: '활', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/pDYJ1pW-bow.webp', description: "일반적인 무기 중에 가장 귀여운 무기일 겁니다. 총과 비슷하게 맞은 대상에서 마법 효과를 발현시키지만, 관통력 때문에 훨씬 더 치명적입니다. 마법이 상대방의 신체 안에서 폭발하는 경우가 많으니까요. 대신 그만큼 기술과 훈련이 많이 필요하답니다!" },
    { id: 'gun', title: '총', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/hFJNPhVK-gun.webp', description: "경험적으로, 투사체가 빠를수록 마법 효과는 미미해집니다. 그래서 총을 쏘면 완전한 마법 효력의 극히 일부분밖에 낼 수 없지만, 충분한 총알을 빠르게 퍼붓는다면 효과는 금방 중첩됩니다. 총알에 마법을 '충전'하면 총알에 맞은 대상에 마법의 효과가 발현됩니다." },
    { id: 'launcher', title: '발사기', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HDn7Cp98-launcher.webp', description: "총과 비슷하지만 발사기는 대상 지역에 광역으로 마법 피해를 줍니다. 가령 소닉붐을 사용하면 우리가 아는 폭발이 일어나고, 방화광을 사용하면 사방에 불길이 번지게 되겠죠! 대신 발사되는 미사일이 느리고, 수동으로 장전해야 합니다." },
];

export const WEAPON_PERKS: CompanionOption[] = [
    { id: 'chatterbox', title: 'CHATTERBOX', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Fb5g2S8G-chatterbox-weapons.webp', cost: 2, description: "Your weapon is able to talk! Can buy {w}Personality Traits{/w} from the list below using {w}Weapons Points{/w}. Not only can it give you useful advice, but it can perform many other tasks. Ever wanted an AR-15 that also played Bach? No? Oh..." },
    { id: 'transforming', title: 'TRANSFORMING', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4whs2qV0-transforming-weapons.webp', cost: 5, description: "Choose another {w}Category{/w}. Your weapon can now transform between it and its default category, although the transition will take two or three seconds. Greatly boosts your versatility. Can be taken multiple times." },
    { id: 'comically_oversized', title: 'COMICALLY OVERSIZED', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Y4mdbWKC-comicallyoversized-weapons.webp', cost: 5, description: "Pretty simply, this just makes your weapon really, absurdly big, and boosts its power proportionally. This stacks with {w}High Power{/w} for devastating effects. Don't worry, you'll be strong enough to wield the thing pretty easily." },
    { id: 'double_trouble', title: 'DOUBLE TROUBLE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5gjh9jWQ-doubletrouble.webp', cost: 10, description: "You've got two arms, right? So why not two guns, or two swords? It may take some extra training to get the hang of dual wielding, but it can effectively double your weapons' effectiveness and versatility.", requirement: "Can't be Bow" },
    { id: 'high_power', title: 'HIGH POWER', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cShYQtfr-highpower.webp', cost: 8, description: "Even without magic applied, your weapon is now strong enough to damage even mages. If a {w}Gun{/w}, it fires High-Explosive Incendiary Armor-Piercing (HEIAP) ammunition; if a {w}Sword{/w}, it uses advanced nanowire alloy blades; and so on.", requirement: "Can't be Wand or Staff" },
    { id: 'recall', title: 'RECALL', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yc5sTMrK-recall.webp', cost: 2, description: "Mages tend to have an extremely firm grip on their weapons, but it's not perfect. If your weapon gets knocked or pulled out of your hand somehow, all you have to do is gesture out to it, and it will do its best to try and fly back into your grip." },
    { id: 'purifying_blade', title: 'PURIFYING BLADE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ZR6bMq8r-purifyingblade.webp', cost: 12, description: "Your weapon has been personally blessed by the Mother and passively stabilizes the universe. This massively boosts the damage it does against Sinthru and Allmillor; such entities seem to fear it. Doesn't help against other mages." },
    { id: 'attuned_spell', title: 'ATTUNED SPELL', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/212GVWJt-attunedspell.webp', cost: 15, description: "Your weapon is custom-built to accommodate some of your spells and push them to the absolute max of their power. Click the book icon to select from your known spells. This can be taken multiple times." },
    { id: 'thermal_supercharge', title: 'THERMAL SUPERCHARGE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/N2VGQjZ6-thermalsupercharge.webp', cost: 0, description: "Can be either made of raw ice if you have {w}Ice Cold{/w}, or raw flames if you have {w}Pyromaniac{/w}. They scale up depending on your tier to be much more damaging than a normal attack would be, and cannot be destroyed as long as you hold them.", requirement: "Requires, and is required if, Thermal Weaponry" },
    { id: 'physically_attached', title: 'PHYSICALLY ATTACHED', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fYgRCYLM-physicallyattached.webp', cost: 0, description: "Your weapon is built around your arm, essentially replacing it while it's equipped. This means that you don't have to worry about being disarmed, even by the most powerful telekinetics. Unless you are {i}literally{/i} disarmed, of course...", requirement: "Requires, and is required if, Heavily Armed" },
];

export const WEAPON_PERKS_KO: CompanionOption[] = [
    { id: 'chatterbox', title: '수다쟁이', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Fb5g2S8G-chatterbox-weapons.webp', cost: 2, description: "당신의 무기가 말을 해요! 무기 점수를 사용해서 동료 항목의 성격을 설정해 줄 수 있습니다. 유용한 충고를 해 줄 수도 있고, 기타 여러 가지 일을 할 수도 있죠. 바흐 음악을 연주하는 AR-15를 갖고 싶어하신 적 없으신가요? 없다구요? 네..." },
    { id: 'transforming', title: '변형', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4whs2qV0-transforming-weapons.webp', cost: 5, description: "추가적인 무기 종류를 하나 고르고, 당신의 무기를 변환시킬 수 있게 됩니다. 변환 시간이 2-3초 정도 걸리지만, 그만한 전술적 유용성이 생깁니다. 이 특성은 여러 번 고를 수 있습니다." },
    { id: 'comically_oversized', title: '특대 사이즈', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Y4mdbWKC-comicallyoversized-weapons.webp', cost: 5, description: "간단하게 말해서 무기의 크기가 말도 안 되게 커지고 힘도 그에 비례해서 강해지는 겁니다. 고출력과 중첩해서 파괴적인 위력을 얻을 수도 있습니다. 걱정 마세요. 아무리 무기가 커도 당신이 사용하는 데는 문제 없으니까." },
    { id: 'double_trouble', title: '쌍수', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5gjh9jWQ-doubletrouble.webp', cost: 10, description: "팔이 두 개인데, 총이나 칼은 왜 두 개면 안 되죠? 한 번에 무기 두 개를 다루려면 추가적인 훈련이 좀 필요하겠지만, 대신 그만큼 효과적이고 유연하게 싸울 수 있으니까요.", requirement: "활은 선택 불가" },
    { id: 'high_power', title: '고출력', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cShYQtfr-highpower.webp', cost: 8, description: "당신의 무기가 마법이 적용되지 않은 상태로도 마법소녀들에게 피해를 줄 수 있을 만큼 강화됩니다. 총이라면 고폭소이철갑탄을 쏘고, 도검이라면 고급 나노와이어 합금 칼날이 달려 있고, 뭐 그런 거죠.", requirement: "완드나 스태프는 선택 불가" },
    { id: 'recall', title: '소환', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yc5sTMrK-recall.webp', cost: 2, description: "마법소녀들은 무기를 놓치는 일이 좀처럼 없지만, 가끔은 실수할 수도 있는 법입니다. 싸움 중에 무기가 날아가 버리거나 힘으로 빼앗겼다면, 손짓 한 번만 하면 무기가 가능한 한 당신의 손으로 돌아올 겁니다." },
    { id: 'purifying_blade', title: '정화의 칼날', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ZR6bMq8r-purifyingblade.webp', cost: 12, description: "어머니께서 당신의 무기를 직접 축성하시고 우주를 안정화시키는 권능을 부여하셨습니다. 당신의 무기가 신스루와 올밀러들에게 입히는 피해가 몇 배로 증폭되며, 그놈들이 이 무기를 두려워하게 됩니다. 다만 다른 마법소녀들과 싸울 때는 도움이 되지 않습니다." },
    { id: 'attuned_spell', title: '마법 조율', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/212GVWJt-attunedspell.webp', cost: 15, description: "당신의 무기는 맞춤 제작되어 당신이 사용하는 마법을 최대한의 위력으로 시전할 수 있게 해 줍니다. 책 아이콘을 클릭해서 마법을 고르세요. 이 특성은 중복해서 선택할 수 있습니다." },
    { id: 'thermal_supercharge', title: '열에너지 과충전', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/N2VGQjZ6-thermalsupercharge.webp', cost: 0, description: "당신이 '한기'를 보유했다면 순수 얼음으로, '방화광'을 보유했다면 불꽃으로 당신의 무기를 만들 수 있습니다. 각각의 마법 등급에 따라 무기의 위력이 강해지며, 평범한 공격보다 몇 배의 파괴력을 내게 됩니다. 또한, 당신이 잡고 있는 한 무기가 파괴되지 않습니다.", requirement: "열 병기 필요, 열 병기 시 필수" },
    { id: 'physically_attached', title: '신체 부착', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fYgRCYLM-physicallyattached.webp', cost: 0, description: "당신의 팔을 중심으로 무기가 제작되어서, 장착되어 있는 동안에는 사실상 당신의 팔을 대신하게 됩니다. 그러니 아무리 강한 염동력 능력자라도 당신의 무장을 해제시킬 수는 없습니다. 팔을 통째로 뜯어 버리기라도 하지 않는다면 말이죠.", requirement: "중무장 필요, 중무장 시 필수" },
];

// BEASTS
export const BEAST_INTRO = {
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LD0Nhf3X-beasts.webp',
    description: "Mages pretty much love pets. This is an almost universal fact. And what better pet than a powerful, mythological creature? You can decide exactly what they look and act like."
};

export const BEAST_INTRO_KO = {
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LD0Nhf3X-beasts.webp',
    description: "마법소녀들은 애완동물을 좋아합니다. 우주적 사실이죠. 그리고 강력한 신화 생물만큼 좋은 애완동물이 어디 있겠습니까? 당신의 애완동물의 모습과 행동거지를 설정할 수 있습니다."
};

export const BEAST_CATEGORIES: CompanionOption[] = [
    { id: 'humanoid', title: 'HUMANOID', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/354FrQRd-humanoid.webp', description: "Broadly applies to anything bipedal or at least vaguely hominid-esque in stature. You can make creatures that look very human, but never exactly so. It will always be immediately obvious to everyone who sees them, in some way or another, that your beast is not truly part of mankind." },
    { id: 'pawed', title: 'PAWED', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8nVM7whK-pawed.webp', description: "This covers pretty much all mammals that have paws, like cats, dogs, otters, and what have you. Compared to ungulates, they tend to be pretty thickset and sturdy and have shorter fur. Great for hugs! These are the most popular type of beast, as they make for excellent pets and companions." },
    { id: 'ungulate', title: 'UNGULATE', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/vxRZgc77-ungulate.webp', description: "This covers all the mammals that have hooves, from horses, to elephants, to rhinoceroses, and all that. Compared to pawed mammals, they tend to be pretty thickset and sturdy and have shorter fur. Great as work animals! They are most popular as mounts. Mages particularly love unicorns." },
    { id: 'avian', title: 'AVIAN', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/F4SRndPr-avian.webp', description: "Pretty popular as they're associated with flying. Of course, not all avians are actually capable of flight. Just ask the humble penguin. Signified by their feathers and pokey beaks. They're fairly popular as pets and familiars, but not as much as mammals are." },
    { id: 'reptilian', title: 'REPTILIAN', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8nVd4J22-reptilian.webp', description: "Not too popular among most, since their scaley bodies and angular features tend to make them unappealing as pets. But some find them absolutely adorable in their own way, and some mages covet them for their association with strength and power." },
    { id: 'aquatic', title: 'AQUATIC', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/B5dwQkqG-aquatic.webp', description: "These sorts of pets aren't very popular in most places, but their immense popularity in the Unterseeisch tends to make up for that. They can survive on land just fine, too. In fact, this category also covers amphibians." },
    { id: 'insectoid', title: 'INSECTOID', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fGTNHfvK-insectoid.webp', description: "Probably the least popular pets and familiars, especially if we're talking anything besides butterflies and the occasional moth. They just creep most people out! But they're good for mages who like scaring and intimidating others, and again, some find them weirdly cute." },
    { id: 'abstract', title: 'ABSTRACT', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mCwvxzJY-abstract.webp', description: "This encompasses perhaps the broadest range of creatures, since they are no longer required to even look remotely like a real animal. They can be formed in ways that defy all biological sense, and are utterly unique to the mage who owns them." },
];

export const BEAST_CATEGORIES_KO: CompanionOption[] = [
    { id: 'humanoid', title: '인간형', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/354FrQRd-humanoid.webp', description: "이족보행을 하거나 적어도 대충은 인간과 비슷한 형체를 하고 있는 것들입니다. 사람을 닮게 만들 수는 있지만, 사람과 똑같이 만들 수는 없습니다. 누가 봐도 당신의 동물이 진짜 사람이 아니라는 걸 곧바로 알 수 있을 겁니다. 적어도 어디 한 군데는 티가 나거든요." },
    { id: 'pawed', title: '포유류', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8nVM7whK-pawed.webp', description: "당신도 잘 알 겁니다. 정확히는 고양이, 강아지, 수달, 기타 등등, 발톱과 육구가 달린 발이 있는 포유류 종류입니다. 우제류와 비교하면 날씬하고 털이 북실북실하죠. 껴안기 참 좋구요! 동반자나 애완동물로는 더할 나위 없기 때문에 가장 인기 많은 동물 종류입니다." },
    { id: 'ungulate', title: '우제류', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/vxRZgc77-ungulate.webp', description: "발굽 달린 포유류들입니다. 말, 코끼리, 코뿔소 등등이 있죠. 대체로 몸집이 크고, 힘이 좋고, 털이 짧습니다. 일도 잘 하구요, 타고 다니는 동물로도 인기가 참 많습니다. 마법소녀들은 특별히 유니콘을 좋아하죠." },
    { id: 'avian', title: '조류', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/F4SRndPr-avian.webp', description: "비행과 관련돼서 참 인기가 많습니다. 물론 모두 다 날 수 있는 건 아니에요. 펭귄만 봐도 그렇죠. 깃털과 뾰족한 부리가 특징입니다. 애완동물이나 패밀리어로도 인기가 많지만 포유류들만큼은 아니에요. 아무래도 우리가 우리와 같은 종을 좋아하니까요." },
    { id: 'reptilian', title: '파충류', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8nVd4J22-reptilian.webp', description: "각진 신체와 몸을 덮는 비늘 때문에 애완동물로 그렇게 인가가 많지는 않습니다. '귀여운 맛'이 없거든요! 하지만 파충류들에 애정을 갖고 키우는 사람들도 꽤 있고, 몇몇 마법소녀들은 힘을 상징하는 이 동물들을 아낀답니다." },
    { id: 'aquatic', title: '수생 생물', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/B5dwQkqG-aquatic.webp', description: "거의 인기가 없는 편이긴 하지만, 운터시쉬에서의 초월적인 인기 때문에 다 만회가 됩니다. 거기서는 모든 애완동물이 물고기 종류니까요! 걱정하지 마세요, 물 밖에서도 살아갈 수 있으니까요. 여기에는 양서류들도 포함되니까." },
    { id: 'insectoid', title: '곤충', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fGTNHfvK-insectoid.webp', description: "나비나 아주 가끔 나오는 나방 종류를 제외하면 가장 인기없는 종일 겁니다. 그냥 보면 무섭잖아요! 하지만 남들 놀래키고 위협하기 좋아하는 마법소녀들에게는 딱이고, 이상하게 이런 동물들이 귀엽다는 사람들도 있습니다." },
    { id: 'abstract', title: '추상적', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mCwvxzJY-abstract.webp', description: "이 분류에 웬만한 생물체들이 다 들어갈 겁니다. 진짜 동물하고 하나도 안 닮아도 되거든요. 생물학적으로 말이 되든 안 되든 상관없고, 주인 마법소녀의 취향에 따라 모든 것이 결정됩니다. 그리고 앞의 7가지 종류에 안 들어가는 모든 것들이 이곳에 포함됩니다." },
];

export const BEAST_SIZES: CompanionOption[] = [
    { id: 'tiny', title: 'TINY', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fVBrj8sk-tiny.webp', description: "Commonly associated with fairy-esque beasts. They're known for often possessing great magical prowess, but are physically frail and can hardly muster enough strength to lift a milk jug. At most, they're around the size of a housecat." },
    { id: 'small', title: 'SMALL', cost: 10, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yF8GqTKT-small.webp', description: "Big enough to wrap your arms around and give a big hug! At this size, they can be very effective physically against mundane targets, although they will still struggle when fighting against mages. At most, they're around the size of a large wolf." },
    { id: 'medium', title: 'MEDIUM', cost: 25, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/9mP6CbR7-medium.webp', description: "Now we're getting somewhere! At this point, they are about the size of an adult human or bigger. With the right perks, they can be a threat even to mages, or at least a distraction. At most, they're around the size of a large horse." },
    { id: 'large', title: 'LARGE', cost: 35, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ymdGcYzH-large.webp', description: "By this point, their durability and physical damage output is increasing exponentially alongside their size. Hell, with their weight, they might be able to just squish a mage! At most, they're much larger than an elephant." },
    { id: 'humongous', title: 'HUMONGOUS', cost: 50, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/k2VmBB2p-humongous.webp', description: "This is truly a legendary beast, towering over their foes and capable of dominating an entire battlefield! Mundane warriors cringe in horror, and even other mages will be intimidated. At most, they're around the size of a multi story building." },
];

export const BEAST_SIZES_KO: CompanionOption[] = [
    { id: 'tiny', title: '초소형', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fVBrj8sk-tiny.webp', description: "요정 같은 생물들이 이 범주에 들어갑니다. 마법적 능력은 높은 것으로 알려져 있지만, 신체 능력은 우유 주전자 하나도 들지 못할 만큼 약합니다. 몸집은 가장 커 봐야 집고양이 정도입니다." },
    { id: 'small', title: '소형', cost: 10, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yF8GqTKT-small.webp', description: "당신이 팔을 둘러 껴안을 수 있을 정도의 크기입니다! 이 정도 크기라면 일반인들은 쉽게 제압할 수 있겠지만 다른 마법소녀들과 싸우기는 어려울 겁니다. 최대 체급은 큰 늑대 정도입니다." },
    { id: 'medium', title: '중형', cost: 25, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/9mP6CbR7-medium.webp', description: "이제 좀 뭐가 되는 것 같은데요! 성인과 비슷하거나 더 큰 동물입니다. 알맞은 특성이 있다면 마법소녀들에게도 위협을 가하거나 최소한 주의를 끌 수 있을 정도는 됩니다. 최대 체급은 큰 말 정도입니다." },
    { id: 'large', title: '대형', cost: 35, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ymdGcYzH-large.webp', description: "이쯤 되면 크기에 비례해 그 강력함과 맷집이 기하급수적으로 증가합니다. 몸무게만으로도 마법소녀를 깔아뭉갤 수도 있으니까요! 최대 체급은 코끼리를 훨씬 뛰어넘습니다." },
    { id: 'humongous', title: '초대형', cost: 50, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/k2VmBB2p-humongous.webp', description: "거대한 몸집으로 적들을 압도하며 전장 전체를 지배할 수 있는 전설적인 야수들입니다. 싸움에 나선 일반인들은 그 모습만 봐도 공포에 질릴 것이고, 마법소녀들도 제대로 긴장하겠죠. 최대 체급은 몇 층 높이의 건물 정도입니다." },
];

export const BEAST_PERKS: CompanionOption[] = [
    { id: 'chatterbox_beast', title: 'CHATTERBOX *', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PGXNyRS9-chatterbox-beast.webp', description: "Your beast has human-like sapience and can speak. You can purchase {w}Personality Traits{/w} for it from the list below using {w}Beast Points{/w}." },
    { id: 'noble_steed', title: 'NOBLE STEED', cost: 3, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/v42dHjbj-noblespeed.webp', description: "It's always possible to ride most beasts in a pinch, but this Upgrade makes them faster and naturally suited to accepting riders comfortably for very long durations, making for perfect mounts. Naturally, they must be at least {w}Medium{/w} size or larger.", requirement: "Requires Medium size or larger" },
    { id: 'free_flying', title: 'FREE FLYING', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/h1BKtHrt-freeflying-X.webp', description: "Your beast will be given a pair of wings big enough to propel them through the air! {w}Tiny{/w} beasts can reach 300 MPH; {w}Medium{/w} beasts can reach 200 MPH; and {w}Humongous{/w} beasts can reach 100 MPH. Acceleration also decreases with size." },
    { id: 'hybrid', title: 'HYBRID', cost: 4, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BKckgz69-hybrid.webp', description: "The categories above a bit too limiting for you? Choose a second Category. You can mix and match traits between the two categories however you see fit. Some truly bizarre creatures have been created this way! Can be taken multiple times." },
    { id: 'elemental_breath', title: 'ELEMENTAL BREATH', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SDwpS8hh-elementalbreath.webp', description: "The beast can now expel some sort of damaging substance from its mouth. Good ol fire? An ancient of water? Acid? Poison? Something else? The choice is all yours! The amount produced obviously varies depending on the beast's size." },
    { id: 'natural_weaponry', title: 'NATURAL WEAPONRY', cost: 2, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7tqGBFQg-naturalweaponry.webp', description: "This varies massively depending on the sort of beast we're dealing with. Maybe they're a wolf with preternaturally sharp claws? Or a serpent with powerfully constricting coils? Whatever the case, they can do slight damage to mages." },
    { id: 'weakening_poison', title: 'WEAKENING POISON', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wrSRNnQF-weakeningpoison.webp', description: "Your beast is venomous or can spit a poison that relaxes the muscles of even a mage, sapping them slowly of their energy. Given enough toxin, they can eventually be paralyzed completely! Quite coveted by alchemists." },
    { id: 'unnerving_appearance', title: 'UNNERVING APPEARANCE', cost: 3, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/d0XNjQSV-unnervingappearance.webp', description: "Your beast has a truly disturbing, eldritch appearance, to the point you horrify or shake the sanity of weak-willed or sensitive. It's not too bad once you get used to it, though. Kinda cute, in a way.", requirement: "Free if Undead" },
    { id: 'steel_skin', title: 'STEEL SKIN', cost: 6, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DHCpgSn2-steelskin.webp', description: "Your beast's skin is somehow hardened and quite difficult for even mages to do much damage to. Maybe they're covered in scales as solid as metal, or a complex chitinous or fibrous armor, or maybe their flesh is merely preternaturally durable.", requirement: "Free if Automaton" },
    { id: 'slime', title: 'SLIME', cost: 4, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8n84Q7b7-slime.webp', description: "Your beast is partially made out of a slime which is, by default, quite bouncing, sloshy and solid, like a water balloon mixed with a pillow. In combat, though, they can become sticky, slowing or even slowly acidically dissolving foes." },
    { id: 'elemental', title: 'ELEMENTAL', cost: 6, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/XZmd2wdB-elemental.webp', description: "The beast will appear to be covered in or made out of fire, water, ice, lightning, a poisonous slime, or any other similar material. This will not boost their durability, but can harm enemies who draw too near or attack physically." },
    { id: 'chlorophyll', title: 'CHLOROPHYLL', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/23p4470f-chlorophyll.webp', description: "The beast will appear to be made out of either plant like or fungal material, and will be massively rejuvenated by direct sunlight, energizing and healing it. It's not more vulnerable to fire {i}per se{/i}, but burns do disable this healing in a localized areas." },
    { id: 'magical_beast', title: 'MAGICAL BEAST *', cost: 15, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BkDcLwv-magicalbeast.webp', description: "Can be purchased multiple times. Beast can use one spell from pg 3-5 which: 1. Cannot be from Blessings of {i}Tidings, Dissatisfaction, Defeat, Creation{/i}. 2. Cannot have any requirements and must be {wn}Kaarn{/wn}-level spells." },
    { id: 'automaton_perk', title: 'AUTOMATON', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MyZjpyZV-automation-beast.webp', description: "Your beast is not a genuine biological creature, but an artificial facsimile! They tend to be quite intelligent and have extremely tough metallic alloys instead of skin. If destroyed, they can self destruct into a massive explosion.", requirement: "Requires, and is required if, Robotocist or Nanite Form" },
    { id: 'undead_perk', title: 'UNDEAD', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/dJPmf4zF-undead-beast.webp', description: "They don't smell nice, and they're not exactly pretty, either. On the other hand, they have no biological needs, are extremely resilient to pain or damage, and will slowly pull themselves back together if torn to pieces.", requirement: "Requires, and is required if, Undead Beast" },
];

export const BEAST_PERKS_KO: CompanionOption[] = [
    { id: 'chatterbox_beast', title: '수다쟁이 *', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PGXNyRS9-chatterbox-beast.webp', description: "마법소녀의 동물들은 일반 동물들보다 월등히 지능이 높지만, 이 경우에는 그것조차 넘어서 인간에 필적하는 지능에 말을 할 수 있는 능력까지 갖췄습니다! 남은 동물 점수를 사용해서 동물의 성격을 설정해 줄 수 있습니다." },
    { id: 'noble_steed', title: '고귀한 기마', cost: 3, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/v42dHjbj-noblespeed.webp', description: "급한 상황이 닥치면 웬만한 동물들을 다 탈 수 있습니다. 하지만 이 특성이 있으면 그 속도가 빨라질 뿐만 아니라, 동물들이 오랜 기간 동안 주인을 편하게 태우고 다니는 것에 익숙해질 것입니다. 평소에도 타고 다니기 안성맞춤이죠. 당연히 크기가 중형 이상이어야만 합니다.", requirement: "중형 크기 이상 필요" },
    { id: 'free_flying', title: '자유로운 비행', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/h1BKtHrt-freeflying-X.webp', description: "하늘을 날 수 있는 날개가 주어집니다! 초소형이라면 최대 480km/h, 중형이라면 320km/h, 초대형이라면 160km/h의 속도로 날 수 있습니다. 가속력 역시 크기에 비례해 줄어듭니다." },
    { id: 'hybrid', title: '하이브리드', cost: 4, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BKckgz69-hybrid.webp', description: "동물종의 다양성이 너무 적은가요? 종류를 하나 더 선택하세요. 이제 선택한 모든 종의 특성을 자유롭게 섞을 수 있습니다. 이 방식으로 만들어진 동물들 중에는 정말 희한한 친구들이 많습니다! 이 특성은 중복해서 고를 수 있습니다." },
    { id: 'elemental_breath', title: '원소의 숨결', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SDwpS8hh-elementalbreath.webp', description: "당신의 동물은 입에서 무언가를 뱉어내 피해를 줄 수 있게 됩니다. 고전적인 불일까요? 강한 물줄기? 산? 독? 아니면 다른 무언가? 선택은 당신의 몫입니다! 물론 그 양은 동물의 체급에 따라 달라집니다." },
    { id: 'natural_weaponry', title: '자연의 무기', cost: 2, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7tqGBFQg-naturalweaponry.webp', description: "어떤 동물이냐에 따라 얘기가 달라집니다. 늑대의 말도 안 되게 날카로운 발톱일까요? 아니면 뱀의 엄청난 똬리 힘일까요? 다만 뭐가 됐든 마법소녀들에게 치명상을 줄 수는 없습니다." },
    { id: 'weakening_poison', title: '약화의 독소', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wrSRNnQF-weakeningpoison.webp', description: "당신의 동물은 근육을 이완시키고 천천히 힘을 빼앗는 독을 품고 있거나, 내뿜을 수 있습니다. 마법소녀도 예외는 아닙니다. 독의 양이 충분하다면 대상을 완전히 마비시키는 것도 가능합니다! 연금술사들이 이 독을 얻지 못해 안달이 나 있죠." },
    { id: 'unnerving_appearance', title: '형언할 수 없는 형상', cost: 3, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/d0XNjQSV-unnervingappearance.webp', description: "당신의 동물은 아주 섬뜩한, 마치 이 세상 동물이 아닌 것 같은 모습을 하고 있습니다. 예민하거나 허를 찔린 적들은 공포에 질리거나 이성이 마비될 겁니다. 뭐, 익숙해지면 그러려니 할 만 합니다. 어떻게 보면 귀엽기도 하구요.", requirement: "언데드인 경우 무료" },
    { id: 'steel_skin', title: '강철 피부', cost: 6, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DHCpgSn2-steelskin.webp', description: "당신의 동물은 그 피부가 경화되어, 마법소녀들조차도 유의미한 피해를 주기가 어렵습니다. 금속만큼 단단한 비늘을 갖고 있거나, 단단한 외골격 갑피가 있거나, 아니면 그냥 살갗이 매우 튼튼할 수도 있죠.", requirement: "오토마톤인 경우 무료" },
    { id: 'slime', title: '슬라임', cost: 4, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8n84Q7b7-slime.webp', description: "당신의 동물은 신체 일부분이 슬라임으로 구성되어 있습니다. 기본적으로 물풍선과 베개를 섞어 놓은 듯한 탄성과 찰팍임, 그리고 어느 정도의 형태를 갖고 있죠. 대신 전투에 들어가면 끈끈해지거나, 상대를 느리게 하거나, 심지어는 산으로 서서히 녹여 버릴 수도 있습니다." },
    { id: 'elemental', title: '정령', cost: 6, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/XZmd2wdB-elemental.webp', description: "불이나 물, 얼음, 번개, 맹독 슬라임, 기타 물질에 덮여 있는 동물입니다. 딱히 몸이 튼튼해지는 것은 아니지만, 너무 가까이 접근하거나 물리적으로 공격하려는 적들에게 피해를 줄 수는 있죠." },
    { id: 'chlorophyll', title: '엽록소', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/23p4470f-chlorophyll.webp', description: "당신의 동물은 식물이나 균류로 만들어진 것처럼 보입니다. 햇빛에 노출되면 빠르게 힘을 되찾고 상처를 회복할 수 있습니다. 그 자체로 화염에 취약해지지는 않지만, 화상을 입으면 그 부위는 햇빛을 통한 재생력을 잃어버립니다." },
    { id: 'magical_beast', title: '마수 *', cost: 15, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BkDcLwv-magicalbeast.webp', description: "이 특성은 여러 번 고를 수 있습니다. 당신의 동물이 마법 한 가지를 사용할 수 있습니다. 단: 1) 길조 / 불만족 / 패배 / 창조의 축복에 해당하는 마법을 고를 수는 없습니다. 2) 필요 조건이 없어야 하고, 카른 등급의 마법만 고를 수 있습니다." },
    { id: 'automaton_perk', title: '오토마톤', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MyZjpyZV-automation-beast.webp', description: "당신의 동물은 생명체가 아니라 인공적으로 흉내낸 기계입니다! 지능은 꽤 높은 편이고, 피부는 초고강도의 금속 합금으로 대체되어 있습니다. 파괴될 때는 자폭하여 광범위한 폭발을 일으킬 수도 있구요.", requirement: "로봇술사 또는 나나이트 형체 필요" },
    { id: 'undead_perk', title: '언데드', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/dJPmf4zF-undead-beast.webp', description: "냄새가 좋지도 않고, 예쁘지도 않습니다. 대신, 생물학적인 욕구도 없고, 고통이나 피해 저항력이 높습니다. 그리고 몸이 찢겨 나가더라도 천천히 몸을 짜맞추고 다시 일어날 겁니다.", requirement: "언데드 야수 필요" },
];

// VEHICLES
export const VEHICLE_INTRO = {
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xSpV8KXJ-vehicles.webp',
    description: "Mages can already fly around quickly, but vehicles tend to be much easier and have much faster acceleration, so they're good for leisure and combat situations. They look cool, too."
};

export const VEHICLE_INTRO_KO = {
    imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xSpV8KXJ-vehicles.webp',
    description: "마법소녀들은 빠르게 비행할 수 있는 능력이 있지만, 그래도 탈것이 훨씬 더 편하고 가속도도 좋습니다. 여유를 즐길 때나 싸울 때에는 쓸만하죠. 멋도 있구요."
};

export const VEHICLE_CATEGORIES: CompanionOption[] = [
    { id: 'motorcycle', title: 'MOTORCYCLE', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5WsP0Fsg-motorcycle.webp', description: "A really fun, simple vehicle. Just try not to crash! Mages tend to get launched like a catapult, going flying through brick walls and everything! By default, its fastest possible speed is 200 mph." },
    { id: 'car', title: 'CAR', cost: 10, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Cp94zpff-car.webp', description: "Ever longed to find yourself behind the wheel of a large automobile? Your car will have all the best and latest upgrades, and can be of any model. By default, its fastest possible speed is 300 mph." },
    { id: 'submarine', title: 'SUBMARINE', cost: 10, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/YFVFdSrZ-submarine.webp', description: "There's a lot to be found under the sea, from entire thriving cities to ancient ruins full of wonders. Hell, there's a whole Dominion down there! By default, its fastest possible speed is 300 mph." },
    { id: 'boat', title: 'BOAT', cost: 10, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Z62yjPnT-boat.webp', description: "Lorem ipsum. By default, its fastest possible speed is 300 mph." },
    { id: 'tank', title: 'TANK', cost: 20, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/n4q6Ghn-tank.webp', description: "While quite slow, and not as offensively powerful as mechas, it is more sturdy and well-armored, making it optimal for defensive positions. By default, its fastest possible speed is 100 mph." },
    { id: 'plane', title: 'PLANE', cost: 30, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jPb9YcyK-plane.webp', description: "Good for travelling across vast distances quite quickly, but it lacks the precise movement of helicopters or the destructive power of mechas. By default, its fastest possible speed is 500 mph." },
    { id: 'helicopter', title: 'HELICOPTER', cost: 30, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/C3ZqFNZ1-helicopter.webp', description: "Can be kind of hard to drive, but allows easy movement in all directions to rain death on your enemies from above. By default, its fastest possible speed is 300 mph." },
    { id: 'mecha', title: 'MECHA', cost: 40, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/W4qQWW22-mecha.webp', description: "These terrifyingly massive humanoid robots are considered some of the most fearsome weapons on earth, able to compete with mages! By default, its fastest possible speed is 400 mph." },
];

export const VEHICLE_CATEGORIES_KO: CompanionOption[] = [
    { id: 'motorcycle', title: '오토바이', cost: 0, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5WsP0Fsg-motorcycle.webp', description: "단순하고 재미있습니다. 사고만 안 나게 조심하세요! 마법소녀들은 무슨 대포알마냥 급발진하면서 벽에 들이받고 난리가 나는 경우가 많으니까요. 기본적으로 최고 속력은 320km/h입니다." },
    { id: 'car', title: '자동차', cost: 10, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Cp94zpff-car.webp', description: "크고 멋진 승용차를 운전하는 게 꿈이셨나요? 당신의 차는 최신 기종에 최고의 업그레이드를 다 받은 상태이고, 모델도 마음대로 정할 수 있습니다. 기본적으로 최고 속력은 480km/h입니다." },
    { id: 'submarine', title: '잠수함', cost: 10, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/YFVFdSrZ-submarine.webp', description: "바닷속을 탐험하면 번성하는 해저 도시부터 수수께끼 가득한 고대 유적까지 참 볼 것이 많습니다. 아니, 애초에 국가 하나가 바닷속에 있잖아요! 기본적으로 최고 속력은 480km/h입니다." },
    { id: 'boat', title: '보트', cost: 10, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Z62yjPnT-boat.webp', description: "로렘 입숨.\n\n기본적으로 최고 속력은 480km/h입니다." },
    { id: 'tank', title: '탱크', cost: 20, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/n4q6Ghn-tank.webp', description: "느리기도 하고, 메카처럼 화력이 충만하지도 않지만, 그래도 견고한 데다 중장갑이라 수비에는 뛰어납니다. 기본적으로 최고 속력은 160km/h입니다." },
    { id: 'plane', title: '항공기', cost: 30, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jPb9YcyK-plane.webp', description: "먼 거리를 빠르게 이동하는 데에는 안성맞춤이지만, 헬리콥터의 정밀한 기동이나 메카의 파괴력은 없습니다. 기본적으로 최고 속력은 800km/h입니다." },
    { id: 'helicopter', title: '헬리콥터', cost: 30, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/C3ZqFNZ1-helicopter.webp', description: "조종이 좀 힘들지만, 모든 방향으로 자유자재로 움직이며 상공에서 적들에게 죽음의 포화를 퍼부을 수 있습니다. 기본적으로 최고 속력은 480km/h입니다." },
    { id: 'mecha', title: '메카', cost: 40, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/W4qQWW22-mecha.webp', description: "이 무시무시하고 거대한 인간형 로봇들은 이 세계에서 가장 공포스러운 병기들입니다. 때로는 이 메카들만으로도 마법소녀들을 상대할 수 있으니까요! 기본적으로 최고 속력은 640km/h입니다." },
];

export const VEHICLE_PERKS: CompanionOption[] = [
    { id: 'chatterbox_vehicle', title: 'CHATTERBOX', cost: 3, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/q3F89rjz-chatterbox-vehicle.webp', description: "Be it magically given a soul, or a typical AI, your vehicle has a mind of its own! It can drive itself, perform all sorts of tasks and commands, and even talk to you. Can buy {w}Personality Traits{/w} from the list below using {w}Vehicle Points{/w}.", requirement: "Free for Car" },
    { id: 'comically_oversized_vehicle', title: 'COMICALLY OVERSIZED', cost: 10, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DHz2NFqt-comicallyoversized-vehicle.webp', description: "Bigger really is better! Make that car big enough to live in comfortably, or turn that boat into a yacht or a pirate ship, or that mecha into a proper 10-story tall gundam! These larger vehicles are more durable and powerful than the defaults." },
    { id: 'transforming_vehicle', title: 'TRANSFORMING', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xKJjzv3v-transforming-vehicle.webp', description: "Choose a second {w}category{/w}; now your vehicle can transform between the two at the push of a button! Can be purchased multiple times. You don't have to purchase the other category, but it can't be more expensive than the default." },
    { id: 'hellfire_volley', title: 'HELLFIRE VOLLEY', cost: 8, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Ts61JcN-hellfirevolley.webp', description: "Fires volleys of small but quick heat-seeking missiles that devastate other vehicles and even do moderate damage to any mages who are caught directly in the cluster explosion. Pretty effective, but it's possible for the missiles to be outran.", requirement: "Free for Tank or Mecha" },
    { id: 'speed_boost', title: 'SPEED BOOST', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/v4T8r3kX-speedboost.webp', description: "There's plenty of ways to make things go faster, from complex magical enchantments, to simply strapping rockets to it. In any case, this increases the vehicle's maximum speed by 100 MPH. This can be purchased up to 3 times." },
    { id: 'force_field', title: 'FORCE FIELD', cost: 7, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BHMYw0dk-forcefield.webp', description: "For when armor won't cut it, it's best to avoid taking any hits in the first place. This gear consumes a lot of energy soaking up damage on the vehicle's behalf, but if subjected to too powerful an assault, it will need to shut down to recharge." },
    { id: 'nanowire_armor', title: 'NANOWIRE ARMOR', cost: 7, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/bnYkqZJ-nanowirearmor.webp', description: "Composed of germanium wires each billionths of a meter in diameter and reinforced with directed energy reactive armour, allowing the vehicle to tank immense amounts of damage without so much as a chip on the paint." },
    { id: '"houdini"_system', title: '"HOUDINI" SYSTEM', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SDhsTB06-houdinisystem.webp', description: "An advanced cloaking system that hides your vehicle almost completely from the visible spectrum, leaving only a faint blur, although it can still be detected via other means like infrared. It makes no sounds while cloaked, but can't fire its weapons." },
    { id: 'the_trident', title: 'THE TRIDENT', cost: 9, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1G5Qpx3j-thetrident.webp', description: "An ordinary gun does little to a mage... but this no ordinary gun. It's actually an automatic railgun firing shells at mach 7, over thrice as fast as regular bullets! Legend says it costs 400,000$ to fire this baby for only 12 seconds." },
    { id: 'armageddon_cannon', title: 'ARMAGEDDON CANNON', cost: 15, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xKjhj6Gg-armageddoncannon.webp', description: "Fires a magitech missile that bursts in midair, creating a point of immense density that draws in objects with its powerful gravity well, before triggering an antimatter explosion powerful enough to seriously wound even a mage!", requirement: "Requires Tank or Mecha" },
];

export const VEHICLE_PERKS_KO: CompanionOption[] = [
    { id: 'chatterbox_vehicle', title: '수다쟁이', cost: 3, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/q3F89rjz-chatterbox-vehicle.webp', description: "마법으로 영혼을 부여받았든, 그냥 흔한 인공지능이든 간에, 어쨌든 당신의 탈것에 의식이 생겼습니다! 자율 주행은 기본에, 이것저것 시키는 것도 할 수 있고, 말도 합니다. 남은 탈것 점수를 사용해서 성격을 설정해 줄 수 있습니다.", requirement: "자동차인 경우 무료" },
    { id: 'comically_oversized_vehicle', title: '초거대 탈것', cost: 10, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DHz2NFqt-comicallyoversized-vehicle.webp', description: "크고 아름다운 건 항상 옳지요! 자동차가 집처럼 편히 살 수 있을 만큼 크다던가, 보트가 크루즈나 해적선이 된다던가, 메카를 10층 건물 높이의 완전체 건담으로 만들 수 있습니다. 이 거대한 탈것들은 원래보다 더 튼튼하고 강합니다." },
    { id: 'transforming_vehicle', title: '변형', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xKJjzv3v-transforming-vehicle.webp', description: "두 번째 탈것 종류를 선택하세요. 이제 버튼 하나만 누르면 탈것이 자유롭게 변형됩니다. 이 특성은 여러 번 선택할 수 있습니다. 단, 추가적으로 선택하는 탈것 종류는 원래보다 비용이 클 수 없습니다." },
    { id: 'hellfire_volley', title: '지옥불 포화', cost: 8, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Ts61JcN-hellfirevolley.webp', description: "작지만 빠른 열추적 미사일을 퍼부어, 다른 탈것들을 박살내고 휘말린 마법소녀들에게도 어느 정도의 피해를 줄 수 있습니다. 효과는 의심의 여지가 없습니다만, 빠른 속도로 미사일을 따돌릴 수는 있습니다.", requirement: "탱크나 메카는 무료" },
    { id: 'speed_boost', title: '속도 증가', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/v4T8r3kX-speedboost.webp', description: "복잡한 마법 주문이든, 단순히 로켓을 매달아 놓든, 뭔가를 더 빨리 가게 하는 방법은 많습니다. 이 경우에는 탈것의 최대 속도가 160km/h 만큼 상승합니다. 최대 3번 선택할 수 있습니다." },
    { id: 'force_field', title: '역장', cost: 7, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BHMYw0dk-forcefield.webp', description: "장갑이 먹히지 않을 수도 있는 만큼, 아예 공격을 안 맞는 것이 최선입니다. 이 장비는 대량의 에너지를 소모해 차량에 가해지는 공격을 흡수할 수 있습니다. 하지만 너무나 강력한 화력에 노출되면 재충전을 위해 잠시 작동이 정지됩니다." },
    { id: 'nanowire_armor', title: '나노와이어 장갑', cost: 7, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/bnYkqZJ-nanowirearmor.webp', description: "나노미터 두께의 게르마늄 와이어를 에너지 반응성 장갑으로 강화했습니다. 당신의 탈것은 페인트에 흠집 하나 안 난 채로 무지막지한 화력을 받아 낼 수 있습니다." },
    { id: '"houdini"_system', title: '"후디니" 시스템', cost: 5, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SDhsTB06-houdinisystem.webp', description: "이 고급 은폐 시스템을 이용하면 당신의 탈것이 가시광선 대역에서 사실상 투명화되어, 흐릿한 일렁임 정도만 남기게 됩니다. 다만 적외선이나 기타 다른 수단으로는 탐지할 수 있습니다. 은폐 시에는 소리도 나지 않지만, 모든 무기를 사용할 수 없게 됩니다." },
    { id: 'the_trident', title: '트라이던트', cost: 9, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1G5Qpx3j-thetrident.webp', description: "일반 총이라면 마법소녀에게 거의 효과가 없지만, 이건 그런 시시한 총이 아닙니다. 마하 7의 속도로 탄환을 발사하는 자동 레일건이니까요! 12초 발사하는 데 40만 달러가 든다는 전설이 있죠..." },
    { id: 'armageddon_cannon', title: '아마겟돈 포', cost: 15, imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xKjhj6Gg-armageddoncannon.webp', description: "이 포에서 발사되는 마법공학 미사일은 공중에서 폭발하며 주변 모든 것들을 끌어들이는 강력한 중력장을 형성합니다. 그리고 잠시 후, 마법소녀라도 휘말리면 중상을 입을 수 있는 엄청난 반물질 폭발이 일어납니다!", requirement: "탱크나 메카만 선택 가능" },
];
