
import type { BitterDissatisfactionSigil, BitterDissatisfactionPower } from '../../types';

export const BITTER_DISSATISFACTION_DATA = {
    title: "THE BLESSING OF BITTER DISSATISFACTION",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fdXhrk7T-main1.webp",
    description: `How can dissatisfaction be a blessing, you may ask? Well, think about it. All human progress has been driven by people who were dissatisfied with the way things were. Even the illustrious Garden of Eden, hidden away above our façade of a sky, was created as a gift by a father for his daughter, for he was dissatisfied with the harsh realities of the universe from which he came. Poor Priscillia was filled with dissatisfaction, never taken seriously even by her own family — a feeling she harnessed when she, within minutes, weaved an entire army of puppet warriors to fend off a Sinthru attack on early Halidew Station, in an act that stunned the magical world and cemented this Blessing as essential.
    
Contrary to popular belief, this is the blessing of change, not creation. You cannot create things via alchemy, only change their form, sacrificing something to obtain something else of relatively equal value.`
};

export const BITTER_DISSATISFACTION_DATA_KO = {
    title: "씁쓸한 불만족의 축복",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fdXhrk7T-main1.webp",
    description: `불만족이 어떻게 축복이냐구요? 음, 이렇게 생각해 보세요. 인류의 모든 발전은 현재 상황에 만족하지 못한 이들의 손에 이루어졌습니다. 그 에덴의 정원조차 가혹한 예전 우주의 현실에 만족하지 못했던 아버지가 딸을 위한 선물로 만들어, 우리 세계의 하늘 위에 숨겨 놓은 것이니까요. 프리실라는 불행하게도 가족들의 진심어린 애정을 단 한 번도 받지 못한 채 불만이 가득 쌓여 있었습니다. 할리듀 스테이션이 초창기에 신스루의 공격을 받았을 때, 그녀는 그 감정을 끌어내어 수많은 꼭두각시 전사들을 조종하며 몇 분 안에 그 습격을 진압했습니다. 마법 세계 전체가 놀랐고, 이 축복의 권능 역시 널리 인정받았죠.

많은 이들의 생각과는 달리 이 축복은 창조가 아닌 변화를 관장합니다. 연금술로 무언가를 만들 수는 없습니다. 그저 무언가를 희생해서 그 모습을 바꾸어, 대략 동등한 가치를 지닌 다른 무언가를 만들어낼 수 있을 뿐이죠.`
};

export const BITTER_DISSATISFACTION_SIGIL_TREE_DATA: BitterDissatisfactionSigil[] = [
    { id: 'fireborn', title: 'FIREBORN', description: 'Choose two: +1 Brewing, +1 Soul Alchemy, +1 Transformation', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], type: 'Fireborn', benefits: { brewing: 1, soulAlchemy: 1, transformation: 1 } },
    { id: 'brewer_i', title: 'BREWER I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['fireborn'], type: 'Brewer', benefits: { brewing: 1 } },
    { id: 'beastmother_i', title: 'BEASTMOTHER I', description: 'What could be more beautiful than creating new life?', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['fireborn'], type: 'Beastmother', benefits: { soulAlchemy: 1 } },
    { id: 'shifter_i', title: 'SHIFTER I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['fireborn'], type: 'Shifter', benefits: { transformation: 1 } },
    { id: 'brewer_ii', title: 'BREWER II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['brewer_i'], type: 'Brewer', benefits: { brewing: 1 } },
    { id: 'beastmother_ii', title: 'BEASTMOTHER II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['beastmother_i'], type: 'Beastmother', benefits: { soulAlchemy: 1 } },
    { id: 'shifter_ii', title: 'SHIFTER II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['shifter_i'], type: 'Shifter', benefits: { transformation: 1 } },
    { id: 'brewer_iii', title: 'BREWER III', description: "Unlocks The Promised Light of Morelli", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['brewer_ii'], type: 'Brewer', benefits: { brewing: 2 }, unlocks: 'the_promised_light_of_morelli' },
    { id: 'beastmother_iii', title: 'BEASTMOTHER III', description: "Unlocks Mage's Familiar III", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['beastmother_ii'], type: 'Beastmother', benefits: { soulAlchemy: 2 }, unlocks: 'mages_familiar_iii' },
    { id: 'shifter_iii', title: 'SHIFTER III', description: "Unlocks Shed Humanity II", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['shifter_ii'], type: 'Shifter', benefits: { transformation: 2 }, unlocks: 'shed_humanity_ii' },
    { id: 'mageweaver', title: 'MAGEWEAVER', description: "Time to play God\nUnlocks Human Marionettes", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['brewer_iii', 'beastmother_iii', 'shifter_iii'], type: 'Mageweaver', benefits: { soulAlchemy: 1 }, unlocks: 'human_marionettes' },
    { id: 'parasitology', title: 'PARASITOLOGY', description: "Unlocks Malrayoots", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['brewer_iii', 'beastmother_iii', 'shifter_iii'], type: 'Parasitology', benefits: { transformation: 1 }, unlocks: 'malrayoots' },
];

export const BITTER_DISSATISFACTION_SIGIL_TREE_DATA_KO: BitterDissatisfactionSigil[] = [
    { id: 'fireborn', title: '불의 아이', description: '2개를 선택하세요: 양조 +1, 영혼 연금술 +1, 변신술 +1', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], type: 'Fireborn', benefits: { brewing: 1, soulAlchemy: 1, transformation: 1 } },
    { id: 'brewer_i', title: '양조사 I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['fireborn'], type: 'Brewer', benefits: { brewing: 1 } },
    { id: 'beastmother_i', title: '동물의 어머니 I', description: '새 생명을 만들어내는 것보다 더 아름다운 것이 어디 있겠습니까?', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['fireborn'], type: 'Beastmother', benefits: { soulAlchemy: 1 } },
    { id: 'shifter_i', title: '변신술사 I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['fireborn'], type: 'Shifter', benefits: { transformation: 1 } },
    { id: 'brewer_ii', title: '양조사 II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['brewer_i'], type: 'Brewer', benefits: { brewing: 1 } },
    { id: 'beastmother_ii', title: '동물의 어머니 II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['beastmother_i'], type: 'Beastmother', benefits: { soulAlchemy: 1 } },
    { id: 'shifter_ii', title: '변신술사 II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['shifter_i'], type: 'Shifter', benefits: { transformation: 1 } },
    { id: 'brewer_iii', title: '양조사 III', description: "약속된 모렐리의 빛 해금", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['brewer_ii'], type: 'Brewer', benefits: { brewing: 2 }, unlocks: 'the_promised_light_of_morelli' },
    { id: 'beastmother_iii', title: '동물의 어머니 III', description: "마녀의 패밀리어 III 해금", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['beastmother_ii'], type: 'Beastmother', benefits: { soulAlchemy: 2 }, unlocks: 'mages_familiar_iii' },
    { id: 'shifter_iii', title: '변신술사 III', description: "괴수화 II 해금", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['shifter_ii'], type: 'Shifter', benefits: { transformation: 2 }, unlocks: 'shed_humanity_ii' },
    { id: 'mageweaver', title: '마녀 직조자', description: "신의 반열에 올라서세요.\n인간 마리오네트 해금", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['brewer_iii', 'beastmother_iii', 'shifter_iii'], type: 'Mageweaver', benefits: { soulAlchemy: 1 }, unlocks: 'human_marionettes' },
    { id: 'parasitology', title: '기생충학', description: "말레이우트 해금", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['brewer_iii', 'beastmother_iii', 'shifter_iii'], type: 'Parasitology', benefits: { transformation: 1 }, unlocks: 'malrayoots' },
];

export const BREWING_DATA: BitterDissatisfactionPower[] = [
    { id: 'vitae_potions', title: 'VITAE POTIONS', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Pz33YG7f-a1.webp', description: "Vampires are best suited to absorbing the vitae from blood, but all lifeforms are technically capable under the right conditions. Drinking enriched blood potions not only provides a modest amount of near-instant healing, revitalizes you and stabilizes your wounds, and even strengthens you briefly.", grade: 'kaarn' },
    { id: 'colorless_odorless', title: 'COLORLESS, ODORLESS', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MDCXz1rd-a2.webp', description: "You can create conventional poisons using mundane ingredients which can immediately cause pain, paralysis, and other debilitating effects. You can also imbue other spells into magical poisons which are slower to take effect, but which can afflict victims for weeks. Click the book icon to view the Curse Encyclopedia.", grade: 'kaarn' },
    { id: 'magecraft_boosters', title: 'MAGECRAFT BOOSTERS', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jCqzd0n-a3.webp', description: "When drunken, you can choose from any of the Stolen Blessings, and for the next hour, you will gain one random non-{r}Xuth{/r}-tier power from that blessing for up to an hour. Through this, you can gain one power from each Blessing per day. Effects stack to up to 3 powers at once via multiple elixirs.", grade: 'kaarn' },
    { id: 'mass_production', title: 'MASS PRODUCTION', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/27tCKT2s-a4.webp', description: "You can now create diluted versions of potions that can be pumped out in greater quantities, as they require far less resources and time to produce. Perfect if you need to resupply quick, especially if supplying an entire team out in the field, or if you want to make a living selling thousands of potions.", grade: 'kaarn' },
    { id: 'water_of_life', title: 'WATER OF LIFE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yc75fWqq-a5.webp', description: "Water mixed with boiled Alspry wings. Each liter drunken provides a week of time in which you do not have to eat to stave off hunger, nor eat to stave off thirst, nor sleep to keep energized; in fact, it will be totally impossible for you to get tired or run out of stamina unless affected by certain spells.", grade: 'kaarn' },
    { id: 'bolstering_tonics', title: 'BOLSTERING TONICS', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G3Bzw372-a6.webp', description: "Temporarily boost your skills or resistances, though one of each at a time. The more specific the skill or resistance, the longer and more potent than the effect. For example, a resistance towards magic will be much less potent than a resistance towards fire; same for your skill in combat vs in swordfighting.", grade: 'kaarn' },
    { id: 'love_potion', title: 'LOVE POTION', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/F48YPN8z-a7.webp', description: "A perfume that makes all around more open to suggestion, romantic, and amorous than they usually are. This effect is strong enough to aid greatly in persuasion and seduction, but weak enough others won't notice. Drinking it temporarily makes one extremely lovey dovey - dangerously so!", grade: 'kaarn' },
    { id: 'the_promised_light_of_morelli', title: 'THE PROMISED LIGHT OF MORELLI', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/NggdYG1z-a8.webp', description: "{i}Requires {g}Brewer III.{/g}{/i} The holy grail of brewing, each of these potions requires the still-beating heart of a Grimsayer-level Allmillor, alongside some other ingredients that will be a pain to acquire. However, for a few days or so, it will provide {i}all{/i} of your powers with boosts. (The specific effects are the same as those displayed when the BOOST button for each respective magic category is activated.)", requires: ['brewer_iii'], grade: 'purth' },
];

export const BREWING_DATA_KO: BitterDissatisfactionPower[] = [
    { id: 'vitae_potions', title: '생명혈 물약', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Pz33YG7f-a1.webp', description: "비록 뱀파이어들이 피에서 생명력을 가장 잘 흡수하는 존재들이긴 하지만, 조건만 맞으면 다른 생명체들도 그렇게 할 수 있습니다. 이 농축된 피의 물약을 마시면 적당한 즉발 치유를 받을 수 있을 뿐만 아니라, 원기가 회복되고, 상처는 안정화되고, 잠시 동안 힘까지 강화됩니다.", grade: 'kaarn' },
    { id: 'colorless_odorless', title: '무색무취', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MDCXz1rd-a2.webp', description: "평범한 재료들을 사용해서 복용자에게 고통과 마비, 기타 심신을 깎아먹는 효과를 주는 독을 만들 수 있습니다. 또한, 마법으로 만들어낸 독에 다른 주문의 효과를 부여할 수도 있습니다. 이 독은 효과가 나타나기까지 시간이 걸리지만, 몇 주 동안이나 피해자를 괴롭힐 수 있습니다. 저주 백과사전을 보려면 책 아이콘을 클릭하세요.", grade: 'kaarn' },
    { id: 'magecraft_boosters', title: '마법 강화제', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jCqzd0n-a3.webp', description: "이 마법약을 마시면 훔쳐온 축복 중 하나를 선택할 수 있습니다. 다음 한 시간 동안, 그 축복의 하위 마법 중 하나를 무작위로 얻습니다. (단, {r}주스{/r} 등급의 마법은 제외됩니다.) 한 축복은 하루에 한 번만 선택할 수 있습니다. 이 마법약으로 얻는 마법은 동시에 3종류까지 중첩됩니다.", grade: 'kaarn' },
    { id: 'mass_production', title: '대량 생산', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/27tCKT2s-a4.webp', description: "농도가 희석된 물약을 대량으로 조제할 수 있게 됩니다. 이런 물약은 훨씬 적은 재료와 시간을 들여서 만들 수 있습니다. 전장에서 한 팀 전체를 지원해야 하는 등 물약의 빠른 재보급이 필요하거나, 물약 장사로 거금을 만지고 싶어하는 당신에게 안성맞춤입니다.", grade: 'kaarn' },
    { id: 'water_of_life', title: '생명수', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yc75fWqq-a5.webp', description: "알스프리의 날개를 끓여 물과 섞었습니다. 생명수 1리터당 1주일 동안 먹거나, 마시거나, 잠을 자지 않아도 버틸 수 있습니다. 더 정확히 말하면, 특정 마법에 당하는 것이 아니고서는 피로해지거나 체력이 다할 일이 없어집니다.", grade: 'kaarn' },
    { id: 'bolstering_tonics', title: '강화 작용제', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G3Bzw372-a6.webp', description: "한 가지 능력이나 저항력을 일시적으로 상승시키는 물약입니다. 상승시키고자 하는 것이 구체적일수록 효과가 오래 지속되고, 더 강해집니다. 예를 들면, \"마법 저항력 상승\"은 \"화염 마법 저항력 상승\"보다 효과가 약하고, \"전투 능력 상승\"은 \"검술 능력 상승\"보다 효과가 약합니다.", grade: 'kaarn' },
    { id: 'love_potion', title: '사랑의 묘약', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/F48YPN8z-a7.webp', description: "이 향수는 주변 모든 이들을 원래보다 훨씬 개방적이고, 낭만적이고, 사랑을 원하게 만듭니다. 묘약의 효과는 누군가를 설득하거나 유혹하는 일이 훨씬 쉬워지지만, 대놓고 눈치챌 만큼 강하지는 않습니다. 만약 마시게 된다면 사람이 일시적으로나마 정말 달달하게 바뀝니다. 좀 위험할 정도로요!", grade: 'kaarn' },
    { id: 'the_promised_light_of_morelli', title: '약속된 모렐리의 빛', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/NggdYG1z-a8.webp', description: "{i}{g}양조사 III{/g}가 필요합니다.{/i} 이 물약은 양조사들의 성배와도 같습니다. 한 번 만들 때마다 무려 맥동하는 그림세이어급 올밀러의 심장이 필요하며, 다른 재료들도 구하기 정말 어려운 건 덤입니다. 하지만 물약을 마시면 며칠 동안 당신의 모든 힘이 강화됩니다. (구체적인 효과는 각 마법 카테고리의 'BOOST' 버튼을 활성화했을 때 나타나는 효과와 동일합니다.)", requires: ['brewer_iii'], grade: 'purth' },
];

export const SOUL_ALCHEMY_DATA: BitterDissatisfactionPower[] = [
    { id: 'mages_familiar_i', title: "MAGE'S FAMILIAR I", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1JJ2K55b-a9.webp', description: "A mage just isn't complete without a cute little familiar. All it will take is the soul of some lesser beast or simple monster! You have {w}30 Beast Points{/w} with which to design your familiar on the {i}Reference Page{/i}. Note that you can only have one familiar. If it dies, you can easily reform it with an incantation.", grade: 'kaarn' },
    { id: 'mages_familiar_ii', title: "MAGE'S FAMILIAR II", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5hdF5kct-a10.webp', description: "{i}Requires {w}Mage's Familiar I.{/w}{/i} Some mages delve deeper into the art of soul alchemy, creating even more intimidating beasts to fight by their side. You are given {w}30 extra Beast Points{/w} with which to design your familiar, for a total of {w}60 Beast Points{/w}. Remember that you still only have one, though.", requires: ['mages_familiar_i'], grade: 'kaarn' },
    { id: 'mages_familiar_iii', title: "MAGE'S FAMILIAR III", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/h1w4jdbw-a11.webp', description: "{i}Requires {w}Mage's Familiar II{/w} and {g}Beastmother III.{/g}{/i} By now, you likely have a truly incredible monster at your beck and call! You are given {w}30 extra Beast Points{/w} with which to design your familiar, for a total of {w}90 Beast Points{/w}. Create anything you'd like, from a towering dragon to a magical fairy!", requires: ['mages_familiar_ii', 'beastmother_iii'], grade: 'purth' },
    { id: 'human_marionettes', title: 'HUMAN MARIONETTES', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fz6JV3yF-a12.webp', description: "{i}Requires {r}Mageweaver.{/r}{/i} You have reached such a state of absolute power that you may perform a feat only the Mother of Azure is ordinarily capable of: creating a new mage. Of course, yours can't quite live up to the standard of hers. After all, while they are, on an objective level, clearly human, there's something deeply {i}off{/i} about them, as if they're merely a puppet being pulled by invisible strings. Plus, you will need to somehow acquire extant human souls to create them. Regardless, you will never find another companion so loyal. You are given {w}100 Companion Points{/w} to use on the {i}Reference Page{/i}. You can split these up inbetween multiple puppets, so long as they are divided equally. That means you can have: 1 puppet with {w}100 points{/w}, 2 with {w}50 points{/w}, 4 with {w}25 points{/w}, 5 with {w}20 points{/w}, 10 with {w}10 points{/w}, 20 with {w}5 points{/w}, 25 with {w}4 points{/w}, {i}or{/i} 50 with {w}2 points{/w} each. You can just have the same perks and choices apply to all of them, so there's no need to design them individually unless you really want to. If one is destroyed, you can recreate them, but it will take an amount of hours equal to the number of points invested in said puppet.", requires: ['mageweaver'], grade: 'xuth' },
    { id: 'beastmaster', title: 'BEASTMASTER', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HRj24jL-a13.webp', description: "{i}Requires {w}Mage's Familiar I.{/w}{/i} You're now no longer limited to only a single familiar. You can take as many as you'd like, so long as the {w}Beast Points{/w} you've acquired can be split up evenly between them. For example, if you have {w}Mage's Familiar II{/w}, you can create two familiar using {w}30 points{/w} each.", requires: ['mages_familiar_i'], grade: 'kaarn' },
    { id: 'self_duplication', title: 'SELF DUPLICATION', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Mkp93Yhw-a14.webp', description: "You can divvy up portions of your own soul into up to ten different bodies; these can be controlled as a hive consciousness, but have no autonomy and are quite fragile, turning to dust when killed. Still, they can cause a lot of damage and confusion! Give your soul time to reconstitute before doing this again.", grade: 'kaarn' },
    { id: 'personification', title: 'PERSONIFICATION', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xKjtcpbz-a15.webp', description: "With a single incantation, you can imbue a simple soul into almost any object! They'll be able to fly and move around, talk, and might even grow a face. You can select a {w}Companion Build{/w} from the {i}Reference Page{/i} that consists ONLY of {i}Personality Traits{/i}. However, it doesn't always have to be that personality; it can change depending on necessity. A popular trick is turning grenades into suicide bombers.", grade: 'kaarn' },
];

export const SOUL_ALCHEMY_DATA_KO: BitterDissatisfactionPower[] = [
    { id: 'mages_familiar_i', title: "마녀의 패밀리어 I", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1JJ2K55b-a9.webp', description: "귀여운 패밀리어 없이는 마법소녀를 논할 수 없습니다. 동물이나 작은 괴물의 영혼 하나만 있으면 됩니다! 동물 점수 30점이 주어지고, 참고 페이지에서 당신만의 패밀리어를 디자인할 수 있습니다. 한 번에 하나의 패밀리어만 데리고 다닐 수 있습니다. 패밀리어가 죽으면 주문을 외우는 것으로 쉽게 재탄생시킬 수 있습니다.", grade: 'kaarn' },
    { id: 'mages_familiar_ii', title: "마녀의 패밀리어 II", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5hdF5kct-a10.webp', description: "{i}{w}마녀의 패밀리어 I{/w}이 필요합니다.{/i} 몇몇 마법소녀들은 영혼 연금술을 보다 깊이 탐구하여 자신들의 옆을 지킬 더욱 무서운 야수들을 만들어내기도 합니다. 패밀리어에게 투자할 수 있는 동물 점수 30점이 추가로 주어집니다. 단, 여전히 하나의 패밀리어만 보유할 수 있습니다.", requires: ['mages_familiar_i'], grade: 'kaarn' },
    { id: 'mages_familiar_iii', title: "마녀의 패밀리어 III", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/h1w4jdbw-a11.webp', description: "{i}{w}마녀의 패밀리어 II{/w}와 {g}동물의 어머니 III{/g}가 필요합니다.{/i} 이쯤 되면 실로 대단한 괴물이 당신과 함께합니다! 패밀리어에게 투자할 수 있는 동물 점수 30점이 추가로 주어집니다. 거대한 용부터 마법을 부리는 요정에 이르기까지, 원하는 것은 뭐든 만들어 보세요!", requires: ['mages_familiar_ii', 'beastmother_iii'], grade: 'purth' },
    { id: 'human_marionettes', title: '인간 마리오네트', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fz6JV3yF-a12.webp', description: "{i}{r}마녀 직조자{/r}가 필요합니다.{/i} 당신의 힘은 절대적인 경지에 도달하여, 본래라면 하늘빛의 어머니만이 가능한 일을 할 수 있게 됩니다. 바로 새로운 마법소녀를 만드는 것이죠. 물론 당신의 창조물은 어머니의 것에 비할 바가 못 됩니다. 물론 객관적으로 보았을 때도 완연한 인간의 모습을 하고 있지만, 뭔가가 크게 엇나가 있습니다. 마치 보이지 않는 실로 조종받는 퍼펫들 같습니다. 거기다가 이들을 만들기 위해서는 어떻게든 현존하는 인간의 영혼을 구해야 합니다. 그래도 창조에 성공한다면 이보다 더 충성스러운 동료는 어디서도 찾을 수 없을 겁니다.\n\n퍼펫에 투자할 동료 점수 {w}100점{/w}이 주어집니다. 점수를 균등하게 분배하기만 한다면, 보유할 수 있는 퍼펫의 숫자에는 제한이 없습니다. 가령 100점을 투자해 퍼펫 하나를, 또는 25점씩을 투자해 퍼펫 넷을 만들 수 있는 식입니다. 모든 선택지를 통일할 수도 있고, 원한다면 각각의 퍼펫별로 다른 설정을 할 수도 있습니다. 퍼펫이 파괴되면 다시 만들어낼 수 있지만, 투자한 동료 점수 1점당 1시간이 소요됩니다.", requires: ['mageweaver'], grade: 'xuth' },
    { id: 'beastmaster', title: '동물 조련사', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HRj24jL-a13.webp', description: "{i}{w}마녀의 패밀리어 I{/w}이 필요합니다.{/i} 이제 보유할 수 있는 패밀리어의 수에 재한이 없어집니다. 단, 각각의 패밀리어들에게 동물 점수를 균일하게 투자해야 합니다. 예를 들어 동물 점수 60점이 있다면 각각 30점으로 두 마리의 패밀리어를 만들 수 있습니다.", requires: ['mages_familiar_i'], grade: 'kaarn' },
    { id: 'self_duplication', title: '자가 복제', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Mkp93Yhw-a14.webp', description: "당신의 영혼을 나누는 것으로 최대 10체의 분신을 반들 수 있습니다. 이들은 집단의식을 통해 조종할 수 있지만, 자율성이 없고, 내구력이 약합니다. 분신들은 죽게 되면 먼지가 되어 사라집니다. 잘 활용하면 분신을 이용해 큰 피해와 혼란을 야기할 수 있습니다! 다만 능력을 재사용하기 전에 당신의 영혼이 회복할 시간을 두어야 합니다.", grade: 'kaarn' },
    { id: 'personification', title: '개성화', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xKjtcpbz-a15.webp', description: "주문을 한 번 외우면 어떤 물체에든 간단한 영혼을 주입할 수 있습니다. 하늘을 날거나, 돌아다니거나, 말을 하거나, 심지어 얼굴이 생겨날 수도 있습니다. 참고 페이지의 동료 항목에서 성격을 하나 골라 줄 수 있습니다. 전형적인 활용법은 수류탄을 자폭 돌격병으로 바꿔 버리는 겁니다.", grade: 'kaarn' },
];

export const TRANSFORMATION_DATA: BitterDissatisfactionPower[] = [
    { id: 'material_transmutation', title: 'MATERIAL TRANSMUTATION', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MxNpVDcG-a16.webp', description: "The most traditional alchemy. Simply allows you to change the shape and composition of inorganic objects you are touching as long as matter is not created nor destroyed. Larger objects take exponentially longer times to alter. Makes the {w}High Power{/w} upgrade for melee weapons free.", grade: 'kaarn' },
    { id: 'internal_manipulation', title: 'INTERNAL MANIPULATION', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7NLKj2Tb-a17.webp', description: "Change your bones and organs at will. Turn your heart into a geyser of poisonous, boiling blood, your bones into a flurry of blades jutting from your skin, your eyes into ultrasensitive machines that can help see through illusions, etc. Taking internal damage temporarily negates control of that area.", grade: 'kaarn' },
    { id: 'shed_humanity_i', title: 'SHED HUMANITY I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VY72fqbQ-a18.webp', description: "You can shift into a truly monstrous form with a simple incantation! Design your transformed form with {w}50 Beast Points{/w} on the {i}Reference Page{/i} excluding options marked with an *. Staying in this altered form requires conscious exertion, though, so you'll probably only keep it up for 3 hours a day.", grade: 'kaarn' },
    { id: 'shed_humanity_ii', title: 'SHED HUMANITY II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Qv47xV8n-a19.webp', description: "{i}Requires {w}Shed Humanity I{/w} and {g}Shifter III.{/g}{/i} You are given {w}30 extra Beast Points{/w} with which to design your transformed form, for a total of {w}80 Beast Points{/w}, though still excluding options marked with an *. You can also stay in this form for upwards of 6 hours per day before growing exhausted with it.", requires: ['shed_humanity_i', 'shifter_iii'], grade: 'purth' },
    { id: 'phase_shift', title: 'PHASE SHIFT', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0yVZzwxC-a20.webp', description: "You can spontaneously transform your body, or parts of it, from a solid into a liquid or gas. While in these amorphous forms, you will still be totally mobile and able to fit through small cracks while extremely difficult to detect. You can still fight and are hard to hurt, but vulnerable to ice or fire.", grade: 'kaarn' },
    { id: 'rubber_physiology', title: 'RUBBER PHYSIOLOGY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ks2kk5fP-a21.webp', description: "The other mages always ask you to grab things off tall shelves for them. After all, your limbs can stretch to 50x their default length, and are {i}super{/i} flexible. In fact, most of your entire body can be molded into a wide assortment of shapes, allowing you to fit through a keyhole or split around attacks!", grade: 'kaarn' },
    { id: 'supersize_me', title: 'SUPERSIZE ME', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/3J0Fvyv-a22.webp', description: "Want to see the world from a different angle? On a whim, you can change your height from 4 inches, anywhere between 1/64th your default height, to 64x your default height. Being massive is prohibitively exhausting to do for more than a half hour at a time, not to mention destructive!", grade: 'kaarn' },
    { id: 'malrayoots', title: 'MALRAYOOTS', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GQm4L0Cn-a23.webp', description: "{i}Requires {bp}Parasitology.{/bp}{/i} Large, fat, maggot-like parasites that enter victims and forcibly transform them. Spend {w}70 Beast Points{/w} on these forms if they can only affect mages, or {w}40{/w} if they can affect everyone. You can coerce these victims by offering them the antidote only if they do your bidding.", requires: ['parasitology'], grade: 'sinthru' },
];

export const TRANSFORMATION_DATA_KO: BitterDissatisfactionPower[] = [
    { id: 'material_transmutation', title: '물질 연금술', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MxNpVDcG-a16.webp', description: "가장 전통적인 연금술입니다. 물질을 창조하거나 소멸시키지 않는 한도에서, 당신이 접촉하고 있는 무기물의 모양이나 조성을 바꿀 수 있습니다. 물질의 크기가 클수록 소모되는 시간이 기하급수적으로 증가합니다. 근접 무기에 적용되는 {w}고출력{/w} 업그레이드의 비용이 사라집니다.", grade: 'kaarn' },
    { id: 'internal_manipulation', title: '체내 조작', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/7NLKj2Tb-a17.webp', description: "뼈와 장기를 마음대로 변화시킬 수 있습니다. 당신의 혈액이 맹독으로 끓어오르게 하고, 피부에서 칼날 같은 뼈를 솟구치게 하고, 안구를 변화시켜 환상조차 꿰뚫어보는 예민함을 가질 수 있습니다. 신체 부위에 내상을 입으면 잠시 동안 그곳을 대상으로 마법을 사용할 수 없게 됩니다.", grade: 'kaarn' },
    { id: 'shed_humanity_i', title: '괴수화 I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VY72fqbQ-a18.webp', description: "간단한 주문으로 진정한 괴물의 형상을 취할 수 있습니다! 참고 페이지에서 동물 점수 50점을 사용해 당신의 변신 형태를 디자인할 수 있습니다. 단, *가 표시된 선택지들은 고를 수 없습니다. 이 변신 형태를 유지하려면 계속해서 힘을 써야 하기 때문에 하루에 3시간 정보밖에 유지할 수 없을 겁니다.", grade: 'kaarn' },
    { id: 'shed_humanity_ii', title: '괴수화 II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Qv47xV8n-a19.webp', description: "{i}{w}괴수화 I{/w}과 {g}변신술사 III{/g}가 필요합니다.{/i} 변신 형태에 투자할 수 있는 동물 점수가 30점 추가로 주어집니다. 여전히 *가 표시된 선택지들은 고를 수 없습니다. 변신 형태의 지속 시간이 하루에 6시간으로 증가합니다.", requires: ['shed_humanity_i', 'shifter_iii'], grade: 'purth' },
    { id: 'phase_shift', title: '위상 변화', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0yVZzwxC-a20.webp', description: "원할 때 신체의 일부나 전신을 액체나 기체 상태로 바꿀 수 있습니다. 마법을 사용한 상태에서도 기동성을 잃지 않으며, 작은 틈새에도 끼어들어갈 수 있고, 당신을 탐지하는 것이 극도로 어려워집니다. 이 상태에서도 전투가 가능하고, 피해도 쉽게 입지 않지만, 냉기나 화염 공격에는 취약해집니다.", grade: 'kaarn' },
    { id: 'rubber_physiology', title: '고무고무 신체', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ks2kk5fP-a21.webp', description: "다른 마법소녀들이 항상 당신에게 높은 선반 위에 있는 저것들을 좀 꺼내 달라고 할 겁니다. 당신의 팔다리가 50배까지 늘어날 수 있고 엄청나게 유연해졌으니까요. 사실, 팔다리뿐만 아니라 전신을 다양한 모양으로 바꾸며 열쇠구멍을 비집고 들어가거나 공격을 흘려낼 수도 있습니다!", grade: 'kaarn' },
    { id: 'supersize_me', title: '거대화', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/3J0Fvyv-a22.webp', description: "세상을 다른 시선에서 보고 싶으신가요? 마음만 먹으면 당신의 몸집을 최대 64배까지 키우거나 줄일 수 있습니다. 한 번에 30분 이상 거대화를 하면 체력적으로 무리를 하게 된다는 것만 조심하세요. 주변이 다 부서질 수도 있다는 건 말할 필요도 없구요!", grade: 'kaarn' },
    { id: 'malrayoots', title: '말레이우트', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GQm4L0Cn-a23.webp', description: "{i}{bp}기생충학{/bp}이 필요합니다.{/i} 구더기를 닮은 크고 뚱뚱한 기생충들을 상대에게 주입시켜 강제로 변이시킵니다. 변이 형태는 동물 점수를 사용하여 디자인할 수 있습니다. 마법소녀들만을 대상으로 할 경우 동물 점수 70점, 모든 이들을 대상으로 할 경우 40점이 주어집니다. 당신의 명령을 따르지 않으면 치료제를 주지 않겠다는 말로 피해자들을 협박할 수 있을 겁니다.", requires: ['parasitology'], grade: 'sinthru' },
];
