
import type { ClosedCircuitsSigil, ClosedCircuitsPower } from '../../types';

// Closed Circuits
export const MARGRA_DATA = {
    title: "MARGRA, DAUGHTER OF UNITY",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LDwmm3Br-main1.webp",
    description: `The youngest of the Daughters, born only millennia ago. People forget this, but back in the time of the original Sinjade Doctrine, mages were bestowed basically unlimited power. Obviously, this could not last long. To prevent an uprising, in the Sinthru Covenant, the Mother offered these mages immense influence over the world's politics via voting in the newly established Red-Jade Council, and Margra was birthed to serve as their intermediary. Some say the Red-Jade Council is a glorified social club; a bunch of bored old corporate CEOs getting together to play bingo and gossip like schoolgirls. Others say they're the true power behind the throne, cementing their influence through artificial scarcity and pulling all the strings while the Mother slowly devolves into a ceremonial figurehead. ({i}I will say, if that last one were true, Mother would probably be quite pleased with the arrangement, in my opinion. She never was one for geopolitics...{/i})

Her spells are probably the most rarely studied of all of them, for they're far less straightforward and generally require more significant amounts of thought and creativity put into how they can be used — you won't find any good old projectile spells in her arsenal! However, if you put in the legwork and are the clever sort, you'll find that the blessings she offers are often the best a mage could hope for. In fact, she offers far more {r}Xuth{/r}-level spells than any of the other daughters! Just know you may be vulnerable if the direct combat-oriented mages catch you off your guard.`
};

export const MARGRA_DATA_KO = {
    title: "통합의 딸 마그라",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LDwmm3Br-main1.webp",
    description: `마그라는 불과 천 년 전에 태어난 자매들의 막내입니다. 이제 그 사실을 기억하는 사람들조차 얼마 없지만, 그 옛날 신제이드 대원칙 하에서는 모든 마녀들이 사실상 무한한 힘을 가질 수 있었습니다. 당연히 그 시절이 오래 갈 수는 없었지요. 폭동을 막기 위해 어머니께서는 신스루 마녀단원들에게 세계 정치를 좌지우지할 수 있는 권한을 주셨습니다. 바로 새롭게 설립된 홍옥의 의회에서 의사 표결을 하는 것이었죠. 그리고 마그라는 의회의 중개인 역할을 하기 위해 창조되었습니다. 몇몇 사람을은 홍옥의 의회가 겉만 번지르르한 사교 클럽에 불과하다고 합니다. 꽉 막힌 대기업 총수들이 무슨 여고생들마냥 별의별 소문을 갖고 떠들어 댄다고 합니다. 다른 사람들은 의회가 이 세계의 진정한 실세라고 합니다. 공급을 통제하며 권력을 키우고, 어머니를 상징적인 지도자로 세우고 뒤에서 암약한다고 합니다. ({i}사실 흑막설이 맞다면 어머니께서도 꽤 기분 좋아하실 거라고 생각합니다. 지정학은 별로 좋아하지 않으셨거든요.{/i})

마그라의 마법은 가장 연구되는 빈도가 적습니다. 직관성이 가장 떨어지고, 마법의 효과 발현을 위해서는 보다 깊은 생각과 창의성이 필요하기 때문입니다. 여기엔 그 흔한 투사체 발사 마법이 없어요! 하지만 당신이 충분히 똑똑하고 성실하다면, 마그라의 축복이 마법소녀가 누릴 수 있는 최고의 축복이라는 것을 알게 될 겁니다. 당장 {r}주스{/r} 등급 마법의 숫자만 봐도 월등히 많으니까요! 그래도 방심한 상태에서 직접 전투에 특화된 마녀들에게 기습당하면 위험하다는 건 잊지 마세요.`
};

export const CLOSED_CIRCUITS_DATA = {
    title: "THE BLESSING OF CLOSED CIRCUITS",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SwdQ7cVY-main2.webp",
    description: `Okay, to clear things up: magitech is the art of creating semi-magical technology, while technomancy is the art of controlling existing technology connected to the Web. The Web could be thought of as a verse of its own, layered over and connected to our reality. If you want to start cracking systems, you'll have to {w}make a{/w} {w}Net Avatar{/w}, which is sort of like an additional, digital alter ego. Of course, corporations and stuff don't really want you cracking their databases open, so expect firewalls, spiderbots, and other defenses! Destroyed net avatars take a month to be recreated.

Another bonus: a few decades ago, Laser Focus Inc. accidentally leaked a bunch of experimental self-replicating nanites, and by now they've proliferated the entire atmosphere a trillion times over. They don't really do much by themselves, but they're super low security, so technomancer have found they can easily make 'em do a whole bunch of things!`
};

export const CLOSED_CIRCUITS_DATA_KO = {
    title: "폐쇄회로의 축복",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SwdQ7cVY-main2.webp",
    description: `자, 확실히 짚고 넘어가죠. 마법공학은 공학에 마법을 접목시키는 것이고, 기계마법은 웹상에 연결된 기술을 조종하는 것입니다. 웹 또한 우리의 현실과 연결된 하나의 가상 우주라고 볼 수 있죠. 혹시 웹상의 시스템 크랙에 손을 대고 싶다면, {w}넷 아바타{/w}부터 만들어야 합니다. 디지털 세계의 겉보기 자아 같은 것이죠. 물론, 기업체 등등에서는 자기들 데이터베이스가 털리는 것을 가만 두고 보지 않을 것이기 때문에, 방화벽이나 웹 크롤러, 기타 방어 프로그램들이 당신을 막으려 할 겁니다. 혹시 이들에게 넷 아바타가 공격당해 파괴된다면, 재구성되는 데 한 달이 걸립니다.

한 가지 좋은 소식이 더 있습니다. 몇십 년 전에 레이저포커스 주식회사에서 실수로 실험용 자가복제 나나이트들을 유출시키는 사고가 있었습니다. 그리고 그 수가 이제는 1조 배 가까이 늘어났구요. 나나이트들은 자체적으로는 거의 아무것도 하지 않지만, 보안 등급이 최하급입니다. 그 덕분에 기계마법을 이용하면 나나이트로 온갖 기상천외한 일들을 할 수 있죠!`
};

export const CLOSED_CIRCUITS_SIGIL_TREE_DATA: ClosedCircuitsSigil[] = [
    { id: 'script_kiddy', title: 'SCRIPT KIDDY', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], benefits: { netAvatar: 1 } },
    { id: 'kyrotik_armor', title: 'KYROTIK ARMOR™', description: 'Get all suited up!\nUnlocks Nanite Armor I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['script_kiddy'], unlocks: ['nanite_armor_i'], benefits: { naniteControl: 2 } },
    { id: 'heavy_duty', title: 'HEAVY DUTY', description: 'Unlocks Nanite Armor II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['kyrotik_armor'], unlocks: ['nanite_armor_ii'], benefits: { naniteControl: 2 } },
    { id: 'ez_hack', title: 'EZ-HACK™', description: "With our software, you'll be a pro hacker in no time!", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['script_kiddy'], benefits: { technomancy: 1 } },
    { id: 'hacker_i', title: 'HACKER I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['ez_hack'], benefits: { technomancy: 1 } },
    { id: 'nanite_master', title: 'NANITE MASTER', description: 'Unlocks Nanite Armor III', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['heavy_duty'], unlocks: ['nanite_armor_iii'], benefits: { naniteControl: 1 } },
    { id: 'black_hat', title: 'BLACK HAT', description: 'Unlocks 9R1M01R3.RPM', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['hacker_2'], unlocks: ['9r1m01r3_rpm'], benefits: { technomancy: 1 } },
    { id: 'hacker_2', title: 'HACKER 2', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['hacker_i'], benefits: { technomancy: 1 } },
    { id: 'l33t_h4xx0r', title: 'L33T H4XXOR', description: 'Unlocks Manual Override', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['hacker_2'], unlocks: ['manual_override'], benefits: { technomancy: 2 } },
    
];

export const CLOSED_CIRCUITS_SIGIL_TREE_DATA_KO: ClosedCircuitsSigil[] = [
    { id: 'script_kiddy', title: '스크립트 초보', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], benefits: { netAvatar: 1 } },
    { id: 'kyrotik_armor', title: '카이로틱 아머™', description: '제대로 갖춰입어 보세요!\n나나이트 갑옷 I 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['script_kiddy'], unlocks: ['nanite_armor_i'], benefits: { naniteControl: 2 } },
    { id: 'heavy_duty', title: '중장갑', description: '나나이트 갑옷 II 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['kyrotik_armor'], unlocks: ['nanite_armor_ii'], benefits: { naniteControl: 2 } },
    { id: 'ez_hack', title: '이지-핵™', description: "이 프로그램만 있으면 당신도 프로 해커!", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['script_kiddy'], benefits: { technomancy: 1 } },
    { id: 'hacker_i', title: '해커 I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['ez_hack'], benefits: { technomancy: 1 } },
    { id: 'nanite_master', title: '나나이트 달인', description: '나나이트 갑옷 III 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['heavy_duty'], unlocks: ['nanite_armor_iii'], benefits: { naniteControl: 1 } },
    { id: 'black_hat', title: '블랙 해커', description: '9R1M01R3.RPM 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['hacker_2'], unlocks: ['9r1m01r3_rpm'], benefits: { technomancy: 1 } },
    { id: 'hacker_2', title: '해커 II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['hacker_i'], benefits: { technomancy: 1 } },
    { id: 'l33t_h4xx0r', title: '근ㅣ트 해귀', description: '수동 제어 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['hacker_2'], unlocks: ['manual_override'], benefits: { technomancy: 2 } },
];

export const NET_AVATAR_DATA: ClosedCircuitsPower[] = [
    { id: 'f41th_jhc', title: 'F41TH.JHC', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xKGt7pKD-a1.webp', description: "For you, the Web is a stereotypical void of data and network nodes, and you look much like yourself. You're a jack-of-all-trades with the ability to create powerful viruses to sabotage specific parts of a system, ranging from detection to defense, giving you a lot of flexibility in your approach.", grade: 'kaarn' },
    { id: 'ch402_mp5', title: 'CH402.MP5', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/D3mF73p-a2.webp', description: "For you, the Web is a bitter scarlet battleground, and you a scarred general. You have no interest in stealth; you are like a walking DDOS, and every system is sent into panic by your approach as they're flooded with junk data. You bring security systems to their knees through sheer brute force.", grade: 'kaarn' },
    { id: 'n05t4lg14_fmj', title: 'N05T4LG14.FMJ', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/3Kk4szK-a3.webp', description: "For you, the Web is a maze of places from old memories viewed through a haze of VHS static, and you an innocent child. You're small, clever, and move silently, and are easily underestimated and overlooked as you sneak through their labyrinthian databases. They'll never even know you were there.", grade: 'kaarn' },
    { id: '9r1m01r3_rpm', title: '9R1M01R3.RPM', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nMX1VrSL-a4.webp', description: "{i}Requires {bp}Black Hat.{/bp}{/i} To you, the Web is just a bunch of junk you brushed aside to get to your goals, and you don't bother fighting fair. The coven has shown you backdoors hardcoded into most technology. You've also gained a botnet — compromised avatars who can do all your dirty work for you.", requires: ['black_hat'], grade: 'sinthru' },
];

export const NET_AVATAR_DATA_KO: ClosedCircuitsPower[] = [
    { id: 'f41th_jhc', title: 'F41TH.JHC', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xKGt7pKD-a1.webp', description: "당신은 웹을 전형적인 네트워크 노드와 데이터 패킷으로 인식합니다. 당신의 넷 아바타는 당신과 별반 다르지 않습니다. 강력한 바이러스를 만들어 시스템 일부에 공작을 가할 수 있습니다. 공격은 물론, 탐지나 방어에 이르기까지, 유연한 접근이 가능한 팔방미인형 능력입니다.", grade: 'kaarn' },
    { id: 'ch402_mp5', title: 'CH402.MP5', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/D3mF73p-a2.webp', description: "당신에게 웹이란 유혈이 낭자하는 가혹한 전장입니다. 그리고 당신은 역전의 장군이지요. 은밀함은 당신의 관심 밖입니다. 마치 걸어다니는 DDOS처럼, 접근하는 모든 시스템에 정크 데이터를 쏟아부어 패닉을 발생시킵니다. 보안 시스템 따위는 힘만으로 무릎꿇릴 수 있을 것입니다.", grade: 'kaarn' },
    { id: 'n05t4lg14_fmj', title: 'N05T4LGI4.FNJ', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/3Kk4szK-a3.webp', description: "당신은 웹을 브라운관 TV를 통해 보는, 추억의 장소들이 엮인 미로로 인식합니다. 당신은 어린 아이처럼 작고, 똑똑하고, 은밀하게 움직입니다. 당신이 거대 데이터베이스에 조용히 숨어든다 해도 보통은 신경쓰지 않을 것입니다. 사실 당신이 왔다 간 줄도 모를 겁니다.", grade: 'kaarn' },
    { id: '9r1m01r3_rpm', title: '9R1M01R3.RPM', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nMX1VrSL-a4.webp', description: "{i}{bp}블랙 해커{/bp}가 필요합니다.{/i} 당신에게 웹이란 목표에 도달하기 위해 치워 버려야 하는 쓰레기일 뿐입니다. 그리고 당신은 정정당당한 승부를 할 생각이 추호도 없습니다. 당신은 마녀단을 통해 대부분의 기술에 접근할 수 있는 백도어 코드를 얻었습니다. 당신 대신 더러운 일들을 맡아 해 줄 봇넷들은 덤이구요.", requires: ['black_hat'], grade: 'sinthru' },
];

export const TECHNOMANCY_DATA: ClosedCircuitsPower[] = [
    { id: 'domain_master_i', title: 'DOMAIN MASTER I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/JF7DTbMf-a5.webp', description: "You can exert influence over any many types of simpler mundane devices around you. Instantly change displays, disable security systems, unlock electric doors, empty vending machines and ATMs, disable phones, and all sorts of other things. Much harder to sabotage high-level security devices.", grade: 'kaarn' },
    { id: 'weapon_sabotage', title: 'WEAPON SABOTAGE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/RTxcKHj0-a6.webp', description: "Sabotage enemy weaponry during battle! The difficulty of this depends on how many Weapon Points have been invested in said weapon. At worst, you may just cause it to shoot slightly slower or do slightly less damage; at best, you might cause it to jam up or even explode in the users hands!", grade: 'kaarn' },
    { id: 'digital_infiltrator', title: 'DIGITAL INFILTRATOR', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zhYYCKxZ-a7.webp', description: "These people really think their flimsy passwords are going to protect them? You're an expert at cracking computers, servers, databases, and hacking people's accounts and even entire websites. New security measures are being released every single day, though, so try to keep up with the arms race.", grade: 'kaarn' },
    { id: 'manual_override', title: 'MANUAL OVERRIDE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PZ30Dhcz-a8.webp', description: "{i}Requires {g}L33T H4XXOR.{/g}{/i} Instead of merely being able to sabotage things, your other powers can now take control of them. Turn security turrets against their own controllers, take remote control of mechs, vehicles, and enemy's weapons, and control every single byte of computers and phones.", requires: ['l33t_h4xx0r'], grade: 'purth' },
    { id: 'domain_master_ii', title: 'DOMAIN MASTER II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fzSgSGCg-a9.webp', description: "{i}Requires {w}Domain Master I.{/w}{/i} You're now more capable of taking on military-grade security devices. Disable security cameras and turrets, easily slip through sealed entrances and laser-grid security systems, and duck through facilities without setting off a single alarm.", requires: ['domain_master_i'], grade: 'kaarn' },
    { id: 'vehicle_sabotage', title: 'VEHICLE SABOTAGE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Fb2tFR8J-a10.webp', description: "Same as above. The more {i}Vehicle Points{/i} invested in a vehicle, the more difficult it is to sabotage. At worst, you can make it flash a few error screens and be a bit more difficult to control and drive; at best, you'll be able to suddenly shut off all steering, or cause internal damage that'll have to be repaired.", grade: 'kaarn' },
    { id: 'counter_hacker', title: 'COUNTER HACKER', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wZwL5LsV-a11.webp', description: "You're an expert at combat with other Avatars in the web, overloading their systems until they disappear completely. This is used either to defeat other hackers attempting to infiltrate your device, or to take down guard avatars who are personally defending systems you're trying to sabotage.", grade: 'kaarn' },
    { id: 'verse_hijack', title: 'VERSE HIJACK', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VcTqTNRp-a12.webp', description: "{i}Requires {bp}9R1M01R3.RPM.{/bp}{/i} You now have a backdoor into Nero Inc.'s software! You can attack verses in various ways, from uploading malware, causing natural disasters, shrinking their spread or area of effect, etc. However, they'll know the general area the attacks are coming from.", requires: ['9r1m01r3_rpm'], grade: 'sinthru' },
];

export const TECHNOMANCY_DATA_KO: ClosedCircuitsPower[] = [
    { id: 'domain_master_i', title: '연결망 지배자 I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/JF7DTbMf-a5.webp', description: "당신의 힘을 이용해 주변의 간단한 전자장비를 조작할 수 있게 됩니다. 디스플레이를 순식간에 바꾸거나, 보안 시스템을 해제하거나, 전자식 자물쇠를 열거나, 자판기나 ATM을 털거나, 휴대전화를 먹통으로 만들거나 하는 것들입니다. 보다 높은 등급의 보안이 걸려 있는 것들은 뚫기가 훨씬 어렵습니다.", grade: 'kaarn' },
    { id: 'weapon_sabotage', title: '무기 사보타주', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/RTxcKHj0-a6.webp', description: "전투 중에 상대방이 들고 있는 무기를 사보타주할 수 있습니다! 그 무기에 투자된 무기 점수가 많을수록 공작이 어려워집니다. 최악으로는 고작 연사 속도가 조금 느려지거나 피해량이 조금 줄어드는 선에서 끝나겠지만, 최선으로는 무기가 재밍되거나 상대의 손에서 폭발할 수도 있습니다!", grade: 'kaarn' },
    { id: 'digital_infiltrator', title: '디지털 침투자', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zhYYCKxZ-a7.webp', description: "고작 비밀번호 몇 자리 건다고 보호가 된다구요? 당신은 컴퓨터나 서버, 데이터베이스, 사용자 계정, 심지어 웹사이트 자체를 능숙하게 해킹할 수 있습니다. 다만 하루하루 새로운 보안 절차와 패치가 적용되고 있기 때문에, 뒤쳐지지 않으려면 나름대로 노력해야 할 겁니다.", grade: 'kaarn' },
    { id: 'manual_override', title: '수동 제어', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PZ30Dhcz-a8.webp', description: "{i}{g}근ㅣ트 해귀{/g}가 필요합니다.{/i} 당신의 능력은 단순한 사보타주를 넘어서 직접 조종에까지 미칩니다. 경비 포탑의 총구를 주인에게로 돌리고, 탈것이나 메카, 적들의 무기를 원격으로 조종하고, 컴퓨터나 휴대전화 속 프로세서도 마지막 1바이트까지 제어할 수 있습니다.", requires: ['l33t_h4xx0r'], grade: 'purth' },
    { id: 'domain_master_ii', title: '연결망 지배자 II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/fzSgSGCg-a9.webp', description: "{i}{w}연결망 지배자 I{/w}이 필요합니다.{/i} 당신은 군사시설에 사용되는 보안까지 뚫을 수 있게 됩니다. 감시 카메라나 경비 포탑을 무력화시키고, 잠긴 문이나 레이저 보안 시스템을 뚫고, 경보 하나 울리지 않고 각종 극비 시설에 침입할 수 있습니다.", requires: ['domain_master_i'], grade: 'kaarn' },
    { id: 'vehicle_sabotage', title: '탈것 사보타주', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Fb2tFR8J-a10.webp', description: "무기 사보타주와 비슷합니다. 탈것 점수가 많이 투자된 탈것일수록 공작이 어려워집니다. 최악으로는 에러 창이 몇 개 뜨거나 운전이 살짝 힘들어지는 수준에서 그치지만, 최선으로는 갑자기 모든 조종이 먹통이 되거나 내부 결함이 발생해 즉시 수리가 필요하게 될 수도 있습니다.", grade: 'kaarn' },
    { id: 'counter_hacker', title: '카운터 해커', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wZwL5LsV-a11.webp', description: "당신은 웹상에서 다른 아바타를 상대하는 일의 전문가입니다. 그들의 시스템을 과부하시켜 끝내 완벽히 소멸시키는 것이죠. 이 능력은 당신을 공격하려는 해커들을 물리치는 데 사용하거나, 당신이 공격하려는 시스템을 보호하는 경비 아바타들을 제압하는 데 사용할 수 있습니다.", grade: 'kaarn' },
    { id: 'verse_hijack', title: '가상 우주 하이재킹', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VcTqTNRp-a12.webp', description: "{i}{bp}9R1M01R3.RPM{/bp}이 필요합니다.{/i} 당신은 네로 주식회사에 접근할 수 있는 백도어 코드를 얻었습니다! 이제 가상 우주를 다양한 방법으로 공격할 수 있게 됩니다. 맬웨어를 주입하거나, 재해를 일으키거나, 영역을 축소시키는 것 이외에도 수많은 방법이 가능합니다. 하지만, 공격당하는 쪽에서도 공격의 대략적인 위치는 파악할 수 있을 겁니다.", requires: ['9r1m01r3_rpm'], grade: 'sinthru' },
];

export const NANITE_CONTROL_DATA: ClosedCircuitsPower[] = [
    { id: 'heavily_armed', title: 'HEAVILY ARMED', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HLP0j1R8-a13.webp', description: "Instead of holding your weapon in your hand, you can call upon any nanites in the area to conjoin in the shape of your weapon around one of your limbs, turning said limb into a cannon, sword, hammer, power fist, or what have you. Design it with {w}30 Weapon Points{/w} on the {i}Reference Page{/i}.", grade: 'kaarn' },
    { id: 'nanite_armor_i', title: 'NANITE ARMOR I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/svKCdq1T-a14.webp', description: "{i}Requires {y}Kyrotik Armor™.{/y}{/i} We here at Kyrotik vow to keep our customers safe so they may live another day and buy more products! To this end, with as little as a snap of your fingers, nanites will arrange themselves in the shape of a comfy bodysuit that massively boosts durability!", requires: ['kyrotik_armor'], grade: 'lekolu' },
    { id: 'nanite_armor_ii', title: 'NANITE ARMOR II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mrW6KLr8-a15.webp', description: "{i}Requires {y}Nanite Armor I{/y} and {g}Heavy Duty.{/g}{/i} A bit less comfortable, but fitting for those who want maximum protection! Your armor now has extra thick reinforced plates around certain vital areas that are nearly impenetrable by almost all attacks. They don't offer nearly 100% coverage, though.", requires: ['nanite_armor_i', 'heavy_duty'], grade: 'purth' },
    { id: 'nanite_armor_iii', title: 'NANITE ARMOR III', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HL5CpngK-a16.webp', description: "{i}Requires {g}Nanite Armor II{/g} and {r}Nanite Master.{/r}{/i} Takes the form of an extremely comfortable thin bodysuit, almost like a second skin. However, the kinetic energy of attacks directed at it simply ceases to exist, in flagrant disregard for the first law of thermodynamics. If a bullet is fired, it will suddenly lose all momentum an instant before hitting its target; even a tank shell will clatter to the ground without the wearer even feeling it. Thermal energy is also controlled, creating a pocket of safe and comfortable air around its wearer. Its offers immense defensive capabilities despite being so thin. It can also be made to change color and appearance instantly according to the wearer's whims; if they wish, it can even be made to resemble normal clothes. However, there will always be at least a few 'weak points' in the armor that a knowledgeable opponent can exploit; failing this, attacks that encompass the victim completely are second best in terms of effectiveness. In one case, after being subject to a nuclear blast at point-blank range, the wearer was completely disintegrated, but the suit was later recovered without so much as a single scratch.", requires: ['nanite_armor_ii', 'nanite_master'], grade: 'xuth' },
    { id: 'metal_skin', title: 'METAL SKIN', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4Z0WFgjN-a17.webp', description: "When your skin is penetrated, nanites will fill the wound and solidify, essentially patching it up and staunching any bleeding. As natural healing processes kick in, these patches will be replaced by healthy bodily cells, but in the meantime, they prevent blood loss or your wounds getting worse.", grade: 'kaarn' },
    { id: 'nanite_form', title: 'NANITE FORM', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/QvztGcdK-a18.webp', description: "You can trigger a couple minutes-long transformation in which nanites reconfigure your entire body into a robotic form. Design this form with {w}40 Beast Points{/w} on the {i}Reference Page{/i}, but the default category must be {w}Humanoid{/w} and you cannot select options marked with *.", grade: 'kaarn' },
    { id: 'grey_goo', title: 'GREY GOO', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/QjMHmKt0-a19.webp', description: "Just by concentrating on a nearby foe, you can have nearby nanites pick them apart molecularly. Near-instant death for mundanes, but mages are too durable to be affected beyond some pain. If they are already cut, however, those wounds will slowly be eaten away at and get larger and worse.", grade: 'kaarn' },
];

export const NANITE_CONTROL_DATA_KO: ClosedCircuitsPower[] = [
    { id: 'heavily_armed', title: '중무장', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HLP0j1R8-a13.webp', description: "무기를 손에 들고 싸우는 대신, 주변의 나나이트를 팔이나 다리에 둘러 신체와 일체화된 검, 대포, 망치, 파워 피스트 등등으로 변형시킬 수 있습니다. 무기의 세세한 특징은 참고 페이지에서 무기 점수 30점으로 디자인할 수 있습니다.", grade: 'kaarn' },
    { id: 'nanite_armor_i', title: '나나이트 갑옷 I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/svKCdq1T-a14.webp', description: "{i}{y}카이로틱 아머tm{/y}가 필요합니다.{/i} 저희 카이로틱에서는 모든 고객님들께서 더 많은 제품들을 구매하실 수 있도록 최고의 보호를 제공하겠습니다! 손가락 한 번만 튕기면 주변의 나나이트가 편안한 바디슈트 형태로 조합되어 최적의 방호를 제공합니다.", requires: ['kyrotik_armor'], grade: 'lekolu' },
    { id: 'nanite_armor_ii', title: '나나이트 갑옷 II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/mrW6KLr8-a15.webp', description: "{i}{y}나나이트 갑옷 I{/y}과 {g}중장갑{/g}이 필요합니다.{/i} 편안함은 약간 희생되었지만, 방어력을 극대화시킨 갑옷입니다. 당신의 갑옷에는 신체의 취약한 부분을 보호할 두꺼운 장갑판이 추가되었습니다. 거의 모든 공격에 뚫리지 않지만, 전신을 완벽하게 보호해 주지는 않는다는 것을 명심하세요.", requires: ['nanite_armor_i', 'heavy_duty'], grade: 'purth' },
    { id: 'nanite_armor_iii', title: '나나이트 갑옷 III', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HL5CpngK-a16.webp', description: "{i}{g}나나이트 갑옷 II{/g}와 {r}나나이트 달인{/r}이 필요합니다.{/i} 이 갑옷은 마치 두 번째 피부처럼 아주 얇고 편안한 바디슈트의 형태를 취합니다. 하지만, 갑옷에 닿는 모든 공격은 열역학 제 1법칙마저 무시하며 즉시 운동에너지를 잃어버립니다. 즉, 총알이 날아와도 갑옷에 닿기 직전에 모든 운동량을 잃어버리고, 전차 포탄도 착용자에게에게 아무 느낌도 주지 못한 채 땅으로 굴러떨어질 것입니다. 이 갑옷은 열에너지 또한 제어하며, 착용자 주변에 안전하고 편안한 공기층을 형성해 줍니다. 이 갑옷은 그 얇은 두께로는 상상이 되지 않는 극한의 방호력을 자랑합니다. 또한, 착용자가 원한다면 즉시 그 형태나 색상을 변형할 수 있고, 심지어는 평상복처럼 만들어 놓을 수도 있습니다. 하지만, 적절한 지식이 있는 상대라면 공략할 수 있는 '취약점'도 몇 군데 존재합니다. 취약점을 찾지 못한다면 갑옷을 입은 대상을 사방에서 둘러싸는 형태로 공격하는 것이 차선책입니다. 한 번은 착용자가 영거리에서 핵폭발에 휘말린 적이 있는데, 착용자는 그대로 증발당했지만 갑옷은 흠집 하나 나지 않은 채 회수되었다고 합니다.", requires: ['nanite_armor_ii', 'nanite_master'], grade: 'xuth' },
    { id: 'metal_skin', title: '금속 피부', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4Z0WFgjN-a17.webp', description: "피부에 상처를 입을 때마다 나나이트가 상처 부위를 틀어막아 지혈합니다. 상처가 자연적으로 치유되면 나나이트가 건강한 세포로 대체되긴 하지만, 치유 과정 동안에는 상처의 악화나 실혈을 막아 줄 겁니다.", grade: 'kaarn' },
    { id: 'nanite_form', title: '나나이트 형체', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/QvztGcdK-a18.webp', description: "몇 분 간의 변신 과정을 거쳐, 전신을 나나이트 로봇 형태로 바꿀 수 있습니다. 변신 형태는 참고 페이지에서 동물 점수 40점으로 디자인할 수 있지만, 반드시 인간형이어야 하고, *가 표기된 선택지는 고를 수 없습니다.", grade: 'kaarn' },
    { id: 'grey_goo', title: '회색 점액질', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/QjMHmKt0-a19.webp', description: "근방의 적에게 정신을 집중하면, 주변의 나나이트가 그를 분자 단위로 갉아먹게 할 수 있습니다. 일반인들은 거의 즉사하겠지만, 마녀들에게는 약간의 고통만 줄 수 있습니다. 대신, 이미 상처를 입은 상태라면, 상처가 천천히 잠식되며 더 커지고, 더 깊어집니다.", grade: 'kaarn' },
];
