
import type { CompellingWillSigil, CompellingWillPower } from '../../types';

export const ARABELLA_DATA = {
    title: "ARABELLA, DAUGHTER OF HOPE",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/V0242j3P-main5.webp",
    description: `The middle child of the family, and perhaps the most famous, or at least uncontroversial. She's appeared at various times throughout history to save all mankind whenever it needed her most, most notably leading Gohwood's Holy Knights during the war, so she's beloved by all but the most cynical souls and has become the {i}de facto{/i} mascot of mages in general. Believe me when I say Jipangu has made a {i}ton{/i} of cartoons about her. Unfortunately, I fear that deep down, Arabella has come to despise her own fame. I can always sense that she wishes she could just be a normal girl, and not have to spend eternity locked away in her gilded palace in Eden. The Mother reminds her that she serves the people best as a symbol; a beacon of hope, a watchful protector, a role model for them all to aspire to. Still... I've heard whispers she lets her moonlight disguised as a normal mage and go on adventures down on Earth, from time to time. Keep an eye out, and maybe, you just might meet her...
    
Her blessings are so straight-forward and pragmatic that many mages don't really bother to study anything beyond them. Stuff like throwing fireballs, conjuring familiars, brewing potions... you know, all the things that immediately spring to mind when you think 'magic'. Some hipsters laugh at this brand of magic for being 'boring' and 'soulless', but I think, deep down, they must regret having passed over such useful, fundamental spells...`
};

export const ARABELLA_DATA_KO = {
    title: "희망의 딸 아라벨라",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/V0242j3P-main5.webp",
    description: `아라벨라는 자매들 중 셋째이자 아마 가장 유명하고, 최소한 딱히 논란은 없는 존재입니다. 그녀는 과거에도 인류가 가장 필요로 할 때에 모습을 드러내 모두를 구하고는 했는데, 전쟁 중에 고흐우드의 성기사들을 직접 통솔했던 것이 가장 잘 알려져 있습니다. 그러니 가장 시니컬한 이들을 빼고는 모두들 아라벨라를 사랑하고, 그녀가 사실상 마법소녀들의 마스코트가 된 것도 놀랄 일은 아닙니다. 지팡구에 가 보면 아라벨라가 나오는 동인지가 한 트럭이에요. 하지만, 그녀 자신은 맘속으로 그 유명세를 싫어하는 것이 아닐까 그게 걱정됩니다. 그저 평범한 소녀가 되고 싶다는 그녀의 소망이, 에덴에 있는 황금 궁전에서 영원히 같혀 지내기 싫다는 바람이 항상 느껴지거든요. 어머니께서는 아라벨라가 이렇게 희망의 등대로, 항상 지켜보는 수호신으로, 모두의 롤 모델로 남아 주는 것이 가장 바람직하다고 말씀하시지만... 제가 듣기로는 아라벨라가 때때로 평범한 마법소녀로 변장하고 이 세계에서 모험을 즐기는 이중생활을 할 때 눈감아 주시기는 한다고 들었어요. 열심히 찾아보면 당신이 그녀를 마주칠 수도 있겠죠...

아라벨라의 축복은 아주 직접적이고 실용적입니다. 많은 마법소녀들이 그녀가 주는 축복 이상을 탐구할 필요성을 못 느끼는 경우가 많아요. 화염구를 던지고, 패밀리어를 소환하고, 마법약을 조제하고... '마법'하면 떠오르는 전형적인 이미지들이 모여 있으니까요. 몇몇 힙스터들은 이 부류의 마법들을 '노잼' 내지는 '영혼 없다'고 까내리지만, 그쪽도 속으로는 이렇게 쓸만한 기초 마법들을 건너뛴 걸 후회하고 있을 거에요...`
};

export const COMPELLING_WILL_DATA = {
    title: "THE BLESSING OF COMPELLING WILL",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VhFNX8k-main6.webp",
    description: `The second most basic Blessing by my estimation, this encompasses much of the direct means of dealing damage at a range, from fireballs to energy beams to just smacking things with your targets. While other may be of other more creative means of attacking that are as effective, having some tried-and-true basic attacks to fall back on can mean the difference between life and death in a pinch. Essentially, this Blessing encompasses the incredibly broad concept of 'mental manipulation of energy' -- a.k.a. telekinesis. This is useful even in regular day-to-day life: it's like having a dozen extra pairs of hands! Plus, once you start manipulating things on the atomic level, you can get very creative...
    
Explaining its historical significance would be difficult since this Blessing was used extensively in every conflict. A poll performed by Cauldron Magazine indicated that over 38% of mages specialize in this Blessing primarily.`
};

export const COMPELLING_WILL_DATA_KO = {
    title: "강렬한 의지의 축복",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/VhFNX8k-main6.webp",
    description: `저는 이게 두 번째로 기초적인 축복이라고 생각합니다. 원거리에서 직접적으로 피해를 줄 수 있는 대부분의 마법들이 포진해 있는데, 화염구나 에너지 빔이나 기차 집어던지기 같은 것들이에요. 더 효과적의고 창의적인 방법들이 물론 있지만, 이렇게 검증된 기초 공격 수단을 보험으로 가지고 있는 것은 절체절명의 순간에 생사를 가를 수 있답니다. 간단히 말하지면 이 축복은 '에너지의 정신적 조작' 이라는 아주 넓은 개념을 다룹니다. 줄여 말하면 염력이죠. 물론 일상 생활에서도 유용합니다. 마치 손이 열두 개쯤 더 있는 것 같을 거에요! 거기다가, 원자 단위의 조작을 할 수 있게 되면, 완전 이야기가 달라지죠...

이 축복의 역사적 중요성을 설명하는 건 쉽지 않아요. 웬만한 분쟁에는 다 등장했으니까요. 한 번 컬드론 잡지에서 설문 조사를 한 적이 있는데, 이 축복에 특화되어 있는 마녀들이 전체의 38%를 넘는다고 합니다.`
};

export const COMPELLING_WILL_SIGIL_TREE_DATA: CompellingWillSigil[] = [
    { id: 'manipulator', title: 'MANIPULATOR', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], benefits: { telekinetics: 1, metathermics: 1 } },
    { id: 'telekinetic_i', title: 'TELEKINETIC I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['manipulator'], benefits: { telekinetics: 1 } },
    { id: 'thermal_master', title: 'THERMAL MASTER', description: 'Unlocks Pyromaniac III and Ice Cold III', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['manipulator'], benefits: { metathermics: 2 }, unlocks: ['pyromaniac_iii', 'ice_cold_iii'] },
    { id: 'psycho', title: 'PSYCHO', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['telekinetic_i', 'thermal_master'], benefits: { telekinetics: 1, metathermics: 1 } },
    { id: 'thermosword', title: 'THERMOSWORD™', description: 'Unlocks Thermal Weaponry', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['telekinetic_i', 'thermal_master'], benefits: { metathermics: 1 }, unlocks: ['thermal_weaponry'] },
    { id: 'telekinetic_ii', title: 'TELEKINETIC II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['psycho'], benefits: { telekinetics: 1 } },
    { id: 'reality_bender', title: 'REALITY BENDER', description: 'Unlocks Subatomic Manipulation', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['telekinetic_ii'], benefits: { telekinetics: 1 }, unlocks: ['subatomic_manipulation'] },
];

export const COMPELLING_WILL_SIGIL_TREE_DATA_KO: CompellingWillSigil[] = [
    { id: 'manipulator', title: '조작자', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], benefits: { telekinetics: 1, metathermics: 1 } },
    { id: 'telekinetic_i', title: '염력 I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['manipulator'], benefits: { telekinetics: 1 } },
    { id: 'thermal_master', title: '열의 달인', description: '방화광 III과 한기 III 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['manipulator'], benefits: { metathermics: 2 }, unlocks: ['pyromaniac_iii', 'ice_cold_iii'] },
    { id: 'psycho', title: '정신확장', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['telekinetic_i', 'thermal_master'], benefits: { telekinetics: 1, metathermics: 1 } },
    { id: 'thermosword', title: '써모소드™', description: '열 병기 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['telekinetic_i', 'thermal_master'], benefits: { metathermics: 1 }, unlocks: ['thermal_weaponry'] },
    { id: 'telekinetic_ii', title: '염력 II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['psycho'], benefits: { telekinetics: 1 } },
    { id: 'reality_bender', title: '현실 왜곡사', description: '분자세계 조작 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['telekinetic_ii'], benefits: { telekinetics: 1 }, unlocks: ['subatomic_manipulation'] },
];

export const TELEKINETICS_DATA: CompellingWillPower[] = [
    { id: 'psychic_force_i', title: 'PSYCHIC FORCE I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PZwsqvSr-t1.webp', description: "You can telepathically exert incredible force on inorganic objects within a modest radius, enough to send a double-decker truck flying at a foe, or fire an armory's worth of guns at a foe simultaneously. The more mass you are affecting, the less precise you can be. Effect weakens with greater distance.", grade: 'kaarn' },
    { id: 'psychic_force_ii', title: 'PSYCHIC FORCE II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8gBhVJg7-t2.webp', description: "{i}Requires {w}Psychic Force I.{/w}{/i} Your psychic influence and range is doubled, allowing you to bring buildings down or toss a train at your enemy. You can also effectively change the direction or intensity of gravity within a sizable area. With great effort, you can briefly affect your enemy directly.", requires: ['psychic_force_i'], grade: 'kaarn' },
    { id: 'forcefield', title: 'FORCEFIELD', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TxM6PW00-t3.webp', description: "You can create a small spherical field that deflects against even the most powerful kinetic attacks. However, it can get exhausting to deflect multiple attacks, so you can't expect to just stand there and let your forcefield soak up an entire barrage. Best to use it only briefly to block individual moves.", grade: 'kaarn' },
    { id: 'subatomic_manipulation', title: 'SUBATOMIC MANIPULATION', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xK6ymNs9-t4.webp', description: "{i}Requires {r}Reality Bender.{/r}{/i} Your telekinetic powers are now precise enough to affect change on a molecular level. Of course, one problem persists: you still can't actually perceive individual atoms, much less individually manipulate them. However, your power is 'smart' enough to understand your intentions if performing the following actions:\n- Reverse entropy and stabilize radioactive materials (or vice versa).\n- Manipulate photons within a few meters to create detailed visual illusions.\n- Gradually change the structure or materials of inorganic objects being touched or held, even to the point of slowly creating or destroying matter.\n- Violate the Pauli Exclusion Principle and allow solid objects to phase through each other. For example, you can walk through a wall, or cause someone to sink into the concrete ground beneath them as if it were quicksand.\n- After a short period of deep concentration on an area, can spontaneously create, and then split, fissile nuclides in order to induce a micro-nuclear explosion equivalent to around 0.1 kilotons of TNT maximum. Don't stand too close!", requires: ['reality_bender'], grade: 'xuth' },
    { id: 'energy_channel', title: 'ENERGY CHANNEL', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/39gVtQw0-t5.webp', description: "This allows two abilities. First, you can throw basketball-sized glowing balls of energy from your hand at high speeds, which explode on impact. These aren't too powerful, but can be rapidly fired. The second is a high-powered, constant beam of energy. It's hard to hit, but devastating to its target.", grade: 'kaarn' },
    { id: 'aquatic_force', title: 'AQUATIC FORCE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/27wvHSZq-t6.webp', description: "You have a particular power over liquids. You can telekinetically move upwards of billions of gallons of water — enough to part the Red Sea, with enough effort! You can move smaller quantities at rapid speeds, sending bursts of water at foes with enough force to annihilate entire buildings.", grade: 'kaarn' },
    { id: 'sonic_boom', title: 'SONIC BOOM', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gn9v6g1-t7.webp', description: "After a few seconds' preparation, you can let out a massive burst of telekinetic force in all directions powerful enough to capsize a battleship and send a tank flying into the sky. Such power is released that it damages even yourself significantly, meaning it's best saved as a last-ditch attack or finisher.", grade: 'kaarn' },
];

export const TELEKINETICS_DATA_KO: CompellingWillPower[] = [
    { id: 'psychic_force_i', title: '염동력 I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PZwsqvSr-t1.webp', description: "적당한 거리 내에 있는 무기체에 정신적으로 힘을 투사할 수 있습니다. 2층 버스를 적에게 날리거나 무기고 하나를 채울 만한 총기들을 동시에 발사할 수 있을 정도입니다. 영향을 주는 대상의 질량이 커질수록 정밀도가 떨어지며, 거리가 멀어질수록 효과가 약해집니다.", grade: 'kaarn' },
    { id: 'psychic_force_ii', title: '염동력 II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8gBhVJg7-t2.webp', description: "{i}{w}염동력 I{/w}이 필요합니다.{/i} 당신의 염동력은 더욱 강화되어 건물을 통채로 무너뜨리거나 적들에게 기차를 던져 버릴 수도 있습니다. 또한 상당한 범위 내에서 중력의 방향이나 세기를 변화시킬 수도 있습니다. 힘을 최대한 끌어올리면 적들도 잠시나마 붙잡을 수 있습니다.", requires: ['psychic_force_i'], grade: 'kaarn' },
    { id: 'forcefield', title: '역장', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TxM6PW00-t3.webp', description: "작은 구형의 에너지장을 형성하여 아무리 강한 물리적 공격이라도 튕겨낼 수 있습니다. 하지만 공격을 여러 번 받아치면 몸에 무리가 오기 때문에, 가만히 서서 역장만으로 모든 공격을 받아내는 것은 좋은 생각이 아닙니다. 단발 공격이 들어오기 직전에 잠깐 활성화시켜 막아내는 방식이 가장 좋습니다.", grade: 'kaarn' },
    { id: 'subatomic_manipulation', title: '분자세계 조작', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/xK6ymNs9-t4.webp', description: "{i}{r}현실 왜곡사{/r}가 필요합니다.{/i} 당신의 염력은 분자 단위의 조작이 가능할 만큼 정밀해졌습니다. 물론 한 가지 문제는 있죠. 아무리 마법소녀라도 단일 원자를 조작하는 것은 고사하고 그것들을 볼 수도 없습니다. 하지만 당신이 원한다면 정확히 다음 행동들을 구사할 수 있게 됩니다:\n-엔트로피를 역전시키고, 방사능 물질을 안정화시킵니다. (역으로도 가능합니다)\n-몇 미터 내의 광자를 조작하여 아주 정교한 시각적 환상을 만들어냅니다.\n-당신과 접촉하고 있는 무기체의 구조나 조성을 천천히 변화시킵니다. 물질을 서서히 창조하거나 소멸시킬 수도 있습니다.\n-파울리 배타 원리를 무시하고 고체들이 서로를 투과할 수 있게 합니다. 가령 벽을 뚫고 걷는다거나, 콘크리트 바닥 위에 서 있는 사람을 모래늪에 빠진 것마냥 가라앉게 할 수 있습니다.\n-짧은 시간 동안 한 지역에 집중한 후, 핵자들을 생성, 분열, 충돌시켜 국소적으로 핵폭발을 일으킵니다. 폭발의 최대 위력은 TNT 0.1킬로톤에 상응합니다. 너무 가까이 가지 마세요!", requires: ['reality_bender'], grade: 'xuth' },
    { id: 'energy_channel', title: '에너지 집중', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/39gVtQw0-t5.webp', description: "두 가지 기술을 사용할 수 있게 됩니다. 먼저 손에서 농구공 크기의 빛나는 에너지탄을 고속으로 발사할 수 있습니다. 에너지탄은 목표에 닿으면 폭발하고, 위력이 대단하지는 않지만 연사할 수 있습니다. 다른 기술은 지속형 고출력 에너지 광선입니다. 맟추기는 힘들지만 위력은 파괴적이죠.", grade: 'kaarn' },
    { id: 'aquatic_force', title: '수류의 힘', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/27wvHSZq-t6.webp', description: "당신은 물을 특별히 잘 다룰 수 있습니다. 염력으로 수백억 리터의 물을 조종할 수 있는데, 노력만 한다면 홍해도 가를 수 있는 수준입니다! 소량의 물이라면 재빠르게 조종할 수 있습니다. 건물 정도는 부숴 버릴 수 있는 세기의 급류를 적들에게 쏘아 보낼 수 있는 것이죠.", grade: 'kaarn' },
    { id: 'sonic_boom', title: '소닉붐', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gn9v6g1-t7.webp', description: "몇 초 동안 마법을 준비한 후, 염력을 사방으로 방출합니다. 그 위력은 전함을 뒤집어 버리고 탱크를 저 하늘 높이 날려 버릴 수 있습니다. 시전자 자신도 큰 피해를 입기 때문에, 최후의 수단으로 아껴 놓거나 전투를 마무리하기 위해 사용하는 것이 좋을 겁니다.", grade: 'kaarn' },
];

export const METATHERMICS_DATA: CompellingWillPower[] = [
    { id: 'pyromaniac_i', title: 'PYROMANIAC I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/whthGWtP-t8.webp', description: "The most generic type of magic out there! Let waves of superheated air smash into your enemy, or billow out pillows of flame to surround them from all sides... or just throw a fireball. That works, too. Your fire is unnaturally hot but still doesn't do a ton of damage -- but it is very painful.", grade: 'kaarn' },
    { id: 'pyromaniac_ii', title: 'PYROMANIAC II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0yf69srk-t9.webp', description: "{i}Requires {w}Pyromaniac I.{/w}{/i} Combatants will have to keep their distance, for your flames are always growing of course, but only are they stronger, but you can manipulate greater amounts of fire in more precise ways, and even superheat your own body to the point it's painful just to be near you.", requires: ['pyromaniac_i'], grade: 'kaarn' },
    { id: 'pyromaniac_iii', title: 'PYROMANIAC III', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Ld8yvM4y-t10.webp', description: "{i}Requires {w}Pyromaniac II{/w} and {g}Thermal Master.{/g}{/i} Your flames are now even stronger, and you're like walking sun in combat, to the point the bullets melt in midair before even making it close. Such is your might that you can you can fill the battlefield with walls of flame, or call down devastating firestorms.", requires: ['pyromaniac_ii', 'thermal_master'], grade: 'purth' },
    { id: 'ice_cold_i', title: 'ICE COLD I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/S4FSZry2-t11.webp', description: "You can turn the battlefield into a miserable tundra that can slow, but that still won't do much to the average foe beyond distracting them. More effective is forming massive chunks and spikes of ice and hurling them at your foes at high speeds, or causing them to just up from the ground.", grade: 'kaarn' },
    { id: 'ice_cold_ii', title: 'ICE COLD II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jPX2LPPY-t12.webp', description: "{i}Requires {w}Ice Cold I.{/w}{/i} Not only is your ability to create and fire icy projectiles boosted tenfold, but you can now strike your opponent with gusts of super chilled air, partially freezing enemies and chipping away at their ability to fight. If they're weakened, you can freeze them in a block of ice!", requires: ['ice_cold_i'], grade: 'kaarn' },
    { id: 'ice_cold_iii', title: 'ICE COLD III', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/sJ6QSYB6-t13.webp', description: "{i}Requires {w}Ice Cold II{/w} and {g}Thermal Master.{/g}{/i} Anything that so much as nears you in combat will freeze solid nearly instantly, and you can create massive structures out of ice to capture your foes or hurl an entire glacier at an unlucky foe. Your breath alone is so cold it almost nears absolute zero.", requires: ['ice_cold_ii', 'thermal_master'], grade: 'purth' },
    { id: 'plasma_strike', title: 'PLASMA STRIKE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SXC6TcSb-t14.webp', description: "Project a bolt of lightning at a foe! Requires a lot of precision, so it's hard to hit quick targets. However, it's the real deal, with thunder that can be heard for miles, a surface of the sun, and powerful blinding light! It will take a few seconds to charge another bolt.", grade: 'kaarn' },
    { id: 'thermal_weaponry', title: 'THERMAL WEAPONRY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8qm4WL9-t15.webp', description: "{i}Requires {y}Thermosword.{/y}{/i} Have no fear, loyal customer! These little black rods may look useless, but they're actually channels for any thermal power you can pass through them into a weapon! Design a {w}Bladed Melee{/w} or {w}Blunt Melee{/w} for {w}30 Weapon Points{/w} on the {i}Reference Page{/i}.", requires: ['thermosword'], grade: 'lekolu' },
];

export const METATHERMICS_DATA_KO: CompellingWillPower[] = [
    { id: 'pyromaniac_i', title: '방화광 I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/whthGWtP-t8.webp', description: "가장 흔한 마법 중 하나입니다! 초고온의 열파로 적을 공격하거나, 사방에서 화염 기둥을 소환하거나... 아니면 그냥 화염구를 하나 던지거나요. 그것도 먹힌답니다. 당신이 소환하는 화염은 별나게 뜨겁지만 그렇게 파괴력이 강하지는 않습니다. 그래도 맞으면 정말 아파요.", grade: 'kaarn' },
    { id: 'pyromaniac_ii', title: '방화광 II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0yf69srk-t9.webp', description: "{i}{w}방화광 I{/w}이 필요합니다.{/i} 당신과 맞서는 자들은 불과 열기에 휩싸이지 않으려면 거리를 벌려야 할 겁니다. 화염의 위력이 강해질 뿐만 아니라, 능력을 더 광범위하고 정밀하게 다룰 수 있고, 당신을 중심으로 온도를 극도로 높여서 당신에게 다가오기만 한 상대에게 고통을 안겨 줄 수도 있습니다.", requires: ['pyromaniac_i'], grade: 'kaarn' },
    { id: 'pyromaniac_iii', title: '방화광 III', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Ld8yvM4y-t10.webp', description: "{i}{w}방화광 II{/w}와 {g}열의 달인{/g}이 필요합니다.{/i} 당신은 근접전 전문가에게는 악몽과도 같은 존재입니다. 전장 한가운데에 작열하는 태양이 놓인 것처럼, 총포탄이 당신에게 닿기 전에 녹여 버릴 수 있습니다. 당신의 힘은 너무나 강대해서 전장을 화염의 장벽으로 뒤덮어 버리거나, 파괴적인 화염 폭풍을 불러낼 수 있을 정도입니다.", requires: ['pyromaniac_ii', 'thermal_master'], grade: 'purth' },
    { id: 'ice_cold_i', title: '한기 I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/S4FSZry2-t11.webp', description: "당신은 전장을 영하 몇십 도의 눈보라로 뒤덮을 수 있습니다. 다만 평범한 마법소녀에게는 주의 분산 이상의 효과를 거두기는 어려울 겁니다. 보다 더 효과적인 활용법으로는 거대한 얼음 송곳들을 소환하여 적들에게 발사하거나, 땅 밑에서 얼음 칼날을 솟아나게 해 적들을 공격하는 것이 있겠죠.", grade: 'kaarn' },
    { id: 'ice_cold_ii', title: '한기 II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/jPX2LPPY-t12.webp', description: "{i}{w}한기 I{/w}이 필요합니다.{/i} 얼음을 소환하고 투사하는 당신의 능력이 열 배 강해집니다. 뿐만 아니라, 거센 한파로 적들을 타격하여 신체를 부분적으로 빙결시키고 전투력을 깎아먹을 수 있습니다. 약화된 적이라면 얼음 기둥 안에 가둬버릴 수도 있구요!", requires: ['ice_cold_i'], grade: 'kaarn' },
    { id: 'ice_cold_iii', title: '한기 III', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/sJ6QSYB6-t13.webp', description: "{i}{w}한기 II{/w}와 {g}열의 달인{/g}이 필요합니다.{/i} 전투 중에 당신에게 근접하는 모든 것들은 즉시 얼어붙어 버릴 겁니다. 손짓 한 번으로 거대한 얼음 조형물을 만들어낼 수도 있고, 불운한 적에게 거대 빙하를 던져 버릴 수도 있죠. 당신의 숨결 자체도 절대영도에 근접할 만큼 차갑습니다.", requires: ['ice_cold_ii', 'thermal_master'], grade: 'purth' },
    { id: 'plasma_strike', title: '플라즈마 타격', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SXC6TcSb-t14.webp', description: "적에게 번개 줄기를 발사합니다! 정밀도가 많이 필요하기 때문에 빠르게 움직이는 목표는 맞히기 어렵습니다. 하지만 그 온도는 태양 표면의 다섯 배에 달하고, 섬광은 눈이 순간적으로 멀어 버릴 정도에다가, 뒤따르는 천둥은 몇 킬로미터 밖에서도 모두가 들을 수 있을 정도입니다. 한 번 발사하면 다시 사용하기까지 충전 시간이 몇 초 필요합니다.", grade: 'kaarn' },
    { id: 'thermal_weaponry', title: '열 병기', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/8qm4WL9-t15.webp', description: "{i}{y}써모소드™{/y}가 필요합니다.{/i} 잘 오셨습니다, 고객님! 이 작은 검정 막대기들은 얼핏 보면 쓸모없어 보이지만, 당신이 가지고 있는 열과 냉기의 힘을 집중시켜 무기의 형태로 구현한답니다! 참고 페이지에서 근접 도검이나 근접 둔기를 하나 디자인할 수 있습니다. 무기 점수 30점이 주어집니다.", requires: ['thermosword'], grade: 'lekolu' },
];
