
import type { GraciousDefeatSigil, GraciousDefeatPower } from '../../types';

export const GRACIOUS_DEFEAT_DATA = {
    title: "THE BLESSING OF GRACIOUS DEFEAT",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/N6q8pdqh-main5.webp",
    description: `What a shame. Such a beautiful and fascinating blessing... marred by such a terrible history. The Sinthrus used it once to inflict the most horrid torments upon their enemies, nominally to make them endure the same torture they put the Child of God through. It is said that the {t}Broken Daughter{/t} was created this way — not that I should speak of such things...

Where some see tragedy, others see only opportunity. You see, verses are essentially tiny simulated universes existing in a sort of metaphysical 'orbit' around our own... and in the wake of the aforementioned nastiness, nobody wanted to touch them, so Nero Inc seized the opportunity to buy up all the real estate! Our reality only has so much processing power with which to handle all these verses, after all. But yeah, at the start, your verse is just going to be a simple, plain, flat black void. If you really want to spruce up the place, you're gonna have to cough up some dough...`
};

export const GRACIOUS_DEFEAT_DATA_KO = {
    title: "품위있는 패배의 축복",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/N6q8pdqh-main5.webp",
    description: `참으로 부끄러운 일입니다. 이렇게 아름답고도 우아한 축복이... 끔찍한 역사에 이용당하고 말았으니까요. 한때 신스루들이 적들에게 가장 끔찍한 고통을 주는 데 이 축복을 사용했다는 전례가 있습니다. 신스루들은 '그 아이'가 겪었던 고통을 똑같이 겪게 해 주겠다는 명분을 내세웠습니다. 이것이 {t}부서진 자매{/t}가 탄생한 배경이라고들 하는데 - 사실 이런 이야기는 꺼내서는 안 됩니다.

이 축복은 누군가에게는 비극이지만, 또 누군가에게는 기회이기도 합니다. 가상 우주들은 간단히 말하면 현실 우주 주변의 메타물리적인 궤도를 돌고 있는 아주 작은 모방 우주입니다... 그리고 앞선 흑역사 때문에 누구도 건드리려 하지 않았죠. 그래서 네로 주식회사에서 기화를 잡고 모든 가상 우주들을 선점했습니다. 사실 우리의 현실에는 모든 가상 우주들을 감당할 만한 처리 능력이 없기도 하구요. 뭐, 어쨌든, 당신이 관리하게 될 가상 우주는 처음에는 완전한 무의 공간으로 시작합니다. 그곳을 꾸미고 싶다면 적당한 예산 투자가 필요하겠죠...`
};

export const GRACIOUS_DEFEAT_SIGIL_TREE_DATA: GraciousDefeatSigil[] = [
    { id: 'gd_fireborn', title: 'FIREBORN', description: 'Your education into fire has begun.', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], type: 'Fireborn', benefits: { entrance: 1, features: 2 } },
    { id: 'cultivate_i', title: 'CULTIVATE I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['gd_fireborn'], type: 'Cultivate', benefits: { features: 1 } },
    { id: 'realmkeeper', title: 'REALMKEEPER™', description: 'Join hundreds of happy customers!', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['gd_fireborn'], type: 'Realmkeeper', benefits: { influence: 1, features: 2 } },
    { id: 'cultivate_ii', title: 'CULTIVATE II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['cultivate_i'], type: 'Cultivate', benefits: { features: 1 } },
    { id: 'strengthen_i', title: 'STRENGTHEN I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['realmkeeper'], type: 'Strengthen', benefits: { influence: 1 } },
    { id: 'sweet_suffering', title: 'SWEET SUFFERING', description: 'Unlocks Gathoth Puzzle', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['strengthen_i'], type: 'Sweet Suffering', benefits: { influence: 1 }, unlocks: 'gathoth_puzzle' },
    { id: 'realmmaster', title: 'REALMMASTER™', description: 'Unlocks Advanced Verse Package', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['strengthen_i'], type: 'Realmmaster', benefits: { influence: 1, features: 2 }, unlocks: 'advanced_verse_package' },
    { id: 'pocket_god', title: 'POCKET GOD', description: 'Unlocks Reality Invasion', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['realmmaster'], type: 'Pocket God', benefits: { influence: 1 }, unlocks: 'reality_invasion' },
    { id: 'strengthen_ii', title: 'STRENGTHEN II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['realmmaster'], type: 'Strengthen', benefits: { influence: 1 } },
];

export const GRACIOUS_DEFEAT_SIGIL_TREE_DATA_KO: GraciousDefeatSigil[] = [
    { id: 'gd_fireborn', title: '불의 아이', description: '이제 불 속으로 뛰어드는 법을 배울 시간입니다.', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], type: 'Fireborn', benefits: { entrance: 1, features: 2 } },
    { id: 'cultivate_i', title: '구축 I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['gd_fireborn'], type: 'Cultivate', benefits: { features: 1 } },
    { id: 'realmkeeper', title: '렐름키퍼™', description: '수많은 고객들과 함께하세요!', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['gd_fireborn'], type: 'Realmkeeper', benefits: { influence: 1, features: 2 } },
    { id: 'cultivate_ii', title: '구축 II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['cultivate_i'], type: 'Cultivate', benefits: { features: 1 } },
    { id: 'strengthen_i', title: '강화 I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['realmkeeper'], type: 'Strengthen', benefits: { influence: 1 } },
    { id: 'sweet_suffering', title: '달콤한 고통', description: '가토스의 퍼즐 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['strengthen_i'], type: 'Sweet Suffering', benefits: { influence: 1 }, unlocks: 'gathoth_puzzle' },
    { id: 'realmmaster', title: '렐름마스터™', description: '고급 가상 우주 패키지 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['strengthen_i'], type: 'Realmmaster', benefits: { influence: 1, features: 2 }, unlocks: 'advanced_verse_package' },
    { id: 'pocket_god', title: '소우주의 신', description: '현실 침범 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['realmmaster'], type: 'Pocket God', benefits: { influence: 1 }, unlocks: 'reality_invasion' },
    { id: 'strengthen_ii', title: '강화 II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['realmmaster'], type: 'Strengthen', benefits: { influence: 1 } },
];

export const ENTRANCE_DATA: GraciousDefeatPower[] = [
    { id: 'painted', title: 'PAINTED', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/hxwxmbjT-d1.webp', description: "You painted your verse into existence. Quite an awe-inspiring work, too; even not knowing its true nature, people find themselves drawn to its mesmerizing aura. Getting to your verse is as easy as jumping headlong into your painting. Just be careful not to let it get lost or burn up!", grade: 'kaarn' },
    { id: 'momento', title: 'MOMENTO', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/v64y1fmx-d2.webp', description: "You verse is based upon a treasured memory. Thus, a momento can be used to temporarily open a portal that anybody can exit and enter through. This requires a ritual that takes much less time than {i}Within{/i}, but much more than {i}Painted{/i}. At least the momento can be a lot more durable and hideable.", grade: 'kaarn' },
    { id: 'within', title: 'WITHIN', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GvLyQ4Bq-d3.webp', description: "Your verse exists within yourself; therefore, there's no chance of it getting lost or destroyed, unless you forget about it. However, it will require hours of deep, serious meditation and introspection to enter. To visit, others will have to do the same while making physical contact with you.", grade: 'kaarn' },
    { id: 'gathoth_puzzle', title: 'GATHOTH PUZZLE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GLJBWxz-d4.webp', description: "{i}Requires {bp}Sweet Suffering.{/bp}{/i} During the Sinthru Doctrine, this was the only way to enter verses. To enter your verse, a puzzle box must be solved; if you can fool or force someone into solving the puzzle, it will be extremely difficult for them to escape from your verse unless you let them out.", requires: ['sweet_suffering'], grade: 'sinthru' },
];

export const ENTRANCE_DATA_KO: GraciousDefeatPower[] = [
    { id: 'painted', title: '그림', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/hxwxmbjT-d1.webp', description: "당신은 그림을 그려서 가상 우주를 창조했습니다. 그 그림 자체도 충분히 감탄을 자아내는 수작인지라, 그림의 실체를 모르는 사람들도 홀리듯이 다가오고는 합니다. 그냥 당신의 그림에 머리부터 뛰어든다면 당신의 가상 우주로 들어갈 수 있을 겁니다. 대신 그림이 분실되거나 불타지 않게 조심하세요!", grade: 'kaarn' },
    { id: 'momento', title: '상징물', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/v64y1fmx-d2.webp', description: "당신의 가상 우주는 당신만의 소중한 기억을 토대로 하고 있습니다. 그 기억과 관련된 특별한 물건을 사용해서 짧은 시간 동안 가상 우주와 통하는 포탈을 열 수 있습니다. 모든 사람들이 포탈을 이용할 수 있습니다. 포탈을 열고 가상 우주로 들어가는 시간은 내재보다는 훨씬 짧지만, 그림보다는 훨씬 깁니다. 그래도 그림보다는 훨씬 튼튼하고 숨기기도 쉬운 물건을 이용할 수 있으니까요.", grade: 'kaarn' },
    { id: 'within', title: '내재', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GvLyQ4Bq-d3.webp', description: "당신의 가상 우주는 당신 자신의 내면 세계에 존재합니다. 따라서 당신이 잊지 않는 한 파괴되거나 소실되지 않습니다. 하지만, 몇 시간 동안 깊이 명상과 사색을 해야 당신의 가상 우주로 발을 들일 수 있습니다. 다른 사람들이 당신의 가상 우주에 들어오려면 당신과 접촉하고 있는 상태에서 같이 명상을 해야 하구요.", grade: 'kaarn' },
    { id: 'gathoth_puzzle', title: '가토스의 퍼즐', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/GLJBWxz-d4.webp', description: "{i}{bp}달콤한 고통{/bp}이 필요합니다.{/i} 신스루 대원칙이 적용되던 시절에는 이 방법을 통해서만 가상 우주로 들어갈 수 있었습니다. 가상 우주에 들어가기 위해서는 퍼즐 상자를 하나 풀어내야 합니다. 만약 다른 사람을 속이거나 협박해서 퍼즐을 풀게 한다면, 그들은 당신의 가상 우주에 갇히게 됩니다. 당신이 직접 풀어 주지 않는 이상 탈출하는 것은 거의 불가능하지요.", requires: ['sweet_suffering'], grade: 'sinthru' },
];

export const FEATURES_DATA: GraciousDefeatPower[] = [
    { id: 'natural_environment', title: 'NATURAL ENVIRONMENT', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/b8HvHJr-d5.webp', description: "Adds 30 acres of any sort of wilderness you want to your verse. Doesn't even have to make geological sense, really. Just go nuts! You won't have to deal with any of the downsides to environments you pick, either. Not very big, but can be taken multiple times; each time, it doubles the acreage.", grade: 'kaarn' },
    { id: 'artificial_environment', title: 'ARTIFICIAL ENVIRONMENT', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PzZBpstp-d6.webp', description: "Adds 30 acres of any sort of civilized area you want to your verse. From cities, to towns, to scattered buildings, all fitting in with the environment. If you have no real inhabitants, though, it will all be abandoned. Not very big, but can be taken multiple times; each time, it doubles the acreage.", grade: 'kaarn' },
    { id: 'shifting_weather', title: 'SHIFTING WEATHER', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/C5qzYThh-d7.webp', description: "By default, your verse will be one of endless night on a cloudless day with a mild temperature. With this, you can shake things up a bit. You can stick to realistic weather events, or go crazy with it. Want to watch a supernova in the sky every night? A volcano that erupts lightning instead of lava?", grade: 'kaarn' },
    { id: 'living_inhabitants', title: 'LIVING INHABITANTS', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/pvGVPyr8-d8.webp', description: "Adds a new species of native life to your verse. Can choose between two species types: very highly populated ones, who you can design with {w}40 Beast Points{/w}, or rarer ones with fewer individuals, which you can design with {w}70 Beast Points{/w} on the {i}Reference Page{/i}. Can be taken multiple times.", grade: 'kaarn' },
    { id: 'broken_space', title: 'BROKEN SPACE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1hXCpyN-d9.webp', description: "The environments you create within your verse are unbound by laws of physics and reason. Create a place that folds in on itself, twisting upside down in places and sideways in others, or etc. Note that it affects where you're immediately standing, so you cannot make it impossible to survive or navigate.", grade: 'kaarn' },
    { id: 'broken_time', title: 'BROKEN TIME', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TMd0WRBT-d10.webp', description: "Time is all subjective, you know. This feature lets you choose how time moves differently from the 'real' world. This can range from a day in the verse being a week in real time, or vice versa. You can also set it to vary depending on one's location within the verse, or even from person to person.", grade: 'kaarn' },
    { id: 'promised_land', title: 'PROMISED LAND', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Sj84yc9-d11.webp', description: "Verses are resource intensive things, and there's only so much processing power to go around. By default, only around 15 other people can visit your verse at the same time before serious errors will occur. This option can be taken multiple times; each time, it doubles the population limit of your verse.", grade: 'kaarn' },
    { id: 'verse_attendant', title: 'VERSE ATTENDANT', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G3PrvJXy-d12.webp', description: "Adds a human caretaker to your verse, charged with keeping things tidy in your stead while you are away. You can design them with {w}50 Companion Points{/w} on the {i}Reference Page{/i}. Not too practical, but it will be nice to see a friendly face every time you visit. Can be taken multiple times.", grade: 'kaarn' },
];

export const FEATURES_DATA_KO: GraciousDefeatPower[] = [
    { id: 'natural_environment', title: '자연적 환경', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/b8HvHJr-d5.webp', description: "12헥타르 면적의 자연을 당신의 가상 우주에 추가합니다. 딱히 지질학적 고증 같은 건 생각할 필요가 없습니다. 마음대로 하세요! 당신이 고른 지형이나 환경의 단점을 고려할 필요도 없습니다. 주어지는 면적이 넓지는 않지만, 이 선택지는 여러 번 고를 수 있고, 고를 때마다 주어지는 면적이 두 배 증가합니다.", grade: 'kaarn' },
    { id: 'artificial_environment', title: '인공적 환경', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/PzZBpstp-d6.webp', description: "12헥타르 면적의 문명화된 지역을 당신의 가상 우주에 추가합니다. 도시나 마을, 여기저기 흩어진 건물, 모두 상관없습니다. 다만 그곳에 아무도 상주하지 않는다면 그냥 버려진 지역이 될 것입니다. 주어지는 면적이 넓지는 않지만, 이 선택지는 여러 번 고를 수 있고, 고를 때마다 주어지는 면적이 두 배 증가합니다.", grade: 'kaarn' },
    { id: 'shifting_weather', title: '기상이변', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/C5qzYThh-d7.webp', description: "아무 설정을 하지 않는다면, 당신의 가상 우주는 적당한 기온에, 하늘은 구름 한 점 없고, 해가 뜨지 않습니다. 이 능력이 있으면 상황을 좀 바꿔 놓을 수 있죠. 현실적인 날씨 변화만 일으킬 수도 있고, 온갖 것들을 시도할 수도 있습니다. 매일 밤 초신성 폭발을 볼 수도 있고, 용암 대신 번개를 뿜어내는 화산을 만들 수도 있죠.", grade: 'kaarn' },
    { id: 'living_inhabitants', title: '우주의 마수', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/pvGVPyr8-d8.webp', description: "당신의 가상 우주에 머물게 될 새로운 종족을 만듭니다. 그 수가 매우 많은 종족이라면 {w}동물 점수 40점{/w}을 이용해 디자인할 수 있습니다. 수가 적은 희귀종이라면 {w}동물 점수 70점{/w}을 이용해 디자인할 수 있습니다. 이 선택지는 여러 번 고를 수 있습니다.", grade: 'kaarn' },
    { id: 'broken_space', title: '뒤틀린 공간', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1hXCpyN-d9.webp', description: "당신의 가상 우주 내부의 환경은 모든 물리와 이성의 법칙을 무시합니다. 스스로 접혀들어가는 장소를 만들 수도 있고, 위아래나 양 옆이 배배 꼬인 장소를 만들 수도 있습니다. 다만 당신이 차지하는 공간은 영향을 받지 않기 때문에, 길을 찾거나 살아남는 것이 불가능한 가상 우주를 만들 수는 없습니다.", grade: 'kaarn' },
    { id: 'broken_time', title: '뒤틀린 시간', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TMd0WRBT-d10.webp', description: "알다시피 시간은 상대적입니다. 이 능력으로는 당신의 가상 우주 내 시간의 흐름을 현실 시간과 비교해 설정할 수 있습니다. 가령 가상 우주 내의 하루가 현실의 1주일과 같게 할 수도 있고, 그 역으로도 가능합니다. 또한, 가상 우주 내의 지역별로, 아니면 가상 우주를 방문한 사람들마다 시간의 흐름을 다르게 할 수도 있습니다.", grade: 'kaarn' },
    { id: 'promised_land', title: '약속의 땅', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Sj84yc9-d11.webp', description: "가상 우주는 수많은 리소스가 투입되기 때문에 처리 능력이 제한됩니다. 따라서 기본적으로는 당신의 가상 우주에 최대 15명의 방문자만 들일 수 있고, 그 이상이 되면 치명적인 오류가 발생합니다. 이 선택지는 여러 번 고를 수 있고, 고를 때마다 방문자 제한을 두 배 늘려 줍니다.", grade: 'kaarn' },
    { id: 'verse_attendant', title: '가상 우주 관리자', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G3PrvJXy-d12.webp', description: "당신이 부재중일 때 가상 우주를 맡아 관리할 인간 관리자를 추가합니다. {w}동료 점수 50점{/w}이 주어지고, 참고 페이지에서 디자인할 수 있습니다. 아주 실용적이지는 않지만, 가상 우주에 들어갈 때마다 반갑게 맞아 주는 누군가가 있다면 참 좋겠죠. 이 선택지는 여러 번 고를 수 있습니다.", grade: 'kaarn' },
];

export const INFLUENCE_DATA: GraciousDefeatPower[] = [
    { id: 'advanced_verse_package', title: 'ADVANCED VERSE PACKAGE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BKqYq4hV-d13.webp', description: "{i}Requires {y}Realmmaster™.{/y}{/i} We here at Nero Inc want you to feel the power of a God at your fingertips! With this package, your verse will no longer be static; you'll be able to change the landscape, weather, and everything else with your thoughts alone! You will truly be its undisputed master!", requires: ['realmmaster'], grade: 'lekolu' },
    { id: 'summon_creature', title: 'SUMMON CREATURE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cKMXwGFS-d14.webp', description: "{i}Requires {w}Living Inhabitants.{/w}{/i} Open portals just long enough to summon a few monsters native to your verse into the 'real' world! Unlike your familiar, you will be able to summon multiple before they'll be forced to return to their realm.", requires: ['living_inhabitants'], grade: 'kaarn' },
    { id: 'summon_attendant', title: 'SUMMON ATTENDANT', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cSZKpWTK-d15.webp', description: "{i}Requires {w}Verse Attendant.{/w}{/i} Open portals to allow your attendant to move between your verse and the real world. She will be obligated to act according to your whims, and will be invested in protecting you and the verse. Similarly to creatures, she can only stick in the 'real' world for a few hours.", requires: ['verse_attendant'], grade: 'kaarn' },
    { id: 'reality_invasion', title: 'REALITY INVASION', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/23CzLcNp-d16.webp', description: "{i}Requires {r}Pocket God.{/r}{/i} Everywhere you go, nearby environmental conditions change to reflect those in your verse; for example, if your verse is a desert, things become warmer and arid. Stay in a place for long enough, and you can create Versestones to open tears in reality through which your verse will begin to leak. They always have to be visible and out in the open. Your verse's landscape will appear in reality in slowly growing spheres around each tear; these spheres will be considered part of your verse, and thus, your creatures and attendant can roam freely there, and your godlike powers have full sway. These spheres of influence can be destroyed by destroying the Versestones in their centers, which can be done using long-ranged attacks unless the sphere has already spread massively. Thus, many mages aim to nip any tears in the bud before they get too big to destroy easily. The closer you are to tears in reality, the easier it is to open portals to your verse, allowing spells like {w}Summon Creature{/w} to be done faster and in greater numbers. Tears in reality also act as portals, making it much easier to enter and exit your verse. The more your influence spreads in reality, the bigger and more powerful your verse itself will become.", requires: ['pocket_god'], grade: 'xuth' },
    { id: 'summon_weather', title: 'SUMMON WEATHER', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4RmNGH7s-d17.webp', description: "{i}Requires {w}Shifting Weather.{/w}{/i} Create chaos by opening dozens of tiny portals to flood the battlefield with a weather event from your verse! Bursts of lightning from a megastorm? Flows of lava from a volcano? Sky's the limit. Not targeted, so better for area control than direct combat.", requires: ['shifting_weather'], grade: 'kaarn' },
    { id: 'overlord', title: 'OVERLORD', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/b5NzzRdS-d18.webp', description: "While within the boundaries of your Verse, you not only have control of the world around you, but your own form. You assume a godlike shape while within your verse, which you can design with {w}Infinite Beast Points{/w} on the {i}Reference Page{/i}, excluding any options marked with a *.", grade: 'kaarn' },
    { id: 'soul_harvest', title: 'SOUL HARVEST', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5hcgQpXy-d19.webp', description: "{i}Requires {bp}Gathoth Puzzle.{/bp}{/i} Ordinarily, no visitors can die in your verse; they will merely respawn. With this, death for them is permanent, though it is for you, too, if they fight back. Killing mages in particular in your realm will cause it to grow in size and boost the strength of your influences.", requires: ['gathoth_puzzle'], grade: 'sinthru' },
];

export const INFLUENCE_DATA_KO: GraciousDefeatPower[] = [
    { id: 'advanced_verse_package', title: '고급 가상 우주 패키지', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/BKqYq4hV-d13.webp', description: "{i}{y}렐름마스터™{/y}이 필요합니다.{/i} 네로 주식회사에서는 당신에게 신이 된 듯한 기분을 선사합니다! 이 패키지가 있으면 당신의 가상 우주는 더 이상 정적으로 남지 않습니다. 당신의 생각만으로 지형, 날씨, 그 외 모든 것을 뒤바꿀 수 있습니다! 진정한 세계의 지배자가 되는 것이죠!", requires: ['realmmaster'], grade: 'lekolu' },
    { id: 'summon_creature', title: '마수 소환', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cKMXwGFS-d14.webp', description: "{i}{w}우주의 마수{/w}가 필요합니다.{/i} 잠시 동안 포탈을 열어, 당신의 가상 우주에 사는 마수 몇 마리를 '현실' 세계로 소환할 수 있습니다! 패밀리어와는 다르게 한 번에 여러 마리의 마수를 부릴 수 있지만, 몇 시간이 지나면 당신의 가상 우주로 돌아가게 됩니다.", requires: ['living_inhabitants'], grade: 'kaarn' },
    { id: 'summon_attendant', title: '관리자 소환', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/cSZKpWTK-d15.webp', description: "{i}{w}가상 우주 관리자{/w}가 필요합니다.{/i} 포탈을 열어 당신의 관리자가 가상 우주와 현실을 오고 갈 수 있게 합니다. 관리자는 당신의 명령에 따르며, 당신과 가상 우주를 보호하는 데 주력합니다. 마수들과 마찬가지로 현실 세계에서는 몇 시간밖에 있을 수 없습니다.", requires: ['verse_attendant'], grade: 'kaarn' },
    { id: 'reality_invasion', title: '현실 침범', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/23CzLcNp-d16.webp', description: "{i}{r}소우주의 신{/r}이 필요합니다.{/i} 당신이 가는 곳마다 주변 환경이 당신의 가상 우주를 반영하는 방향으로 변화합니다. 가령 가상 우주가 사막이라면 주변 기온이 올라가고 건조해지는 식입니다. 한 장소에 오래 머무른다면, 우주석을 만들어 현실에 균열들을 내고 가상 우주와 이어지게 할 수 있습니다. 우주석은 모습을 숨길 수 없고, 개방된 장소에 있어야 합니다. 각 균열 주변에 당신의 가상 우주가 구형의 형태로 나타나서 점점 팽창합니다. 이 구형 영역 내부는 당신의 가상 우주로 판정되기 때문에 관리자나 마수들이 자유롭게 있을 수 있고, 당신의 능력 또한 십분 발휘할 수 있습니다. 이 영역을 파괴하기 위해서는 영역 중심부의 우주석을 없애야 하는데, 팽창이 너무 많이 진행되지 않았다면 원거리 공격을 동원해 처리할 수 있습니다. 이 때문에 대부분의 마녀들은 현실에 균열이 나타난다면 처리가 어려워지기 전에 빠르게 진화하려고 노력합니다.\n\n당신이 현실의 균열에 가까이 있으면 있을수록 당신의 가상 우주로 통하는 포탈을 더욱 쉽게 열 수 있습니다. 즉, 마수 소환과 같은 마법을 더 빠르게, 대규모로 시전할 수 있게 됩니다. 또한, 이 균열들을 포탈로 활용해 당신의 가상 우주를 더 쉽게 드나들 수 있습니다. 가상 우주가 현실에 더 많은 영향을 줄수록 가상 우주는 더 강대해지게 됩니다.", requires: ['pocket_god'], grade: 'xuth' },
    { id: 'summon_weather', title: '기상 확산', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4RmNGH7s-d17.webp', description: "{i}{w}기상이변{/w}이 필요합니다.{/i} 수십 개의 작은 포탈을 열어, 당신의 가상 우주에서 나타나는 기상 현상으로 전장을 뒤덮습니다! 초거대 폭풍에서 번개가 내리칠 수도 있고, 화산에서 용암이 폭발할 수도 있습니다. 한계는 전혀 없습니다. 다만 목표를 지정할 수는 없기 때문에 직접 전투보다는 전장 장악에 효과적입니다.", requires: ['shifting_weather'], grade: 'kaarn' },
    { id: 'overlord', title: '최고존엄', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/b5NzzRdS-d18.webp', description: "가상 우주 내부에서 당신의 권능은 당신 자신의 육체에까지 미칩니다. 가상 우주 내부에서 신적인 형상을 취할 수 있습니다. 참고 페이지에서 동물 점수를 무한히 사용하여 신적인 형상을 디자인할 수 있습니다. 단, *가 표기된 선택지는 제외됩니다.", grade: 'kaarn' },
    { id: 'soul_harvest', title: '영혼 수확', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5hcgQpXy-d19.webp', description: "{i}{bp}가토스의 퍼즐{/bp}이 필요합니다.{/i} 일반적으로는 당신의 가상 우주를 방문한 이들은 죽게 된다면 곧바로 되살아날 뿐입니다. 하지만, 이 능력이 있으면 가상 우주에서도 영원한 죽음을 맞게 됩니다. 다만, 당신도 포함되기 때문에 그들의 저항을 조심해야 합니다. 가상 우주 안에서 마녀들을 죽인다면, 당신의 가상 우주가 확장되고 그 영향의 효과도 증가합니다.", requires: ['gathoth_puzzle'], grade: 'sinthru' },
];
