
import type { LostHopeSigil, LostHopePower } from '../../types';

export const FIDELIA_DATA = {
    title: "FIDELIA, DAUGHTER OF UNDERSTANDING",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ZR57tp80-main2.webp",
    description: `The middle child among the Daughters, and by far the most mysterious and mired in rumors. Even I only rarely see her emerge from the Twilight Palace up in the Garden. Yet, at the same time, she is also the most likely to personally connect with her followers, with many reporting her appearing to them in times of great need or visiting them in their dreams. This personableness has led her to fame... and scandals. As the Sinthru covens ravaged the land, outrage spread over revelations that she'd been seen consorted with high-ranking coven members before the revolt, to the point of being Elvira's lover. And she was always the Daughter who felt the most sympathy for the Child of God...
    
Of course, the official position is that she was never involved with the Sinthru covens, and is actually just misunderstood — she is, after all, something of a patron saint for misunderstood mages. She oversees all the magic with dreadful and dark reputations — such as necromancy — but which actually hold great beauty and utility, and she supports all those who are maligned or mistreated for failing to conform to society's standards. Her campaigns have been very successful over the millenia, and now, people tend to be very accepting of even the most extreme of differences. So really, there's no need to believe those silly rumors! She's such a kind girl, it kills me to see her plagued by all these silly conspiracy theories. Especially {i}all of{/i} those absurd ones about her sealing away an entire Blessincxvqmeuywitpdrrinbojkgt.`
};

export const FIDELIA_DATA_KO = {
    title: "오성의 딸 피델리아",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ZR57tp80-main2.webp",
    description: `피델리아는 자매들 중 셋째이자 가장 신비하고 소문투성이인 존재입니다. 저조차도 그녀가 에덴의 정원 속에 있는 자기의 황혼 궁전에서 나오는 모습을 거의 본 적이 없어요. 하지만, 자매들 중에는 추종자들과 가장 많은 접촉을 하는 존재이기도 합니다. 수많은 이들이 절체절명의 순간에 피델리아의 모습을 보았다거나, 그들의 꿈 속에 그녀가 찾아왔다고 말하고는 합니다. 피델리아는 이런 성격 덕분에 꽤 유명해졌고... 수많은 스캔들의 대상이 되기도 했습니다. 신스루 마녀단들이 이 땅을 횡행할 때, 피델리아가 마녀단의 간부들과 일찍이 내통하는 사이였다는 이야기가 돌기도 했었고, 심지어는 고위 리치 엘비라와 연인 사이였다는 말도 나왔습니다. 게다가 신의 아이를 가장 많이 동정했던 자매이기고 했고...

물론 공식적인 입장을 말씀드리면 피델리아는 신스루 마녀단과 전혀 관련이 없습니다. 그냥 오해일 뿐이죠. 사실 피델리아는 모든 오해받는 마법소녀와 마녀들의 수호성인 같은 존재입니다. 피델리아가 관장하는 마법들은 강령술과 같이 비록 평판은 나쁘지만 특유의 아름다움과 유용성을 간직하고 있고, 그녀 자신도 사회의 기준에 맞추지 못한다는 이유로 음해와 비방에 시달리는 이들을 돕고 있습니다. 지난 천 년간 이어져 온 그녀의 노력이 헛되지 않았는지, 이제 사람들은 꽤 극단적인 차이도 포용해 주는 경우가 많습니다. 그러니 아까 그 바보같은 소문을 믿을 이유는 없는 셈이죠! 이렇게 친절한 피델리아가 온갖 음모론의 희생양이 되는 모습이 참 마음이 아프네요. 특히 그 말도 안되는, 피델리아가 축복 하나를 아예 봉인해버ㄹㅊㅋㅍㅌㅂ고뎌ㅛ지세으ㅜㅠㅐㅓㅏ햘ㄴㅁ`
};

export const LOST_HOPE_DATA = {
    title: "THE BLESSING OF LOST HOPE",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/607svvK8-main3.webp",
    description: `Death is basically hardcoded into our reality; once the data that once composed a person's psyche is overwritten (which only takes a matter of hours) it cannot be regained. However, certain strange phenomena blur the lines between life and death, the most famous of which being spirits. These spirits aren't the full-fledged person, but a sort of psychic echo, like the residue of all their emotions and experiences left in the halls of time, with an origin akin to Distortions. As our reality destabilizes, these spirits become more prominent, and those who control them more powerful.
    
Further research into this discipline has yielded means of imbuing those spirits into corpses in order to create creatures somewhere in between the boundaries of life and death. Even the most advanced of these grotesque creatures cannot be exactly the same person they used to be, and their new personalities trend towards being more... macabre.`
};

export const LOST_HOPE_DATA_KO = {
    title: "잃어버린 희망의 축복",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/607svvK8-main3.webp",
    description: `죽음은 우리의 삶에 하드코딩되어 있습니다. 한 사람을 정의하는 데이터가 고작 몇 시간 만에 덮어씌워지면 다시는 되찾을 수 없죠. 하지만, 생사의 경계를 넘는 몇몇 이상현상들도 분명 존재합니다. 가장 유명한 것이 바로 우리가 혼령이라고 부르는 존재들이지요. 이들은 완전한 인간이 아니라 정신의 메아리에 가깝습니다. 시간의 궁전 속에 남겨진 모든 잔류 사념과 경험의 집합체로, 어찌 보면 왜곡체와 근원이 비슷하지요. 현실의 불안정성이 커질수록, 영혼들의 존재감도 커지고 그들을 부릴 수 있는 마녀들의 힘도 더욱 강력해집니다.

이 분야를 더욱 깊이 파고든 자들은 이 영혼들을 시체에 빙의시켜 삶과 죽음 사이 어딘가에 있는 창조물들을 만들어 내는 법을 알아냈습니다. 이 괴이들은 아무리 발전된 마법으로 창조되더라도 생전의 인격과 완전히 같아질 수는 없으며, 보통 더... 음산한 성정을 지니게 되는 경우가 많습니다.`
};

export const LOST_HOPE_SIGIL_TREE_DATA: LostHopeSigil[] = [
    { id: 'young_witch', title: 'YOUNG WITCH', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], type: 'Young Witch', benefits: { channeling: 2 } },
    { id: 'spirit_channel', title: 'SPIRIT CHANNEL', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['young_witch'], type: 'Spirit Channel', benefits: { channeling: 1 } },
    { id: 'deadseer', title: 'DEADSEER', description: 'Unlocks Life Drain', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['young_witch'], type: 'Deadseer', benefits: { channeling: 1 }, unlocks: 'life_drain' },
    { id: 'necromancer', title: 'NECROMANCER', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['spirit_channel'], type: 'Necromancer', benefits: { necromancy: 1 } },
    { id: 'forbidden_arts_i', title: 'FORBIDDEN ARTS I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['deadseer'], type: 'Forbidden Arts', benefits: { blackMagic: 1 } },
    { id: 'lazarus', title: 'LAZARUS', description: 'Unlocks The Moon Samurai', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['necromancer'], type: 'Lazarus', benefits: { necromancy: 2 }, unlocks: 'the_moon_samurai' },
    { id: 'forbidden_arts_ii', title: 'FORBIDDEN ARTS II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['necromancer'], type: 'Forbidden Arts', benefits: { blackMagic: 1 } },
    { id: 'forbidden_arts_iii', title: 'FORBIDDEN ARTS III', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['lazarus'], type: 'Forbidden Arts', benefits: { blackMagic: 1 } },
    { id: 'lich_queen', title: 'LICH QUEEN', description: 'Unlocks Flowers of Blood', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['lazarus'], type: 'Lich Queen', benefits: { blackMagic: 1 }, unlocks: 'flowers_of_blood' },
];

export const LOST_HOPE_SIGIL_TREE_DATA_KO: LostHopeSigil[] = [
    { id: 'young_witch', title: '어린 마녀', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], type: 'Young Witch', benefits: { channeling: 2 } },
    { id: 'spirit_channel', title: '혼령 조종', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['young_witch'], type: 'Spirit Channel', benefits: { channeling: 1 } },
    { id: 'deadseer', title: '사령술사', description: '생명력 흡수 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['young_witch'], type: 'Deadseer', benefits: { channeling: 1 }, unlocks: 'life_drain' },
    { id: 'necromancer', title: '강령술사', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['spirit_channel'], type: 'Necromancer', benefits: { necromancy: 1 } },
    { id: 'forbidden_arts_i', title: '금지된 기술 I', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['deadseer'], type: 'Forbidden Arts', benefits: { blackMagic: 1 } },
    { id: 'lazarus', title: '나사로', description: '월광의 사무라이 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['necromancer'], type: 'Lazarus', benefits: { necromancy: 2 }, unlocks: 'the_moon_samurai' },
    { id: 'forbidden_arts_ii', title: '금지된 기술 II', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['necromancer'], type: 'Forbidden Arts', benefits: { blackMagic: 1 } },
    { id: 'forbidden_arts_iii', title: '금지된 기술 III', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/nq80Y3pk-sinthru.webp', prerequisites: ['lazarus'], type: 'Forbidden Arts', benefits: { blackMagic: 1 } },
    { id: 'lich_queen', title: '리치 여왕', description: '혈화 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['lazarus'], type: 'Lich Queen', benefits: { blackMagic: 1 }, unlocks: 'flowers_of_blood' },
];

export const CHANNELLING_DATA: LostHopePower[] = [
    { id: 'spirit_medium', title: 'SPIRIT MEDIUM', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/qYcLvjjC-b1.webp', description: "Through all sorts of various means, you can ask questions of the remnants of any dead person's soul. They couldn't lie to you if you wanted to, so you can obtain {i}all{/i} of their knowledge. Just be careful. Dead men {i}do{/i} tell tales — but sometimes it's better if those tales had died with them.", grade: 'kaarn' },
    { id: 'fata_morgana_curse', title: 'FATA MORGANA CURSE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MxhYZ0vz-b2.webp', description: "All it requires is a ritual and a strand of a victim's hair. Poltergeists will sabotage their lives, whisper in the ears of their friends and drive them away, and cause them to whiff spells at vital moments. Can be subtle to be nearly undetectable as a curse, or can be elevated into a full-blown haunting.", grade: 'kaarn' },
    { id: 'spectral_form', title: 'SPECTRAL FORM', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HTWWzLNL-b3.webp', description: "You can shift yourself into a spectral form for an hour or two through a minutes-long ritual. You will be incorporeal and impossible for a non-necromancer to damage, but you can't use your powers. You can be invisible to most mages and all mundanes, and can move and manipulate objects like a poltergeist.", grade: 'kaarn' },
    { id: 'life_drain', title: 'LIFE DRAIN', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/WNxV5jRM-b4.webp', description: "{i}Requires {g}Deadseer.{/g}{/i} Every few seconds you can fire a projectile that latches a small spirit leech to a foe. These can be removed, but are hard to find on the body as they are small and near-invisible. Each very slowly sucks life energy from your foe and sends it to you, gradually rejuvenating and healing you.", requires: ['deadseer'], grade: 'purth' },
];

export const CHANNELLING_DATA_KO: LostHopePower[] = [
    { id: 'spirit_medium', title: '망자와의 대화', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/qYcLvjjC-b1.webp', description: "여러 수단을 동원하여 망자의 잔류 영혼에게 질문을 할 수 있습니다. 영혼들은 거짓말을 할 수 없기 때문에 그들의 모든 지식을 흡수할 수 있습니다. 그래도 조심하세요. 아무리 죽은 자들이 말을 하게 된다 해도... 죽음과 함께 묻히는 것이 나았을 이야기들도 있는 법이니까요.", grade: 'kaarn' },
    { id: 'fata_morgana_curse', title: '환영의 저주', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/MxhYZ0vz-b2.webp', description: "저주를 내리려는 대상의 머리카락 한 올을 가지고 의식을 치르기만 하면 됩니다. 폴터가이스트들이 대상의 일상을 방해하고, 온갖 귓속말로 친구 사이를 갈라 놓고, 결정적인 순간마다 마법 시전을 방해할 겁니다. 저주에 걸린 것도 모를 정도로 미묘하게 조절할 수도 있고, 대놓고 온갖 귀신들로 괴롭힐 수도 있습니다.", grade: 'kaarn' },
    { id: 'spectral_form', title: '영체화', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/HTWWzLNL-b3.webp', description: "당신은 몇 분 동안 의식을 치르는 것으로 1~2시간 동안 영체화할 수 있게 됩니다. 완전한 무형의 존재가 되어, 강령술이 아니라면 피해를 입지 않게 되지만, 당신의 힘도 사용할 수 없게 됩니다. 영체화 상태에서는 일반인들은 물론, 대부분의 마법소녀들의 눈에 보이지 않으며, 폴터가이스트처럼 사물을 움직이고 조작할 수 있습니다.", grade: 'kaarn' },
    { id: 'life_drain', title: '생명력 흡수', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/WNxV5jRM-b4.webp', description: "{i}{g}사령술사{/g}가 팔요합니다.{/i} 몇 초마다 한 번씩, 맞은 상대에게 혼령 거머리를 부착시키는 투사체를 발사할 수 있습니다. 혼령 거머리는 떼어낼 수는 있지만, 아주 작고 사실상 투명하기 때문에 찾기 쉽지 않습니다. 각각의 거머리들은 대상에게서 천천히 생명력을 빨아들입니다. 빨아들인 생명력은 당신에게 전송되어, 상처를 서서히 치유하고 원기를 회복시킵니다.", requires: ['deadseer'], grade: 'purth' },
];

export const NECROMANCY_DATA: LostHopePower[] = [
    { id: 'undead_beast', title: 'UNDEAD BEAST', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/WZxGTKd-b5.webp', description: "You will be able to revive the body of a great and mythological creature, and bind it to your soul so that it may always serve you. If your guardian creature is ever killed or injured, it can simply stitch itself back together, piece by piece. Design it with {w}60 Beast Points{/w} on the {i}Reference Page{/i}.", grade: 'kaarn' },
    { id: 'rise_from_your_graves', title: 'RISE FROM YOUR GRAVES', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/KpqpjH4D-b6.webp', description: "A quick ritual that reforms everybody who has ever perished in an area, usually bringing back a couple dozen zombies. They have supernatural strength and speed, though they're relatively fragile and can't fly. They also infect every mundane human they bite, so, uh, try not to start a major outbreak.", grade: 'kaarn' },
    { id: 'grasping_dead', title: 'GRASPING DEAD', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yFqw8Lqy-b7.webp', description: "Can form a {i}massive{/i} ball of decaying, powerful limbs and half-assembled bodies, before projecting it at a target with incredible force. If it collides, not only will it do significant damage, but the victim will become stuck in a tangled ball of tightly grasping, strong limbs, leaving them open to further attacks.", grade: 'kaarn' },
    { id: 'the_moon_samurai', title: 'THE MOON SAMURAI', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/3mNP4Mth-b8.webp', description: "{i}Requires {g}Lazarus.{/g}{/i} Jipangu was {i}de facto{/i} ruled over by its samurai warriors until the Empress reclaimed power and cursed her foes to never find peace. Now, many small armies of unkillable, powerful ghost warriors work as mercenaries in exchange for souls. The more souls, the longer they serve you.", requires: ['lazarus'], grade: 'purth' },
];

export const NECROMANCY_DATA_KO: LostHopePower[] = [
    { id: 'undead_beast', title: '언데드 야수', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/WZxGTKd-b5.webp', description: "거대한 신화생물의 육신을 되살리고, 당신의 영혼과 결속시켜 항상 당신을 따르도록 할 수 있습니다. 이 야수는 피해를 입거나 죽임을 당한다면, 천천히 시간을 들여 몸을 짜맞추며 회복합니다. 동물 점수 {w}60점{/w}이 주어집니다. 참고 페이지에서 언데드 야수의 세부 디자인을 할 수 있습니다.", grade: 'kaarn' },
    { id: 'rise_from_your_graves', title: '무덤에서 일어나라', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/KpqpjH4D-b6.webp', description: "이 간단한 의식은 대상 지역에서 죽었던 모든 사람들을 되살립니다. 보통 좀비 몇십 마리가 소환됩니다. 좀비들은 초인적인 힘과 속도를 지니고 있지만, 내구력은 상대적으로 약하고 비행을 할 수 없습니다. 일반인은 좀비에게 물리면 감염되기 때문에, 음, 좀비 사태를 일으키지 않게 조심하세요.", grade: 'kaarn' },
    { id: 'grasping_dead', title: '사자의 손아귀', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/yFqw8Lqy-b7.webp', description: "반쯤 남은 시신과 썩어가고 우악스러운 사지로 이루어진 거대한 구체를 형성한 후 엄청난 힘으로 대상에게 날립니다. 구체가 충돌하면 엄청난 피해를 줄 뿐만 아니라 대상을 수많은 손아귀로 제압하여, 후속 공격에 무방비로 노출시킵니다.", grade: 'kaarn' },
    { id: 'the_moon_samurai', title: '월광의 사무라이', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/3mNP4Mth-b8.webp', description: "{i}{g}나사로{/g}가 필요합니다.{/i} 한때 지팡구는 사무라이들이 실권을 쥐고 있었습니다. 그러다 여황제가 권력을 되찾고 그들이 절대 안식을 취하지 못하게 저주를 내렸죠. 이제 이 사무라이들은 강력한 불사의 유령군단이 되어, 영혼을 받고 용병 일을 해 주고 있습니다. 더 많은 영혼을 바치면 더 오랫동안 당신을 섬길 것입니다.", requires: ['lazarus'], grade: 'purth' },
];

export const BLACK_MAGIC_DATA: LostHopePower[] = [
    { id: 'undead_thrall', title: 'UNDEAD THRALL', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/M0cSVF7-b9.webp', description: "To revive a mundane is, for a necromancer, trivial and can be done en masse. But to revive a mage defies the will of the Mother, and is an altogether risker art. You can now revive your fallen foes into zombielike, mindless versions of their past selves, though they'll lack large portions of their old power and intelligence. Mages are horrified by the threat of being turned into one of these flesh puppets. You're also good enough to create one true Thrall, a rare and powerful undead with some soul still intact, designed with {w}50 Companion Points{/w}.", grade: 'sinthru' },
    { id: 'vampirism', title: 'VAMPIRISM', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Txyw78RQ-b10.webp', description: "Involves technically giving up your life only to immediately revive yourself as an undead creature. Vampires are known for their supernatural beauty and charisma, but blood withdrawal can turn them into gaunt, weak things. Sunlight burns with gradually increasing intensity upon their skin. However, drinking blood boosts their strength, speed and durability; those who've consumed, say, a hundred barrels reach twice the aptitude of an average mage. Draining a mage to death allows you to steal one non-{r}Xuth{/r}-tier power for months.", grade: 'sinthru' },
    { id: 'cursemakers_cookbook', title: "CURSEMAKER'S COOKBOOK", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/bRPQXz5x-b11.webp', description: "With a DNA sample like a strand of a victim's hair, you can subject them to a curse based on one of your other powers. For example, with {w}Pyromancer{/w}, they may feel a constant burning pain; with {w}Rise from your Graves{/w}, all nearby dead may rise and attack them; and etc. Click the book icon to view the Curse Encyclopedia. Additionally, once a century under the rare Witching Moon, you can curse a person and everyone who shares their blood, and it can only be removed if you die or remove it yourself.", grade: 'sinthru' },
    { id: 'flowers_of_blood', title: 'FLOWERS OF BLOOD', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/vvjRnPmd-b12.webp', description: "{i}Requires {r}Lich Queen.{/r}{/i} The feared archlich Elvira, head of the first Sinthru coven before she was captured, was known for watering an enchanted garden with the blood of her foes. While your garden remains undestroyed and watered with a human's worth of blood on a weekly basis, you are unkillable. You are essentially an invincible skeleton piloting a comfortable meat suit; even if everything else is burned away, your skeleton will remain and still be animate (albeit significantly weakened), unable to be destroyed even by the core of the sun.", requires: ['lich_queen'], grade: 'xuth' }
];

export const BLACK_MAGIC_DATA_KO: LostHopePower[] = [
    { id: 'undead_thrall', title: '언데드 노예', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/M0cSVF7-b9.webp', description: "일반인을 되살리는 것은 강령술사에게 어려운 일이 아닙니다. 무더기로 되살릴 수도 있는걸요. 하지만 마녀를 되살리는 것은 어머니의 의지에 반하는 것인 만큼, 훨씬 더 큰 위험을 수반합니다. 당신은 이제 죽은 적들을 이성이 없는 좀비에 가까운 존재로 되살릴 수 있게 됩니다. 다만 생전에 가지고 있던 마력, 힘, 그리고 지능의 대부분을 잃어버립니다. 죽은 후에 이런 꼭두각시로 이리저리 부려질 수도 있다는 것은 마녀들에게 커다란 위협이 됩니다. 또한, 당신은 언데드 노예를 하나 만들 수도 있습니다. 어느 정도의 이성을 유지하고 있는 희귀하고 강력한 언데드입니다. 동료 점수 {w}50점{/w}을 사용해서 세부 사항을 디자인할 수 있습니다.", grade: 'sinthru' },
    { id: 'vampirism', title: '흡혈', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Txyw78RQ-b10.webp', description: "이론적으로는 당신의 목숨을 내놓고, 곧바로 언데드로 되살아나는 것일 뿐입니다. 뱀파이어들은 초자연적인 미모와 매력을 갖고 있지만, 피를 소모하게 된다면 혐오스럽고 야위고 약한 모습으로 변합니다. 햇빛을 받으면 피부가 점점 더 심하게 타들어갑니다. 하지만 흡혈을 한다면 힘과 속도, 체력이 강화되고, 가령 백 명분의 피를 마시면 평범한 마법소녀의 두 배에 달하는 힘을 갖게 됩니다. 또한, 마법소녀를 흡혈해서 죽인다면 그녀의 마법 중 하나를 한 달 동안 훔칠 수 있습니다. ({r}주스{/r} 등급의 마법은 제외됩니다.)", grade: 'sinthru' },
    { id: 'cursemakers_cookbook', title: "저주술사의 고서", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/bRPQXz5x-b11.webp', description: "상대의 DNA 샘플만 있다면, 당신이 보유한 다른 마법에 기초한 저주를 걸 수 있게 됩니다. 가령 방화광으로는 지속적인 화상의 고통을 느끼게 되고, 무덤에서 일어나라로는 주변의 시체들이 부활해서 공격을 받게 되는 식입니다. 상세한 저주의 효과는 책 아이콘을 클릭하면 나오는 저주 백과사전에 명시되어 있습니다. 또한, 백 년에 한 번 마녀의 달이 뜰 때, 한 사람과 그의 모든 혈통에 저주를 걸 수 있습니다. 그 저주는 당신이 죽거나 직접 해제하지 않는 한 영원히 지속됩니다.", grade: 'sinthru' },
    { id: 'flowers_of_blood', title: '혈화', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/vvjRnPmd-b12.webp', description: "{i}{r}리치 여왕{/r}이 필요합니다.{/i} 신스루 마녀단의 첫 수장이었던 악명높은 고위 리치 엘비라는 적들의 피를 이용해 그녀의 마법 정원을 가꾸었습니다. 당신의 정원이 파괴당하지 않고 일주일에 한 번 한 사람 분량의 피를 공급받기만 한다면, 당신은 불사가 됩니다. 육체라는 로봇을 다루는 무적의 해골 조종사가 되는 셈이죠. 다른 모든 것이 불타 사라지더라도 당신의 뼈는 남아서 움직이고, 회복할 수 있습니다 (물론 심하게 약화됩니다). 가장 강렬한 태양빛도 당신을 죽일 수 없습니다.", requires: ['lich_queen'], grade: 'xuth' }
];
