
import type { RighteousCreationSigil, SpecialtyChoice, RighteousCreationPower } from '../../types';

// Righteous Creation
export const RIGHTEOUS_CREATION_DATA = { 
    title: "THE BLESSING OF RIGHTEOUS CREATION", 
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Fb149kMB-main3.webp", 
    description: "The Blessing most enjoyed by the more innovative and entrepreneurial of mages, and the one responsible for nearly all of the amazing inventions that characterize modern life. Metamagic was its earliest form, back in the very primal eras; shortly {i}after{/i} {i}Theosis{/i}, almost everyone on Earth enjoyed some level of magical ability, and they experimented with ways to push these powers to the limits. As society grew more complex, we even learned how to harness arcane matter. Once upon a time, the mere presence of a mage would incur surges, saps and dips in all nearby electrical circuits, but nowadays, most electronics have been thoroughly “magic-proofed” (although powerful spells or big battles have still been known to cause blackouts). This has brought on a new era of magitech, which has birthed some incredible luxuries. The difference between them all, can, perhaps, be most easily explained by the continuum between tech and magic. Magitech is heavy on the tech side of things, and metamagic on the magic side, while arcane constructs are half-and-half." 
};

export const RIGHTEOUS_CREATION_DATA_KO = { 
    title: "정당한 창조의 축복", 
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Fb149kMB-main3.webp", 
    description: "가장 혁신적이고 사업가적인 마녀들이 주로 다루는 축복입니다. 그리고 현대인의 삶을 책임지는 수많은 문명의 이기들 뒤에 있는 축복이기도 하죠. 머나먼 과거, 원시 시대의 메타마법이 이 축복의 시작이었습니다. 테오시스가 일어나고 얼마 지나지 않았을 때는 지구상의 모든 인류가 어느 정도의 마법 능력을 갖게 되었고, 그 한계를 탐구하고 시험하는 연구가 활발히 진행되었습니다. 사회가 복잡해지고 발전함에 따라 비전 물질을 끌어오는 방법까지 알게 되었죠. 한때는 마녀가 있는 것만으로도 인근 전자 회로가 죄다 망가지는 시절도 있었습니다만, 요즘은 웬만한 전자 장비는 철저하게 \"마법 방호\" 처리가 되어 출시됩니다. (물론 충분히 강력한 마법이나 거대한 전투가 벌어지면 대규모 고장이나 정전 사태가 발생하기도 하죠.) 이 때문에 마법공학에서도 새로운 시대가 열렸고 놀라운 사치품들이 등장하기도 했습니다. 이 축복에서 다루는 능력들의 차이는 이들이 기술과 마법 사이 어디쯤에 위치하고 있는지로 설명할 수 있습니다. 마법공학은 공학적 측면이 강하고, 메타마법은 마법적 측면이, 그리고 비전 구조체는 대략 중간 지점에 있습니다." 
};

export const RIGHTEOUS_CREATION_SIGIL_TREE_DATA: RighteousCreationSigil[] = [
    { id: 'rookie_engineer', title: 'ROOKIE ENGINEER', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], benefits: { specialty: 1 } },
    { id: 'polymat', title: 'POLYMATH™', description: 'Take the Vex Co. training regimen for instant results!', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['rookie_engineer'], benefits: { specialty: 1 } },
    { id: 'technician', title: 'TECHNICIAN', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['rookie_engineer'], benefits: { magitech: 1, arcaneConstructs: 1 } },
    { id: 'magician', title: 'MAGICIAN', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['rookie_engineer'], benefits: { metamagic: 1 } },
    { id: 'magitechnician', title: 'MAGITECHNICIAN', description: 'Unlocks Master Mechanic I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['technician'], unlocks: ['master_mechanic_i'], benefits: { magitech: 2 } },
    { id: 'arcane_wizard', title: 'ARCANE WIZARD', description: 'Unlocks Roboticist II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['technician'], unlocks: ['roboticist_ii'], benefits: { arcaneConstructs: 2 } },
    { id: 'metamagician', title: 'METAMAGICIAN', description: 'Unlocks Ace in the Hole', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['magician'], unlocks: ['ace_in_the_hole'], benefits: { metamagic: 2 } },
    { id: 'master_magitech', title: 'MASTER MAGITECH', description: 'Unlocks Master Mechanic II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['magitechnician'], unlocks: ['master_mechanic_ii'], benefits: { magitech: 2 } },
    { id: 'master_arcana', title: 'MASTER ARCANA', description: 'Unlocks Divine Clay', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['arcane_wizard'], unlocks: ['divine_clay'], benefits: { arcaneConstructs: 2 } },
    { id: 'metamaster', title: 'METAMASTER', description: "Unlocks Maria's Gift", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['metamagician'], unlocks: ["marias_gift"], benefits: { metamagic: 2 } },
];

export const RIGHTEOUS_CREATION_SIGIL_TREE_DATA_KO: RighteousCreationSigil[] = [
    { id: 'rookie_engineer', title: '초보 공학자', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], benefits: { specialty: 1 } },
    { id: 'polymat', title: '폴리매스™', description: '벡스 주식회사의 훈련 프로그램을 수료하고 즉각적인 결과를 얻으세요!', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/DD9xYmP9-lekolu.webp', prerequisites: ['rookie_engineer'], benefits: { specialty: 1 } },
    { id: 'technician', title: '기술 전문가', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['rookie_engineer'], benefits: { magitech: 1, arcaneConstructs: 1 } },
    { id: 'magician', title: '마법 탐구자', description: '', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTm8fcLb-kaarn.webp', prerequisites: ['rookie_engineer'], benefits: { metamagic: 1 } },
    { id: 'magitechnician', title: '마법공학자', description: '전문 기계공 I 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['technician'], unlocks: ['master_mechanic_i'], benefits: { magitech: 2 } },
    { id: 'arcane_wizard', title: '비전술사', description: '로봇술사 II 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['technician'], unlocks: ['roboticist_ii'], benefits: { arcaneConstructs: 2 } },
    { id: 'metamagician', title: '메타마법사', description: '비장의 한 수 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Dg6nz0R1-purth.webp', prerequisites: ['magician'], unlocks: ['ace_in_the_hole'], benefits: { metamagic: 2 } },
    { id: 'master_magitech', title: '마법공학 달인', description: '전문 기계공 II 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['magitechnician'], unlocks: ['master_mechanic_ii'], benefits: { magitech: 2 } },
    { id: 'master_arcana', title: '비전의 달인', description: '신성한 점토 해금', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['arcane_wizard'], unlocks: ['divine_clay'], benefits: { arcaneConstructs: 2 } },
    { id: 'metamaster', title: '메타마스터', description: "마리아의 선물 해금", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['metamagician'], unlocks: ["marias_gift"], benefits: { metamagic: 2 } },
];

export const RIGHTEOUS_CREATION_SPECIALTIES_DATA: SpecialtyChoice[] = [
    { id: 'magitech_specialty', title: 'MAGITECH', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/R441YsHB-b1.webp', description: "A discipline that focuses largely on technology, with magic only used to 'grease the wheels', so to speak, and allow your machines to operate on a level beyond what a mundane engineer would be capable of. Taking this specialty is required to take {i}any{/i} powers in the {w}Magitech{/w} category.", grade: 'kaarn' },
    { id: 'arcane_constructs_specialty', title: 'ARCANE CONSTRUCTS', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/svNL1LN9-b2.webp', description: "The art of creating things in physical reality through the use of magic. These constructs can then be blended with technology; for example, magically creating an artificial soul to place in a mechanical body. Taking this specialty is required to take {i}any{/i} powers in the {w}Arcane Constructs{/w} category.", grade: 'kaarn' },
    { id: 'metamagic_specialty', title: 'METAMAGIC', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Z1f6CyLD-b3.webp', description: "The study of magic itself. While it's stereotyped as highly theoretical, it has countless practical uses if pushing your powers to their absolute limits, or expanding the arsenal of yourself and others, is what you desire. Taking this specialty is required to take {i}any{/i} powers in the {w}Metamagic{/w} category.", grade: 'kaarn' },
];

export const RIGHTEOUS_CREATION_SPECIALTIES_DATA_KO: SpecialtyChoice[] = [
    { id: 'magitech_specialty', title: '마법공학', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/R441YsHB-b1.webp', description: "공학에 중점을 둔 이 학문에서는 마법을 '바퀴에 기름칠을 하는' 정도로만 활용하여, 기계들이 일반적인 공학의 범주를 넘어서서 작동할 수 있게 합니다. 마법공학 분류에 있는 능력을 선택하려면 이 특기를 선택해야 합니다.", grade: 'kaarn' },
    { id: 'arcane_constructs_specialty', title: '비전 구조체', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/svNL1LN9-b2.webp', description: "마법을 이용하여 물리적인 구조물을 만드는 능력입니다. 이것들을 공학기술과 접목시킬 수도 있는데, 가령 인공적으로 영혼을 창조해 기계 몸체에 넣을 수 있습니다. 비전 구조체 분류에 있는 능력을 선택하려면 이 특기를 선택해야 합니다.", grade: 'kaarn' },
    { id: 'metamagic_specialty', title: '메타마법', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Z1f6CyLD-b3.webp', description: "마법 그 자체를 연구하는 학문입니다. 이론만 공부한다는 편견이 있지만, 자신의 힘을 한계까지 극대화시키고 싶거나 자신과 동료들의 능력의 폭을 넓히고 싶다면 정말 큰 실질적 도움을 줄 겁니다. 메타마법 분류에 있는 능력을 선택하려면 이 특기를 선택해야 합니다.", grade: 'kaarn' },
];

export const RIGHTEOUS_CREATION_MAGITECH_DATA: RighteousCreationPower[] = [
    { id: 'kaboom', title: 'KABOOM!', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4ZxQx8Ys-b4.webp', description: "You are an expert at creating explosives! You can even combine them with various magical effects, like ice, fire, electricity, music, or what have you. You can create bombs with preternaturally large yields with impressively few resources, though other mages may be able to disarm them.", grade: 'kaarn' },
    { id: 'max_security', title: 'MAX SECURITY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1JjHpwKW-b5.webp', description: "You can create security systems, traps, and defenses effective even against mages. Nearly impenetrable blast doors, autoturrets that fire high explosive rounds with pinpoint accuracy, traps that freeze trespassers inside a solid block of ice, and all sorts of other neat traps and alarm systems.", grade: 'kaarn' },
    { id: 'venture_capitalist', title: 'VENTURE CAPITALIST', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0pSRK1TW-b6.webp', description: "You are incredibly good at inventing consumer commodities which don't have a ton of practical purposes, but which are extremely fun, useful or convenient. People will trip over themselves to buy these products, so this is a good skill to hone if your main goal is to get filthy stinkin' rich.", grade: 'kaarn' },
    { id: 'tinkerer', title: 'TINKERER', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/JjZqQj86-b7.webp', description: "You can create advanced mundane technology out of the most absurdly useless parts, and at stunning speeds. In a few minutes, make a sci-fi weapon, suit of armor, computer, or etc out of a few boxes of scrap and tidbits. You can also repair and modify existing mundane technology nearly instantly.", grade: 'kaarn' },
    { id: 'weaponsmith', title: 'WEAPONSMITH', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Kzpm0BNT-b8.webp', description: "You are an expert at doling out death with maximum efficiency, and can forge entire arsenals. Create your masterpiece using {w}40 Weapon Points{/w} on the {i}Reference Page{/i}. You can also upgrade the weapons of others, granting them {w}10{/w} extra {w}Weapon Points{/w} to work with. Doesn't stack.", grade: 'kaarn' },
    { id: 'rocket_propulsion', title: 'ROCKET PROPULSION', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G3HT97WL-b9.webp', description: "Regular humans would not doubt go flying into a wall instantly using this, but with your power of flight, you're much better at steering yourself. These customized systems allow you to increase your maximum flying speed by an extra 100 MPH, on top of massively boosting your acceleration.", grade: 'kaarn' },
    { id: 'master_mechanic_i', title: 'MASTER MECHANIC I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zhJDc8ZL-b10.webp', description: "{i}Requires {g}Magitechnician.{/g}{/i} You are now capable of making your own highly advanced, magically enchanted dream ride! You will be given {w}50 Vehicle Points{/w} to work with on the {i}Reference Page{/i}. You can also upgrade others' vehicles, granting them {w}10{/w} extra {w}Vehicle Points{/w} to work with. Doesn't stack.", requires: ['magitechnician'], grade: 'purth' },
    { id: 'master_mechanic_ii', title: 'MASTER MECHANIC II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/w3Dv8Hc-b11.webp', description: "{i}Requires {r}Master Magitech{/r} and {g}Master Mechanic I.{/g}{/i} Nothing's cooler than fighting giant monsters in a giant robot! In this spirit, you now have {w}100 Vehicle Points{/w} with which to build your dream ride. Plus, you'll know how to continually upgrade your ride and its weapons to make it even bigger and better.", requires: ['master_magitech', 'master_mechanic_i'], grade: 'xuth' },
];

export const RIGHTEOUS_CREATION_MAGITECH_DATA_KO: RighteousCreationPower[] = [
    { id: 'kaboom', title: '콰광!', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4ZxQx8Ys-b4.webp', description: "당신은 폭발물의 전문가입니다! 당신이 만든 폭발물에 다양한 마법 효과를 부여할 수 있습니다. 얼음, 불, 전기, 음악, 원하는 건 뭐든 가능합니다. 극히 적은 재료만을 가지고도 무시무시한 화력의 폭탄을 만들 수도 있지만, 폭탄이 다른 마녀들에게 해체당할 수도 있어요.", grade: 'kaarn' },
    { id: 'max_security', title: '최고 보안 등급', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1JjHpwKW-b5.webp', description: "마녀들도 상대할 수 있는 보안 시스템이나 함정, 기타 방어 시설을 만들 수 있습니다. 거의 뚫어낼 수 없는 방폭 문이나, 엄청난 정밀도로 폭발 유탄을 쏴대는 자동 포탑, 침입자를 얼음으로 빙결시켜 버리는 트랩, 그 외 다양한 함정이나 경보 메커니즘이 있겠죠.", grade: 'kaarn' },
    { id: 'venture_capitalist', title: '벤처 자본가', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/0pSRK1TW-b6.webp', description: "당신은 새로운 소비재를 발명하는 데 재능이 있습니다. 실용적인 쓰임새가 아주 많지는 않지만, 그래도 재미나 편리성 면에서는 뛰어난 것들입니다. 사람들은 이런 물건들을 사는 데 혈안이 될 겁니다. 당신의 목표가 일단 돈방석 위에 앉는 것이라면 이 능력을 갈고 닦는 것이 좋을 거에요.", grade: 'kaarn' },
    { id: 'tinkerer', title: '땜장이', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/JjZqQj86-b7.webp', description: "당신은 가장 쓸모없는 재료로도 순시간에 가장 뛰어난 기계장치들을 만들어 낼 수 있습니다. 공상과학 무기나 갑옷, 컴퓨터 등등을 폐품 더미 몇 상자만 있으면 몇 분 안에 만들어 낼 수 있는 것이죠. 그리고 현존하는 장비와 기계를 금세 수리하고 개조할 수도 있게 됩니다.", grade: 'kaarn' },
    { id: 'weaponsmith', title: '무기 제작자', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Kzpm0BNT-b8.webp', description: "당신은 최대 효율로 죽음을 선사하는 것의 전문가입니다. 무기고 하나를 혼자 채울 수도 있죠. 참고 페이지에서 무기 점수 {w}40점{/w}을 사용해 당신의 역작을 만들 수 있습니다. 또한 다른 이들의 무기를 강화시켜, 투자할 수 있는 무기 점수 {w}10점{/w}을 추가시켜 줄 수도 있습니다. 강화는 한 무기에 한 번만 가능합니다.", grade: 'kaarn' },
    { id: 'rocket_propulsion', title: '로켓 추진', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/G3HT97WL-b9.webp', description: "일반인들이라면 이 능력을 사용하자마자 벽에 들이받겠지만, 당신의 비행 능력이라면 훨씬 더 안정적으로 날 수 있을 겁니다. 이 커스텀 시스템을 사용하면 최대 비행 속도가 160km/h만큼 증가하고, 가속도 또한 엄청나게 상승합니다.", grade: 'kaarn' },
    { id: 'master_mechanic_i', title: '전문 기계공 I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zhJDc8ZL-b10.webp', description: "{i}{g}마법공학자{/g}가 필요합니다.{/i} 당신은 이제 당신만의 꿈의 탈것을 만들 수 있습니다. 가장 발전된 기계공학에 마술적 강화를 접목시켜서 말이죠! 참고 페이지에서 탈것 점수 {w}50점{/w}을 사용해서 탈것을 만들 수 있습니다. 또한 다른 이들의 탈것을 강화시켜, 투자할 수 있는 탈것 점수 {w}10점{/w}을 추가시켜 줄 수도 있습니다. 강화는 한 탈것에 한 번만 가능합니다.", requires: ['magitechnician'], grade: 'purth' },
    { id: 'master_mechanic_ii', title: '전문 기계공 II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/w3Dv8Hc-b11.webp', description: "{i}{g}전문 기계공 I{/g}과 {r}마법공학 달인{/r}이 필요합니다.{/i} 거대 로봇병기에 탄 채 거대괴수를 해치우는 것보다 쿨한 건 없죠! 당신만의 탈것에 투자할 수 있는 탈것 점수가 {w}100점{/w}으로 늘어납니다. 또한, 당신은 탈것과 그 부속 무장을 지속적으로 업그레이드하여 더 크고 멋지게 만드는 방법을 깨닫게 됩니다.", requires: ['master_magitech', 'master_mechanic_i'], grade: 'xuth' },
];

export const RIGHTEOUS_CREATION_ARCANE_CONSTRUCTS_DATA: RighteousCreationPower[] = [
    { id: 'tears_in_space', title: 'TEARS IN SPACE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1tBD1v9X-b12.webp', description: "This is the spell that revolutionized travel and industry in ways too innumerable to list. With a long ritual, you can open a portal in a place, and then connect two opened portals, allowing travel instantly between them. Takes some time, though, so don't expect to make one during combat.", grade: 'kaarn' },
    { id: 'roboticist_i', title: 'ROBOTICIST I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Gf98rSRf-b13.webp', description: "You will be an expert at infusing simplistic artificial souls into machinery, allowing you to create a plethora of customized robots to fulfill all sorts of minor roles and conveniences. You will also be given {w}40 Beast Points{/w} on the {i}Reference Page{/i} with which to design your 'magnum opus'.", grade: 'kaarn' },
    { id: 'roboticist_ii', title: 'ROBOTICIST II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SDTT4cpR-b14.webp', description: "{i}Requires {w}Roboticist I{/w} and {g}Arcane Wizard.{/g}{/i} Not only can your robots be more mechanically complex, but the quality of the artificial souls you create for them is also boosted almost to the point of true sapience. Create another 'magnum opus' using {w}50 Companion Points{/w} on the {i}Reference Page{/i}.", requires: ['roboticist_i', 'arcane_wizard'], grade: 'purth' },
    { id: 'divine_clay', title: 'DIVINE CLAY', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/KpqTKjq5-b15.webp', description: "{i}Requires {r}Master Arcana{/r} and {w}Arcane Matter.{/w}{/i} You can form and sculpt glowing arcane matter like clay with your mind alone, which will, after a few seconds, solidify into a physical material of your choice, all the way from concrete to titanium. This can be done in large enough quantities to construct a palace in a matter of minutes. Mages with this ability tend to become exorbitantly wealthy as architects, building entire cities single-handedly in weeks or months. It can also be used to build complex mechanical devices in mere seconds, although you are limited to what you already know how to make. This process is also fast enough to create weapons, walls and structures to defend yourself while mid-battle; however, arcane matter is quite fragile, so these structures will be weak for the two or three seconds before they can 'solidify'.\n\nThe Red-Jade council works to continue its policy of artificial scarcity by rendering this impossible via zoning laws. They won't mind if you make some sweet digs for you and your friends, but taking over the real estate market will {i}make{/i} very powerful {i}enemies{/i}. However, all housing options and upgrades become absolutely free for you.", requires: ['master_arcana', 'arcane_matter'], grade: 'xuth' },
    { id: 'camouflage', title: 'CAMOUFLAGE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TxfWgc5z-b16.webp', description: "You can create a camouflage texture that bends light around objects, essentially rendering them seethrough. Use this on a cloak, and you can essentially render yourself invisible. It will never even be picked up by thermals; the only sign of its existence will be a very faint shimmer.", grade: 'kaarn' },
    { id: 'all_seeing', title: 'ALL-SEEING', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/qM82bnqX-b17.webp', description: "You have the ability to create arcane satellites; \"eyes in the sky\" that you can move and control through thoughts alone, all visual input being instantly relayed to your mind. Many of these can be created, although they are each limited in the area they can cover. They are very hard to spot.", grade: 'kaarn' },
    { id: 'arcane_matter', title: 'ARCANE MATTER', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/9Pb8s7Q-b18.webp', description: "You can slowly create small amounts of arcane matter that can be refined into duplicates of objects you've saved the \"blueprints\" for; very useful for making replacements. You can even duplicate entire buildings if you don't mind spending a few weeks weaving new matter.", grade: 'kaarn' },
];

export const RIGHTEOUS_CREATION_ARCANE_CONSTRUCTS_DATA_KO: RighteousCreationPower[] = [
    { id: 'tears_in_space', title: '공간 균열', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/1tBD1v9X-b12.webp', description: "여행도, 산업도, 송두리째 뒤바꿔 놓은 마법입니다. 장시간 의식을 치른 뒤 특정한 장소에 포탈을 열고, 열린 포탈 두 곳을 연결하여 그 사이에서 즉각적인 순간이동이 가능하게 할 수 있습니다. 시전 시간이 길기 때문에 전투시에 활용할 수는 없다는 것을 명심하세요.", grade: 'kaarn' },
    { id: 'roboticist_i', title: '로봇술사 I', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Gf98rSRf-b13.webp', description: "당신은 기계장치에 단순한 인공 영혼을 부여하는 방법을 통해, 여러 잡일을 처리할 커스텀 로봇들을 만들 수 있게 됩니다. 또한, 당신의 로봇 '대표작'에 투자할 동물 점수 {w}40점{/w}을 얻습니다. (참고 페이지에서 디자인하세요)", grade: 'kaarn' },
    { id: 'roboticist_ii', title: '로봇술사 II', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SDTT4cpR-b14.webp', description: "{i}{w}로봇술사 I{/w}과 {g}비전술사{/g}가 필요합니다.{/i} 당신의 로봇들은 기계적으로도 복잡할 뿐만 아니라, 로봇을 구동하는 인공 영혼이 실제 인간의 그것과 매우 흡사해집니다. 또 하나의 '대표작'을 만들 수 있고, 참고 페이지에서 동료 점수 {w}50점{/w}으로 디자인할 수 있습니다.", requires: ['roboticist_i', 'arcane_wizard'], grade: 'purth' },
    { id: 'divine_clay', title: '신성한 점토', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/KpqTKjq5-b15.webp', description: "{i}{r}비전의 달인{/r}과 {w}비전 물질{/w}이 필요합니다.{/i} 점토 형상의 빛나는 비전 물질을 생각만으로 형성하고 조각할 수 있습니다. 이 물질은 몇 초 뒤 당신이 선택한 물리적 소재로 고체화됩니다. 콘크리트에서 티타늄에 이르기까지, 소재의 제한은 없습니다. 이 마법을 대규모로 사용한다면 커다란 궁전이라도 몇 분 만에 만들어낼 수 있습니다. 이 마법을 사용하는 마녀들은 건축가로써 수많은 명성과 부를 쌓아올리는 경우가 많습니다. 혼자 힘으로 몇 주나 몇 달 만에 도시 하나를 만들어 낼 수 있으니까요. 또한, 몇 초 만에 복잡한 기계장치를 만들어내는 데 사용할 수도 있습니다. 다만, 기계장치에 대한 당신의 이해가 전제되어 있어야 합니다. 마법의 시전은 충분히 빨라서, 전투 중에 무기나 벽, 기타 구조물을 만들어 공방에 활용할 수도 있습니다. 단, 비전 물질 자체는 꽤 약하기 때문에 '고체화'되기 전 2-3초의 짧은 시간 동안은 공격에 취약합니다.\n\n홍옥의 의회에서는 이 마법의 활용을 토지사용제한법으로 규제해서 '인위적 희소성' 정책을 유지하려고 합니다. 친구들과 같이 입을 옷을 만드는 정도야 신경쓰지 않겠지만, 부동산 시장의 큰손이 되겠다고 나서면 꽤 무서운 적들을 만들게 될 겁니다. 대신 주거 옵션 정도는 무료로 누릴 수 있겠죠.", requires: ['master_arcana', 'arcane_matter'], grade: 'xuth' },
    { id: 'camouflage', title: '위장', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TxfWgc5z-b16.webp', description: "물체 주변으로 빛을 굴절시켜 물체를 사실상 투명화시키는 위장 물질을 만들 수 있게 됩니다. 이것을 망토에 적용하면 말 그대로 투명 망토가 되는 것이죠. 이 물질은 심지어 열 감지도 비켜갑니다. 아주 작은 일렁거림 말고는 아무것도 보이지 않을 것입니다.", grade: 'kaarn' },
    { id: 'all_seeing', title: '천리안', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/qM82bnqX-b17.webp', description: "비전 위성, 그러니까 \"하늘에 떠 있는 눈\"들을 만들 수 있게 됩니다. 이 위성들은 당신이 생각만으로 조종할 수 있고, 모든 시각적 신호를 즉시 당신의 의식으로 전송합니다. 여러 개의 위성을 만들 수 있지만, 각각 커버할 수 있는 영역에는 한계가 있습니다. 위성들은 발견하기 매우 어렵습니다.", grade: 'kaarn' },
    { id: 'arcane_matter', title: '비전 물질', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/9Pb8s7Q-b18.webp', description: "소량의 비전 물질을 오랜 시간에 걸쳐 만들어 낼 수 있습니다. 이 물질은 당신이 \"설계도\"를 가지고 있는 물체를 복제하는 데 활용할 수 있습니다. 대체품을 만드는 데 제격이죠. 물질 조작에 몇 주를 투자할 여유가 있다면, 건물도 통째로 복제할 수 있습니다.", grade: 'kaarn' },
];

export const RIGHTEOUS_CREATION_METAMAGIC_DATA: RighteousCreationPower[] = [
    { id: 'dehexification', title: 'DEHEXIFICATION', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/211q0DFJ-b19.webp', description: "You've extensively studied every curse and hex out there, and the long, complex rituals required to remove them. Is it kind of a boring power? Well... yes, I suppose so. But when you've been afflicted with a Reinman's Curse miles from civilization, I assure you, you'll be very happy that you took this.", grade: 'kaarn' },
    { id: 'power_share', title: 'POWER SHARE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/qF7ZRn0c-b20.webp', description: "You can share one non-Metamagic, {w}Kaarn{/w}-tier power you have with all of your teammates (must be within 10 kmn of you, can affect up to 10 people at a time). You can, instead, allow one of your allies to {w}use{/w} {w}Power Share{/w}, with the team. if multiple teammates use Power Share, it caps at 3.", grade: 'kaarn' },
    { id: 'power_theft', title: 'POWER THEFT', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/pBXwGWdH-b21.webp', description: "By making physical contact and reciting an incantation, you can steal one power from an enemy. It must fit the guidelines for a power usable {i}by a{/i} {w}Beast{/w}, as listed on the {i}Reference Page{/i}. They can steal their power back by simply touching you, or it will be returned automatically in a half hour.", grade: 'kaarn' },
    { id: 'marias_gift', title: "MARIA'S GIFT", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gbFxhkSc-b22.webp', description: "{i}Requires {r}Metamaster.{/r}{/i} Typically, granting Stolen Blessings is the sole domain of the Mother, but you have achieved such a grasp of metamagic that you can emulate this ability. Think of this power as having 100 'points' you can spend at a time. For 1 point, you can grant any mundane either five {w}Kaarn{/w}-tier powers, or two {w}Kaarn{/w}-tier powers and one {g}Purth{/g}-tier power. Alternatively, you can spend 10 points to grant another mage one {c}Ruhai{/c}-tier power, or 25 for a {b}Milgrath{/b}-tier power. These can be revoked at any time for a refund. You cannot spend more points giving one person more powers.\n\nPerhaps your greatest ability is to shed your form at will and become a floating, shining ball of pure magical energy — nicknamed the titular \"Maria's Gift\". This cancels all powers granted through above means. Instead, you may enter the body of any living entity, able to see through its eyes and communicate telepathically. Until you leave their body, they will possess all your non-Metamagic powers, alongside any of their own. You cannot have multiple Gifts in the same body, nor can you cannot chain multiple Gifts into eachother like a Matryoshka doll. Used wisely, the result is invariably one of the most powerful entities in the world.", requires: ['metamaster'], grade: 'xuth' },
    { id: 'power_sight', title: 'POWER SIGHT', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/sz81vym-b23.webp', description: "Just by looking at a mage, you can instantly know what their powers are, except their Metamagic or Sinthru ones. You can also tell what category their weakness or requirement falls into, and when a mundane is secretly a mage. Unlike mindreading, this ability completely bypasses mental blocks.", grade: 'kaarn' },
    { id: 'broken_limiter', title: 'BROKEN LIMITER', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Z6kmKnfX-b24.webp', description: "You can overcome certain restrictions built in to your spells to prevent you from pushing your body past its safe limits. At any time, you {i}can{/i} {w}Boost{/w} any of your powers, but doing so will cause you to continually damage yourself. The more you boost at a time, the more pain and damage you suffer.", grade: 'kaarn' },
    { id: 'ace_in_the_hole', title: 'ACE IN THE HOLE', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TMd7WbZr-b25.webp', description: "{i}Requires {g}Metamagician.{/g}{/i} Nothing's funner than revealing a secret technique your foe didn't even know you had! Drawing from desperation, you can transform into a superpowered version of your alter ego which possesses a free {r}Xuth{/r}-tier spell of your choice. This form can be used 30 mins per month.", requires: ['metamagician'], grade: 'purth' },
];

export const RIGHTEOUS_CREATION_METAMAGIC_DATA_KO: RighteousCreationPower[] = [
    { id: 'dehexification', title: '저주 해제', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/211q0DFJ-b19.webp', description: "당신은 현존하는 모든 저주나 사술을 깊이 연구했고, 그것들을 해제하는 길고 복잡한 의식들도 꿰고 있습니다. 좀 따분한 능력인가요? 음... 뭐, 그렇긴 하죠. 하지만 문명과 단절된 상태에서 마부의 저주에 걸리게 되었다면, 이 능력을 가진 걸 정말 다행이라고 생각하게 될 거에요.", grade: 'kaarn' },
    { id: 'power_share', title: '마법 공유', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/qF7ZRn0c-b20.webp', description: "메타마법에 속하지 않는 {w}카른{/w} 등급의 마법 하나를 모든 팀원들과 공유할 수 있습니다. (팀원들이 당신 주위 반경 10km 안에 있어야 하며, 최대 10명의 팀원들과 공유할 수 있습니다) 또는, 동료 한 명이 그 자신의 능력을 팀원들과 공유하도록 할 수도 있습니다. 마법 공유를 활용하는 동료들이 다수 있다면, 최대 3종류의 마법을 공유할 수 있습니다.", grade: 'kaarn' },
    { id: 'power_theft', title: '마법 도둑', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/pBXwGWdH-b21.webp', description: "대상과 신체 접촉을 하는 상태에서 주문을 외우는 것으로 그의 능력 한 가지를 훔칠 수 있습니다. 대상이 당신과 신체 접촉을 하면 능력을 되돌려받을 수 있고, 그게 아니라면 30분 후 능력이 되돌아갑니다. 훔칠 수 있는 능력의 조건은 다음과 같습니다.\n\n1) 길조 / 불만족 / 패배 / 창조의 축복에 해당하지 않아야 합니다.\n2) 별다른 필요 조건이 없고, {w}카른{/w} 등급이어야 합니다.", grade: 'kaarn' },
    { id: 'marias_gift', title: "마리아의 선물", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/gbFxhkSc-b22.webp', description: "{i}{r}메타마스터{/r}가 필요합니다.{/i} 일반적으로 훔쳐온 축복을 마법소녀들에게 부여하는 것은 어머니만 하실 수 있는 일입니다. 하지만 당신은 메타마법에 대한 깊은 이해를 바탕으로 이 일을 흉내낼 수 있게 됩니다. 이 능력은 '점수' 100점을 배분하는 방식으로 생각할 수 있습니다. 1점을 투자하면 일반인에게 {w}카른{/w} 등급 능력 5종류를 부여하거나, {w}카른{/w} 등급 능력 2종류와 {g}퍼르스{/g} 등급 능력을 부여할 수 있습니다. 10점을 투자하면 다른 마법소녀에게 {c}루하이{/c} 등급 능력을 부여할 수 있고, 25점을 투자하면 다른 마법소녀에게 {b}밀그라스{/b} 등급 능력을 부여할 수 있습니다. 능력의 부여는 언제든 취소하여 점수를 되돌려받을 수 있습니다. 한 사람에게는 능력을 한 번만 부여할 수 있습니다.\n\n이 마법의 진정한 힘은 언제든 육체를 초월하여 순수한 마법 에너지로 가득찬 빛나는 구체로 변하는 것입니다. 소위 \"마리아의 선물\"이라고 불리는 것이죠. 구체로 변신하면 모든 능력 부여가 취소됩니다. 대신, 살아 있는 존재라면 누구든 그 몸 속으로 들어가 감각을 공유하고 텔레파시로 소통할 수 있게 됩니다. 당신이 깃든 대상은 당신이 떠날 때까지 메타마법을 제외한 당신의 모든 능력을 사용할 수 있게 됩니다. 마리아의 선물은 한 대상에게 중복될 수 없고, 마트료시카처럼 선물들을 서로 연결할 수도 없습니다. 그래도 현명하게 사용한다면 세계에서 손꼽힐 만큼 강력한 존재를 볼 수 있을 것입니다.", requires: ['metamaster'], grade: 'xuth' },
    { id: 'power_sight', title: '마법 간파', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/sz81vym-b23.webp', description: "다른 마녀를 바라보면 즉시 어떤 능력을 가지고 있는지 알 수 있습니다. 단, 메타마법이나 신스루 등급의 마법은 간파할 수 없습니다. 능력에 약점이나 특정 조건이 있는지, 마녀가 일반인인 척 정체를 숨기고 있는지도 알 수 있습니다. 이 능력은 텔레파시 계열과는 달리 정신 차단벽을 무시합니다.", grade: 'kaarn' },
    { id: 'broken_limiter', title: '한계 돌파', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/Z6kmKnfX-b24.webp', description: "신체에 반동 피해를 주지 않기 위해 당신의 마법에 내재된 제한들을 풀어 버릴 수 있습니다. 당신은 언제든 당신의 능력을 {w}강화{/w}시킬 수 있지만, 그 대가로 계속해서 피해를 받게 됩니다. 한 번에 많은 능력을 강화시키면 그만큼 고통과 피해가 중첩됩니다.", grade: 'kaarn' },
    { id: 'ace_in_the_hole', title: '비장의 한 수', imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/TMd7WbZr-b25.webp', description: "{i}{g}메타마법사{/g}가 필요합니다.{/i} 적들이 상상도 하지 못했던 비밀 기술을 꺼내는 것만큼 재미있는 것도 없죠! 절박한 순간에 당신은 초인적인 형체로 변신하여, 당신이 원하는 {r}주스{/r} 등급의 마법 한 종류를 조건 없이 사용할 수 있게 됩니다. 이 변신은 한 달에 30분 동안만 가능합니다.", requires: ['metamagician'], grade: 'purth' },
];
