
import type { StarCrossedLoveSigil, StarCrossedLovePact } from '../../types';

// Star Crossed Love
export const STAR_CROSSED_LOVE_DATA = {
    title: "THE BLESSING OF STAR CROSSED LOVE",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/d0jrxK9t-main4.webp",
    description: `In her great magnanimity, the Mother does not mind Mages drawing power from sources other than herself. Plenty of other entities have obtained great power they can share with you, either {i}through{/i} {i}Theosis{/i}, drawing from the divinity of the Child of God like the Mother, or by taking advantage of distortions in the framework of our universe, or other even more esoteric means. However, while the Mother {i}tries to be{/i} {i}laissez faire{/i} with her subjects — often to her detriment — other entities won't be so kind, and will make demands of you. Displease them, and they'll take back their powers.

In my opinion, if there's ever a new Doctrine, this blessing will be the first to go. It's driven too many mages to turn on their sisters or go on rampages. The Mother always learns towards freedom, but if you study the history carefully, you'll realize that pretty much every problem that exists in our universe came about because she was too lenient...`
};

export const STAR_CROSSED_LOVE_DATA_KO = {
    title: "불행한 사랑의 축복",
    imageSrc: "https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/d0jrxK9t-main4.webp",
    description: `어머니께서는 아량이 넓으시기 때문에 마법소녀들이 다른 곳에서 힘을 끌어와 쓴다고 해도 개의치 않아 하십니다. 당신에게 힘을 나누어 줄 수많은 다른 존재들이 있습니다. 그 방식은 어머니처럼 신의 아이의 신성력을 끌어오는 {i}테오시스{/i}가 될 수도 있고, 우리 우주의 왜곡 현상을 이용하는 것일 수도 있고, 기타 모종의 비밀스러운 방법일 수도 있습니다. 다만, 어머니께서는 마법소녀들이 자유롭게 놓아 두시지만 (그래서 그것이 때때로 어머니께 해가 되기도 하지만), 다른 존재들은 그렇게 친절하지 않습니다. 당신에게 뭔가를 요구할 것이고, 당신에게 만족하지 않는다면 그 힘을 빼앗을 겁니다.

제 생각으로는 새로운 대원칙이 세워진다면 이 축복이 가장 먼저 퇴출될 겁니다. 이것 때문에 수많은 마녀들이 동료들을 배신하거나 폭주하고 말았거든요. 어머니께서는 항상 자유를 강조하시지만, 역사를 깊이 공부한다면 당신도 알 수 있을 거에요. 이 세계의 거의 모든 문제는 어머니께서 너무 자유방임주의이셨던 것 때문에 일어났다는 걸...`
};

export const STAR_CROSSED_LOVE_SIGIL_TREE_DATA: StarCrossedLoveSigil[] = [
    { id: 'sworn_fealty', title: 'SWORN FEALTY', description: "You've vowed your undying loyalty to a powerful entity.\n+1 Pact", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], benefits: { pacts: 1 } },
    { id: 'dual_loyalty', title: 'DUAL LOYALTY', description: "Usually entities don't appreciate sharing, but...\n+1 Pact", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['sworn_fealty'], benefits: { pacts: 1 } },
];

export const STAR_CROSSED_LOVE_SIGIL_TREE_DATA_KO: StarCrossedLoveSigil[] = [
    { id: 'sworn_fealty', title: '충성 서약', description: "당신은 강대한 존재에게 변함없는 충성을 맹세했습니다.\n+1 계약", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/SFbsP2R-juathas.webp', prerequisites: [], benefits: { pacts: 1 } },
    { id: 'dual_loyalty', title: '이중 충성', description: "이 존재들은 보통 두 주인을 섬기는 것을 좋게 보지 않습니다만...\n+1 계약", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/rfs5FtF3-xuth.webp', prerequisites: ['sworn_fealty'], benefits: { pacts: 1 } },
];

export const STAR_CROSSED_LOVE_PACTS_DATA: StarCrossedLovePact[] = [
    { id: 'onis_blessing', title: "ONI'S BLESSING", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4wHGP0W5-c1.webp', description: "You've been marked as the host of an Oni since birth, and thus enlisted in their endless war against all other Yokai. They're most common in Jipangu, but even in other Dominions, they will track you down and attempt to sow as much destruction in your life as they can, going after loved ones and sabotaging your life. You must never miss an opportunity to end any Yokai you meet permanently. In return, you get permanent Boosts to {i}all{/i} Good Tidings spells, and your guardian oni can appear to aid you in combat once per year. Design them with {w}100 Beast Points{/w}.", grade: 'xuth' },
    { id: 'jade_emperors_challenge', title: "THE JADE EMPEROR'S CHALLENGE", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/chVk5k32-c2.webp', description: "The most powerful man in the Sinjade Doctrine who craved death but could find no foe able to grant it to him, up until he dueled the Mother herself, who could only just barely defeat him. Even at 1/10 the power of his mortal self, his spirit is still overflowing with strength to spare. To please him, you must defeat a truly powerful foe at least once every couple dozen years; each foe must be significantly stronger than the previous one. Completing {w}1 Xuth Trial{/w} grants a refund of {w}half{/w} its cost. And completing {w}2 Xuth Trials{/w} unlocks the ability to purchase a {w}3rd Xuth Sigil{/w}.", grade: 'xuth' },
    { id: 'lost_kronacks_deal', title: "LOST KRONACK'S DEAL", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5xK2QtBD-c3.webp', description: "The elusive leader of the Ninth Dominion, only know as a creature who made his way to our universe from the Greater Net, and who was left behind when his brethren returned to their home and left him behind. He asks only that, once every year, you bring him the soul of a mage for him to feast him, strengthening him. In return, you will be granted preternatural immunity from the effects of one section of spells, such as the {i}Metathermics{/i} section or the {i}Mental Manipulation{/i} section. Over time, he'll demand souls more and more often.", grade: 'xuth' },
    { id: 'sun_forgers_boon', title: "SUN FORGER'S BOON", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTZVxmmj-c4.webp', description: "Having lost all magic, this ancient emperor turned to his own inventions to feed and shelter his people during the Forsaken Age, and he's since become the patron saint of human ingenuity. Any sigil that you use to buy a spell that creates a weapon, companion, beast, or vehicle is now halved in price. Additionally, at any point on the {i}Reference Page{/i}, you can convert 1 {bpx}BP{/bpx} into {w}2 Vehicle, Weapon, Beast or Companion Points{/w} as many times as you want (although you can still never invest more than {w}100 points{/w} into any one creation).", grade: 'xuth' },
    { id: 'cheissiliths_bargain', title: "CHEISSILITH'S BARGAIN", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/JWSPqbjh-c5.webp', description: "Cheissilt was the first of the dragons, and is known for being unusually fluffy among them. At the end of the Forsaken Age, she is the very beast that the Mother rode into the Garden of Eden, and witnessed the slaying of God. Still acting as the Mother's right hand, she considers herself humanity's undying shepherd. She's convinced they'd survive longer if they abandoned specialization for variety. {j}Juathas{/j} sigils, including this one's, become completely free; however, the price of {g}Purth{/g} and {r}Xuth{/r} sigils is doubled.", grade: 'xuth' },
    { id: 'evoghos_vow', title: "EV'OGHOS' VOW", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ccrTKtgN-c6.webp', description: "The great and terrible \"god of the sea\", living in the stygian depths of the deepest trench of the Unterseeisch, many, many miles under the ocean's surface, a place so impossibly deep the laws of physics begin to break down. He shuns material possessions, believing a mage must be preoccupied by the spiritual; thus, if visited, he will allow you to convert 50 {fpx}FP{/fpx} {i}into{/i} 50 {bpx}BP{/bpx}. You must also take a vow of loneliness. You cannot choose any {w}Classmates{/w} {i}or{/i} {w}Colleagues{/w}; the only friends you can ever have in this world are the ones you magically create.", grade: 'xuth' },
    { id: 'kuri_odans_charm', title: "KURI-ODAN'S CHARM", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wNsbKjFZ-c7.webp', description: "For gamblers, the Kuri-Odan, the most powerful of the Yokai, will offer you a part of his soul in the form of a small charm, entrusting you to keep this vital part of him safe from harm. You lose {w}50 BP{/w}, {i}but gain{/i} {kp}100 KP{/kp}, which can be spent exclusively on sigils. Powers bought {i}with{/i} {kp}KP{/kp} {i}will{/i} slowly activate over time, likely taking a few centuries before you come to full power. This means your potential is much greater, but you'll be vulnerable for a long time: if anyone can break your charm, you will lose {i}every{/i} {kp}KP{/kp} {i}power{/i} you haven't yet activated. {i}Right-Click on Sigil Tree nodes to purchase them with KP.{/i}", grade: 'xuth' },
    { id: 'sinthrus_contract', title: "SINTHRU'S CONTRACT", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LhXMYMg7-c8.webp', description: "Desecrate your soul by swearing eternal loyalty to the Sinthru, the vilest devils who aim to kill the Mother and free the Child for their own no-doubt selfish purposes. You will be sworn to their service, and once people inevitably find out about this, you will be cast out by all of society, declared an enemy of all mankind and hunted down with the full force of Mother's empire. As long as you continue serving them, though, {i}all{/i} {bp}Sinthru{/bp} sigils are free as long as you have the prerequisite sigils, and there's no longer any limit on how many you can take.", grade: 'sinthru' },
];

export const STAR_CROSSED_LOVE_PACTS_DATA_KO: StarCrossedLovePact[] = [
    { id: 'onis_blessing', title: "오니의 축복", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/4wHGP0W5-c1.webp', description: "당신은 태어났을 때부터 오니의 숙주로 점찍어졌습니다. 다른 요괴들과의 영원한 전쟁에 참여하게 될 전사로 당신의 이름이 이미 올라가 있지요. 그 요괴들은 지팡구에 가장 많지만, 당신이 다른 국가에 있다 하더라도 당신을 추적해서 당신의 인생을 최대한 망치려고 들 겁니다. 당신의 소중한 사람들을 공격하고, 기회만 되면 발목을 잡아 대겠죠. 당신이 요괴를 마주치게 된다면, 그 목숨을 끊어 버릴 기회를 절대 놓쳐서는 안 됩니다. 그 대가로 모든 길조의 축복 마법들이 영구적으로 강화되고, 일 년에 한 번 당신의 보호자 오니를 소환해 전투를 돕게 할 수 있습니다. 보호자 오니는 {w}동물 점수 100점{/w}으로 디자인할 수 있습니다.", grade: 'xuth' },
    { id: 'jade_emperors_challenge', title: "옥황의 도전", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/chVk5k32-c2.webp', description: "신제이드 대원칙 시기에 가장 강한 힘을 지녔던 남자는 죽음을 갈망했지만 그 어떠한 적도 그에게 죽음을 선물할 수 없었습니다. 그는 이내 어머니와 직접 결투를 하게 되었고, 어머니께서도 그를 겨우 꺾으셨습니다. 그는 지금 영혼 상태로 전성기 힘의 10분의 1밖에 갖고 있지 않지만, 여전히 충분히 힘이 넘쳐납니다. 그를 만족시키기 위해서는 약 25년마다 강적을 찾아내어 꺾는 모습을 보여줘야 합니다. 그리고 그 강적은 점차적으로 강력해져야 하고요. 그 대가로 {w}주스 시련{/w} 1개를 완료하면 소모 비용의 절반을 환급받으며, 시련 2개를 완료하면 세 번째 주스 표식을 구매할 수 있는 능력이 해금됩니다.", grade: 'xuth' },
    { id: 'lost_kronacks_deal', title: "길을 잃은 크로나크의 거래", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/5xK2QtBD-c3.webp', description: "아홉 번째 국가의 베일에 싸인 지도자입니다. 그레이터 네트에서 우리 우주로 발을 들였다가, 모든 동족들이 고향 우주로 돌아갔을 때 홀로 남겨졌다는 것만이 알려져 있습니다. 그가 요구하는 것은 단 하나입니다. 자신이 포식하고 힘을 키울 수 있도록, 당신이 매년 마녀의 영혼을 하나 가져다 주는 것입니다. 그 대가로 당신은 한 부류의 마법에 완전한 면역을 얻습니다. ({i}정신 조작{/i}이나 {i}메타열역학{/i}과 같은 분류를 말합니다.) 시간이 지나면 그는 점점 더 많은 영혼을 요구할 것입니다.", grade: 'xuth' },
    { id: 'sun_forgers_boon', title: "태양 제련사의 선물", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/zTZVxmmj-c4.webp', description: "이 고대 황제는 버림받은 시대에 모든 마법을 잃어버리게 되자 자신의 발명품들을 이용해 백성들을 지켜냈습니다. 그 이후로 태양 제련사는 인간 지성의 수호신이 되었습니다. 무기, 동료, 동물, 탈것을 만드는 마법에 표식을 사용한 경우, 그 소모값이 반감됩니다. 또한, {i}참고 페이지{/i}에서 {bpx}축복 점수{/bpx} 1점을 {w}2점의 무기, 동료, 동물 또는 탈것 점수{/w}로 변환할 수 있습니다. (변환 횟수에는 제한이 없지만, 한 창조물에는 최대 {w}100점{/w}만 투자할 수 있습니다.)", grade: 'xuth' },
    { id: 'cheissiliths_bargain', title: "케이실트의 제안", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/JWSPqbjh-c5.webp', description: "케이실트는 가장 처음 등장한 용족들 중 하나입니다. 그리고 용족답지 않게 성격이 부드러운 것으로 유명하죠. 버림받은 시대가 막을 내릴 때, 어머니께서는 케이실트를 타고 에덴의 정원으로 오르셨고, 신의 최후를 지켜보셨습니다. 케이실트는 아직도 어머니의 오른팔 위치에 서서 스스로를 인류의 영원한 인도자로 여기고 있습니다. 그녀는 인류가 특화를 버리고 다양성에 투자한다면 훨씬 더 오래 살아남을 수 있을 것이라고 확신합니다. 모든 {j}자타스{/j} 표식의 소모 비용이 제거되지만, {g}퍼르스{/g}와 {r}주스{/r} 표식의 소모 비용이 두 배가 됩니다.", grade: 'xuth' },
    { id: 'evoghos_vow', title: "엡'오고스의 맹세", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/ccrTKtgN-c6.webp', description: "위대하고 공포스러운 \"심해의 신\"은 운터시쉬의 가장 깊은 곳, 칠흑 같은 심연에 머무릅니다. 그 곳은 너무나도 깊어서 물리 법칙마저 깨진다고 합니다. 엡'오고스는 모든 물질적 소유를 배격하고 마녀라면 영혼에 가치를 두어야 한다고 믿습니다. 따라서 그를 찾게 된다면 {fpx}행운 점수{/fpx} 50점을 {bpx}축복 점수{/bpx} 50점으로 바꿀 수 있습니다. 그 대신, 고독의 맹세를 해야 합니다. {w}클래스메이트{/w}나 {w}동료{/w}를 고를 수 없습니다. 당신이 사귈 수 있는 친구는 당신의 마법으로 만들어낸 존재들뿐입니다.", grade: 'xuth' },
    { id: 'kuri_odans_charm', title: "쿠리-오단의 부적", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/wNsbKjFZ-c7.webp', description: "가장 강력한 요괴인 쿠리-오단은 도박을 좋아하는 이들에게 작은 부적의 형태로 그 자신의 영혼 일부를 나누어 줍니다. 당신은 그 영혼을 소중히 지켜내야 합니다. 당신은 {w}축복 점수 50점{/w}을 잃고, 그 대신 표식에만 사용할 수 있는 {kp}쿠리-오단 점수 100점{/kp}을 얻습니다. 이 점수로 얻게 된 능력은 서서히 개화합니다. 아마 완전한 개화까지는 몇백 년이 걸릴 겁니다. 즉, 당신의 잠재력은 훨씬 강해지게 되지만, 그 대신 오랜 시간 동안 취약해집니다. 누군가가 그 부적을 찾아내어 파괴한다면 아직까지 개화되지 않은 모든 능력을 잃어버리게 되니까요. 표식 트리의 표식을 우클릭하여 사용된 축복 점수를 쿠리-오단 점수로 대체할 수 있습니다.", grade: 'xuth' },
    { id: 'sinthrus_contract', title: "신스루의 계약", imageSrc: 'https://cdn.jsdelivr.net/gh/theapple1234/saviapple_Seinarumagecraft_CYOA/public/images/LhXMYMg7-c8.webp', description: "신스루는 어머니를 살해하고 아이를 해방시켜 그들의 사악한 목적에 동원하려 하는 가장 사악한 악마들입니다. 당신은 이들에게 영원한 충성을 맹세하고 당신 자신의 영혼을 더럽히게 됩니다. 이 맹세는 돌이킬 수 없습니다. 다른 이들이 필연적으로 당신이 한 짓을 깨닫게 되면, 당신을 모든 사회에서 추방하고, 인류의 적으로 선포하고, 어머니의 이름으로 당신을 추적하여 처단하는 데 모든 노력을 쏟을 것입니다. 하지만, 신스루에게 계속해서 충성을 바치면 모든 {bp}신스루{/bp} 표식의 소모 비용이 제거됩니다. (단, 여전히 필요 조건은 채워야 합니다.) 또한, 보유할 수 있는 신스루 표식의 개수 제한이 사라집니다.", grade: 'sinthru' },
];
